### ISSUE TITLE
Proposal: Resource-Policy Controls and SLAs

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#100]
As part of a shared network, peers impose resource demands on each other. For SSB to work, the network (that is, its members) needs to provide guarantees. Contracted guarantees are called SLAs (https://en.wikipedia.org/wiki/Service-level_agreement).

Example SLAs which SSB uses:
- Feed replication: the feed will be stored and rehosted, within some rate limit.
- Blob replication: a certain amount of disk space and bandwidth will be allocated for blobs to be stored and rehosted.

At present, they're implicit. Pubs and peers provide some resources, for free, so long as members don't abuse the network. This is risky as the network grows, and so we've begun to implement [resource-policy controls in Scuttlebot](https://github.com/ssbc/scuttlebot/pull/261). But, so far, theyve been hard-coded and inaccessible to users. (See https://github.com/ssbc/scuttlebot/pull/261#issuecomment-157544106 for more about my concerns on this.)

There are a couple ways we might address this, but I'm going to propose something that's fairly direct: a config toolset, similar to what you'd find in an OS control panel. With it available to us, we can work on hiding it away, so it's only there when the user needs it (just as OS control panels are now).
- Add resource-policy controls to Patchwork, so that each user can view their current usage, and change their resource-usage policies.
- Add a protocol for sharing the chosen policies between peers, along with information about the policy (such as language describing the agreement), so that resource-availability may be displayed within Patchwork. For instance, if "BobsScuttlePub" sets a policy that I may use 10GB of blobs, then I'd be able to see that disk availability in my control panel, and see how much I've used so far.

Ideally it would look like a disk usage panel:

![screen shot 2015-11-18 at 2 13 29 pm](https://cloud.githubusercontent.com/assets/1270099/11252969/9785a8ee-8dfe-11e5-8303-f9b009fa35c5.png)

Something clean and graphic-y. You could see what's available to you, locally and on the network, and drill down into how it's been used, by yourself and peers. If you don't like something about the usage (maybe "jojo" is really putting out a lot of garbage pictures lately) then you might change the (sane) default policy to say, "only give jojo 5mb for blobs".

The protocol would only need to share policies between peers if a "guarantee" is needed. So, when I change Jojo's settings, I probably wouldn't tell him, because he's not relying on me to give him resources. But, if I'm running a pub and I change one of the members' policies, that _would_ be shared.

Eventually, this panel/protocol could be a way for people to exchange resources with each other.

Also -- might make sense for this to be a separate program that Patchwork calls out to.

**Comment by dominictarr** [comment]
okay so to boil this down to something we can do soon, we need configurable policies, and overrides per user. (currently there are hardcoded limits depending on how many follow-hops to that feed)

what about: 
``` js
var MB = 1024*1024
{
  hops: [
    null,  //zero hops. you.
    null,  //one hop, your friends
   20*MB //two hops, FOAF.
}
```

we could apply this same pattern for replication rates i think.

**Comment by pfraze** [comment]
I suggest we look at role-labels, intermixed with IDs:

```js
{
  master: null, // you
  friend: null, // one hop, your friends
  foaf: 20*MB, // two hops, FOAF
  '@HSZ7V+Hrm0mbqNGkINtN1CL8VEsY1CDMBu5yPCHg5zI=.ed25519': 100*MB // bob
}
```

that'd leave us some flexibility to define new roles
