### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1000]
Reported by @black-puppydog on Scuttlebutt:

```
TypeError: Cannot read property 'content' of undefined
    at bumpFilter (/scratch/taurus/dwynen/applications/patchwork/sbot/private-feed.js:110:17)
    at threadSummary (/scratch/taurus/dwynen/applications/patchwork/sbot/private-feed.js:99:27)
    at pull.drain (/scratch/taurus/dwynen/applications/patchwork/lib/thread-summary.js:34:7)
    at /scratch/taurus/dwynen/applications/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /scratch/taurus/dwynen/applications/patchwork/node_modules/pull-stream/throughs/filter.js:17:11
    at /scratch/taurus/dwynen/applications/patchwork/node_modules/pull-stream/throughs/filter.js:17:11
    at drain (/scratch/taurus/dwynen/applications/patchwork/node_modules/pull-paramap/index.js:23:11)
    at /scratch/taurus/dwynen/applications/patchwork/node_modules/pull-paramap/index.js:37:11
    at /scratch/taurus/dwynen/applications/patchwork/node_modules/pull-stream/throughs/through.js:19:9
    at /scratch/taurus/dwynen/applications/patchwork/node_modules/pull-stream/throughs/filter.js:17:11
```

**Comment by black-puppydog** [comment]
Now I get this instead:

```
Error: expected buffer, found string
    at /home/daan/code/patchwork/node_modules/flumeview-hashtable/index.js:39:43
    at /home/daan/code/patchwork/node_modules/atomic-file/inject.js:46:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

and patchwork is stuck "indexing".
I tested this with two build environments. One is Ubuntu 16.04, where nodejs is running in a conda environment, and one is Ubuntu Neon, where nodejs is "properly" installed. Reverting to the commit before that fixes the issue (but on the machine with conda I still have the blob issue then of course).

Now that I'm home and can test against the "proper" nodejs install, it seems the environment might have something to do with it...

**Comment by christianbundy** [comment]
@black-puppydog 

I'm about 90% sure that that issue occurs when you switch between two versions without an `npm install`, so it's using the wrong version of flumeview-hashtable (see https://github.com/flumedb/flumeview-hashtable/issues/2). You can resolve it with `rm -f ~/.ssb/flume/keys.ht`, but please make a new issue if the problem persists.
