### ISSUE TITLE
Spellcheck context menu has an extra horizontal line

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1002]
I think this might be from #980, cc: @Powersource

**Comment by christianbundy** [comment]
Oops, I forgot to describe it: this only happens when you spell something wrong and right-click it:

![Screenshot from 2019-04-26 10-26-04](https://user-images.githubusercontent.com/537700/56825403-de014700-680d-11e9-9b28-d26a8a4207b8.png)

**Comment by Powersource** [comment]
Ah must have slipped through as I never misspell :sunglasses:

**Comment by Powersource** [comment]
Yep in 3.11.6 the google button is between those two lines.

**Comment by christianbundy** [comment]
Ha! My excuse is that I'm seeing #996 (I assume you're not experiencing that bug?). I've just opened a PR to resolve this, which *also* solves this problem:

![Screenshot from 2019-04-26 10-55-42](https://user-images.githubusercontent.com/537700/56826758-dd6aaf80-6811-11e9-91f9-12d0682db1c9.png)

**Comment by Powersource** [comment]
Aah haha didn't think of that case.
