### ISSUE TITLE
module leveldown  was compiled against a different Node.js version using NODE_MODULE_VERSION 64. This version of Node.js requires NODE_MODULE_VERSION 57. 

### ISSUE THREAD

**Issue by roberto68** [ssbc/patchwork#1011]
`
... Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)     at Object.Module._extensions..node (module.js:671:18)     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)     at Module.load (module.js:561:32)     at tryModuleLoad (module.js:504:12)     at Function.Module._load (module.js:496:3)     at Module.require (module.js:586:17)     at require (internal/module.js:11:18)     at bindings (/home/roberto/bin/patchwork/node_modules/bindings/bindings.js:84:48)     at Object.<anonymous> (/home/roberto/bin/patchwork/node_modules/level/node_modules/leveldown/leveldown.js:3:36)
`
I rebuilded leveldown module, but still same problem. ``
FYI I use node v10.15.1

**Comment by gergelypolonkai** [comment]
What OS are you on? How did you install Patchwork?

**Comment by roberto68** [comment]
I installed via npm and I'm on Fedora 28 - kernel  5.0.9-200.fc29.x86_64

**Comment by christianbundy** [comment]
@roberto68 

What commands did you use to trigger this? Running `npm install` should run the post-install script that recompiles everything, but you can do it manually with `npm run rebuild` (*not* `npm rebuild`, btw).

Any chance you're running `electron2 index.js` or something? We've recently upgraded Electron so if you're using a system Electron you'll need to use Electron 4.

**Comment by roberto68** [comment]
thanks I run `npm run rebuild leveldown` and now it's running fine
