### ISSUE TITLE
run patchwork on a headless server

### ISSUE THREAD

**Issue by khimaros** [ssbc/patchwork#1014]
I have a server which I use to run my `sbot server`. I'd love to host patchwork as a web service so that I could browse from my laptop/phone.

Is such a thing already possible?

**Comment by christianbundy** [comment]
It's not currently possible, unfortunately. Right now Patchwork is coupled to Electron, but I'd love to have that fixed if someone has bandwidth for it.

**Comment by black-puppydog** [comment]
that sounds more like you want to be running ssb-server directly, with the appropriate plugins. or what do you mean by "headless"? What would you want to run on you phone to browse? The best practical thing that's already out there for that IMO would be patchfoo, running standalone or as an ssb-server plugin.
For browsing only, maybe ssb-viewer.
