### ISSUE TITLE
patchwork prompting to setup new profile on every load in latest master

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#1015]
<img width="1712" alt="Screen Shot 2019-05-02 at 10 07 28 AM" src="https://user-images.githubusercontent.com/66834/57045632-58284480-6cc2-11e9-9e45-be073535791a.png">

This dialog is popping up on startup, but otherwise it seems to be fine.

**Comment by black-puppydog** [comment]
Yes, this has snuck in with one of the latest commits. I noticed it first when testing #1010 but I didn't look into which commit causes this.

**Comment by christianbundy** [comment]
Looks like `sbot.id` is now `undefined`, but we're not handling the error correctly. Found with:

```diff
diff --git a/main-window.js b/main-window.js
index 92e32485..7268135a 100644
--- a/main-window.js
+++ b/main-window.js
@@ -61,7 +61,11 @@ module.exports = function (config) {
 
   // prompt to setup profile on first use
   onceTrue(api.sbot.obs.connection, (sbot) => {
+      console.log('sbot', sbot)
+      console.log('sbot.id', sbot.id)
     sbot.latestSequence(sbot.id, (_, key) => {
+      console.log(_)
+      console.log(sbot.key)
       if (key == null) {
         api.profile.sheet.edit({ usePreview: false })
       }
```
