### ISSUE TITLE
Error: could not connect to sbot

### ISSUE THREAD

**Issue by roberto68** [ssbc/patchwork#1016]
I've checked for this issue but I've different output here it is 
```
ssb-friends: createFriendStream legacy api used
/home/roberto/.nvm/versions/node/v10.15.1/lib/node_modules/git-ssb/node_modules/git-ssb-web/server.js:19
  if (err) throw err
           ^

Error: could not connect to sbot
    at /home/roberto/.nvm/versions/node/v10.15.1/lib/node_modules/git-ssb/node_modules/ssb-client/client.js:70:23
    at /home/roberto/.nvm/versions/node/v10.15.1/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:80:24
    at Socket.<anonymous> (/home/roberto/.nvm/versions/node/v10.15.1/lib/node_modules/git-ssb/node_modules/multiserver/plugins/net.js:66:11)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  Error: connect ECONNREFUSED 127.0.0.1:8008
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
TypeError: Cannot read property 'length' of null
    at Socket.socket.write (/home/roberto/bin/patchwork/node_modules/broadcast-stream/index.js:22:37)
    at /home/roberto/bin/patchwork/node_modules/scuttlebot/plugins/local.js:84:13

```
I've installed git-ssb globally too, tried with the global flag  `npm start --use-global-ssb` but the result is the same

**Comment by christianbundy** [comment]
That's a warning rather than an error -- are you wanting git-ssb to work, or just concerned about the "Error:" output? Also, I think you'd need `npm start -- --use-global-ssb` otherwise that flag is passed to npm.

**Comment by gergelypolonkai** [comment]
It happens to me, even when using the AppImage. I’d consider adding a UI element that shows the user that hey, you’re not connected to the ssb-server, your messages won’t pass through, and don’t expect new ones to arrive. Then, when the connection is restored, either remove that UI element, or change it to a happy face :)

**Comment by gergelypolonkai** [comment]
…or at least display an informational log message on the console that the connection has been restored…

**Comment by christianbundy** [comment]
@gergelypolonkai 

This issue is specific to the git-ssb in the background. Is that what you're having trouble with? If not, I'd love if you could create another issue.
