### ISSUE TITLE
Post with *just* the right length gets truncated

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1019]
This post: `%lJ9WIhzVnk0q5hXldrKD+8jVmeNHHExHIemO4PEmwMY=.sha256`

![screenie](https://user-images.githubusercontent.com/189241/57139648-1d9fd400-6db6-11e9-9f88-ec3a6c7741f8.png)

The problem seems to be that the post renders to something that is *just* above the threshold for "show more" truncation. Seems like a corner case to me.

**Comment by christianbundy** [comment]
Nice, thanks for finding this and reporting it!

**Comment by mmckegg** [comment]
You can probably fix this by adjusting the magic number here: https://github.com/ssbc/patchwork/blob/master/lib/expander-hook.js#L22

**Comment by black-puppydog** [comment]
The example I gave back then doesn't truncate for me any longer. The code that Matt pointed at didn't change though. :thinking: 
Closing for now, feel free to re-open if it occurs again.

**Comment by black-puppydog** [comment]
![image](https://user-images.githubusercontent.com/189241/106768008-c9d1b700-663b-11eb-91c0-918604248f6c.png)

![image](https://user-images.githubusercontent.com/189241/106768099-e2da6800-663b-11eb-87cb-8bdc4a90fd23.png)
