### ISSUE TITLE
Document release workflow

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1023]
This should probably be in the repo somewhere, but the release cycle is pretty simple.

<details><summary>Brain dump: click to expand</summary>

1. Check out `master` and make sure you're 100% up-to-date with origin. `git fetch origin && git reset --hard origin/master` makes this pretty simple.

2. `npm version $whatever`, usually this will be `npm version patch` or `npm version minor` but when doing a prerelease you have to do `npm version prerelease --preid beta`. This is fine to do in `master` IMO because it isn't changing any code.

3. `git push --tags origin master` should push your commit **and the tag**, which should set off Travis which will push a draft release. Look at the [releases](https://github.com/ssbc/patchwork/releases) and you should see the draft.

4. Wait for all of the builds to finish, it takes ~10 minutes for macOS and Linux but ~25 minutes for Windows. Then you'll edit the draft, change the title from "1.0.0" to "Patchwork v1.0.0" and set a body with the output of `npm run --silent release-notes`.

5. If it's an alpha or beta make sure to tick the "this is a prerelease box" at the bottom, hit "preview" to make sure you haven't borked your Markdown, and then hit "publish" release.

</details>

**Comment by christianbundy** [comment]
Release notes now generated with: `npm run --silent release-notes`

Bonus points on linuxy systems:

```
npm run --silent release-notes | xclip -selection c
```

:clipboard:

**Comment by black-puppydog** [comment]
Since there's not much more to document here, I propose closing this
