### ISSUE TITLE
Thread view showing messages out of order

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1025]
:frowning: 

![Screenshot from 2019-05-06 14-52-58](https://user-images.githubusercontent.com/537700/57257605-c9dbf780-700e-11e9-951e-5a74ef25f9e4.png)

![Screenshot from 2019-05-06 14-53-07](https://user-images.githubusercontent.com/537700/57257613-cfd1d880-700e-11e9-8e38-bee97db4c3ff.png)

**Comment by ahdinosaur** [comment]
i think this is a known issue where Manyverse messages (such as the message by Andre) don't include the causal [tangles](https://github.com/cn-uofbasel/ssbdrv/blob/master/doc/tangle.md) (i.e. `root` and `branch`), so Patchwork gets confused when trying to render based on sorted causality (via `ssb-sort`) versus rendering based on received (or asserted?) timestamp.

**Comment by christianbundy** [comment]
Thanks for the tip! Do you think would that break the thread order for only messages from Manyverse or would that change the order of other messages as well? I'm noticing that this is happening in a few different places:

![Screenshot from 2019-05-07 06-46-10](https://user-images.githubusercontent.com/537700/57304248-d48ca000-7093-11e9-927d-bab631918916.png)

**Comment by mmckegg** [comment]
@christianbundy 

Have you checked to see if this is the case when restarting patchwork and going to the thread, or only after realtime updates? I seem to recall realtime thread ordering is a bit lazy (as in it doesn't bother doing a causal sort when updating open views, just uses sync order)

**Comment by christianbundy** [comment]
I hadn't checked that, thanks for the recommendation. I've tried and it looks like even after restarting Patchwork it still has the incorrect order:

![Screenshot from 2019-05-11 09-36-11](https://user-images.githubusercontent.com/537700/57572518-48021a80-73d0-11e9-8f22-f2f4f4592572.png)

**Comment by Powersource** [comment]
Yeah I think the manyverse thing happens every time. cc @staltz I couldn't find an issue on gitlab about this, is this on the roadmap?
