### ISSUE TITLE
Pages sometimes don't load when offline

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1028]
Backlink: [%f5dkMKJdfRM+KEsRx8SCS1jrQkLkYuSwzIR2hR3n6dI=.sha256](https://viewer.scuttlebot.io/%25f5dkMKJdfRM%2BKEsRx8SCS1jrQkLkYuSwzIR2hR3n6dI%3D.sha256)

When I’m disconnected, nothing loads, e.g. when I click twice on Public, and I get a bunch of these:

```
Error {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/daan/.ssb/gossip.json~',
  dest: '/home/daan/.ssb/gossip.json' }
```

This only seems to happen on my laptop, and not consistently either. Sometimes "Public" loads just fine regardless of how often I click it.

**Comment by Powersource** [comment]
This happens to me when I'm connected to really shitty wifi. Do we have another issue for that? Probably similar cause.
