### ISSUE TITLE
Issue feature request: Warning msg PNG images Exif data it is not removed. 

### ISSUE THREAD

**Issue by wwwhtml** [ssbc/patchwork#1042]
Hello Folks,

I stumble upon the fact that Patchwork is not removing the exif data from those uploaded png images.

After some messages back and forth with @christianbundy, it was decided to open this issue feature request, a warning for those uploading PNG files via Patchwork, their Meta Data or Exif Data is not being removed removed. Please check what the appropriate terms, I personal bounce between Exif Data and Meta Data.  

Anyhow, perhaps the message should read something like: 
"Warning! At this time PNG images uploaded via Patchwork cannot have their meta data removed. We are aware of it and we will be fixing that issue when we find the solution."

Thank you!

**Comment by Fastidious** [comment]
I don't this as a problem, but a feature. Maybe making it a setting, and let the user decide whether to scrub EXIF or not?

**Comment by wwwhtml** [comment]
> I don't this as a problem, but a feature. Maybe making it a setting, and let the user decide whether to scrub EXIF or not?

I brought that up as privacy concern. 
But, I agree with you, users could be presented with the option if they want privacy or not (yes or not to EXIF data).
