### ISSUE TITLE
3.12.0.beta2 Unverified developer on osx el-capitan

### ISSUE THREAD

**Issue by k4ml** [ssbc/patchwork#1043]
Trying to install beta2 but it failed verifying:-

“Patchwork” can’t be opened because it is from an unidentified developer

OTOH, I can install Patchbay 8.0.1.

I'm using OSX 10.11.6.

**Comment by christianbundy** [comment]
@k4ml 

Hey, I think this is covered by #836, can you confirm that you can [open apps from unidentified developers](https://support.apple.com/kb/PH25088?locale=en_US)? I think @mixmix signs Patchbay releases with his Apple cert, but I don't have one. :disappointed:

**Comment by christianbundy** [comment]
I think this is a duplicate, please comment back if I've closed this in error.
