### ISSUE TITLE
Another Stuck Scuttling (os10.14)

### ISSUE THREAD

**Issue by cricketlova** [ssbc/patchwork#1044]
Currently on macOS Mojave v.10.14
Electron Version 4.2.0

Can't seem to get my scuttlebutt to unscuttle! (Screenshots attached)

<img width="1297" alt="Screen Shot 2019-05-20 at 12 33 57 AM" src="https://user-images.githubusercontent.com/5195677/58004025-0855c580-7a97-11e9-99ab-f8adc34c1314.png">
<img width="784" alt="Screen Shot 2019-05-20 at 12 34 16 AM" src="https://user-images.githubusercontent.com/5195677/58004026-0855c580-7a97-11e9-9057-2670fc2082c5.png">

**Comment by christianbundy** [comment]
Hey, sorry to hear you're running into problems. Could you post which version of Patchwork you're running?

**Comment by cricketlova** [comment]
hey @christianbundy - the screenshots above were from when I built from source (not sure what that one pulls): 
<img width="633" alt="Screen Shot 2019-05-20 at 11 17 14 AM" src="https://user-images.githubusercontent.com/5195677/58042961-dd985b00-7af0-11e9-9eca-92e4d9df5f41.png">

but I've also tried Patchwork v3.11.6 (install from mac.dmg), Patchwork v3.12.0-alpha.1 (install from mac.dmg), and Patchwork v3.12.0-beta.2 (install from mac.dmg) -- and all still were scuttling the database infinitely.

Is there anything that I could do to give you more info - apologies, sort of new to SSB, terminal, and git

**Comment by christianbundy** [comment]
Thanks for the info! This looks suspiciously similar to https://github.com/ssbc/patchwork/issues/1041, could you read through that issue and see whether any of the fixes work? My intuition is that something is corrupted but I'm not sure what. :confused:

**Comment by cricketlova** [comment]
@christianbundy - that is exactly the cure! Just had to delete that file and everything began populating

Thanks!

**Comment by christianbundy** [comment]
I'm still bummed that we're having this problem, but I'm happy that it was resolved in this case. Please let me know if it happens again, I'm really hoping that the newest prerelease resolves this!
