### ISSUE TITLE
error loading sodium bindings: libsodium.so.23

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#1045]
when running latest `beta.2`, i get the following warning in the console:

> error loading sodium bindings: libsodium.so.23: cannot open shared object file: No such file or directory
> falling back to javascript version.

after doing a build locally and looking at `dist/linux-unpacked/`, i don't see any `libsodium.so.23`.

i'll see if i can fix this, as i encountered this while working on #983, but turns out it affects the AppImage as well.

**Comment by christianbundy** [comment]
Any chance this was resolved by #1040?

**Comment by ahdinosaur** [comment]
given my understanding, i don't think it would be, but i can check later.

do you not see the same error message?

**Comment by christianbundy** [comment]
No, I'm on Arch Linux and I've got something funky going on where AppImages work for me even though they throw errors on Ubuntu machines (both Mix and Piet had the same errors). The story so far:

- Originally we didn't have any glob to ignore prebuilds and so the binaries were *huge*.
- Matt sent me a PM pointing out that the binary size had increased and pointed to the code that would minimize it.
- I added a super-terse version of the code that somehow removed *all* prebuilds, not just the ones I selected.
- Somehow this didn't cause problems for me but Mix noticed it while building Patchbay and Piet could confirm the issue.
- The solution seemed to be removing the `files` key with the ignore-list glob, which was merged as #1040.

I'd *love* to get rid of irrelevant prebuilds, but I want to make super sure it's not just working on my machine and breaking on Ubuntu.

**Comment by christianbundy** [comment]
Btw, if you get a chance I'm super curious to know whether this is fixed in `master` now. I'd love to get the build smaller, but currently my focus is just making sure the builds aren't broken on anyone's system.

I really appreciate the tinkering you're doing with getting the build smaller, just know that if there are problems *it's not you*, and even though the docs seem authoritative I'm about 90% sure there's a bug in electron-builder that's borking the `files` glob.

**Comment by christianbundy** [comment]
Just tested Ubuntu and it looks like this is working again. Woo! I'm going to remove the "blocking release" tag, is this good to close now?

**Comment by ahdinosaur** [comment]
yes, this does work on the latest release! so i'll close this, but leave #1046 open (maybe rename) to focus on how we minimize the builds. and agree, "works on my machine" is not enough for a release, glad you were able to find something that works to release :smiley_cat:

**Comment by christianbundy** [comment]
Woo! Happy this works, I'm excited to see the future of #1046. :heart:
