### ISSUE TITLE
Emoji broken on windows

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1053]
@mixmix reported this on 3.12.0 beta 0 and @cblgh reported this on beta 3, both on windows.

**Comment by christianbundy** [comment]
Reposting my response on SSB:

> Thanks! If possible could you post the config that’s output when starting Patchwork from a terminal and / or try right-clicking an image and viewing it in a browser to see if there are errors?

**Comment by cblgh** [comment]
yeah i'm on 3.12

electron console tells me, for each emoji, that the file is not found:

![image](https://user-images.githubusercontent.com/3862362/58208632-6546bb00-7ce5-11e9-9e63-4741c925f89e.png)

**Comment by Powersource** [comment]
We're using a symlink to point the emoji dir to the dependency `emoji-named-characters`'s pngs dir. Didn't we switch to a new windows installer? I'm guessing it's not unpacking symlinks properly. @cblgh could you look at the img or emoji dirs and check to see if they're there and that the emoji dir is a symlink? (or this is how it looks in my dev environment, I'm assuming the build doesn't move stuff around too much?)
