### ISSUE TITLE
feature request: Vimium style link shortcuts

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1055]
![XewzIX42Inb+CZl8FazlvxQ7Uw= sha256](https://user-images.githubusercontent.com/32660718/58360838-b79bef00-7e3f-11e9-8d99-4c8aa24c7006.jpg)

Echoing a feature idea from "@w".  Browser addons like Vimium have a feature which gives a unique code to each link on the page so you can follow them using only the keyboard.  This allows you to browse without using a mouse, which is helpful for people with carpal tunnel etc.

Or, is there a way to view Patchwork content from a regular browser by connecting to localhost?

**Comment by Powersource** [comment]
Not patchwork but if you want to use ssb from a browser you could e.g. use patchfoo.
