### ISSUE TITLE
Your posts shouldn't show at the top of public + private feeds

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1056]
IMO having your own posts and replies show up in the public feed makes Patchwork *very* hard to use, once you publish a few replies your feed gets completely taken over by your own posts and you can't read anything from anyone else.

**Comment by black-puppydog** [comment]
I think that's actually a more general problem of how to keep track of threads. It already came up a couple of times, like eg here `%/T27AtEr3KEItSgJdwdW6X+5kB/4HA2TbbaNmTUh7To=.sha256`.

I personally think a bulletin-board like interface would be great to keep track of threads. :P

**Comment by christianbundy** [comment]
> bulletin-board like interface

Do you mean like Reddit, or something different?

**Comment by black-puppydog** [comment]
might be like reddit, but actually I was thinking more along the lines of phpBB or discourse.
at least for discussion style posts (as opposed to photo sharing posts or events) this might be super useful. I find it much easier to keep track of phpBB and discourse threads than ssb threads at the moment.

and it's not just ssb either. twitter and facebook have the same problem in my opinion. it's this "timeline" concept I think, where current stuff washes up at the top, but there's no concept of really tracking and organizing discussion. reddit is much better in that way, with subs and topics. I'm not a big fan of hierarchical discussions and up/down voting, but that's a (related but) distinct issue.

**Comment by marylychee** [comment]
yeah agreed.

how does the *unread* and *new* things work?

and personally I enjoy patchbay's condenseness of inbox - potentially we could have a similar thing, for patchwork's participating thread, to reduce infinite scroll/checking??

actually I'd like that for mentions too - or the options for it to be condense ? I guess this would be more like facebook's notification feature then tho??

_______

regarding your original concern @christianbundy maybe is there a way we can filter?? I also find it annoying, that when I hit publish, there's a public (1) one new message, but it's just me lol
