### ISSUE TITLE
Long gathering descriptions are truncated

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1057]
Only happens when viewing it directly, it's rendered correctly in feeds (show more/less, and shows everything when you show more).

Example %6Qd/cgjMkoZ4Df4bbLnTGXNZN2C0t9zPoe6yKbT5d9g=.sha256

![image](https://user-images.githubusercontent.com/1427063/58363005-68d17200-7e9e-11e9-8f8c-8e5d6d0dfda5.png)

**Comment by black-puppydog** [comment]
May or may not be related to #1019 ?
