### ISSUE TITLE
Any plans to release to Windows Store?

### ISSUE THREAD

**Issue by lostmsu** [ssbc/patchwork#1058]
That should cover Windows signing (becomes unnecessary) and automatic updates.

**Comment by Powersource** [comment]
What's the process for getting on there? Could we publish programmatically (and therefore through CI)? I notice that the package on [flathub](https://flathub.org/apps/details/nz.scuttlebutt.Patchwork) isn't even up to date, and it feels like windows store would be even more likely to fall behind (if we can't automate it).

At the moment none (I think) of the active developers are using windows so we're even having trouble [testing stuff on windows](https://github.com/ssbc/patchwork/pull/1054). Is this feature something you could help out with?

**Comment by lostmsu** [comment]
The process is a multi-step process, and requires a one-time fee of ~$20 for registration, unless you can find someone, who is already registered, whom you trust.

https://developer.microsoft.com/en-us/store/register

Electron seems to have some official docs on how to build a Windows Store app: https://electronjs.org/docs/tutorial/windows-store-guide

The only thing I am not sure about is if Travis can publish to Windows Store, or one has to create an Azure DevOps pipeline for that.

When you say you have trouble testing stuff, do you mean manual testing, or is there an automated test framework that you use?

**Comment by Powersource** [comment]
I'm referring to manual testing, but having automated tests for the ui would be awesome.

**Comment by Powersource** [comment]
This sounds like the thing we'd need to automate the publishing https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services
