### ISSUE TITLE
Add ability to create & use peer-invites

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1059]
Peer-invites as in https://github.com/ssbc/ssb-peer-invites

Asked @dominictarr and he said they're (mostly?) (any caveats? how's the pub support?) done. I'm thinking I'm gonna start working on this after my blob-summoning PR is done.

UX wise I'm thinking to add a button next to the Join pub button for creating invites, and turning the Join pub button into a generic Use invite button for both using pub invites and peer invites. The other option is to do like what we were doing with dht invites and create two new buttons next to the Join pub button, but I feel like we'd end up with a lot of buttons in the end and people wouldn't know which one to put their invite in. Thoughts on ux @mmckegg @cblgh ?

Any tips for how to test this in an easy way? I'm thinking I should maybe pack up my desktop computer and unfollow my laptop account, and then "rejoin" by inviting my desktop again. Would be nice to test with a fresh account though. Maybe I should just leave that part of the testing to someone else once the PR is up :P

**Comment by Powersource** [comment]
🙃

**Comment by christianbundy** [comment]
If you assign yourself to an issue/PR the bot won't touch it. It only acts on issues that are old and have nobody who has assigned themselves to it.
