### ISSUE TITLE
Improve the UX of creating a thread fork

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1060]
Issues with the current implementation are:
1. People (especially new ones) click Reply expecting to make a regular reply pointed at that message, but they instead ending up making a fork, which they might not have intended (or realise what that is). I think we at least should re-label the button to Fork, possibly also adding another button that says Reply but just scrolls you to the bottom and @-mentions the person you're replying to.
2. Probably rename it from Fork to e.g. Branch. There was some discussion on this, I don't know what it settled on.
3. I don't think there's a way of making a fork reply to a thread's root message.

And maybe I should fork this issue into 3 separate ones but :man_shrugging:

**Comment by marylychee** [comment]
ahh yes, classic example. 

in roll call for the sbb resign site thread `%cK+/jw5eCxGU0ZBijECjn+Tsj5zC4h8wgW4FlNnAyvU=.sha256`

Maybe reply just takes you to the bottom of the thread but we could have have arrow down like 
<img width="84" alt="image" src="https://user-images.githubusercontent.com/18238352/59141150-3faaf880-89eb-11e9-862b-24958946f92f.png"> to fork? @Powersource

**Comment by marylychee** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/18238352/59141190-d2e42e00-89eb-11e9-8eaa-97ab51a3c2a4.png">

**Comment by marylychee** [comment]
I do think forks need to be a lot more specific, that we're creating like... a subthread. 

I think there's a lot of unintentional subthreads/forks going on

**Comment by marylychee** [comment]
we could also use a 
<img width="35" alt="image" src="https://user-images.githubusercontent.com/18238352/59141231-4c7c1c00-89ec-11e9-8077-c3baabc62742.png"> like github does giving a similar flow with 'Reference in a new issue' but instead a fork

**Comment by Powersource** [comment]
> we could have have arrow down like to fork?

My mind 100% associates a down-arrow like that to mean that it opens a menu of a few options. (I was about to ask if that's what you meant, but I don't think you did?)

Personally, something like ![image](https://user-images.githubusercontent.com/1427063/59163058-cea73600-8afb-11e9-8148-671bf7a0d019.png) or ![image](https://user-images.githubusercontent.com/1427063/59163097-3c536200-8afc-11e9-88b3-b403aa4b70bc.png) would make more sense.

Maybe one solution would be to just rename it, e.g. to Branch, and then base iconography and stuff around that. In the Branch case, having the button literally look like a branch. Now that I spell it out though, that sounds like a bad idea :P 

> like github does giving a similar flow with 'Reference in a new issue'

Ok that's the menu thing. Maybe nice, would give us more room to explain the button. But feels weird if there's only one thing in the menu? And I think I recall UX people complaining about those menus, I'll ddg them a bit.

UX is hard lol

**Comment by marylychee** [comment]
![](https://user-images.githubusercontent.com/1427063/59163097-3c536200-8afc-11e9-88b3-b403aa4b70bc.png)

yes I like this one!! 


Maybe the menu thing has just could be an extra explainer/options: 

- reply in this thread
- branch out this thread

**Comment by Powersource** [comment]
Hmm idk I don't really like adding menus. And without adding the quote reply option I don't think we have enough stuff to fill it with. Maybe put quote reply in a different issue? I can think of a few other ways of implementing that UX-wise.

Without the menu, the fork/branch button would say branch/fork just like Like & Reply do now I guess, and would we need more explainer text than that do you think?

**Comment by cinnamon-bun** [comment]
Is there a good document somewhere about how threading works in SSB (with root pointers etc)?

**Comment by christianbundy** [comment]
My preference would be to remove the input box at the bottom of every thread. It *feels* like a reply to the most recent message but it's actually a reply to the root message. Making people click "reply" on the actual message they want to reply to would make this much simpler IMO. Then it's just a problem of drawing the discussion tree in the UI.

Right now we're taking a structure [like this](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblxuZiAtLT4gYVxuZSAtLT4gYVxuZCAtLT4gYVxuYyAtLT4gYVxuYiAtLT4gYSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) and displaying it [like this](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblxuZiAtLT4gZVxuZSAtLT4gZFxuZCAtLT4gY1xuYyAtLT4gYlxuYiAtLT4gYSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19) and calling it a "fork" when someone does an actual reply [like this](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblxuZiAtLT4gYVxuZSAtLT4gYVxuZCAtLT4gYVxuYyAtLT4gYVxuYiAtLT4gYVxuZyAtLT5mIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0). I've wanted to fix this for months but the code is super complex and I really don't understand it. :confused:

**Comment by christianbundy** [comment]
@cinnamon-bun 

I don't think so, but IIRC there are only two/three depending on how you count:

- `root`: the ID of the message you're replying to
- `fork`: the ID of the parent of the message you're replying to (if one exists) 
- `branch`: totally unrelated, it's a list of messages in the thread that no other mentions have referenced (used for tracking message order and finding "missing messages")

If you have replies `A <-- B <-- C` then C will publish `{ root: 'B', fork: 'A' }` to denote that it's replying to B (which is a reply to A). Sorry if that's overly terse, happy to chat more about it if you'd like more info.

**Comment by Powersource** [comment]
So I was gonna make a new issue but realized I was mostly summarizing this one. Anyway, might be useful notes for someone implementing so here it is:

A PR fixing this would basically:
1. Relabel and [re-icon](https://github.com/ssbc/patchwork/issues/1060#issuecomment-502420975) the current Reply buttons in threads to Fork.
2. Create a new Reply button (old icon) that scrolls you to the textbox at the bottom and maybe @mentions the person you clicked reply on. (we could skip this one if we don't feel like it/have time atm)

:warning:Warnings:
1. The current fork behaviour of replies doesn't happen when you're in the Public view and click reply on the last comment (in that case it actually takes you to the textbox in the thread). wut?
2. The same (un)buggy behaviour as above also happens when you click Reply on the root post in a thread. (so you can't currently fork off a root post, but we'll deal with that later)

**Comment by christianbundy** [comment]
Another idea I just had: maybe we should have two buttons: **reply** and **reply all**.

- **reply** should create a sub-thread about the specific message you've selected
- **reply all** should add a message to the thread as a sibling of the message you've selected

I think this might simplify things because it uses vocabulary that they're already familiar with, although with "reply" we'd probably want to be extra clear that *this is not a private message*.
