### ISSUE TITLE
Smileys and some icons are missing in the Windows build of 3.12.0

### ISSUE THREAD

**Issue by interfect** [ssbc/patchwork#1061]
![image](https://user-images.githubusercontent.com/752054/58384402-27bc8900-7f96-11e9-9358-ee169b430b69.png)

![image](https://user-images.githubusercontent.com/752054/58384412-3c008600-7f96-11e9-8986-92976a649922.png)

In 3.11 these icons showed up fine. In 3.12 they are missing.

The console has a bunch of file not found errors for

```
file:///C:/Users/<me>/AppData/Local/Programs/ssb-patchwork/resources/app.asar/assets/img/emoji/nose.png
```

The app.asar file is there, but apparently it is having trouble looking inside it. There's also an app.asar.unpacked folder next to it, which doesn't contain an `assets`.

**Comment by Powersource** [comment]
Thanks for the report! I believe this is the same issue as https://github.com/ssbc/patchwork/issues/1053 so I'm gonna close this one, reopen if you disagree :)

If it's the same issue, we've got a fix going here https://github.com/ssbc/patchwork/pull/1054 that would love a bit more testing, would be great if you could help out with that :)
