### ISSUE TITLE
custom emojis no longer displaying

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#1062]
[`%A4RCbayBuwjslAIiTrQSA1xgMsSYI3Ru3gX3NB5NcdA=.sha256`](https://viewer.scuttlebot.io/%25A4RCbayBuwjslAIiTrQSA1xgMsSYI3Ru3gX3NB5NcdA%3D.sha256):

> [#Patchfoo](#patchfoo) has custom emojis, but I'm unsure if they are visible in other clients.
>
> E.g.:
>
> :airbnb:	`:airbnb:`
> :amiga:	`:amiga:`
> :conversations:	`:conversations:`
> :debian:	`:debian:`
> :telegram:	`:telegram:`

---

> Yeh I can't see those patchfoo emojis in Patchwork.

---

> hmm, seems to be a regression in Patchwork then, as [support for custom emoji's](https://github.com/ssbc/patchwork/blob/51f6f105a8bfe396ab8b7923951a39b2dccf82ca/modules/message/html/markdown.js#L32) from Patchfoo [was added to Patchwork at one point](https://github.com/ssbc/patchwork/commit/2b26681719856323d66d06c4c0b35411b7cd7a37), for example i like using the emoji's from %D0Cde1F+dIoBVZrvfdZbyO4s2YWiATkEohzKFYQX3hs=.sha256.
>
> but yeah, keen for a general overhaul of emoji's in Patchwork, happy to provide support for anyone interested in the adventure. :smiley_cat: 

---

> I _can_ see them in Patchwork. I'm using the latest version from Flathub, Patchwork 3.10.1.

**Comment by Powersource** [comment]
Wouldn't this be part of the whole how-should-we-render-posts/markdown discussion that people have been having (and that I haven't followed too closely)? I.e. some clients render with some emoji and some with other emoji? (I might also be misunderstanding custom emoji, how do they work anyway?)
