### ISSUE TITLE
arm appimage for raspberry pi based devices?

### ISSUE THREAD

**Issue by thearkadia** [ssbc/patchwork#1069]
Could there be an appimage for arm devices so raspberry pi users could use SSB\Patchwork?

the previous thread about ARM was closed after inactivity https://github.com/ssbc/patchwork/issues/745

**Comment by ahdinosaur** [comment]
hm, yeah this should be possible.

here's a rough work-in-progress attempt: https://github.com/ssbc/patchwork/pull/1070
