### ISSUE TITLE
Patchwork 3.9 (Flatpak) -> 3.12 (.deb install): How to copy profile data?

### ISSUE THREAD

**Issue by kr428** [ssbc/patchwork#1073]
Folks;
subject says it all: Used to run Linux patchwork 3.9 off flathub / flatpak so far. Tried to install 3.12 using the .deb package, which works - but I don't see my profile at all. Plus, I sort of got lost within various local config folders (.ssb, .config/Patchwork) trying to figure out where to move which files.
Can anyone point me to tutorials, explanations, hints on how to handle such a scenario? What is required to move my profile from 3.9 (flatpak version) to 3.12 (deb install)?
Thanks, Kristian

**Comment by Powersource** [comment]
I don't know where flatpak stores its stuff, but I guess it's in some weird location? In that case, find that location, let's say it stores the patchwork stuff in `~/flatpak/patchwork/` (just guessing now). Then you want to move the `~/flatpak/patchwork/.ssb/` folder to `~/.ssb/`. Again, just guessing, let me know if you don't find the .ssb folder :)

And remember that the most important file is `.ssb/secret`, and `.ssb/gossip.json` is very useful too, so back those files up before starting to move stuff around.

**Comment by christianbundy** [comment]
Yeah, I'd look to find your profile data first. Maybe:

```shell
find / -name gossip.json
```

If that returns `/over/the/rainbow/` and **assuming `~/.ssb/` is empty, does not exist, or has data you don't care about**, you can probably `mv /over/the/rainbow/* ~/.ssb/` to get your data to the correct spot. Sorry the flatpak is so out of date! I don't think I know who to contact about that.

**Comment by kr428** [comment]
Cool, thanks, that "fixed" it. For the minutes, the flatpak installation keeps its files in ~/.var/app/nz.scuttlebutt.Patchwork.
