### ISSUE TITLE
Blur profile pics of blocked & ignored users

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1077]
There is a user with a dick pic as their icon.  Many people have blocked them, as have I.

I recently clicked through to their profile page to remember if I had blocked them and although their posts are hidden, their user icon is still shown.

Can we use CSS to blur the user icons of blocked and ignored users?

```
filter: blur(8px);
-webkit-filter: blur(8px);
```

(Those icons might also appear in other contexts besides profile pages such as "who to follow", "connected pubs", lists of another users' friends, etc)

**Comment by marylychee** [comment]
wow true, this seems pretty high priority and potentially fairly easy to implement??

**Comment by Powersource** [comment]
The [deletion PR](https://github.com/ssbc/patchwork/pull/1026) should help against/alleviate this. (I'll ask christian in that PR how fast/frequent the deletions would be)

**Comment by Powersource** [comment]
Started working on a fix here https://github.com/ssbc/patchwork/pull/1079, help finishing it would be appreciated!

**Comment by cinnamon-bun** [comment]
Hooray!

Another place this shows up is in these collapsed items about "UserA blocked UserB".  Ironically it has the effect of broadcasting the offending image to everyone:

![ssb-user-icon-block](https://user-images.githubusercontent.com/32660718/59240889-623f3c00-8bba-11e9-9bf6-fea6242804b2.png)

In that specific case it would be nice to blur the icon on the right whether or not you, the current user, have blocked them.  However if you're already following the user on the right, a blur is probably not needed.

E.g. "blur icon on the right of this widget, unless you are following them"
