### ISSUE TITLE
Don't automatically turn ascii emoji, e.g. ":)", into image emoji

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1078]
This was added some time in the last year and I'm not a fan of it. The meaning of :) vs. :smiley: is quite different to me.

For reference, most chat apps that have this feature have an option for turning it on/off. Not saying *that*'s the solution we should have, just that doing the auto conversion is often controversial.

Also worth considering is how other ssb apps render this. I'm guessing (can someone verify?) that Patchbay doesn't do this, in which case posts get quite a different feel depending on the client you read them in.

This is my opinion, what do others think?

**Comment by black-puppydog** [comment]
I think we should stick to rendering things the way they were written. If someone wants to insert unicode emoji, then they should use unicode emoji. if someone types out `:-)` then they probably mean exactly that. The argument that adding emoji is difficult and the user might really *want* the ascii to be replaced doesn't really make sense to me today when (in patchbay and on any phone and virtually any other place) unicode emoji is easy to insert without remembering code points or such.

**Comment by mmckegg** [comment]
Was it the markdown update that did this? I haven’t seen this happening.

**Comment by christianbundy** [comment]
I think this came from https://github.com/markdown-it/markdown-it-emoji, we should be able to override those shortcuts in ssb-markdown.

**Comment by Powersource** [comment]
Opened a PR in ssb-markdown to fix this https://github.com/ssbc/ssb-markdown/pull/36
