### ISSUE TITLE
Download gatherings for import into calendar

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1083]
I've been wanting this for a while but haven't made an issue for it. I've missed a handful of gatherings because I forgot to make an entry in my actual calendar for them. Maybe an ICS would be helpful? Not sure what the event format landscape looks like these days.

**Comment by Powersource** [comment]
I think @mixmix made some script for exporting gatherings to ics (can't find anything on github tho)

**Comment by christianbundy** [comment]
Found the post: %YgwJgvSUCdtb4XjmU7XhziJiMsJ1EC6XTnVJ1EfCZpA=.sha256
