### ISSUE TITLE
Feature request: A view that only shows people I follow directly

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1087]
I just onboarded a new person to Patchwork.  He asked "how can I see only the people I'm directly following?"

We could add another view for this.  Not sure if it should show threads **started by** people you follow, or threads **participated in** by people you follow.

(In the long term, many of our views could be combined into a "social radius" slider which lets you decide how many hops you want to see.  This could be one of the slider settings.)

**Comment by ahdinosaur** [comment]
how would this differ from the "Public" view? my understanding is that "Public" (the default view) only shows threads started by people you follow directly _or_ posted in channels you subscribe to.

**Comment by cinnamon-bun** [comment]
Oh!  I follow a lot of channels - maybe that's why my Public feed seems so big.  Does it also show posts liked by people you follow?

My wish is an "inner circle" view focused on people I actually know.  2 ways to do this:
* A view only showing threads started by your mutual-follows
* Friend Lists, so you could read just your local friends, just SSB developers, etc.

I guess this is a user wish rather than a specific solution.

**Comment by Powersource** [comment]
>  Does it also show posts liked by people you follow?

The only thing likes affect is that if someone likes a root post (not a comment), you can see that when viewing their profile.

**Comment by trosel** [comment]
This is related https://github.com/ssbc/scuttlebutt.nz/issues/146
