### ISSUE TITLE
Privacy seatbelt: Warn when @-mentioning many people into a private conversation

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1088]
Several times I've accidentally @-mentioned people into a private conversation when I was only trying to refer to them or link out to their account.

It is possible to see this happening by counting the avatar icons in the post preview modal window, but I've missed it each time.

There could be a bigger warning message on the modal window that's shown when starting a conversation with more than 2 people.

" 🎉  You are starting a conversation with the following **5** people: @ a, @ b, @ c, @ d, @ e."

You can't add people to an ongoing conversation, so we don't need to warn about that happening (except maybe to say that it won't work).

**Comment by Powersource** [comment]
Maybe a simpler solution where we wouldn't need a warning is to have a separate text box where you specify recipients. I.e. more like email (so people would be used to it as well).

This would also let us mention people in the first message without sending it to them as well, which is a feature I'm missing.

**Comment by cinnamon-bun** [comment]
> separate text box where you specify recipients

I like that solution more!

**Comment by cinnamon-bun** [comment]
Closing this issue in favor of #1118
