### ISSUE TITLE
Channel names collide with profile name when a message is posted to many channels

### ISSUE THREAD

**Issue by cscottmills** [ssbc/patchwork#1091]
Here's an example:
![Screen-Shot-2019-06-12-at-4 58 39-PM](https://user-images.githubusercontent.com/787173/59386033-b6216080-8d33-11e9-9b75-f32e3b8ee557.jpg)

I'm happy to submit a pull request to tidy this up a bit.

**Comment by christianbundy** [comment]
If you click those channels does it take you to #undefined? I think there's something funky going on there. :sweat_smile:

**Comment by cscottmills** [comment]
Ah, it does. And of course, there's no way to list multiple channels there, is there?

**Comment by christianbundy** [comment]
I don't think so, it looks like they have a `channel` property with spaces between the channels? I wonder which client they used...

**Comment by cscottmills** [comment]
🤔

**Comment by black-puppydog** [comment]
so this would be a case of a (different) client producing a message that we (patchwork) consider invalid, semantically?
I guess we should *not* try to handle this broken `channel` property and instead just make sure that the user gets something other than `#undefined` that makes it clear that it's the message that has a problem, not patchwork?

**Comment by christianbundy** [comment]
Yeah, exactly -- my understanding is that messages can only have one channel, so we should probably validate the input channel before putting it on the screen. :~) Totally agree.

**Comment by cinnamon-bun** [comment]
Most clients now also look for channel names in the message body.  Is the `channel` property obsolete now, especially if it can only hold one channel?

**Comment by christianbundy** [comment]
I'm +1 on obsoleting it in favor of hashtags, but I'm not sure how much work this would take.
