### ISSUE TITLE
Top bar buttons break to multiple lines when viewport is too narrow

### ISSUE THREAD

**Issue by cscottmills** [ssbc/patchwork#1092]
Here's an example:
![Screen Shot 2019-06-12 at 5 02 47 PM](https://user-images.githubusercontent.com/787173/59386490-c84fce80-8d34-11e9-9de4-903ad4108e55.png)

Perhaps the top bar should be refactored to handle any number of buttons? Here's a _very_ rough possibility:

![Screen Shot 2019-06-12 at 5 30 16 PM](https://user-images.githubusercontent.com/787173/59387698-d3f0c480-8d37-11e9-9bf5-cc90f643fda9.png)

Happy to put something better together if there's interest.

**Comment by christianbundy** [comment]
I'd like this, although I'm not on macOS so I can't actually see this change.
