### ISSUE TITLE
digs should be aggregated counts per post.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#110]
in the updates feed,
digs show up with each dig linking to the post in the order they occured.

here is a post I made that got dug several times (including a undig and a redig)
![screen-shot_2015-11-23t13 51 02 1000](https://cloud.githubusercontent.com/assets/259374/11329555/63e662d2-91e9-11e5-838f-730c99a63533.png)

This is really a lot of clutter. It would be much easier to consume this information if it said
"paul, mikola and dust" dug your post.

**Comment by mmckegg** [comment]
This sort of thing has been addressed in [patchwork-next](https://github.com/mmckegg/patchwork-next). Closing!
