### ISSUE TITLE
Reduce line length for better readability

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1102]
See: https://practicaltypography.com/line-length.html

This would bring us up-to-date on the typographic best practices regarding line length, which make posts feel *so* much nicer and easier to read. I didn't realize how much our super-wide lines were making the posts feel huge and intimidating. To me this feels *much* friendlier. :smiley_cat: 

![Screenshot from 2019-06-15 10-58-33](https://user-images.githubusercontent.com/537700/59554739-9751e280-8f5c-11e9-966d-e28ba648ca74.png)

![Screenshot from 2019-06-15 10-53-56](https://user-images.githubusercontent.com/537700/59554722-40e4a400-8f5c-11e9-9f99-b7adab8a0a14.png)

![Screenshot from 2019-06-15 10-54-25](https://user-images.githubusercontent.com/537700/59554723-45a95800-8f5c-11e9-9f2e-3222ae3fadcd.png)

![Screenshot from 2019-06-15 10-54-41](https://user-images.githubusercontent.com/537700/59554724-493cdf00-8f5c-11e9-8cb0-3a4f93c3e3ae.png)

**Comment by black-puppydog** [comment]
I have very strong feelings about this. I do get that it's Easier to Read (TM) but the waste of screen space makes me sad. I even have my screen in portrait mode on the desktop, and even with that it feels like the amount of stuff I can easily scan without scrolling is artificially limited to a fraction of what it could be.

I'm sure some folks will find this much less intimidating, but I  don't find this very nice, simply because suddenly I'd have to scroll twice as much as before, and that means tracking my reading position, or re-finding it after scrolling. So it's not like this doesn't come at a price.

**Comment by christianbundy** [comment]
Thanks! I feel that, and I really do wish that we used horizontal space better. I swear I have opinions that aren't just quotes from typography manuals (especially Butterick's), but I think this is key:

> Therefore, for those embarking on a responsive-design project, one key reminder: **the rules of good typography don’t change with screen size.**
>
> -- https://practicaltypography.com/responsive-web-design.html

I do feel strongly that we could be using horizontal space better (e.g. move avatars to the side of the post, like how GitHub does it), and our undersized font size and whitespace adds to the feeling of the gigantic margins, but I don't think there's anything wrong with [leaving the page margins](https://practicaltypography.com/page-margins.html) in general.

I think the homepage feels especially bare because the left sidebar is attached to the left side of the screen instead of floating a bit closer to the actual content, and thread views don't have *any* sidebars (which looks fine in a modal window like how Twitter does it, but kinda bare how we do it). Long-term I think that we'll need to make some big architectural changes to Patchwork's design but my current strategy is just chipping away at small improvements.

**Comment by christianbundy** [comment]
Quick design draft that makes the 48rem line length look infinitely less crappy. :~)

Would love feedback.

![Screenshot from 2019-06-22 12-12-41](https://user-images.githubusercontent.com/537700/59967995-af3ede80-94e7-11e9-9ed0-3f7bbd42e050.png)

**Comment by christianbundy** [comment]
Doesn't feel like this will happen, closing now.
