### ISSUE TITLE
My ssb broke... Error: when trying to retrive:log

### ISSUE THREAD

**Issue by marylychee** [ssbc/patchwork#1107]
Accidentally opened both patchwork and patch bay at the same time, so I think in both clients trying to index, things crashed kaboom-ed. 

```
Error: when trying to retrive:log,1560666067414at since:680417528
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/flumeview-level/index.js:139:28
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumedb/index.js:70:17
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:75:17
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:680414149-2431614458 < 680418068
    at Object.read (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:93:9)
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:93:9)
```

I think I've done before.... and now again stuck on forever indexing on patchwork, and get this error in patchbay.

What's the best course of action from here? Should I just delete some of the folders from .ssb except my keys and stuff, and re-download everything from the network like I did last time???

**Comment by christianbundy** [comment]
Oh no! Could you post the error message you get from Patchwork when trying to open the latest release? There are a few things that could be going wrong and I don't want to say "delete your flume stuff!" unless that's actually the best course of action.

If you *are* interested in deleting your views, there are commands [here](https://github.com/ssbc/patchwork/issues/1041#issuecomment-492728086). You won't have to download new data from the network (:tada:), this just deletes your database indexes so they'll regenerate.

**Comment by marylychee** [comment]
no worries, @pospi in the end helped me out, so we deleted everything except from gossip, config and secret - sorry I didn't see your helpful suggestion first!!

luckily i was sitting next to Teq then in a local wifi, so I think I redownloaded everything mostly from them, relatively faster than last time this happened. 

I definitely knew it was an indexing error so super helpful to know there is a way for next time this might happen!

**Comment by marylychee** [comment]
ok things went whack again... 

I went ahead and tried your suggestions with: 
```
$ find ~/.ssb/flume/ -mindepth 1 -maxdepth 1 -type d -ok rm -rf {} \;
< rm ... /home/christianbundy/.ssb/flume/search > ? y
< rm ... /home/christianbundy/.ssb/flume/feed > ? y
< rm ... /home/christianbundy/.ssb/flume/query > ? y
< rm ... /home/christianbundy/.ssb/flume/private--oaWWDs8g > ? y
< rm ... /home/christianbundy/.ssb/flume/backlinks--oaWWDs8g > ? y
< rm ... /home/christianbundy/.ssb/flume/time > ? y
< rm ... /home/christianbundy/.ssb/flume/links > ? y
< rm ... /home/christianbundy/.ssb/flume/clock > ? y
```
and deleting ~/.ssb/flume/log.offset


I think I get this problem everytime I use patchbay from the repo folder & maybe i just go npm run dev
and I think I forget to run the sbot first? 

> ## Running the desktop app
> 
> Easy mode (embedded sbot):
> ```sh
> # from the patchbay repo folder
> npm start
> ```
> 

>Harder mode:
>```sh
>sbot server
> #from the patchbay repo folder
> npm run dev
> ```

anyways I *think* something is happening? I don't know

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18238352/59969871-1918c000-959c-11e9-9ebb-86c1a2c0fb6c.png">

**Comment by marylychee** [comment]
I also ran `npm run dist` following @mixmix suggestion [here](https://github.com/ssbc/patchbay/pull/348#issuecomment-504633867)

> the first one might be fatal.

**Comment by christianbundy** [comment]
Hmm, you shouldn't have to delete your offset file, was it throwing errors in Patchwork that made you have to delete that? The only useful data point is that I think Patchwork is using libraries that are more up-to-date than Patchbay, but that's all I've got.

Happy to hop on a call with you and debug if you'd like, it's a bummer things keep breaking. :/

**Comment by marylychee** [comment]
Ok, upon opening and closing Patchwork a few times I think it's indexing!! 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18238352/59970590-b6c8bb00-95ad-11e9-8305-9a7a089014f8.png">

Thanks helping out! Yeah it was a bummer. For next time, how do I see errors in Patchwork? I deleted it because doing the other flume things didn't seem to work. 

It's interesting as I definitely have had this problem at least 3-4 times in the last months and most of the time, it was because I'm jumping between Patchbay & Patchwork.

**Comment by christianbundy** [comment]
I think you can right-click anywhere on the screen and hit "Inspect element", then hit the "console" tab, and the errors *should* be there. Alternatively you can run from source and `npm start` and errors should be output to the console.

**Comment by marylychee** [comment]
ohkay. thank you!!  I think I now just have missing messages... in multiple threads. :O did I broke broke it, when it already broked? 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/18238352/60077204-cb9f7d00-976c-11e9-8bdb-f7194e7dd246.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/18238352/60077485-5f714900-976d-11e9-81a8-b965f372ca00.png">

**Comment by marylychee** [comment]
ok really frustrating :'(  I'm trying to write a post, and reference missing posts, ... and organise ssb website development, and kind of feel like I'm roadblocking everyone as my SSB is broke. 

<img width="367" alt="image" src="https://user-images.githubusercontent.com/18238352/60079376-2c30b900-9771-11e9-948d-b924ec9291ff.png">

**Comment by marylychee** [comment]
could I possibly have forked my feed?

**Comment by christianbundy** [comment]
The last post I see from you is `%dUC67XtTvRkTTF971zjcMzCMlIKzz8QBSUJKe45lgtM=.sha256`, is that correct?

**Comment by marylychee** [comment]
oh no.... that one is 4 days ago. 

what I see is last post is a private message w/ endo 17 hrs ago
and a public post 18 hrs ago... 
(Using patchbay to more easily see what I last posted)


<img width="1148" alt="image" src="https://user-images.githubusercontent.com/18238352/60144790-1d94e100-9807-11e9-97fb-19b0fead4be5.png">

**Comment by marylychee** [comment]
and 1 day ago... 

`%QO86kITfSin3xqlNswARuoVjaVoEmsL7dvaxqNyzrlk=.sha256`

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/18238352/60144952-c04d5f80-9807-11e9-9a17-6e2925b4ddb3.png">
3 likes on it??

**Comment by mixmix** [comment]
I see a message from you 2 hours ago : %Yupg2opyOct6JcDrRWyf60wm0gXeW1A6UzJO9/Z49Gk=.sha256

So I don't think you've forked your feed.

Really do not delete your `log.offset` file again without checking with a scuttlebutt dev. It's very very rare you should need to do that.

**Comment by mixmix** [comment]
it's still possible you are forked for some people, but very unlikely.
The way you would be forked is if you started posting before you had aquired all of your messages back again. That's unlikely because at the moment patchwork is pretty much locked up completely till indexing is all done ... patchbay you might have been able to find somewhere not locked up to post.

For reference if you start Patchwork and Patchbay both at the same time with `npm run start` or with installers, then they bounce off each other, and may partially run, but they won't mess anything up irrevocably. It's safe. With that `npm run lite` or `npm run dev` ... I haven't looked to see if patchwork hosts all of the plugins needed in patchbay at the moment ... actually I know it doesn't (ssb-meme isn't in patchwork), so I would expect that if you try to use that some pages will crash (and might crash the server).

I highly recommend only running one at a time. If you want the same ocnfig (like hops 2) you can set that.

**Comment by christianbundy** [comment]
I see you too -- sorry, I think Patchwork was hiding messages? I'm not sure, I still haven't wrapped my head around the feed summary stuff.

Those "cannot load thread" things are because you deleted the thread from your `log.offset`, sometimes it takes a while to load them back but they *should* come back. I don't think you've forked your feed either, you're good!

**Comment by marylychee** [comment]
damn. yeah ok I wont touch `log.offset` again. 

the cannot load thread is confusing. @mixmix what do you mean as locked up? even private messages? Because maybe that's where I was impatient and still sent things?

like as to why im not sure, I can load Mix's profile post and it stops here `%t4W5WtMY4Wknw+lIdz5WBkOWSooQL7j7znWbjqA+aE8=.sha256` - so max posts im getting up to is 6 days ago

where as with Mikey's profile - I have infinite load like ajax effect reaching up to 6 months ago. 

Is there anything I can do to fix? I'm very sure I ran `npm run dev`

**Comment by marylychee** [comment]
like so much of this is happening 

<img width="873" alt="image" src="https://user-images.githubusercontent.com/18238352/60226525-fc97c300-98ce-11e9-86ce-780e4bdbee85.png">

**Comment by christianbundy** [comment]
This is probably a silly question but have you restarted Patchwork? Maybe check `~/.ssb/gossip.json` and ensure that it's not empty? Not sure if you deleted that but if so maybe your Patchwork doesn't know which peers to connect to?

**Comment by pospi** [comment]
This *could* be unrelated bugs. I've been getting a lot of broken things in
Patchbay since v8 was released- often don't see any friends or follows,
have empty inbox, that kinda stuff. When it happens I usually just kill and
reopen the app and sometimes that helps, sometimes not. The same "have you
tried turning it off and on again" approach does not seem to be working
here :/

**Comment by pospi** [comment]
@mixmix maybe a useful debugging step here would be isolating such problems
to the UI or DB. If some of these "missing message" posts can be found in
the DB then that makes the cause of the bug clearer. It's also unclear
which parts of the DB are specific to Patchbay, and which to Patchwork.
Certainly it seems like different clients give different results.

The contents of `gossip.json` also sounds quite useful, maybe there's a
lack of peers near the root of the problem. These bugs have been happening
persistently, and @marylychee has restarted her clients and wiped
everything bar `secret` & `gossip.json` and done a full resync more than
once. None of that seems to have solved the problem, and she's not trying
to do anything fancy like running sbot separately- just running the apps as
packaged.

**Comment by marylychee** [comment]
@christianbundy yes restarted by closing and reopening a bunch of times and `~/.ssb/gossip.json` not empty. 

The error on patchbay

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/18238352/60234712-a8014180-98e8-11e9-8330-1ef25569384f.png">

I dont know... I think it's not UI @pospi ??

at this rate should I try deleting everything but `secret` & `gossip.json` again, as this time the unique problem was weirdness was from `rm -rf` alot of things from ~/.ssb/flume/
 
The infinite indexing error starts when I switch between patchwork/patchbay/commandline patchbay `run dev` too much.

**Comment by christianbundy** [comment]
Hey have you been running Patchwork from `master` or the latest released version?

**Comment by marylychee** [comment]
latest release. Version 3.14.1

**Comment by christianbundy** [comment]
Sweet, thanks. And have you deleted and rebuilt your indexes since you last opened Patchwork and Patchbay at the same time? Just trying to get a feel for what the current situation is, I'm really not sure why this would be happening.

**Comment by pospi** [comment]
I don't think you should be doing `npm run dev` either. Not sure who gave
that advice but it seems like a bad idea as it means running sbot
separately, doesn't it? I would only ever use `npm start`... keep it
simple...

**Comment by marylychee** [comment]
yes. I've just tried deleting and rebuilding my indexes. It was weird that it seemed to have finished rebuilding them *really fast*... and then so I've checked and still a bunch of missing messages. 🤷‍♀

**Comment by marylychee** [comment]
yes i didn't know that `npm run dev` needed sbot. i was developing so I thought that was better option. *sighs* 

okie dokie - I'm doing the thing. I'm doing to the whole delete everything but `secret` and `gossip.json` again. (and by delete I mean mv into another folder just in case)

**Comment by marylychee** [comment]
OK FIXED <3 THANK GOODNESS. 

have missed u all
