### ISSUE TITLE
When pushing a new sub-release, update the Release Install section with the right file version

### ISSUE THREAD

**Issue by SquidLord** [ssbc/patchwork#1110]
When you get a notification that there is a new version of Patchwork released, you head over to the Release page, look for your OS, click the link, and install, thinking all the while that you are going to be installing the new release.

At least in the case of the page as it currently stands, that's not true for the Windows build.

Especially for light releases, a couple of lines on what's changed since the previous release wouldn't go amiss, either.

This is largely a documentation problem, but it's definitely something that needs to get fixed before the notification that there is a new release goes out.

**Comment by christianbundy** [comment]
Thanks! It looks like I copied the wrong release notes. Just merged #1095 to make this mistake harder to make in the future. Sorry for any trouble!
