### ISSUE TITLE
In private messages, add a "To" field instead of @mentioning recipients

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1118]
A better solution to #1088 

* When starting a new private message, show a "To" or "Recipients" field above the main text box
* No longer make people recipients if they're @-mentioned in the body of the message
* Show warning or don't allow entry of more than 7 recipients (does this number include yourself?)

Reasons for this change

* Avoid accidentally making someone a recipient just by mentioning them
* More familiar and discoverable user experience
* Reduce confusion around adding recipients later in the thread - with the current mention-style it seems like you should be able to add people later by mentioning them, but you can't.  With this change it will be more clear because there will be no "To" box available after the first message

**Comment by cinnamon-bun** [comment]
Still relevant as a roadmap item

**Comment by black-puppydog** [comment]
is there some way to disable stale bot for some issues? I think this one will be relevant until fixed....?

**Comment by Powersource** [comment]
That's ^ how you make stalebot give up :P

**Comment by black-puppydog** [comment]
Now if only I had the skillz to actually do something about this. :cry:
