### ISSUE TITLE
UI to write blog entries

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1121]
So far, there seems to be no UI for this at all.
Doing it properly (from the commandline) involves:

* creating markdown file and adding it as blob. make sure you *don't* include the title in the markdown (as [everyone](https://viewer.scuttlebot.io/%2539f9I0e4bEln%2Byy6850joHRTqmEQfUyxssv54UANNuk%3D.sha256) and their dog seems to assume you should)
* crafting the correct json object
    * getting all the `&` mentions for blobs, including the blog entry itself
    * getting the byte sizes for each of the blobs

this should be possible to do in patchwork, and it could even be a third button if the user tries to post a message that breaches the 8KiB limit. "Do you want to publish this as a blog post instead?"

**Comment by Powersource** [comment]
I would argue this is outside the scope of patchwork. Does ticktack still work?

**Comment by cinnamon-bun** [comment]
Do blogs have the same purpose / semantic meaning as regular posts, but they're just longer and stored as blobs?

**Comment by Powersource** [comment]
They're stored as blobs and are usually longer, but I'd say they should be used sparingly, as regular posts' replication is a lot more consistent.

**Comment by trosel** [comment]
@cinnamon-bun would it solve your use case if you could just write regular posts in markdown?

**Comment by black-puppydog** [comment]
@trosel we already can. but that's not the point here (at least not mine, can't speak for cinnamon) because blog posts, as powesource said, are usually much longer.
Specifically, they exceed the maximum size that the ssb protocol enforces for a message, so longer posts would have to be broken up into multiple parts. Instead, you write one `blog` type message that references the `blob` holding the actual markdown. This allows for theoretically unlimited size blog posts (although most clients cap blob size at 5MB currently) and that's not something that the current format can do.

Regardless, I'd vote to close this, as it is definitely a new feature, and one that currently only tic-tac supports. So I think it is out of scope for an in-maintenance patchwork.
I think this would become relevant again if/when bamboo or other off-chain becomes a thing. because then, essentially every post would be similar to what a blog post is now.
