### ISSUE TITLE
Choose specific font(s) in settings

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1123]
Why:
* Choose a more readable monospace font than default Courier (e.g. on macOS)
* Choose a dyslexia-specific font

How:
* Change the font setting dropdown to list all installed fonts instead of just the 5 generic CSS font families.

This would also be a good time to make a separate setting for the composer font (vs. everything else) for people who want to write their Markdown in monospace.

**Comment by cinnamon-bun** [comment]
...complications:
* How to get a list of system fonts on all platforms
* Make sure emojis still work if they're missing from the font you choose (I'm not sure how this works right now)

**Comment by Powersource** [comment]
I think there are simpler solutions to this (for separate PRs):

1. Change the default macos monospace font (i.e. no option), if people generally agree that the system one is bad.
2. Add a checkbox option for switching to a dyslexia font.
