### ISSUE TITLE
Corrupt tag names on completion box

### ISSUE THREAD

**Issue by ivilata** [ssbc/patchwork#1124]
I came across a weird behaviour in Patchwork 3.12.0 (also present in 3.14.1). When I hit the *Tags* button in a message and start writing the name of a tag, I only get mangled, randomish 9-character tags which look like truncated Base64 text. All completions look like that, tags that I see in other posts or tags that I already used are not among completions either (or maybe they are under a mangled name since some bogus completions show a positive count). Tags already applied to the post show fine, but they don't show up in the completion box either.

I’m not sure if this will be related with #1037 that @christianbundy answered to (I noticed the same slowdown there), and I found no other similar reported issues.

**Comment by christianbundy** [comment]
Hey, just wanted to let you know that your issue is seen and understood. Sorry this is causing trouble for you. I don't really know how the tags code works, and I don't think anyone does (yet!). I've got some other things on my plate right now so I don't have the bandwidth to look into it, but I appreciate you taking the time to make an issue for this bug. I'll update you when I have time to debug and resolve this. Thanks!

**Comment by ivilata** [comment]
I checked and the issue is still present for me in 3.15.0.

**Comment by ivilata** [comment]
Still happening in 3.17.1. Is there anything I can run that involves cleaning up some cached items or something? Thanks!

**Comment by black-puppydog** [comment]
stumbled over this myself. seems similar to #930 ?

**Comment by black-puppydog** [comment]
I just had this again and after debugging a bit for #1037 I think this is related; after I specifically opened the tags page and let the in-memory representation of all tags be loaded, the suggestions started working fine.

**Comment by ivilata** [comment]
@black-puppydog I can reproduce the behavior that you mention in 3.18.0: tags appear mangled, then I visit the *Tags* page, let tags load, then go back to whatever page I was in and voilà, completion shows correct tag names again.

Thanks for the workaround! :smile:
