### ISSUE TITLE
Render regular quotes instead of Smart Quotes

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1125]
Markdown is rendered so that regular quotes `"` turn into smart quotes `“`.  Affects double and single quotes most of the time but not always.

This seems likely to cause problems when people try to share code with each other and cut and paste it from Patchwork.

Is this coming from [ssb-markdown](https://github.com/ssbc/ssb-markdown)?

**Comment by christianbundy** [comment]
Yeah, this was added to ssb-markdown here: https://github.com/ssbc/ssb-markdown/pull/30

I think this is the correct behavior, it only has an effect on text *outside* of code blocks. If you use single backticks you can post `"code"` or triple backticks to post:

```
"code"
```

There are also other problems if you post code outside of code tags, like `#!/usr/bin/bash` being parsed as a hashtag.
