### ISSUE TITLE
Is the patchwork brew cask safe?

### ISSUE THREAD

**Issue by Xeoncross** [ssbc/patchwork#1127]
I don't see any information about this in the install/readme/download guides. Is this safe to use / supported by the dev team?

```
brew search patchwork
==> Casks
patchwork                                            patchwork
```
Looks safe, but no mention of it anywhere makes me want to check.

https://formulae.brew.sh/cask/patchwork#default

**Comment by christianbundy** [comment]
I didn't know there was a brew cask, cool!

I don't know anyone who's maintaining it, but it looks like it's currently up-to-date and [the code](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/patchwork.rb) looks fine to me. If we can identify a maintainer who can keep the cask up-to-date then I'm happy to add a link to the Patchwork readme. I'm not on macOS or I'd be super down to take care of it myself.

**Comment by Powersource** [comment]
Seems to be [a whole bunch](https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+patchwork+is%3Aclosed) of people maintaining it, but @miikka has done a few of the updates.

**Comment by miikka** [comment]
Hi! I use the cask and I’ve updated it many times whenever there has been a new version and nobody else has done it. However, since my Patchwork usage has been on and off, I wouldn’t want to be considered as a maintainer.

**Comment by Powersource** [comment]
@miikka thanks for helping maintain it anyway :) Do you think we should keep looking for 1 maintainer, or doesn't brew work like that? (i.e. do updates always come from different people?)

**Comment by Xeoncross** [comment]
The [changes are pretty minor](https://github.com/Homebrew/homebrew-cask/pull/64974/files). If someone from SSBC just changed the SHA every release it would be pretty easy to have a trusted person do the update.

**Comment by miikka** [comment]
@Powersource, I think it's typical that the updates come from different people. There's even [an easy-to-use tool](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) for updating the version of a cask. You enter the new version and tool downloads the new version, calculates the hash, edits the cask and creates a pull request.

**Comment by Xeoncross** [comment]
Interesting, then perhaps a github webhook could handle this, or a plain git deploy hook.

    $ cd .git/hooks/
    $ vim post-receive

with something like this?

```
#!/bin/bash 
set -eu

BRANCH="master"

while read oldrev newrev ref
do
        # only run on changes to $BRANCH (or whatever branch you would like to deploy)
        if [[ $ref = refs/heads/"$BRANCH" ]];
        then
                cask-repair patchwork
        fi
done
```

**Comment by christianbundy** [comment]
We have a build bot, @hermes-bot, maybe we could integrate with that somehow?
