### ISSUE TITLE
Patchwork uses default system font

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1128]
![image](https://user-images.githubusercontent.com/1427063/59974497-2a1dfd00-95ad-11e9-85d9-4b758b3faefa.png)

Running arch linux. I have the packages `noto-fonts`, `noto-fonts-cjk`, `noto-fonts-emoji`, idk if that'd make a difference.

~~Guessing this is where it's from https://github.com/ssbc/patchwork/pull/1105~~ oops meant https://github.com/ssbc/patchwork/pull/1094

If I deselect this css in the devtools it looks normal again  
`font-family: system-ui, sans-serif;`

**Comment by Powersource** [comment]
Oh and cc @christianbundy I guess.

**Comment by Powersource** [comment]
This might be "my fault" tbh as my system settings are set to use "Droid Sans Mono Dotted Regular", but other programs handle this fine, and we don't know how many would be affected negatively by this change.

**Comment by christianbundy** [comment]
Yeah, this change is definitely coming from switching the font to the system UI font. If you've set your computer to use a specific font I think that's the font we should use in Patchwork, right? Is it common to have someone configure their OS to use a font that they don't want their apps to use? There's a font selection menu in the settings as well if you'd like to override.

**Comment by christianbundy** [comment]
Btw I removed "blocking release" because this change was already released in 3.14.1.

**Comment by christianbundy** [comment]
Backlink: https://github.com/ssbc/patchwork/pull/1101

**Comment by Powersource** [comment]
Ah missed that PR and that setting. Switching it to `sans-serif` seems to have fixed it. Also keeping system font and switching my system font to `DejaVu Sans Book` made stuff look kind of normal too, even if I'm a bit weirded out by stuff that used to be monospace (like firefox tab text) now are non-monospace :P
