### ISSUE TITLE
Blocked people still visible when a friend replies to them

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1132]
I follow A and I've blocked B.

I'm looking at A's profile page.  A has replied to a post by B.  It shows up like this:

```
B: my full original post
            View full thread (22)
A: my reply to B
```

Since I've blocked B I shouldn't see their post.  I don't know what behavior would be better:
1. Hide this entire thread
2. Replace B's original post with "(message from blocked user)" which links to the blocked user's profile page

Is this something to fix in Patchwork or is it coming from [ssb-friends](https://github.com/ssbc/ssb-friends)?

Patchwork 3.14.1.  This may change when we're deleting blocked content from the log (are we already?), but I don't know if the UI should rely on blocked content being absent.

**Comment by Powersource** [comment]
I don't think we're using ssb-friends, as mentioned here https://github.com/ssbc/patchwork/blob/master/lib/server-process.js#L31

The feed-deletion PR is merged, and while there are some weird remnants of the blocked person, I think their actual message should be completely gone. Could you try running master and see if this happens there?

**Comment by black-puppydog** [comment]
still relevant. seeing this on current `master` build with posts being shown that were created *after* I blocked. 
So I'm actually still replicating that blocked account for some reason.

![image](https://user-images.githubusercontent.com/189241/104767052-d7e29500-576b-11eb-80b9-f1121fac00b1.png)

**Comment by Spaceghost** [comment]
I can confirm it as well, I was going to open an issue but this one should suffice.
