### ISSUE TITLE
Channel names in other languages don't get "linked" on posts

### ISSUE THREAD

**Issue by kaotisk-hund** [ssbc/patchwork#1134]
Hi, I am glad I file an issue! Well, I use patchwork writing posts in greek and some versions ago, I was able to write #something-in-greek-channel and when the post was submitted or previewed the greek letter written channel was recognized as link and you could click the channel and go there and blah blah. Now, I see that this doesn't happen anymore. And I guess that something during rendering has gone off, cause the channels still exist but they can't get rendered to links. That's all I got, keep up the good work :)

**Comment by Powersource** [comment]
Yeah I've noticed this is a bit buggy too. I wrote something about how it affects `#malmö` but I can't seem to find that again...

**Comment by qubist** [comment]
( %it1ynal6T4eU6lA6MGU/ZG85+l4hlN6Fpuj5lNdARmA=.sha256 )

<img width="71" alt="Screen Shot 2019-07-20 at 6 03 16 PM" src="https://user-images.githubusercontent.com/3607279/61585759-d235d000-ab31-11e9-87e4-37438bbd7d5b.png">
<img width="79" alt="Screen Shot 2019-07-20 at 6 05 36 PM" src="https://user-images.githubusercontent.com/3607279/61585781-2771e180-ab32-11e9-8c5d-8fdd17a0e495.png">
<img width="85" alt="Screen Shot 2019-07-20 at 6 06 34 PM" src="https://user-images.githubusercontent.com/3607279/61585785-58521680-ab32-11e9-94bd-93beb766fd48.png">

Some observations about this behavior:
* the channel still gets mentioned successfully
* the link that the channel name is formatted with gets cut off before the first non-ascii character (I think)

**Comment by qubist** [comment]
This issue seems to be linked to [this one](https://github.com/svbergerem/markdown-it-hashtag/issues/2) in [markdown-it-hashtag](https://github.com/svbergerem/markdown-it-hashtag) which is the hashtag plugin for the markdown parser.

**Comment by qubist** [comment]
Ok also found a [duplicate issue](https://github.com/ssbc/ssb-markdown/issues/34) on the ssb-markdown repo which is where the code that manages this actually lives. @Powersource you wrote about `#malmö` in this thread. Conversation should continue in that thread, this one should probably be closed?

**Comment by Powersource** [comment]
Thanks for the digging!
