### ISSUE TITLE
Cannot release because of shared database

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1140]
Patchwork currently supports deleted messages because it uses ssb-server@15 but some other clients don't use that so I've been hesitant to release Patchwork for the past few weeks. If we release then users will encounter errors when they use another client that doesn't support deleted messages. There are a few potential solutions but they all have trade-offs and it all comes down to how we're sharing `~/.ssb/`.

**Comment by christianbundy** [comment]
cc: @mmckegg (in the context of shared identity spec, not Patchwork maintenance): do you have any thoughts on the best way to resolve this sort of thing? I remember you said you were working on this problem but I wasn't sure whether it was ready or a few months away.

**Comment by mmckegg** [comment]
@christianbundy 

We had [something that was a prototype](https://github.com/sunrise-choir/ssb-shared-identity), but that has probably been scrapped in favour of some kind of "sameAs".

My current idea about solving this:

- move to every app to running its own ssb-server with a unique ssb_appname, port and secret
- fix it in post (tie the apps together using some kind of sameAs/shared identity, but in the mean time each app just uses seperate identities)

**Comment by christianbundy** [comment]
I think those should work well. I'm a bit concerned about duplication, if we have ~6 clients then I think that would duplicate all of our downloaded messages and indexes. This is a bit specific to the JavaScript implementation, but last night I started thinking about the possibility of namespacing secret-stack plugins.

In a scenario where someone installs Patchwork for the first time it would give a directory to each secret-stack plugin and specify that Patchwork was using that version. For example, ssb-db@1 might be told to place its files in `~/.ssb/db/1/` and a file called `~/.ssb/apps.json` might set:

```json
{
  "patchwork": {
    "ssb-db": 1
  }
}
```

If someone installs Patchbay, which uses the same version of ssb-db, it would add a `"patchbay"` key to `apps.json` and reusing the existing data without any duplication.

If Patchwork upgrades to ssb-db@2 then secret-stack would copy `~/.ssb/db/1/` to `~/.ssb/db/2/` and switch the value for Patchwork in `apps.json` from `1` to `2`. Any secret-stack plugins that use the same version would be shared between clients but a major version bump would give them the ability to use different data-sets.

When Patchbay upgrades to ssb-db@2 in this scenario it would be able to use the previously-created directory without having to generate its own views, and as soon as the value is changed in `apps.json` then we would be able to safely delete `~/.ssb/db/1/`.

Alternatively, maybe duplication is fine for most people? My device only has 64 GB of storage so I'm especially sensitive to the duplication problem.

cc: @mixmix @dominictarr

**Comment by christianbundy** [comment]
Proposed solution: I'll make a PR that hides the auto-delete behavior behind an opt-in setting. Users who want feed deletion can enable it but we can keep it disabled by default until we're confident shipping it by default.
