### ISSUE TITLE
While indexing/syncing, can't follow accounts

### ISSUE THREAD

**Issue by staltz** [ssbc/patchwork#1142]
I was overseeing a friend onboard onto SSB through Wi-Fi sync, and noticed some UX difficulties they had. After receiving some data, you can see some accounts, and begin to follow them. However, as soon as you click "follow", that will recalculate your hops, and then will begin to request replication from many new feeds, so Patchwork went into indexing mode. During this time, the user wanted to follow more accounts, but for some reason, the "follow" button is deactivated while indexing. 

This made it hard to "click *follow* on a bunch of accounts and then wait" because it forced the user to wait in between each follow click.

**Comment by staltz** [comment]
No

**Comment by Powersource** [comment]
lol @stale he said no
