### ISSUE TITLE
Send Someone A PM (from their profile)

### ISSUE THREAD

**Issue by marylychee** [ssbc/patchwork#1149]
send a private message from a button on their profile page?? 

Intuitively I feel like it should be under 'options' but also right now options is like a menu drop down to choose how to follow or block someone. 

all this seems vague to a newcomer perhaps. But anyways maybe having an easy way to send a pm, which takes you to the private message page with the person's name tagged, might be a nice thing ux/ui wise

**Comment by christianbundy** [comment]
I think the button is over at the top right of the profile, can you confirm that it's showing up there for you? I'd be happy to merge a PR moving this somewhere else if there's a more ergonomic location for it.

**Comment by black-puppydog** [comment]
i see it there too. but honestly i noticed that like yesterday. i'd personally put it next to the "friends" and "options" buttons.
