### ISSUE TITLE
Images not loading until app restart

### ISSUE THREAD

**Issue by Frijol** [ssbc/patchwork#1150]
I have been leaving Patchwork open on my computer & for the last few days no images have been loading, including profile pics:

![Screen Shot 2019-07-30 at 7 51 33 AM](https://user-images.githubusercontent.com/454690/62140060-2d3c9500-b29f-11e9-9c5f-678f8099157b.png)

I restarted the app and it works fine now.

Version info:

![Screen Shot 2019-07-30 at 7 51 55 AM](https://user-images.githubusercontent.com/454690/62140100-3ded0b00-b29f-11e9-8fcf-d891f3fadd39.png)

It's a pretty minor bug, so if this is not really big enough to look into right now feel free to close.

**Comment by christianbundy** [comment]
Hey Kelsey! I'm happy to leave this open as a bug, maybe it's something that others are bumping into as well? I appreciate the info that restarting the app is a workaround. Please let me know if this happens again and we can try to debug -- hopefully this is just a fluke that we'll never see again.

:crossed_fingers:
