### ISSUE TITLE
Content warnings maybe shouldn't load images when they're closed

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1160]
Users may not want images from CW'd posts to be downloaded to their device.

Right now when a CW post is collapsed, the content is still being rendered to HTML (with images) but it's hidden using css `max-height: 0`.  It's using the same code that collapses very tall posts.

Fixing this would mean adding a second variable to track CW expansion, and not rendering the content at all when it was collapsed.  (And making sure it interacts well with the tall-post expansion code.)

[Here's where to start](https://github.com/ssbc/patchwork/commit/c76136fb1628ec7fd4bb10b181d70ced01bb120c#diff-3562e4b70e817fca2acfe0da7e1b0edd), in lib/depject/message/html/layout/default.js line 91.

**Comment by cinnamon-bun** [comment]
This could be controlled by #1159 which is about settings for CW behavior

**Comment by black-puppydog** [comment]
I missed this one when you first proposed it, so I'm sorry to jump in here just now, but for what it's worth, I think we should make a clear distinction between mechanisms that will impact what *I see* on my device, and mechanisms that impact how content *spreads* across the network.
An example for the former is a content warning, an example for the latter is a (public) block.

Specifically, I take issue with the proposed behaviour for two reasons:

1. If patchwork downloads messages with CW, but refrains from loading attached blobs, then those won't be available offline.
2. If this became established in other clients, it would prevent the CW'd blobs from spreading if the *sending* side goes offline. That is, if I post a CW'd message with attached blob, it will not spread *at all* until someone manually opens it. If I am offline by that point, it will be unavailable until I'm back online. Of course, pubs usually don't have CW handling, but I wouldn't want to rely on pubs for blob distribution to work at all.
