### ISSUE TITLE
Include message size when complaining about it being too large

### ISSUE THREAD

**Issue by justinabrahms** [ssbc/patchwork#1161]
When I attempt to post a message that's too large, I get the error: "Encoded message must not be larger than 8192 bytes".

How big is the message I tried to post? Feedback would be useful here.

Why isn't there validation earlier in the process (e.g. the preview side) which accounts for message encoding overhead?

**Comment by justinabrahms** [comment]
I believe this is still relevant.

**Comment by black-puppydog** [comment]
So I made a PR to ssb-validate, and tested that it works for me if I manually add my branch of `ssb-validate` to `package.json` as a direct dependency. But `ssb-db` explicitely requires `"ssb-validate": "^4.0.0"` and I don't feel qualified to change that. 
I guess one would need to...
* make a new release tag for `ssb-validate`
* update the dependency in `ssb-db` to that release
* make sure everything still works
* `npm i` in patchwork and release a new `package-lock.json`

correct?
