### ISSUE TITLE
Patchwork stuck v3.16.2

### ISSUE THREAD

**Issue by marylychee** [ssbc/patchwork#1173]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/18238352/63403724-c173c500-c423-11e9-9ffd-461ca956f0e9.png">

After I got new patchwork (awesome work on the channel btw) I'm stuck tho.

After one interaction I get stuck on indexing, and got to close/restart the client. When I click on something again, it gets struck again. 

Seems like I can still see you messages @christianbundy and you replied to me :D
`%cuYEcBsMyYyPhMlaxBCmpl4wuWtDMv2HGm8it/sEEOg=.sha256`

**Comment by marylychee** [comment]
ok fixed, redownloaded latest.

**Comment by christianbundy** [comment]
Happy the new download works! More info here: https://github.com/ssbc/patchwork/issues/1170
