### ISSUE TITLE
Local peers no longer connecting?

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchwork#1175]
I no longer see other local peers show up in the sidebar.  Tested with another Patchwork on another laptop (don't know the version right now) and Manyverse.

In the Manyverse connection tab I see my Patchwork identity appearing and disappearing once a second.

It's possible this is a networking issue but it used to work here, so maybe it's some recently upgraded dependency in Patchwork?

MacOS 10.11.6
Seems to happen on Patchwork 3.14.1, 3.15.0, 3.16.2

**Comment by bitsapien** [comment]
+1 Same here

**Comment by christianbundy** [comment]
Hmm, that's no good. I can confirm that it "works on my machine", but that's not very helpful.

@cinnamon-bun Are there any versions where it still works okay for you? I think we were all using v3.14.1 at dweb camp, and I remember that a bunch of people were showing up in the local sidebar when we were on the same access point.

@bitsapien Which OS are you on?

**Comment by christianbundy** [comment]
Maybe useful: do local peers show up in other clients? I think Oasis should be using all of the same networking software as Patchwork but Patchbay might be slightly different.

**Comment by black-puppydog** [comment]
Worked for me this morning, manyverse & patchwork.
