### ISSUE TITLE
More infinite scuttling and loading, just started in ssb-patchwork-3.16.2-x86_64.AppImage

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1184]
More infinite scuttling and loading, just started in ssb-patchwork-3.16.2-x86_64.AppImage

Shut down, reload, stops it.

It''s doing this, over and over and over:
```
Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
Exception thrown by PacketStream substream end handler Error { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
Exception thrown by PacketStream substream end handler Error { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
Exception thrown by PacketStream substream end handler Error { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
Exception thrown by PacketStream substream end handler Error { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
```

_Originally posted by @bhaugen in https://github.com/ssbc/patchwork/issues/702#issuecomment-525901683_

**Comment by christianbundy** [comment]
Thanks for reporting this @bhaugen! Are you able to open Patchwork at all, or is it totally broken?

**Comment by bhaugen** [comment]
If I shut it down and restart, it's fine. I had several infinite scuttles yesterday, and then today it started getting better. I suspect some data problems, but could be wrong.

**Comment by bhaugen** [comment]
This continues to happen especially if I sleep the computer and then start it up again, if that helps a diagnosis. Same error messages over and over, and same shutdown-restart solution.

I'm still on ssb-patchwork-3.16.2-x86_64.AppImage

**Comment by jalcine** [comment]
I’m currently having this problem. I removed the socket file thinking it’d recreate it.

(Originally published at: https://v2.jacky.wtf/post/cc302416-b25d-4bc2-916f-6ec22823f3b7)
