### ISSUE TITLE
Not connecting to pubs

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#1186]
> Since last week my patchwork also stopped picking working peers to connect and I made a bash script to run gossip.connect $peer calls from a self-chosen list of pubs. Deleting the gossip.json file didn’t change a thing. It’s always picking the same broken/unrachable ones… :(
(fwd of `%O8TZxzA0j2b5aXCXCGcq/SKoM0CDZDC2DVWZlDoQ12A=.sha256`)

not sure what else to share besides an endless list of ECONNREFUSED from my patchwork console from the same 3 pubs over and over.

```
...
info @p13 SSB- friends:sp4.solarpunk.dk:8008:@SP4xNZmDsOuRrjDS6NCcmr3xoieXQOMPBQ4TkUHSJ2M=.ed25519 CONNECTING
info @p13 SSB- friends:sp3.solarpunk.dk:8008:@SP3xGpWJJjhdX78uZiT/hKwTShtSAt4VFZ7OQm9ggzI=.ed25519 CONNECTING
info @p13 SSB- friends:pub.scuttlebuttchess.co.uk:8008:@GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA=.ed25519 CONNECTING
info @p13 SSB- friends:sp4.solarpunk.dk:8008:@SP4xNZmDsOuRrjDS6NCcmr3xoieXQOMPBQ4TkUHSJ2M=.ed25519 ERR "connect ECONNREFUSED 2001:19f0:5001:2e1:18f6:81fd:662d:7921:8008"
info @p13 SSB- friends:sp3.solarpunk.dk:8008:@SP3xGpWJJjhdX78uZiT/hKwTShtSAt4VFZ7OQm9ggzI=.ed25519 ERR "connect ECONNREFUSED 2a01:7e00::f03c:91ff:fea1:75a9:8008"
info @p13 SSB- friends:pub.scuttlebuttchess.co.uk:8008:@GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA=.ed25519 ERR "connect ECONNREFUSED 68.183.32.46:8008"
...
```

oh and i'm using 428f3de1ea2aef72f7e991b9cf61dd85e0b1e24c, so a bit more recent then v3.16.2.

**Comment by christianbundy** [comment]
:(

Could you maybe try the `conn` branch and see if that resolves it? I can't think of any recent changes that might break that. If that doesn't work, maybe a `git bisect` with the last known good version? Sorry I don't know what else it could be.
