### ISSUE TITLE
Include field names in profile page to display what your name and public key are

### ISSUE THREAD

**Issue by trosel** [ssbc/patchwork#1189]
![image](https://user-images.githubusercontent.com/1299322/65377045-4a755a80-dc75-11e9-9f82-021302270498.png)

Lines to edit are around here https://github.com/ssbc/patchwork/blob/master/lib/depject/page/html/render/profile.js#L148

**Comment by christianbundy** [comment]
Thanks for the feature request! I'd love a PR to add information about these fields.
