### ISSUE TITLE
Use dark title bar on Linux

### ISSUE THREAD

**Issue by aadilayub** [ssbc/patchwork#1193]
Currently Patchwork uses a light grey title bar when dark mode is enabled (at least on stock GNOME).

![Screenshot from 2019-10-07 14-07-15](https://user-images.githubusercontent.com/31581044/66299025-27e96f80-e90c-11e9-808a-b0f1cb87684a.png)

It would be nice if the titlebar also becomes dark when dark mode is toggled. 

[Aether](http://getaether.net), another P2P electron app does a pretty good job with this:

![Screenshot from 2019-10-07 14-06-54](https://user-images.githubusercontent.com/31581044/66299119-549d8700-e90c-11e9-9f84-16cd61e6313e.png)

[Standard Notes](http://standardnotes.org) is another Electron app that makes good use of CSD:

![image](https://user-images.githubusercontent.com/31581044/66305746-6a657900-e919-11e9-920b-6eac2dc2f296.png)

**Comment by aadilayub** [comment]
I'd like to help with this issue, so I'm compiling links/relevant info from other projects to help resolve it:

- https://wiki.gnome.org/Initiatives/CSD
- https://github.com/electron/electron/commit/058d0bbe19a61b0709ac75cb258ee65147d9ac57
- https://gitlab.gnome.org/GNOME/gtk/issues/99

**Comment by ajacobs-isp** [comment]
@aadilayub I looked through those links and it does looks possible.  In looking at the Patchwork code the window is instantiated super early and that "dark" flag must be set when it's opened.  (It can't be changed later like many other window options)  I also wasn't 100% sure that the user preferences are available that early so you can check if the theme preference is set to "light" or "dark".  Correct me if I'm wrong there.

**Comment by funwhilelost** [comment]
@aadilayub I looked through those links and it does looks possible.  In looking at the Patchwork code the window is instantiated super early and that "dark" flag must be set when it's opened.  (It can't be changed later like many other window options)  I also wasn't 100% sure that the user preferences are available that early so you can check if the theme preference is set to "light" or "dark".  Correct me if I'm wrong there.
