### ISSUE TITLE
Pasting secret file on new computer install breaks Patchwork

### ISSUE THREAD

**Issue by jrmoreau** [ssbc/patchwork#1195]
I pasted my secret associated with my profile into a fresh install of Patchwork on my new computer after my last crashed. I pasted the secret into the secret file in `~/.ssb/`

Now after saving the secret file and restarting my comp the app just won't launch at all. It's on MacOS Catalina 10.5

Am I missing a step?

**Comment by christianbundy** [comment]
Hey @jrmoreau, sorry to hear you're running into an issue.

Are there any other files in `~/.ssb/`, or just `secret`? I'd try starting Patchwork from the command-line, that way you'll see debug info and hopefully some useful error messages.

**Comment by jrmoreau** [comment]
Thanks @christianbundy - what commands should I try? Happy to keep troubleshooting. Was resigning myself to just creating a new profile entirely.

**Comment by christianbundy** [comment]
I'd personally do something like:

- Close Patchwork and don't open it until you're done
- Create a copy of your secret (and `gossip.json` / `conn.json` if you have them)
- Delete `~/.ssb`
- Re-create `~/.ssb`
- Move the file copies you made earlier into `~/.ssb/`
- Start Patchwork

**Comment by jrmoreau** [comment]
@christianbundy so this is the issue - I didn't backup the gossip.json or conn.json. Only the secret because I thought it was all I needed. That's my mistake.

**Comment by christianbundy** [comment]
That's fine, Patchwork should still open fine even if you don't have the `gossip.json` or `conn.json`.

Two questions:

- Are you running from the source of `master`, or one of the binary builds?
- If you're comfortable sharing it here, what's your public id (should start with `@` followed by a bunch of letters and numbers)?

**Comment by jrmoreau** [comment]
@christianbundy 

- I downloaded Patchwork from https://ahdinosaur.github.io/patchwork-downloader/

- from the secret file I backed up originally my ID is @q7DgocQPPqfkwF8rvsBfdvl6bNq5XNXH4p4aGqSADyU=.ed25519

Patchwork opens fine if I open it from scratch. As mentioned, when I replace the "secret" file in ~/.ssb/ with the exact file I backed up originally, that's when it just doesn't open anymore.

**Comment by christianbundy** [comment]
Are you opening Patchwork before creating the secret? You should never be *replacing* the secret file, you should be inserting the secret file into an empty `~/.ssb/` directory before opening Patchwork.

**Comment by christianbundy** [comment]
Here's a minimal `gossip.json` that should let you replicate with my personal server to get your messages:

```json
[
  {
    "host": "oasis-demo.fraction.io",
    "port": 8008,
    "key": "@samhAxb0x+iykkzoUCsuEBQfFUuYQrVFyNBuMpibidc=.ed25519",
    "address": "net:oasis-demo.fraction.io:8008~shs:samhAxb0x+iykkzoUCsuEBQfFUuYQrVFyNBuMpibidc=",
    "source": "stored",
    "announcers": 0,
    "duration": {
      "mean": 0,
      "stdev": 0,
      "count": 0,
      "sum": 0,
      "sqsum": 0
    },
    "stateChange": 0,
    "failure": 0
  }
]
```

**Comment by christianbundy** [comment]
Btw, it's important that when you use the new secret you don't publish *anything* until you're done syncing. Please avoid using pub invites as well, since those post a message to your feed.

**Comment by jrmoreau** [comment]
Last question before I give it another go @christianbundy what is the file type a secret should be? .json or something else? I just copied the plain text from it and I am not sure if I should save it as a specific format before dropping it into ~/.ssb/

Thank you for all your help!

**Comment by christianbundy** [comment]
Nope, just `~/.ssb/secret` is great. It's not valid JSON because it has `#` characters for comments, but it should be added without a file extension.

**Comment by jrmoreau** [comment]
@christianbundy did the steps as shown - Patchwork just bounces a couple times and never opens. No error being shown.

**Comment by christianbundy** [comment]
Any chance you could attempt building Patchwork from source in this repository? You *may* be able to get error output by running the app from a terminal, but running from source is generally best for debugging.

**Comment by jrmoreau** [comment]
@christianbundy are all the instructions to build from source in the Readme? Seems it was a bit incomplete but just want to make sure regarding which commands I should use.

**Comment by christianbundy** [comment]
The readme should point to the install file: https://github.com/ssbc/patchwork/blob/master/docs/INSTALL.md

**Comment by jrmoreau** [comment]
@christianbundy 

Installed `brew install libtool automake`

fetched repo from Github, CD into directory, ran `yarn` and got this

`No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jamesmoreau/patchwork/node_modules/cld
gyp ERR! node -v v12.11.0`

Is there another command or step I am missing?

**Comment by christianbundy** [comment]
Could you run `brew doctor` to ensure that Homebrew is set up correctly? Looks like maybe you need Xcode.

I googled your error message and this came up: https://github.com/nodejs/node-gyp/issues/1861

I'd try: `xcode-select --install`

If that doesn't work, maybe: https://stackoverflow.com/a/15371967/3236521

**Comment by jrmoreau** [comment]
So I tried to uninstall xcode and reinstall and a lot of those errors went away. What command do I do after yarn?

**Comment by christianbundy** [comment]
Oops, that doesn't look like it's documented. That should be `yarn start`,

**Comment by jrmoreau** [comment]
thanks @christianbundy - I built from source and did `yarn start` and Patchwork opened normally. Then I shut it down with Cntrl+C, then opened ~/.ssb/, deleted the secret file, put my actual secret file in there and also the gossip file in the same directory. Then tried to do `yarn start` again and it didn't open and showed me the following. 

```yarn run v1.19.1
$ electron index.js
SyntaxError: Unexpected token h in JSON at position 1
    at JSON.parse (<anonymous>)
    at reconstructKeys (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:59:23)
    at Object.exports.loadSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:78:12)
    at Object.exports.loadOrCreateSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/index.js:87:20)
    at setDefaults (/Users/jamesmoreau/patchwork/node_modules/ssb-config/defaults.js:55:27)
    at module.exports (/Users/jamesmoreau/patchwork/node_modules/ssb-config/inject.js:7:16)
    at setupContext (/Users/jamesmoreau/patchwork/index.js:187:43)
    at App.<anonymous> (/Users/jamesmoreau/patchwork/index.js:54:3)
    at App.emit (events.js:205:15)
SyntaxError: Unexpected token h in JSON at position 1
    at JSON.parse (<anonymous>)
    at reconstructKeys (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:59:23)
    at Object.exports.loadSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:78:12)
    at Object.exports.loadOrCreateSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/index.js:87:20)
    at setupContext (/Users/jamesmoreau/patchwork/index.js:208:28)
    at App.<anonymous> (/Users/jamesmoreau/patchwork/index.js:54:3)
    at App.emit (events.js:205:15)
TypeError: Cannot read property 'id' of undefined
    at setupContext (/Users/jamesmoreau/patchwork/index.js:211:23)
    at App.<anonymous> (/Users/jamesmoreau/patchwork/index.js:54:3)
    at App.emit (events.js:205:15)
✨  Done in 0.54s.```

**Comment by christianbundy** [comment]
Thanks for building from source.

It's very important that you do not start Patchwork before trying to put your secret file in. Please follow [these instructions](https://github.com/ssbc/patchwork/issues/1195#issuecomment-556051081) and let me know if you still get an error. Good luck!

**Comment by jrmoreau** [comment]
@christianbundy did it again as described and got:

```SyntaxError: Unexpected token h in JSON at position 1
    at JSON.parse (<anonymous>)
    at reconstructKeys (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:59:23)
    at Object.exports.loadSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:78:12)
    at Object.exports.loadOrCreateSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/index.js:87:20)
    at setDefaults (/Users/jamesmoreau/patchwork/node_modules/ssb-config/defaults.js:55:27)
    at module.exports (/Users/jamesmoreau/patchwork/node_modules/ssb-config/inject.js:7:16)
    at setupContext (/Users/jamesmoreau/patchwork/index.js:187:43)
    at App.<anonymous> (/Users/jamesmoreau/patchwork/index.js:54:3)
    at App.emit (events.js:205:15)
SyntaxError: Unexpected token h in JSON at position 1
    at JSON.parse (<anonymous>)
    at reconstructKeys (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:59:23)
    at Object.exports.loadSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/storage.js:78:12)
    at Object.exports.loadOrCreateSync (/Users/jamesmoreau/patchwork/node_modules/ssb-keys/index.js:87:20)
    at setupContext (/Users/jamesmoreau/patchwork/index.js:208:28)
    at App.<anonymous> (/Users/jamesmoreau/patchwork/index.js:54:3)
    at App.emit (events.js:205:15)
TypeError: Cannot read property 'id' of undefined
    at setupContext (/Users/jamesmoreau/patchwork/index.js:211:23)
    at App.<anonymous> (/Users/jamesmoreau/patchwork/index.js:54:3)
    at App.emit (events.js:205:15)
✨  Done in 0.48s.```

**Comment by christianbundy** [comment]
Could you verify that `~/.ssb/secret` looks correct? It looks like the first character might be an `h`.

The file should look exactly like this:

```
# this is your SECRET name.
# this name gives you magical powers.
# with it you can mark your messages so that your friends can verify
# that they really did come from you.
#
# if any one learns this name, they can use it to destroy your identity
# NEVER show this to anyone!!!

{
  "curve": "ed25519",
  "public": "g7ilirhnQ3KIDZ2SOXLqQXzz9e3xP3f1csTTKJF2CHM=.ed25519",
  "private": "rtbQFPE9RQ423VhQiTaAZ466eYurkZiWagf/5mstg2mDuKWKuGdDcogNnZI5cupBfPP17fE/d/VyxNMokXYIcw==.ed25519",
  "id": "@g7ilirhnQ3KIDZ2SOXLqQXzz9e3xP3f1csTTKJF2CHM=.ed25519"
}

# WARNING! It's vital that you DO NOT edit OR share your secret name
# instead, share your public name
# your public name: @g7ilirhnQ3KIDZ2SOXLqQXzz9e3xP3f1csTTKJF2CHM=.ed25519
```

(I made a temporary identity to test this, please don't ever share your secret!)

**Comment by jrmoreau** [comment]
@christianbundy thanks for all your help. At some point (not sure why) I started to not even see the ~/.ssb/ file being generated upon building from source anymore 🙃  - might choose to just create a new profile at this point. Just concerned about how I can reliably back my account up and restore if needed. Tried this on my Mac and Ubuntu machine. No dice either way.

**Comment by christianbundy** [comment]
Hmm, the `~/.ssb/` directory should be created whenever you start Patchwork.

Could you verify that the `~/.ssb/secret` file you backed up looks correct? I'm wondering whether maybe there was a copy + paste error or something that's throwing the above errors.
