### ISSUE TITLE
Auto-switch between dark and light mode based on system settings

### ISSUE THREAD

**Issue by trosel** [ssbc/patchwork#1197]
Utilize electron's nativeTheme API. It was just released in Electron 7  https://electronjs.org/blog/electron-7-0

**Comment by trosel** [comment]
Requires electron to be updated first https://github.com/ssbc/patchwork/issues/1198

**Comment by ajacobs-isp** [comment]
@trosel Is this a dupe or similar to #1193 ?

**Comment by funwhilelost** [comment]
@trosel Is this a dupe or similar to #1193 ?

**Comment by trosel** [comment]
@funwhilelost This is different. #1193 is about a specific styling request. This is about switching themes based on the System settings.
