### ISSUE TITLE
When someone flags a message as spam, the spammer gets a weird JSON message

### ISSUE THREAD

**Issue by feross** [ssbc/patchwork#12]
@mafintosh flagged my message as spam and then I got this message in my inbox:

```
{"type":"flag","flag":{"link":"%wb6717KILS+jLhnxSBklL+og+8/a7Mu27wlOte4FRFM=.sha256","reason":"sp...
3m ago
```

**Comment by pfraze** [comment]
Hah ok, will look into that

**Comment by mafintosh** [comment]
You could also just stop spamming @feross

**Comment by feross** [comment]
https://www.youtube.com/watch?v=6UJpupxhdEw

**Comment by pfraze** [comment]
Resolved in the latest build.
