### ISSUE TITLE
Topics: message format & basic behaviors

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#120]
(This issue is just about the data model for public groups.)

Groups are effectively just a filter on post messages.

 1. How do posts set their group? Can posts have multiple groups?
 2. How are groups declared? Are they unique entities, declared by a message, which the member-messages link to? Or are they simply text-labels?

**Comment by pfraze** [comment]
One thing to decide is, are we implementing Groups, or Topics?

Topics are just a label (sort of like hash-tags) for categorizing posts.

Groups usually have members. In a public group, membership wouldnt do much more than be a social-signal. In secret groups membership will matter more.

If groups are things which must be declared as messages, and linked-to, then you need the original message to know what the group is.

**Comment by pfraze** [comment]
I suggest we just do this as topics, with the following schema:

```js
{
  type: 'post',
  topic: String|[String],
  ...
}
```

Each topic is a string. You can have multiple topics to cross-post in multiple groups. Patchwork builds an index for each topic.

Two options on how to handle topic comparisons:
 1. Require an exact match to consider two topics to be ===.
 2. Make topics case-insensitive, and strip non-alphanumeric characters, such that `'foobar' === 'Foo Bar' === 'foo-bar' === 'foo_bar' === 'foo$bar'`. Patchwork's UI will forbid spaces and non-alphanum characters, to discourage their use. This is to try to reduce the possible variations on the same intended topic.

At first I was inclined toward 2, but maybe it's better to do 1? Why: 1 doesnt presume everybody speaks english, and it gives more flexibility to users, even if can result in more mis-posting.

**Comment by pfraze** [comment]
Some composer mockups:
![screen shot 2015-11-25 at 3 29 41 pm](https://cloud.githubusercontent.com/assets/1270099/11409982/6d1de11c-9389-11e5-94d0-441dada0fb7d.png)
![screen shot 2015-11-25 at 3 29 52 pm](https://cloud.githubusercontent.com/assets/1270099/11409981/6d1c8204-9389-11e5-93ad-8d6e59c5786d.png)

**Comment by pfraze** [comment]
Making topics more distinct in the composer:
![screen shot 2015-11-25 at 3 38 16 pm](https://cloud.githubusercontent.com/assets/1270099/11410132/aa2a73d0-938a-11e5-9c6d-7c12788fb224.png)

**Comment by pfraze** [comment]
Mockup of topics in the sidenav:
![screen shot 2015-11-25 at 3 47 17 pm](https://cloud.githubusercontent.com/assets/1270099/11410285/db1ac534-938b-11e5-9a00-b9c89b5bfd61.png)

**Comment by pfraze** [comment]
Mockup of topics in the topnav of the msg feed:

![screen shot 2015-11-25 at 4 04 44 pm](https://cloud.githubusercontent.com/assets/1270099/11410656/c065d398-938e-11e5-9ba0-cfb7cbc6b197.png)
![screen shot 2015-11-25 at 4 06 10 pm](https://cloud.githubusercontent.com/assets/1270099/11410657/c066e634-938e-11e5-9185-9e72aa46e4cb.png)

**Comment by pfraze** [comment]
Another mockup of topics in the newsfeed, this time replacing the main toolbar:
![screen shot 2015-11-25 at 4 26 56 pm](https://cloud.githubusercontent.com/assets/1270099/11410972/6e12abae-9391-11e5-987c-c6527294a66e.png)

**Comment by pfraze** [comment]
Increasingly leaning toward only allowing 1 topic on a msg, not multiple

**Comment by aredridel** [comment]
Definitely 1. The second is so magical.

the namespacing of these groups is likely to be a major problem -- I tend to have a huge network, and the chance of people colliding on names will make it more like twitter hashtag shouting than any kind of conversation.

**Comment by pfraze** [comment]
agree

**Comment by dominictarr** [comment]
putting everything on the right hand side is probably okay for now, but sooner or later someone will create a million things.

shall we just make a simple one though, and worry about that later? we can keep the same data format, and just change the way the UI collects them?

**Comment by pfraze** [comment]
https://github.com/ssbc/ssb-msg-schemas/pull/12

**Comment by ahdinosaur** [comment]
made a comment that is better suited for this thread: https://github.com/ssbc/patchwork/pull/134#issuecomment-160516990

**Comment by ahdinosaur** [comment]
or actually i recommend ignoring what i just said, since not all links are the same and it's important to provide semantics / meaning to our links. as in, a topic channel shouldn't show *all* messages that backlink to the channel identifier, only the messages that backlink to the channel identifier *through* the link "topic".

more on topic relations in existing linked data implementations: http://patterns.dataincubator.org/book/topic-relation.html

**Comment by pfraze** [comment]
Implemented
