### ISSUE TITLE
Sign releases for macOS, Windows, or both

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1202]
Forked from: https://github.com/ssbc/patchwork/issues/836#issuecomment-545561518

See also: https://www.electron.build/code-signing

Patchwork has [~$5.3k](https://opencollective.com/patchwork/) and I think that *at least* an Apple certificate would solve a common installation pain point. IIRC the newest macOS release makes it even harder to open unsigned apps, and this has been on my todo list forever.

Would this be an acceptable use of Patchwork funds? I don't really want to pay Apple money to make Patchwork usable on their system, but I think the benefits may outweigh the costs.

cc: @cinnamon-bun @Powersource

**Comment by MatthewSteeples** [comment]
For getting it working on Windows, I have used and can recommend [this service](https://www.ksoftware.net/code-signing-certificates). There may well be other places that offer free certs to open source (eg [Certum](https://en.sklep.certum.pl/data-safety/code-signing-certificates.html) appear to do OSS discounts, but that looks to require some hardware for it to be worth doing)

**Comment by coreagile** [comment]
This is super helpful for folks like me who only have access to a work computer that has been so locked down we are not allowed to authorize unidentified apps at all.

**Comment by manishbajpai** [comment]
I think we are talking about $99 fee that apple charges per year, right? If this is the sticking point, can I say that apple also provides a relatively more secure OS (I have no affiliation with apple. Am just a user) and even if that is not true, apple users would appreciate a notarized app. If the cost is still an issue, is there a US charitable non-profit that can receive donations?
