### ISSUE TITLE
linux appimage for v3.17.1 leads to 404

### ISSUE THREAD

**Issue by aadilayub** [ssbc/patchwork#1212]
https://github.com/ssbc/patchwork/releases/download/v3.17.1/ssb-patchwork-3.17.1-x86_64.AppImage

![image](https://user-images.githubusercontent.com/31581044/69654971-7bb83f80-1097-11ea-8e59-675dd8e136e1.png)

Maybe it's a typo? Scrolling down and clicking on the asset itself leads to a successful download. The link in the release notes doesn't work though.

**Comment by black-puppydog** [comment]
confirmed, this is a trivial linking bug. but given #1213 maybe don't upgrade quite yet...

**Comment by christianbundy** [comment]
@aadilayub Thanks for reporting this! I've fixed the link in the release notes and added some info for the #1213 fix. Please upgrade!

**Comment by aadilayub** [comment]
Thanks guys!
