### ISSUE TITLE
"Possible connections" glitches

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1215]
Two things:

- My local pub, libra.fraction.io, keeps popping up at the top of the "possible connections" list every second and then *immediately* disappears. This makes it impossible to click and very visually distracting because it's making the others in the list move up and down in a stuttery fashion once per second. I think "pub.evbogue.com" and "Ql06HdDq1" have the same problem, but they take a few moments to show up again.
- When I hover "ansuz" and click it registers the click and the pub leaves my screen for a moment, but then it comes back. I'm not seeing any error output anywhere, but I'm guessing a connection is failing somewhere?

cc: @staltz

**Comment by staltz** [comment]
This seems to be mostly caused by timing issues in ssb-conn. My fault and I'll think about a solution
