### ISSUE TITLE
Aligned blockfile crash

### ISSUE THREAD

**Issue by dangerousbeans** [ssbc/patchwork#1221]
on e0870c4c3935888c009c46ba549bdb3598460ac1 with an old index, it runs into this:

removing the indexes fixed it, but this issue was there even between releases :c

```sh
$ npm run start

Error {}
Error {}
RangeError: Maximum call stack size exceeded
    at get (/Users/joran/development/patchwork/node_modules/aligned-block-file/blocks.js:1:1)
    at Object.readUInt32BE (/Users/joran/development/patchwork/node_modules/aligned-block-file/blocks.js:93:9)
    at /Users/joran/development/patchwork/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /Users/joran/development/patchwork/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Users/joran/development/patchwork/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Users/joran/development/patchwork/node_modules/aligned-block-file/blocks.js:93:9)
    at Object.getMeta (/Users/joran/development/patchwork/node_modules/flumelog-offset/frame/recoverable.js:31:12)
    at getMeta (/Users/joran/development/patchwork/node_modules/flumelog-offset/inject.js:42:11)
    at next (/Users/joran/development/patchwork/node_modules/pull-cursor/cursor.js:26:11)
    at /Users/joran/development/patchwork/node_modules/pull-cursor/cursor.js:19:11
```

**Comment by christianbundy** [comment]
Thanks for the bug report!

What does "with an old index" mean? Or "this issue was there even between releases"? It looks to me like a problem reading `~/.ssb/flume/log.offset`, so I'm not sure why deleting your indexes would solve it, but I'd love some more info on what happened.

**Comment by dangerousbeans** [comment]
I just upgraded from one release before latest, to latest. So the index was
made with an older patchwork

**Comment by christianbundy** [comment]
Thanks, that's helpful. Was deleting the indexes the first thing you tried?

**Comment by dangerousbeans** [comment]
1 leave overnight
2 console output
3 ssb-doctor thing
4 indexes

**Comment by christianbundy** [comment]
Did you restart Patchwork? Also, by "delete indexes" do you mean *only* the indexes or did you delete `~/.ssb/flume/log.offset` too? The error you pasted was from Patchwork trying to read `~/.ssb/flume/log.offset`.

**Comment by dangerousbeans** [comment]
Whatever the delete indexes button does on the first aid thing, never used
it before

Yes I tried restarting patchwork many many times

**Comment by christianbundy** [comment]
Cool, thanks for all the info. I think the trick here is going to be editing aligned-block-file and flumelog-offset to make sure the real error event is being propaganted. I've seen that `Error {}` output before and it haunts me.

**Comment by asymmetric** [comment]
For others that might be hitting this, [the first aid thing](https://github.com/ssbc/ssb-first-aid-kit/releases). It seems to have worked for me too.
