### ISSUE TITLE
Document "who to follow"

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1224]
Maybe Patchwork should have an FAQ

**Comment by black-puppydog** [comment]
Do we know where people mostly find patchwork? That is, where do they click the "download" button? That would be the place to put that FAQ, no?
Candidates I can think of:

* Release announcements
* Github repo
* ssb website

**Comment by christianbundy** [comment]
Do you mean in the release notes? There's a FAQ in there: https://github.com/ssbc/patchwork/blob/master/docs/release-notes-template.md

**Comment by emaG3m** [comment]
I personally found it / clicked download on the ssb website: https://scuttlebutt.nz/get-started/
(hello, here bc this issue was filed as a result of a question I asked  ^_^)

**Comment by black-puppydog** [comment]
Ohhhh, there's an FAQ shaped hole in that page!

![image](https://user-images.githubusercontent.com/189241/70569102-8d224100-1b99-11ea-959a-4c436b4f3e7f.png)

Of course, this would not be an issue if github allowed linking to the latest stable release with release notes to begin with... :neutral_face:
