### ISSUE TITLE
Debian package in 3.17.2 release links to broken .dmg link

### ISSUE THREAD

**Issue by patrickbolle** [ssbc/patchwork#1230]
The Debian package link directs to a .dmg file which doesn't exist it seems either:
https://github.com/ssbc/patchwork/releases/tag/v3.17.2

Here is the URL the "Debian" link goes to: https://github.com/ssbc/patchwork/releases/download/v3.17.2/ssb-patchwork_3.17.2.dmg

Should be linking to: https://github.com/ssbc/patchwork/releases/download/v3.17.2/ssb-patchwork_3.17.2_amd64.deb

Cheers!

**Comment by christianbundy** [comment]
Oops, thank you! I'll fix this ASAP.

**Comment by christianbundy** [comment]
Fixed in the current release notes and just started a PR to fix in future release notes.
