### ISSUE TITLE
feature request: sort search results

### ISSUE THREAD

**Issue by vi7Quuce** [ssbc/patchwork#1232]
use case:
i remember seeing a recent post about some topic X, and i want to find it again. topic X is quite common and is often discussed in my feed.

when searching in patchwork, results seem to be ordered by relevance. if i could order them by date, i would be able to find the post in question. as it is now, it's buried somewhere in hundreds of posts containing keyword X.

**Comment by christianbundy** [comment]
Thanks for the issue. I agree that's a problem and your solution seems reasonable. I'd merge a patch for that.
