### ISSUE TITLE
Bifurcated messages 

### ISSUE THREAD

**Issue by gmarcos87** [ssbc/patchwork#1233]
If the bifurcated messages can be reconstructed linearly in a thread they should not be rendered as separate threads.
When I wanted to create a succession of messages I was commenting on the last one I added. The result was a chaos of threads and forked messages.

**Comment by gmarcos87** [comment]
See %UcdJrZ5C0ZMPe/NdjNIjSC0uDU001otRyBLINtPz7+k=.sha256 as example

**Comment by Powersource** [comment]
This is "intended behaviour" (for some definition of intended). We want to improve the ux of replies in threads, see this issue for more info https://github.com/ssbc/patchwork/issues/1060
