### ISSUE TITLE
In-app help

### ISSUE THREAD

**Issue by crabmusket** [ssbc/patchwork#1234]
[This page](https://scuttlebutt.nz/docs/introduction/detailed-start/) has heaps of extremely good information about how Patchwork works. For example, the paragraph under the heading "What are all these pubs listed in the Patchwork sidebar? I didn’t join those!"

IMO it'd be really nice for new users to have access to this information immediately within the app itself. For example, adding help buttons [inline with the appropriate sections](https://user-images.githubusercontent.com/904269/71936350-486fe100-31fd-11ea-8cc1-2ac625418d3f.png).

At the very least, things like this could link to the appropriate parts of the website, and help people discover that content. But as a local-first app I think it'd be even better to have the help fully inlined with the experience.

If people like this idea I'd be happy to work on some code :slightly_smiling_face:

**Comment by christianbundy** [comment]
Good idea, I'd be happy to merge something like this.
