### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1238]
Maybe just a crazy experiment I'd like to try, feel free to ignore

Made a thread about it earlier `%VmSd/+sZlkj7uj0oQEwc6pfK+c/bU0Os6/4M7ZxvlIo=.sha256`

Christian replied with some helpful info:

==================

> But is there any way (I don’t think so) to tell patchwork to use a temporary .ssb dir in /tmp

I think that's the `--path` flag, the default is `--path ~/.ssb/`.

> and to not gossip(different network key?)?

With SSB conn we just have to set the config option:

```json
{
  "conn": {
    "autostart": false
  }
}
```

See the `--offline` flag in Oasis for implementation details, but I think that's it.

====================

And I was planning to use cypress but that seems [very alpha](https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/) so far, I wonder if there's anything more mature for electron.

**Comment by Powersource** [comment]
`--path` seems to work great, tried `ssb-patchwork --path '/tmp/patchwork-test-1'` and got a fresh profile

![image](https://user-images.githubusercontent.com/1427063/72664616-5a713100-3a00-11ea-8381-16d55971051a.png)

**Comment by Powersource** [comment]
After a brief web search [Spectron](https://electronjs.org/spectron) seems to be the most popular and mature framework for this.

**Comment by johanbove** [comment]
Integrations are really useful for sure. Thanks for adding this @Powersource 
What do you think of adding a unit test framework too? Something like Mocha.js or Jasmine.js could help make the code base more robust.

**Comment by Powersource** [comment]
Yeah as I mention in the PR

> Eventually I want to move it to look more like the second link, with mocha and stuff, but the first one is simpler so it's probably a better place to start getting it to work.

First step is to get the test tool to work at all :p

**Comment by Powersource** [comment]
as mentioned in the PR, this is unlikely to happen now

**Comment by black-puppydog** [comment]
I want *any* kind of test. Just "does it load and show more than a blank screen" will be the baseline for this.
