### ISSUE TITLE
Settings keyboard shortcut is now global on macOS

### ISSUE THREAD

**Issue by miikka** [ssbc/patchwork#1240]
Whenever I have Patchwork running in the background and I press `Cmd+W` in some other application, instead of that application doing whatever `Cmd+W` does, Patchwork goes to the settings view. What I expected is that the active application handles `Cmd+W` and Patchwork doesn't do anything.

* The intended Patchwork keybinding may be `Cmd+,`. I'm using Dvorak keyboard layout, but some applications handle keybindings as if I was using the Finnish layout which is what is physically printed on the keys. 
* I'm running Patchwork 3.17.2 on macOS Catalina 10.15.2

**Comment by christianbundy** [comment]
Maybe a local shortcut would solve this? https://electronjs.org/docs/tutorial/keyboard-shortcuts

**Comment by miikka** [comment]
Seems like a good idea. The `Cmd-,`/`Cmd+w` mixup is a probably bug in Electron: https://github.com/electron/electron/issues/19747

**Comment by Gozala** [comment]
I noticed that patchwork seems to steal all the keyboard shortcuts whenever it's running so most keyboard shortcuts on other apps like Firefox stop working. I'm pretty sure this is recent regressions as it did not used to be the case before

**Comment by christianbundy** [comment]
I'd be comfortable merging a patch that used a local shortcut *or* reverts the patch that added this behavior.
