### ISSUE TITLE
Profile Description (Bio) empty

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1245]
![Screenshot at 2020-02-01 19-30-11](https://user-images.githubusercontent.com/189241/73597230-1e72bb80-452a-11ea-9596-0535666fb18b.png)

This is on the `3.17.2` commit ( `e4b61a40abf91bdc46a79cf5bc5705649bfcf868` ) but running from git.

Second time this happened today. A restart fixed it, now it's back. My last profile update is not so long ago: `%FqdIfBdumTcMISmFNscJ7cAduPGgQ6WfzobdRsN+EgU=.sha256`
In the inspector, it just looks like this:

![image](https://user-images.githubusercontent.com/189241/73597278-7b6e7180-452a-11ea-8f8c-b9829c2d7b57.png)

**Comment by christianbundy** [comment]
Hmm. I think I saw someone else (Martin?) mention this as well. Absolutely no idea. :(

**Comment by johanbove** [comment]
It's happening in version Patchwork 3.17.6 as well. Unclear what is going on.

**Comment by black-puppydog** [comment]
I haven't seen this one anymore. @johanbove?
I'd tend to close since not reproduced and it clutters the issue tracker...

**Comment by johanbove** [comment]
@black-puppydog  Yep, can be closed. Issue is resolved. Thanks.

**Comment by johanbove** [comment]
Haven't seen it happening either in a while... Not sure if it's still happening. But we can close this for now. @black-puppydog
