### ISSUE TITLE
Preview hanging when URL pasted in post - since 3.17.3

### ISSUE THREAD

**Issue by Danie10** [ssbc/patchwork#1249]
I had been using this code to insert a preview of a YouTube video and it would appear fine. But I noticed since 3.17.3 (executing an AppImage on Manjaro Linux) that it just sits at the "publishing" stage before it shows the preview to publish.

I tested with normal text and it previews fine before publishing.

Tested identical YouTube preview text using older version and it previews fine.

Have also tried trying latest update with the no sandbox option (saw no errors though).

Code I'm using in my post: 
`[![Nextcloud Video](http://img.youtube.com/vi/CKHDxROPUyY/0.jpg)](http://www.youtube.com/watch?v=CKHDxROPUyY)`

So I'm just wondering if any of the changes in the version update may have caused this or whether it is likely a purely local issue?

**Comment by Danie10** [comment]
See this error uin terminal after hitting publish button:

TypeError: Cannot read property 'link' of null
    at /tmp/.mount_PatchwaLjgdW/resources/app.asar/lib/depject/message/html/compose.js:272:42
    at Array.map (<anonymous>)
    at HTMLButtonElement.publish (/tmp/.mount_PatchwaLjgdW/resources/app.asar/lib/depject/message/html/compose.js:270:44)
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: fullscreen.js:14:9
Remote event names: leave-full-screen

**Comment by Danie10** [comment]
Actually let me close this more now as I see I am running the new AppImage, but noticed I have the old version installed from AUR. Let me wait a few days for AUR to update and then try with same install. There may be clashes.

**Comment by Danie10** [comment]
Waiting for AUR update rather.

**Comment by Danie10** [comment]
Have installed the latest version using AUR on Manjaro. I thought the issue was only for my YouTube links, but after testing now with a normal website URL and image, I get the same issue. Just see the publishing button greyed out but no preview pops up. I tried adding the --no-sandbox but made no difference.

A post without any image links or URL is previewing fine.

**Comment by Danie10** [comment]
After rebooting etc and further testing, I noticed even if I just paste a URL link into my post, the preview does not come up. Markdown for headings and bold are working fine.

So it may be something to do with any link pasted into my posts.

**Comment by Danie10** [comment]
Tested same post from Patchwork v3.17.2-2 and 3.17.3 using AppImages - works fine on older version, hangs on newer one.

**Comment by black-puppydog** [comment]
@Danie10 the last comment would imply this is still broken on recent builds... did you test this with 3.18?
