### ISSUE TITLE
Deleting posts?

### ISSUE THREAD

**Issue by ilookedeverywhere** [ssbc/patchwork#1250]
I feel pretty nervous about the fact you cannot edit or delete posts currently on scuttlebutt. Doesn't that go against the idea that your content is _your content_ and you can choose _if_ that content is shared, now or in the future?

I saw an older "issue" post that addressed this, and the comments said a feature was already being worked on to address this. That was back in 2018. Has anything been changed on this matter since then? :)

**Comment by christianbundy** [comment]
Hi. Deleting posts is a thing that most of us want, but it hasn't been implemented yet. If this is something you'd like to work on I'm sure some of us on SSB could help guide you on how to do it, but it *would* be an upgrade to the protocol. Sorry, I don't think this is something we can handle in the Patchwork client..

**Comment by Powersource** [comment]
This is being worked on slowly (look for discussions on e.g. gabby grove on scuttlebutt. And yeah this isn't something we can implement in patchwork right now, but hopefully in the future. Closing this issue now, if you don't mind :)

**Comment by tiotrom** [comment]
Any updates on this? Also, where can I follow the progress? Thanks!
