### ISSUE TITLE
https links not opening in default browser on NixOS

### ISSUE THREAD

**Issue by wakest** [ssbc/patchwork#1252]
I have my default browser set to Firefox, but when I click on a link in Patchwork they open in Gnome Web. I am running NixOS and i3 and using [Patchwork 3.17.2](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/ssb/patchwork) which is the one packaged by Nix Package Manager

**Comment by christianbundy** [comment]
Hmm, that's not good. What happens when you open a terminal and `xdg-open https://example.com`? I really don't remember how those defaults get set.

**Comment by wakest** [comment]
@christianbundy it opens in firefox.

**Comment by wakest** [comment]
confirmed this bug exists on another users install on NixOS today.
