### ISSUE TITLE
UI: Avatar images are stretched

### ISSUE THREAD

**Issue by johanbove** [ssbc/patchwork#1256]
As mentioned [here](https://viewer.scuttlebot.io/%25m1%2FVR8PhIRWIOLlX%2FLStyxtNX%2FgE2gz9Ed1ltWXL7o0%3D.sha256)

**Comment by black-puppydog** [comment]
Game, set, match! Props to @johanbove :)

**Comment by johanbove** [comment]
I seem to have missed a couple of places where the "avatar" image still looks stretched. Will look into this later.
