### ISSUE TITLE
Mac builds have a firewall prompt on every start and don't work

### ISSUE THREAD

**Issue by interfect** [ssbc/patchwork#1260]
Every time I start Patchwork 3.17.5 on Mac, I get a dialog that says:

> Do you want the application “Patchwork Helper (Renderer).app” to accept incoming network connections?

Even if I hit Allow, the next time I start Patchwork I get the same dialog.

Patchwork also seems to be unable to connect to local peers unless I turn off the system's firewall.

**Comment by christianbundy** [comment]
Sorry to hear this, that's not very useful. Does this happen on other SSB clients as well?

**Comment by interfect** [comment]
I haven't tried any other ones; which ones use a compatible version of sbot so I can run them without screwing up my database? I have had trouble swapping between Patchwork and Patchbay in the past on other machines.

March 20, 2020 12:37 PM, "Christian Bundy" <notifications@github.com (mailto:notifications@github.com?to=%22Christian%20Bundy%22%20<notifications@github.com>)> wrote:
	Sorry to hear this, that's not very useful. Does this happen on other SSB clients as well?
