### ISSUE TITLE
UI: Avatar image for Profile on Light theme overflows box

### ISSUE THREAD

**Issue by johanbove** [ssbc/patchwork#1263]
See screenshot for an example.

<img width="1067" alt="Annotation 2020-03-12 143954" src="https://user-images.githubusercontent.com/922765/76527381-6bbe4300-646f-11ea-97f1-4c43b2963984.png">

**Comment by johanbove** [comment]
Currently looking into fixing this.

**Comment by christianbundy** [comment]
I think this was fixed in #1265, yeah?

**Comment by black-puppydog** [comment]
actually, not sure if this is related, but on `master` I'm seeing this sort of layout right now for *all* profiles, not just the ones with non-square profile pics:

![Screenshot_20200321_001013](https://user-images.githubusercontent.com/189241/77212704-77ada300-6b08-11ea-821f-a43a8966c871.png)

**Comment by christianbundy** [comment]
Fun! I wonder why. :/

**Comment by johanbove** [comment]
Perhaps a difference between light and dark mode?

**Comment by johanbove** [comment]
@black-puppydog Thanks for the bug report! Indeed, my "fix" broke that. I just managed to get Patchwork running from the source code locally on my Windows machine and I will fix this avatar issue.

**Comment by johanbove** [comment]
@christianbundy  Please see PR #1267

**Comment by christianbundy** [comment]
Merged! Thanks for that fix.
