### ISSUE TITLE
Always use thread root in replies

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#127]
%GlaVnOqyq0eEvM95AUvzsDKyRr9FcT6/tPlXw+Be7nY=.sha256 illustrates this bug

If you are looking at a non-root of a thread, and post a reply, the root link will be the non-root. That's incorrect - PW should automatically traverse up to the known root.

**Comment by dominictarr** [comment]
hmm, to view a pasted in link in patchwork, currently, the easiest way is to paste it into a draft post, hit preview, and then click on the link.

**Comment by pfraze** [comment]
@dominictarr https://github.com/ssbc/patchwork/issues/92
