### ISSUE TITLE
Spellcheck: please add setting to toggle spellchecking

### ISSUE THREAD

**Issue by kseistrup** [ssbc/patchwork#1272]
It's annoying to have every other word underwaved in red when composing a post. Would it be possible to add a settings item so that spellchecking can be disabled?

**Comment by christianbundy** [comment]
Hi, thanks for the issue. This sounds like a bug to me, the spell checker shouldn't be underlining everything in red. Are you writing posts in the same language that you're using Patchwork with? Or could you add some more info about how you've installed Patchwork? I'd love to fix the bug if possible.

**Comment by kseistrup** [comment]
Oh Bundy, what a shitty issue I posted. I'm sorry.

I meant to submit an enhancement request, I'm pretty sure it's not a bug. When I wrote “every other word” I just meant that I see too many words in underwaved red. I don't use the spellchecker at all, so underwaved words are just a nuisance to me and I want to disable it completely. As far as google knows, it has to be done from the application. I had hoped to fiddle with `~/.config/Eelectron/Preferences` and be done with it for everything that uses electron, but that didn't work.

I installed patchwork via https://aur.archlinux.org/packages/ssb-patchwork with no changes to the PKGBUILD file.

**Comment by christianbundy** [comment]
No problem at all, it's good to chat with you anyway! I think it should be pretty simple to add a way to disable the spell checker by adding a checkbox in the settings. I'll look at it in the next couple days and see if I can figure something out for you!

**Comment by Powersource** [comment]
> Are you writing posts in the same language that you're using Patchwork with

i guess the spellchecker is for the currently selected language then? Will still be a problem for people with languages not selectable in the settings, e.g. swedish. and even then people can write in multiple languages. a hard problem but yeah just being able to disable it mostly fixes it.

**Comment by vtexier** [comment]
Hello, sorry I'm french, and I write a lot of message in English in Patchwork.

The top of the top would be to _select the language of the spellchecker in the parameters_, like we can do with the language of the GUI.

Default will be the same.

I'd like to be helped with the English spellchecker with the french GUI.

**Comment by kseistrup** [comment]
Is a stale bot really useful? Now this issue (and other issues closed by stale bot) will remain in oblivion.

**Comment by black-puppydog** [comment]
@kseistrup it's mostly an acknowledgement of the status quo: there's barely any energy being put into patchwork development. given that, the choice was between "leave all issue open, and have a completely useless issue tracker" or "close all issues without activity, to retain the use of the tracker for those issues that are being addressed." I think nobody's really that happy about it, because both options kinda suck. 

FWIW, if you do have an issue for patchwork, it makes sense to just use the search function in the top right because it finds closed issues by default, too.

**Comment by kseistrup** [comment]
@black-puppydog I fully understand and I think either choice is a bad one. If keeping all issues open until resolved renders the issue tracker useless, then it's just as useless to have a gazillion closed issues, because nobody will ever wander into that area and start resolving issues there — many of them may even be there because they indeed have been resolved and closed, not just because they are stale and closed.
