### ISSUE TITLE
French locale missing some translations

### ISSUE THREAD

**Issue by vtexier** [ssbc/patchwork#1273]
Using Patchwork 3.17.6

In the french GUI: 
* If I "Like" a message ("Aimer") the message become "**Liked**" not translated to "**A aimer**".
* Writing a new message display "**new**" at the top right corner, not translated to "**nouveau**".

**Comment by black-puppydog** [comment]
I'm not really qualified to make these changes. 
But the format for the file is *really* simple. It's just the file `locales/fr.json` and with #1275 most of the yet to be translated strings are in that file, and just need to be changed.

If you want to you can just edit them directly in the github web UI. In that case I'd just need to verify on my machine that the translations still work before we can merge the changes. 
Or I quickly coach you into how to test this locally if you prefer. :)

**Comment by black-puppydog** [comment]
(je peux aussi essayer de faire le coaching en français. :) )

**Comment by vtexier** [comment]
Catched missing translations again:
* The friend options are not translated.
![patchwork_menu](https://user-images.githubusercontent.com/2174016/80523704-c6afe900-898e-11ea-8017-d93aca16f6d3.png)

* The age of a message is not translated:
![patchwork_age](https://user-images.githubusercontent.com/2174016/80523740-d92a2280-898e-11ea-9687-792ddfe3c5fd.png)

**Comment by black-puppydog** [comment]
Something of a standing issue. Feel free to send patches. :)
