### ISSUE TITLE
Broken link for snap package in description for v3.17.7

### ISSUE THREAD

**Issue by willemolding** [ssbc/patchwork#1284]
In the description the link points to https://github.com/ssbc/patchwork/releases/download/v3.17.7/ssb-patchwork_3.17.7.snap but should point to https://github.com/ssbc/patchwork/releases/download/v3.17.7/ssb-patchwork_3.17.7_amd64.snap

I know it is easy to scroll down to the files and download it but it should only be a 3 second fix

**Comment by christianbundy** [comment]
Nice catch! Here's where that's generated: https://github.com/ssbc/patchwork/blob/master/docs/release-notes-template.md
