### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by fabiopolancoe** [ssbc/patchwork#1288]
I tried to run the Patchwork AppImage from Ubuntu Mate but the command line throws this error 

`bash: ./Patchwork-3.17.7.AppImage: cannot execute binary file: Exec format error`

And when i try to run it from Caja (File Manager): Creates a file with this title:

> �F@@��@8@ (invalid encoding)

**Comment by christianbundy** [comment]
Hi! Sorry you're bumping into this problem. Could you post the output of `uname -a`? My guess is that you have the wrong AppImage (e.g. you're using the amd64 binary on arm64) or something similar.

**Comment by fabiopolancoe** [comment]
I am using amd64 on an amd64 processor with a i386 OS. Thanks!

**Comment by christianbundy** [comment]
I don't think Patchwork supports i386 right now. :/ You may have better luck with [Oasis](https://github.com/fraction/oasis) (disclaimer: I work on Oasis and love it) but I'm not familiar with what goes into an i386 OS.

**Comment by fabiopolancoe** [comment]
Ohh, thanks i will also try to run it with WineHQ or directly using Windows but just let me check oasis :wink:
