### ISSUE TITLE
Patchwork fails to start with Node v5.0.0

### ISSUE THREAD

**Issue by magician11** [ssbc/patchwork#129]
When I run `patchwork` using node v5.0.0 I get

`App threw an error when running [Error: Module version mismatch. Expected 46, got 47.]`

Details of error are in this [screenshot](https://dl.dropboxusercontent.com/u/14057353/Screen%20Shot%202015-11-26%20at%2011.06.02%20am.png) (I couldn't copy the text for some reason).

It runs totally fine using node v 4.2.2.

**Comment by dominictarr** [comment]
@pfraze I managed to get past this error by reinstalling things. It looks like this is caused by chloride, which should be installed... @magician11 can you switch back to 5 and try `npm rebuild`?

**Comment by pfraze** [comment]
Solved by https://github.com/ssbc/patchwork/pull/210
