### ISSUE TITLE
Infinite scuttling

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1291]
Hi @christianbundy,

I just replicated this issue. Infinite Scuttling. I read this issue's comments out of order, so *first* I did your `find` to delete cache files etc., which didn't fix things on its own, and when starting Patchwork, saw the following console output:

```
/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/flumelog-offset/inject.js:47
        value: codec.decode(codec.buffer ? value : value.toString()),
                     ^
                                                                                           
SyntaxError: Unexpected token  
```

Eventually I took a backup of `~/.ssb`, deleted the contents of the `flume` directory (except for `log.offset`), and ran `fix-flume-log`, which showed:
```
Ignored error: SyntaxError: Unexpected token  in JSON at position 68
```

Is there any data I can send to help pin down this issue (I still have my old `log.offset`)? It's likely I had two clients running at once at some point and this might've broken things. I'm running Patchwork 3.17.7.767 and Patchbay 8.1.0 on MacOS 10.15.4.

_Originally posted by @mattcen in https://github.com/ssbc/patchwork/issues/1192#issuecomment-631412921_

**Comment by christianbundy** [comment]
Hey @mattcen, sorry you've bumping into this! It's strange that your `log.offset` isn't working with `fix-flume-log`, could you confirm that it's still not working? The 'ignored error' text you posted suggests to me that the error should be fixed now, but if it's not working for you then that's a problem!

Happy to synchronously pair on this sometime if you're a morning person, your 8 am is my 3 pm IIRC.

**Comment by mattcen** [comment]
Gah, sorry for my lack of clarity, @christianbundy; I missed sharing the bit where, in *spite* of the `Ignored error` from `fix-flume-log`, running that *did* fix my problem and I was able to start Patchwork again without issue (after a bunch more indexing).

I guess my question was more around whether or not the `log.offset` corruption was something that is intended to be preventable and whether sharing further data (like the corrupt version of my log) is something that would help track down why it's happening, or whether it's just that having both Patchwork and Patchbay open at once is Not Supported™ (in which case presumably it'd be worth them sharing a lockfile or something to prevent them both trying to write to the database at once)?

I'm happy to pair on this sometime if you think it'd help fix the broader issue, but for extra clarity, my current issue is resolved.

**Comment by christianbundy** [comment]
Oh, no problem at all. I think fix-flume-log could be clearer -- it found a corrupted message, which it skipped, and that's when it produced the "Ignored error" thing. It didn't hit an error, it hit corrupted JSON that it could circumvent.

Patchwork and Patchbay have loads of scuttle-baggage, and are built on foundations that were great for learning but not great for production. For example, FlumeDB is interesting to hack on, but it gets corrupted easily and is super super super slow compared to boring tools like SQLite.

I'm kinda on the "throw my hands up in the air and rewrite a bunch from scratch" end of the spectrum, so I'm doing that with [Oasis](https://github.com/fraction/oasis), and I'm hoping that solves all of these foundational problems without having to deep-dive Patchwork/etc. (FWIW, I don't think anyone is actively working on Patchwork because it's so hard to hack on. I run `npm update` and push releases regularly, but I'm not really touching the current stack very much.)

**Comment by mattcen** [comment]
That all makes sense; thanks for the explanation! Shame, because I rather like the UI of Patch* (though sometimes I still struggle to find posts; not sure if I'm using them wrong or what).

**Comment by christianbundy** [comment]
> Shame, because I rather like the UI of Patch*

If there are any improvements you'd like to make to Oasis, I'd be super down for feedback in that repo. :tada:

**Comment by aadilayub** [comment]
Running into this issue as well. Opening Patchwork after using Oasis causes patch to be stuck indexing forever
![image](https://user-images.githubusercontent.com/31581044/86521725-f76c3d00-be6d-11ea-9f27-4a7ebcf57791.png)

**Comment by ergl** [comment]
I'm also getting this, after trying Oasis, Patchwork no longer works. That's a shame, because I'd prefer to continue using Patchwork. Is there any way of solving this?

**Comment by christianbundy** [comment]
Can you try opening Patchwork from the CLI? There shouldn't be a problem running them both on the same computer as long as you don't start Patchwork while Oasis is running in the background.

**Comment by ergl** [comment]
@christianbundy Unfortunately it's still not working (stuck at the Indexing database phase). This is what I get:

```
Error: could not connect to sbot
    at /usr/local/lib/node_modules/git-ssb/node_modules/ssb-client/client.js:55:17
    at next (/usr/local/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:24:14)
    at /usr/local/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:34:9
    at _cb (/usr/local/lib/node_modules/git-ssb/node_modules/multiserver/plugins/shs.js:28:20)
    at /usr/local/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:118:22
    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:10:5
    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:23:13
    at callback (/usr/local/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:81:7)
    at drain (/usr/local/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:68:39)
  Error: shs.client: server hung up when we sent hello (phase 3).
Possibly we dailed a wrong number, or the server does not wish to talk to us.
    at abort (/usr/local/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:37:45)
    at Object.cb (/usr/local/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:52:26)
    at drain (/usr/local/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:43:23)
  Error: stream ended with:64 but wanted:80
    at drain (/usr/local/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:43:26)
    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:63:18
    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:20:7
    at drain (/usr/local/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:147:5)
    at Socket.emit (events.js:326:22)
    at TCP.<anonymous> (net.js:672:12)
```

And then, a bit later, it prints a bunch of these:

```
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:133:41)
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/ssb-client/node_modules/muxrpc/pull-weird.js:58:44
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/sinks/drain.js:20:24
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream-codec/index.js:98:24)
    at drain (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:46:23)
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:63:18
    at drain (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/stream-to-pull-stream/index.js:143:5)
```

**Comment by christianbundy** [comment]
Is it possible that you might have Oasis running in the background? Apologies if you've tried this already, but have you been able to reproduce this problem after restarting your computer?

**Comment by ergl** [comment]
@christianbundy No, oasis wasn't running in the background. I also can confirm that this still happens even after a restart, getting the same error.

**Comment by mattcen** [comment]
Today I also had a problem with Patchwork not finishing its indexing, but I was getting a different error on the terminal.

I fixed my problem by deleting caches etc, using the following command, which I found on another GitHub issue a while ago:

**Note: This is a destructive command; while it *should* only delete non-essential files, if there's unexpected stuff in your `~/.ssb` directory, that'll be removed too**

```
find ~/.ssb \
  -type f \
  -not -name config \
  -not -name secret \
  -not -name log.offset \
  -not -name conn.json \
  -not -name gossip.json \
  -not -name manifest.json \
  -not -name delete-nonessential \
  -not -path '*/.ssb/blobs/*' \
  -delete
```

I wonder if that's worth a shot?

**Comment by ergl** [comment]
@mattcen Seems like that did the trick! Patchwork works fine now
