### ISSUE TITLE
Am I Forked

### ISSUE THREAD

**Issue by hutson** [ssbc/patchwork#1292]
I've been using using Patchwork for a few years now (@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519), but I've recently started to wonder if, at some point during that period of time, I accidentally forked by feed/log. While I don't comment often (Very rarely in truth), I have made a few comments that have made we wonder if others in the Scuttleverse are not receiving my messages.

So I thought I would throw out the idea that it would be nice if Patchwork provided a way to determine if my feed was still replicating correctly through the network, or whether, perhaps, my feed has forked. In the latter case it would be helpful if Patchwork could provide guidance on how to recover from a forked feed.

**Comment by black-puppydog** [comment]
Hi Hutson,

I can see your feed and you're a "friend of a friend" so I should see your updates.
However, the lastest message I get is this:

```
ssb-server getLatest '@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519' | jq .                                                                        master|… 23:53
{
  "key": "%0kelcgwpkwHXYibdgdH3eodRuRPDORfYno9NmeaPfXA=.sha256",
  "value": {
    "previous": "%WFZtjS1GbmO5Lfe7Arhxj3Rc1mjXZ36Dm3FmHetEKtY=.sha256",
    "author": "@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519",
    "sequence": 164,
    "timestamp": 1540527711224,
    "hash": "sha256",
    "content": {
      "type": "vote",
      "vote": {
        "link": "%b2VuxjJi2v8GkPb8Koe2UTY+LHYbjIY8AghBri7ryTA=.sha256",
        "value": 1,
        "expression": "Like"
      }
    },
    "signature": "Eq0meXBYInVk/9BdZKLSil66Zn2p0dgQSTMueJQKR1sERFxzD+L8PWU1Ql2Pp7JGz7igm5h/jsGAThdA6SzdCw==.sig.ed25519"
  }
}
```

**Comment by black-puppydog** [comment]
That timestamp is from 2018...
So unless you haven't been posting since then there seems to be a problem.
I suggest if your local state is consistent with mine with this command:

`ssb-server createUserStream --id '@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519' | jq 'select(.value.sequence==164)'`

That command *should* return the same message as I posted above. If it doesn't, that means there is a disagreement between my local state (and supposedly some proportion of the rest of the network) and your local state. That would be bad and would probably mean creating a new id (which is simple) and thinking about what to do with your old follows and posts (which is... probably also simple... :P )

**Comment by hutson** [comment]
It appears that my feed _may_ have forked.

That timestamp corresponds with a `like` I made on a message by Andre about Manyverse years ago.

Took a look at my local feed:

```
 hutson  ~  sbot getLatest '@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519'
{
  "key": "%nGLWH0CXDEO7lvesb/9rMatFbwUQp0dJmobmHy8mtjE=.sha256",
  "value": {
    "previous": "%Dy1syeRwox6xisE0q6ZMvljiz7zEpKbzWTExDRDvCKQ=.sha256",
    "sequence": 247,
    "author": "@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519",
    "timestamp": 1590875739346,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@tKyHI72GfrSh1jnj9DWRQmFLcY/kQY5V6oipac52T2w=.ed25519",
      "following": true
    },
    "signature": "VSbX+CAUZ6VGAoFURYGeVEfJxE9M8OL8GpTc3G7LMEL4knT4vIxpIs14zgoxl6uV9uh1IPoMNcaZpP3+8quADA==.sig.ed25519"
  }
}
```

As for sequence number 164:

```
{
  "key": "%wvQDauy+VtgT22gYY+lnDoMusVCrQe+pDtuBWnjH1dw=.sha256",
  "value": {
    "previous": "%F2cOhEiT6WkikePug66KtNqwmN3sciQQxxE/cs6b6tA=.sha256",
    "sequence": 164,
    "author": "@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519",
    "timestamp": 1588646546641,
    "hash": "sha256",
    "content": {
      "type": "tag",
      "version": 1,
      "tagged": true,
      "message": "%ln27/mQKlqDcKPGA7mgzU5ZA+PrsZEhLUIfd/APJEYM=.sha256",
      "root": "%/mLlQrv8nQ1rm0fLBBZkxqg4d3PHc3h4eO4AyY9XXVQ=.sha256",
      "branch": []
    },
    "signature": "b8PLXgBz65Lz79mp5m36XulqtnL4n+RwoI4xzB5qlXi7/k79jX7nVa3B/r5Vqm6Ha6mrTCh/KihEPQozH6fSBQ==.sig.ed25519"
  },
  "timestamp": 1588646546642
}
```

Yeah... that does not match :fearful:

**Comment by black-puppydog** [comment]
Ugh... sorry to hear that. 
Guess it's time to do the feed switcheroo... :neutral_face: 

Did you do anything out of the ordinary with your feed that you would remember after such long time? Running on multiple devices, running multiple clients, migrating data, or re-syncing from an empty offset log? It doesn't matter for what to do right now, but if your feed became corrupted while "just using" patchwork that would obviously be good to know.

**Comment by black-puppydog** [comment]
I exported your feed and uploaded the version my client saw here: https://muchmuch.coffee/hutson.json

This was created like such:

`ssb-server createUserStream --id '@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519' | jq --slurp > /tmp/hutson.json`

Note the `--slurp` in the `jq` invocation, that joins the separate json objects into a list.
You can run the same command and diff the results to find out where you forked (although I'd guess it was at message 164).
Let me know when you have it and I'll delete it again. :)

If you want to, we can figure yout a way (tomorrow) to re-post your post-fork messages to your new feed...

**Comment by hutson** [comment]
> Running on multiple devices, running multiple clients, migrating data, or re-syncing from an empty offset log?

Back in 2018 I did copy my private key to my phone to test Manyverse (Though it was under a different name at the time), but I don't remember posting/voting from the mobile application (I could be mistaken of course). :thinking: 

I also vaguely remember loosing my `.ssb` directory accidentally (Though I had a backup of my key file) back in 2018 around the time my feed forked. A similar incident happened at the beginning of this May.

> if your feed became corrupted while "just using" patchwork that would obviously be good to know.

I'm pretty confident this issue is my own fault. :sweat: 

> You can run the same command and diff the results to find out where you forked (although I'd guess it was at message 164).

Thank you! It looks like my feed forked a little earlier, at sequence number 157:

![Screenshot_20200530_234634](https://user-images.githubusercontent.com/6701030/83345175-bcf30b80-a2d5-11ea-9e55-e637539393b2.png)

The 157 in your copy (On the right) seems to be a post/vote I made back in 2018. The 157 in my copy is a post/vote from this month. So I apparently _lost_ a few entries from back in 2018 that were not sync'd locally before I began committing new entries.

It's pretty neat to see where the fork clearly happens in the diff:

![Screenshot_20200531_004527](https://user-images.githubusercontent.com/6701030/83345384-13614980-a2d8-11ea-9943-7adb1fd25d6d.png)

So that leaves me with the two following questions:

1) Can I reuse one of these feeds (I assume it must be the one that is widely shared) or will I need to create a new identity (Honestly, I dread the answer).

2) Is using `server.add()` from the [`ssb-server`](https://github.com/ssbc/ssb-server#javascript-usage-example-1) example a reasonable way to re-create my feed (I was thinking of using `add()` so that I could specify the timestamp of the post).

**Comment by black-puppydog** [comment]
1. You can, but I wouldn't recommend that. It's not clear who has which state of your feed. I happen to have one version, but parts of the network might have others. Starting over with a new feed is quite easy, just archive the `~/.ssb/secret` somewhere (just in case... I'm a collector type ya know :stuck_out_tongue:) and start your ssb server anew.

2. If you don't want to lose your post-fork messages, I'd have proposed to re-post them on the *new* feed *before* posting any "really new" messages. Thad would probably mean preparing a json file (or rather json-lines file) where you concatenate all the messages to be published, probably ordered by their respective "asserted" timestamps.
For the message mentioned above that would mean this:

```javascript
// ORIGINAL MESSAGE
{
  "key": "%wvQDauy+VtgT22gYY+lnDoMusVCrQe+pDtuBWnjH1dw=.sha256",
  "value": {
    "previous": "%F2cOhEiT6WkikePug66KtNqwmN3sciQQxxE/cs6b6tA=.sha256",
    "sequence": 164,
    "author": "@jX9wRdRM0z+DlRrYGy1qapRPPERQCz0inlcBCSWYx2Y=.ed25519",
    "timestamp": 1588646546641,  // <-- this is the "asserted" timestamp, i.e. the timestamp that your client at the time put on the message. Since you're talking about your own feed, it should be safe to trust this.
    "hash": "sha256",
    "content": {  // <-- you only want to extract the "content" field of each message to re-post
      "type": "tag",
      "version": 1,
      "tagged": true,
      "message": "%ln27/mQKlqDcKPGA7mgzU5ZA+PrsZEhLUIfd/APJEYM=.sha256",
      "root": "%/mLlQrv8nQ1rm0fLBBZkxqg4d3PHc3h4eO4AyY9XXVQ=.sha256",
      "branch": []
    },
    "signature": "b8PLXgBz65Lz79mp5m36XulqtnL4n+RwoI4xzB5qlXi7/k79jX7nVa3B/r5Vqm6Ha6mrTCh/KihEPQozH6fSBQ==.sig.ed25519"
  },
  "timestamp": 1588646546642  // <-- this is the "received" timestamp, i.e. the time your client first saw this message. Since your client is the first to see your own messages, it's only 1 ms apart from the asserted timestamp in this case.
}

// WHAT YOU COULD PASS TO ssb-server publish
{
      "type": "tag",
      "version": 1,
      "tagged": true,
      "message": "%ln27/mQKlqDcKPGA7mgzU5ZA+PrsZEhLUIfd/APJEYM=.sha256",
      "root": "%/mLlQrv8nQ1rm0fLBBZkxqg4d3PHc3h4eO4AyY9XXVQ=.sha256",
      "branch": []
}
```

This approach basically pretends your posts were made right now, all in one batch. It does **not** preserve the original timestamps.
If you want that too, that would mean either doing this in a container/VM and messing with the system time (might be acceptable for a one-off) or writing something that uses the ssb primitives for this, I guess that would be the `ssb-keys` package.
The flow for that would be roughly:

* extract all the messages to be re-posted, in order of their asserted timestamps
* for each message, replace the `previous`, `sequence`, and `author` fields with the appropriate values.
* sign the message, and add it using `ssb-server add` or the equivalent in JS
* keep the key of the newly published message to use for the next iteration's `previous` value.

You see, that's much more involved...

**Comment by hutson** [comment]
> It's not clear who has which state of your feed

That's what I was suspecting, and a key reason to move forward with your suggestion and spin up a new identity. (I ended up just archiving the entire `.ssb` directory, given that it was not consuming much space)

> If you don't want to lose your post-fork messages, I'd have proposed to re-post them on the new feed before posting any "really new" messages.

So I ended up doing two things, first, re-publishing all my votes and tags (It seemed reasonable to bring those over from the other account so that they appeared in Patchwork), and then I re-posted `post` entries since sequence 156.

```
var Client = require('ssb-client')
const feed = require(`./hutson.json`)

Client(function (err, server) {
    if (err) throw err

    for (const entry of feed) {
        if ((entry.value.content.type === `vote`) ||
            (entry.value.content.type === `tag`)) {
                console.log(`entry sequence - ${entry.value.sequence}`);
                server.publish(entry.value.content, function (err, msg) {
                    if (err) {
                        console.log(`err - ${err}`);
                    }
                    console.log(`msg - ${msg.value.sequence}`)
                })
        }
    }
})
```

> You see, that's much more involved...

Yeah, I'm not sure I'm quite up to that at the moment. I also felt it would really only be beneficial for old posts so that they appeared in my timeline based on when I originally wrote the posts. However, that would cause them to be double posted to the original threads, causing confusion and noise/spam for everyone. So I decided against it. Perhaps in the future there will be a way to merge forks. That, combined with `sameAs`, may allow me to gracefully stitch all my accounts/feeds back together.

**Comment by black-puppydog** [comment]
Okay, closing this then. Feel free to reach out if you need further guidance or just to chat, here or on the 'verse. :)

**Comment by hutson** [comment]
Thank you @black-puppydog for your help! :+1: 

Though I caused this thread/issue to get a little off-track, I wanted to reiterate that it would still be nice if Patchwork could provide the same level of assistance through the UI that you have provided to me. Some way to inform users that their feed has forked (So they aren't left feeling ignored) and how to recover.
