### ISSUE TITLE
Restoring from backup: UI doesn't show much for ~14 hours

### ISSUE THREAD

**Issue by funwhilelost** [ssbc/patchwork#1293]
I'm trying to set up Patchwork on a new machine and backed up most of my `.ssb` directory.  I've been trying to start Patchwork on a new machine in a variety of ways but can't seem to get it to sync anything to this new machine.

The most success I've had so far is:
- Wipe the `~/.ssb` directory
- Create an empty `~/.ssb` directory
- Add `secret` and `gossip.json` to the `~/.ssb` directory
- Start Patchwork with `npm start -- --logging.level info`

I see the typical startup behavior, the server logs are showing some things from the `gossip.json`:

```
  path: '/home/funwhilelost/.ssb',
  party: true,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  gossip: { connections: 3, autoPopulate: false },
```

It seems to have picked up my keys from `secret` (I'm assuming `private` is nulled out for security?):
```
  keys: {
    curve: 'ed25519',
    public: 'etENdjc9Qg0hS56E5XkLhf58DYsqK18kit8Sp0qTT/8=.ed25519',
    private: null,
    id: '@etENdjc9Qg0hS56E5XkLhf58DYsqK18kit8Sp0qTT/8=.ed25519'
  },
```

But when it starts up it prompts me for my name, etc. and then two pubs show up in the Connections list:

![image](https://user-images.githubusercontent.com/127476/83580452-05d2dc00-a4f1-11ea-9b0a-9f71a333b490.png)

Nothing seems to happen after waiting a couple hours.  The last two server messages show this:
```
git-ssb is not installed, or not available in path
ssb-friends: stream legacy api used
```

Is there anything else I can do to triage this?

**Comment by funwhilelost** [comment]
Oh, dear.  Spoke too soon.  The floodgates opened after a couple hours and it's all getting re-assembled.  Should we add "back-up" and "restore" instructions to the README?  Should the UI indicate that it may actually be doing something?  Should the UI skip the prompt for the user's name if it detects it's booted up with a `secret` and hasn't rebuilt the database yet?  I'd hate for other people to get into a weird situation with a forked account or something.

**Comment by black-puppydog** [comment]
I'd be for instructions, yes.
I think nowadays, you'd actually want to backup `conn.json` not `gossip.json`, so that's already good to know.

It's fundamentally impossible for patchwork to know when it has synced it's own feed back from the network, or if there is anything to sync at all. So the instructions should definitely include something about making sure you know when syncing is finished.

For the record: I *think* your feed is `@etENdjc9Qg0hS56E5XkLhf58DYsqK18kit8Sp0qTT/8=.ed25519`, and if so, then the latest message I have from this feed has sequence number `428` and key `%ninJs8/zXbtrA8qoaYDrpggqwecg+BFM8L83Jdtne/U=.sha256`

So make sure you have at least that message local before you start posting again. :stuck_out_tongue:

**Comment by funwhilelost** [comment]
About 14 hours in it had filled in most streams and messages but they had no information in them, no friendly names, etc.  I started seeing these in the server output:

```
Exception thrown by PacketStream substream end handler Error {}
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/funwhilelost/git/patchwork/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/funwhilelost/git/patchwork/node_modules/packet-stream/index.js:133:41)
    at /home/funwhilelost/git/patchwork/node_modules/ssb-client/node_modules/muxrpc/pull-weird.js:58:44
    at /home/funwhilelost/git/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/funwhilelost/git/patchwork/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/funwhilelost/git/patchwork/node_modules/packet-stream-codec/index.js:98:24)
    at drain (/home/funwhilelost/git/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/funwhilelost/git/patchwork/node_modules/pull-reader/index.js:63:18
    at drain (/home/funwhilelost/git/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/funwhilelost/git/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
```

On restarting the app it seems to finally be resolving friendly names, etc.
