### ISSUE TITLE
Win7: Infinite load spinners / scuttling, JS error, no server process connection

### ISSUE THREAD

**Issue by amatecha** [ssbc/patchwork#1299]
Hi there,

Running Patchwork 3.18.0 on Win7 64bit.  I think it worked on the first run, but successive runs show loading spinners forever and the application is not usable.  I opened the JS console (via rightclick- Inspect Element, click on Console tab) and saw the following error:
```
Cannot read property 'peers' of undefined
    at Array.<anonymous> (\AppData\Local\Programs\ssb-patchwork\resources\app.asar\lib\depject\sbot.js:105:19)
    at Function.Observable.observable.set (AppData\Local\Programs\ssb-patchwork\resources\app.asar\node_modules\mutant\value.js:12:25)
    at AppData\Local\Programs\ssb-patchwork\resources\app.asar\lib\depject\sbot.js:97:18
[...]
```

Inspecting Server Process just shows the unconnected Dev Tools screen, with no other information -- presumably it never connected to the theoretical Server Process. 

If there are any log files I can dig up to troubleshoot further, just let me know - I can take a look and share whatever might be relevant.  Or.. if it's just too bad cuz I'm using Win7, no worries :)

Now that I think about it I launched patchbay on the same machine.  I could imagine this causing a problem, tho no clue.

**Comment by christianbundy** [comment]
Hey! Sorry to hear that you're having this problem. Are you running Patchbay at the same time?

That looks like a JS error, maybe someone will have time to poke around and fix it.

**Comment by amatecha** [comment]
Now that you mention it, I'm actually not sure if I was running them at the same time -- I did just now notice I had like ~10 patchbay.exe processes still running (I had some issue where clicking "Launch App" in Patchbay causes the app to disappear), but I also tried to repro the above process last night by running Patchwork, then Patchbay then Patchwork (so it's possible they were still leftover from that attempt).  So, it's totally possible Patchbay processes were present the _entire time_ and I just didn't notice.  No way to tell, now, I don't think.

However, now that I killed all those background Patchbay processes, Patchwork is working!  Also just quit & reopened Patchwork once again and it's working fine as far as I can tell.   So, my guess is the problem I encountered was due to Patchbay processes still running in the background that I wasn't aware of.   I think you can close this bug, but I'll comment back here if I see the issue again or find anything to suggest that it wasn't just Patchbay running at the same time :)  Thanks!

**Comment by christianbundy** [comment]
> However, now that I killed all those background Patchbay processes, Patchwork is working!

Oh that's great to hear! Sorry that the debugging process around Patchwork/SSB is a pain point right now, sometimes it's so hard to figure out what's going on. Please let me know if you bump into any other trouble.
