### ISSUE TITLE
Share diaries with only specific people

### ISSUE THREAD

**Issue by jessebett** [ssbc/patchwork#1301]
I am looking at scuttlebutt and am curious if a feature is supported. Sorry if this information is obvious or described elsewhere, I looked at various FAQs without the answer being obvious. 

My impression of scuttlebutt, again I haven't used it yet, is that it will sync my public diary with all my the people I connect with. Is it the case that it always shares my entire state with everyone connected? Or can I be more selective about what content I share with specific groups (like Circles of Google+).

For instance, if I connect with some friends, I get their scuttlebutt. Then I go and connect with some unrelated group, possibly a group I don't want to know about eachother e.g. my extended family that does not approve of my friends' lifestyles. Is it the case that all my friends' scuttlebutt will now be shared with my family?

**Comment by christianbundy** [comment]
Hey! Yeah, this is something that's actively being worked on, but currently you choose between:

- public
- a private group, which has a maximum of 7 people, and you can't change group participants later

It's in progress as [SSB-Tribes](https://github.com/ssbc/ssb-tribes), but we've *just* finished up the important libraries and are now adding it to at least one interface. I'd imagine that this probably won't be added to Patchwork for at least a few months.

**Comment by jessebett** [comment]
@christianbundy Okay thanks for pointing me to Tribes. Until then I will be discerning about my friends ;)
