### ISSUE TITLE
Change "Who to follow" to "Whom to follow"

### ISSUE THREAD

**Issue by RichardLitt** [ssbc/patchwork#1306]
I happen to like using _whom_. I'm aware it's a [silly, old word](https://english.stackexchange.com/questions/56/what-s-the-rule-for-using-who-and-whom-correctly) that is [almost](http://itre.cis.upenn.edu/~myl/languagelog/archives/005054.html) [dead](http://itre.cis.upenn.edu/~myl/languagelog/archives/001437.html). But I like it, and "whom to follow" is the correct usage of the word. 

Is there any way for me to change this, for me, so that we don't end up in a linguistic "Whom is silly" discussion? For instance, is there a preference box we could use? I'm curious. 

Thanks.

**Comment by christianbundy** [comment]
Are you building Patchwork from source? If so, you could edit https://github.com/ssbc/patchwork/blob/master/locales/en.json. If you'd like to see that change in a release, I'd be happy to merge a change to `en.json`. If someone cares enough they can revert it and we can get into a spelling war, but :shrug:.

**Comment by RichardLitt** [comment]
Alright! Opened a PR. Changed all of the instances to make it less confusing later.
