### ISSUE TITLE
Patchwork doesn't include a Dockerfile ?

### ISSUE THREAD

**Issue by flavienbwk** [ssbc/patchwork#1308]
Hi,

Are you planning to add a `Dockerfile` ?

It might be useful to easily install and deplooy patchwork.

**Comment by christianbundy** [comment]
Thanks for creating and issue. Could you describe the problem you're bumping into?

**Comment by flavienbwk** [comment]
It's about deploying quickly and cleanly, with Docker.

**Comment by christianbundy** [comment]
Why are you deploying Patchwork? I'm familiar with Docker (and have written maybe a hundred dockerfiles) but this is a GUI app that I can't imagine 'deploying'. Do you run all of your GUI apps in Docker containers?

**Comment by flavienbwk** [comment]
Sorry this issue can be closed. I misunderstood the project.

**Comment by kgnfth** [comment]
> Sorry this issue can be closed. I misunderstood the project.

You are not alone 😂🤣😂😂🤣

**Comment by black-puppydog** [comment]
Huh? @kgnfth could you elaborate on that? Should we add "Not to be confused with $PROJECT" in the readme?
