### ISSUE TITLE
Translating the project into Persian

### ISSUE THREAD

**Issue by dev0p0** [ssbc/patchwork#1311]
Hi there everyone! Literally :)
I am intrested in translating the project into Persian, is there a method similar to
https://hosted.weblate.org/engage/tox/fa/
for qtox (another wonderful decentralized chat platform) that I can contribute to, so that I can translate most of the projects into Persian?

Thank you

**Comment by dev0p0** [comment]
I have made a fa.json using the en.json in the locales folder, and translated the terms into Persian (Farsi) and made a pull request. Hope that helps. Also I noticed that probably the project has already been translated into Persian before because there is a fa.pak available in the installation folder but Farsi is not available as an option in the settings section of the program when you run it.

**Comment by black-puppydog** [comment]
This was closed by #1313 I guess...
