### ISSUE TITLE
Patchwork build errors on FreeBSD

### ISSUE THREAD

**Issue by samebchase** [ssbc/patchwork#1316]
Hello,
I've recently moved to FreeBSD from ArchLinux, and I've moved over my `.ssb` folder.

I tried building Patchwork and I get the following error:

```
$ npm install --build-from-source

> @felixrieseberg/spellchecker@4.0.12 install /usr/home/samuel/src/patchwork/node_modules/@felixrieseberg/spellchecker
> node-gyp rebuild

gyp: name 'spellchecker_use_hunspell' is not defined while evaluating condition 'spellchecker_use_hunspell=="true"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/home/samuel/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System FreeBSD 12.1-RELEASE
gyp ERR! command "/usr/home/samuel/.nvm/versions/node/v12.18.3/bin/node" "/usr/home/samuel/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/samuel/src/patchwork/node_modules/@felixrieseberg/spellchecker
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @felixrieseberg/spellchecker@4.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @felixrieseberg/spellchecker@4.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Please let me know what I can do to be able to build Patchwork. Thank you in advance.

**Comment by christianbundy** [comment]
Dang, I have no idea how to fix that off the top of my head. I'd probably recommend reaching out to the upstream project and trying to see if they can support FreeBSD. If not, maybe this can be moved to be an optional dependency?

**Comment by samebchase** [comment]
Hey thanks @christianbundy, I'll do that.

Someone else seems to have run into this issue as well: https://github.com/atom/node-spellchecker/issues/87

**Comment by samebchase** [comment]
And someone has a patch here https://github.com/atom/node-spellchecker/pull/125/files

**Comment by samebchase** [comment]
Not sure how we can file issues in https://github.com/felixrieseberg/node-spellchecker because that's a fork of node-spellchecker and the patch to node-spellchecker was declined as per the conversation.

What is the best thing to do in this situation?

**Comment by christianbundy** [comment]
That's frustrating. Can you build Atom from source on FreeBSD? If not, I think a bug report in their repo might make it easier to merge that pull request.

**Comment by samebchase** [comment]
I'll do that. :+1:

**Comment by samebchase** [comment]
@christianbundy: I am running into issues building Atom from source on FreeBSD.

Seeing that we are using felixrieseberg/node-spellchecker which is a fork of the original node-spellchecker, could we fork this for Patchwork's sake and make sure it builds correctly on the BSDs so that users on BSDs can use Patchwork as well.

I could wrangle those various other rejected patches, and create a fork the spellchecker library we use, so that is builds cleanly. Once it works reliably, I will submit a PR to Patchwork using my fork of felixrieseberg/node-spellchecker

I've been on SSB for more than two years, and the last few months not being able to access SSB have been :cry: 

How does that sound?

**Comment by christianbundy** [comment]
I'm comfortable with that, we could even put it in SSBC -- I think that's what's happened with a few other forks. If you make a fork and get it working I'm happy to use that code instead. Sorry you had to try to deal with all the Atom baloney. :/

**Comment by samebchase** [comment]
The situation seems to be more complicated than what I had initially conceived.

It seems Electron doesn't build on FreeBSD as per https://github.com/electron/electron/issues/3797 

:disappointed:

**Comment by christianbundy** [comment]
:/

There's https://github.com/fraction/oasis, which doesn't use Electron, but it's quite a bit younger than Patchwork.

**Comment by samebchase** [comment]
@christianbundy: Yes, I've managed to rejoin the Scuttleverse using Oasis now. Thanks for helping build it!
