### ISSUE TITLE
Patchwork doesn't stop indexing database

### ISSUE THREAD

**Issue by spencerhadley** [ssbc/patchwork#1317]
Infinite database indexing... 
I think the problem started after I opened Patchbay or Patchfox a week ago. Now I can't look at anything in Patchwork. Seems like if I delete the correct item from .ssb Patchwork will properly reload. 

Help?

**Comment by spencerhadley** [comment]
I tried the solution I found in the other instance of infinite indexing.

find ~/.ssb \
  -type f \
  -not -name config \
  -not -name secret \
  -not -name log.offset \
  -not -name conn.json \
  -not -name gossip.json \
  -not -name manifest.json \
  -not -name delete-nonessential \
  -not -path '*/.ssb/blobs/*' \
  -delete

It hasn't helped

**Comment by spencerhadley** [comment]
I gave up, lost my account and started a new one. That was disappointing but I didn't know of another option.

**Comment by black-puppydog** [comment]
Sorry to hear that Spencer. Also sorry to be absent. I was quite out of the world for a while there, only jumping in and out of ssb to keep some mental health...

FWIW, I don't think these three would have had to be excluded:

```
-not -name gossip.json
-not -name manifest.json
-not -name delete-nonessential
```

`gossip.json` is superseded by `conn.json` (which you also keep) and the manifest should be re-generated on startup. I don't know the last one.

My guess would have been the `config` file in this case. I guess you would have kept that? Is there anything specific in there? It would only even exist if you made modifications.

**Comment by mmsenxxx** [comment]
Problem persists, took a break from this project for over a year due to a strange time related bug. Returned this year, not even 48 hours and this problem arose. Copied and then deleted each folder/file. Then copied back into .ssb folder. Did not rectify the issue. Might return next year. Disappointed but c'est la vie.

**Comment by black-puppydog** [comment]
@mmsenxxx was that on the most recent release (v3.18.0) or on which version?

**Comment by mmsenxxx** [comment]
Issue on the most recent release.

> @mmsenxxx was that on the most recent release (v3.18.0) or on which version?

v3.18.0

**Comment by black-puppydog** [comment]
thanks. sorry to hear it didn't work out. let me know if you're back before in one year ;)

**Comment by archerships** [comment]
FWIW, I'm experiencing the same issue.  I was running Patchwork (v 3.18.0.831) on Ubuntu, tried out Patchbay, switched back to Patchwork.  Now Patchwork has been indexing for several hours and does not appear to be making any progress.

**Comment by archerships** [comment]
I was using Patchbay (linux version 8.1.0).  If I open patchbay now, it runs for a little while, but there's nothing in my inbox or posts feed.  And it eventually crashes, and goes blank.
