### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by adrienandrem** [ssbc/patchwork#1321]
I would find useful to be able to minimize Patchwork to tray  
and be able to set this as behavior when closing the window.

**Comment by christianbundy** [comment]
Hi. What OS are you looking for this behavior on? Patchwork is in maintenance mode and generally avoiding adding any new stuff.

**Comment by adrienandrem** [comment]
Hi, it would be on Ubuntu 18.04 with XFCE 4.12.

Isn't maintenance mode temporary?

**Comment by black-puppydog** [comment]
@adrienandrem it can be, if someone wants to step up and take on new issues. 
The problem with patchwork is that it grew through multiple "generations" of developers and has a habit of burning out developers quite fast.

Realistically, https://github.com/fraction/oasis is more likely to become the "default" ssb client soon. Its code base is *much* smaller and more manageable. However, it is not an interface like Patchwork.
Go try it out though if you feel like it. You can start it while patchwork is running, and it will show the same content.

**Comment by adrienandrem** [comment]
@black-puppydog 

> https://github.com/fraction/oasis is more likely to become the "default" ssb client soon.

I wasn't aware of that, I'll give it a try then, thanks!
