### ISSUE TITLE
Options button not working for contacts

### ISSUE THREAD

**Issue by sunjam** [ssbc/patchwork#1328]
#1326 related.  I cannot access "Options" for any specific contact.  Clicking the button does nothing.  Was hoping to block some users I'm seeing in public, but do not follow.

**Comment by christianbundy** [comment]
is this in a stable Patchwork or the new experimental beta?

**Comment by sunjam** [comment]
Experimental beta pre-rust branch. It is in the linked issue.

**Comment by christianbundy** [comment]
cc: @staltz @black-puppydog

**Comment by staltz** [comment]
Pre-rust or post-rust?

**Comment by black-puppydog** [comment]
Actually I've had this for a loooong time but I asked about it on ssb and we couldn't replicate so I always kinda just assumed it was sth wrong with my setup, or I had somehow upset my npm or *something*.

**Comment by black-puppydog** [comment]
Oh. What I wrote there was... false. :P

Actually @soapdog confirmed that but I must have missed that notification.

[`%ySQfyTDAMI97BKQaQ9zl6QHChWMjdJzZ3qjZCT6hz7s=.sha256`](https://ssb.muchmuch.coffee/%25ySQfyTDAMI97BKQaQ9zl6QHChWMjdJzZ3qjZCT6hz7s%3D.sha256)

**Comment by sunjam** [comment]
> Pre-rust or post-rust?

Pre-rust.  See this linked thread from my first post for complete background.



> #1326 related. I cannot access "Options" for any specific contact. Clicking the button does nothing. Was hoping to block some users I'm seeing in public, but do not follow.

**Comment by black-puppydog** [comment]
I looked at this one a  bit yesterday, but I didn't have much time to get to the bottom of it.
I basically just got to this line: 

https://github.com/ssbc/patchwork/blob/54a329a6358694d3f586ed419a6c6aad6f5beecf/lib/depject/contact/html/follow-toggle.js#L97-L105

This line is executed on the client (i.e. in the "browser") and is querying the `zoomFactor` from the `remote`, i.e. the "server".
From what I can tell, this is done through binding via [mutant](https://github.com/mmckegg/mutant).

The second aspect (besides mutant) to this call is that recently, electron has refactored the getter functions to be JS `get` properties. Not sure if that matters.

In any case, the callback given to the getter seems to never be called.

However: if I inspect the window, and evaluate `electron.remote.getCurrentWindow().webContents.zoomFactor` by hand, it returns `1` correctly. 

Not really conclusive, but that's where I'm at right now.

**Comment by soapdog** [comment]
This is happening for me and I am using the release version. I'm not building or running from source, I'm getting the latest version pre-built from this repo.

**Comment by christianbundy** [comment]
@soapdog Clarification: are you running `v3.18.0` or `v3.18.1-beta.1`?

**Comment by soapdog** [comment]
@christianbundy `Patchwork 3.18.1-beta.1`

**Comment by black-puppydog** [comment]
but @christianbundy I've been seeing this for much longer (see above)

**Comment by black-puppydog** [comment]
@sunjam in case you're not reading on ssb, I think I fixed this in #1368. If you want to test this, let me know if you need help. :)
