### ISSUE TITLE
Getting spammed by news sources I don't follow, such as BBC

### ISSUE THREAD

**Issue by sunjam** [ssbc/patchwork#1330]
I'm assuming because of pub association, user timelines are heavily spammed by BBC, Engadget and other publications.  This is extremely frustrating and I'd appreciate if the ability to ignore or hide posts from accounts I'm not following was even easier.

Any guidance or tips appreciated!

**Comment by cbleslie** [comment]
@sunjam Block them. You can manage these settings in the offending accounts profile, under the "Options" dropdown.

**Comment by sunjam** [comment]
Currently not possible for me in Patchwork due to inaccessible option menu
in pre-rust branch on arm64 laptop.  Filed a separate issue for that.
