### ISSUE TITLE
Set number of hops to download

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/patchwork#1339]
It would be awfully nice to be able to configure how many hops away of data to have Patchwork download.  There are times when I would like to download more or fewer than 2 hops.

**Comment by hjacobs** [comment]
I think you can already do this manually by configuring `.ssb/config` and set `friends.hops`: https://github.com/ssbc/ssb-config#configuration

**Comment by KyleMaas** [comment]
Thank you for that - I will have to try it.  But it would be nice if that could be changed from the UI.

**Comment by black-puppydog** [comment]
Yes, actually a more comprehensive settings screen would generally be cool. Very much a feature though and low priority (simply due to limited capacity on our end)
