### ISSUE TITLE
Set .ssb directory outside of main OS partition

### ISSUE THREAD

**Issue by Gaffen** [ssbc/patchwork#1356]
Hey all,

I'm moving machines and I want to set up patchwork on my gaming machine, the problem is that space is a premium there. I want to move where the storage is kept to a secondary hard drive, so that I can afford to store the size of storage that scuttlebutt requires. I'm also on a Windows system - I tried creating a shortcut to the .ssb folder, but this didn't seem to work - though I'm pretty sure it'd work on a unix system with a symlink.

Is this possible? Any tips? I miss chatting with butts, so any advice is appreciated!

-Gaffen

**Comment by black-puppydog** [comment]
So I don't run Windows, but I remember that they *do* have some form of symlinks like we do on unix. 
This superuser [answer](https://superuser.com/a/706587) seems to suggest that you could try this from the command line:

```terminal
mklink /J D:\ssb-data C:\Users\[Username]\somethingsomething\.ssb
```

Not sure what the implications are though. Make a backup of your `secret` and `conn.json` files before you try that. :slightly_smiling_face: 

In terms of building this sort of support into patchwork, that's a long-lasting dream of mine, but I don't know at which depths the ssb stack assumes that specific storage location. Would be an interesting project though... :thinking:

**Comment by black-puppydog** [comment]
@Gaffen please do report back if you try this, I'd be curious to hear the results. It's such a non-issue on Unix, but of course we'd like to have a solution for Windows too, even if it requires commandline magic. That's better than nothing.

**Comment by Gaffen** [comment]
Sorry I'm still kind of between machines right now, but I'll give this a try and let you know the results ASAP :)

**Comment by Gaffen** [comment]
Update; I've just successfully transferred everything from my old mac to my windows PC, using the windows 'symlink' approach and it seems to be working!
