### ISSUE TITLE
Deprecate electron-spellchecker

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1383]
The project hasn't seen any commits in a long time.
And that might be because, according to the electron [docs](https://www.electronjs.org/docs/tutorial/spellchecker):

> Electron has built-in support for Chromium's spellchecker since Electron 8.

So we definitely want to migrate away from that, especially since it drags in some pretty old dependencies.
But it also handles our context menu. So we need to re-write those in some other way.

**Comment by FoundOne** [comment]
Can we have a replacement? I like the idea of having a spellcheck.

**Comment by black-puppydog** [comment]
@FoundOne as I wrote, electron should have a built-in spellchecker now. So yes, we should have one, it should be faster & hopefully better, and require less work from us.

BUT we need to figure out how to do the context menus and such now.
