### ISSUE TITLE
The Gateway seems not to work

### ISSUE THREAD

**Issue by tiotrom** [ssbc/patchwork#1387]
If I right click the date of any of my posts l get either something like this https://viewer.scuttlebot.io/%25ohvqUMZ7UL46ZGwvxtTcZsGiBh5Jw1G2JKtGo5mGVEI%3D.sha256

![image](https://user-images.githubusercontent.com/34804533/105717172-18869f00-5f20-11eb-8a52-a6b1852646d8.png)

Or "User has not chosen to be hosted publicly" - and yet I posted publicly. 

Is this a bug? Thanks!

**Comment by black-puppydog** [comment]
Hi @tiotrom,

It does work, look e.g. https://viewer.scuttlebot.io/@MRiJ+CvDnD9ZjqunY1oy6tsk0IdbMDC4Q3tTC8riS3s=.ed25519 for my feed.
But it doesn't seem to *replicate* your feed. I just wrote a kinda of FAQ about this this morning. Check it out under `%MhAak5ECSmxQ39Ptezta95t8cJSqyCkHKO8XTHTVrWM=.sha256` or [here](https://viewer.scuttlebot.io/%25fnEO0XOWpa%2FhNQ0nkWd%2BXnGpqaqoxXGKHFGljpPX19g%3D.sha256)

**Comment by tiotrom** [comment]
I am jumping to the scuttlebutt thread and continue the conversation there. Cheers!
