### ISSUE TITLE
The yarn build for arm64 does not produce a working application.

### ISSUE THREAD

**Issue by FoundOne** [ssbc/patchwork#1388]
How to reproduce:
1. git clone https://github.com/ssbc/patchwork.git
2. cd patchwork
3. yarn
4. yarn start

What happens:
It opens normally, but starts loading into infinity and fails to load my messages and pictures.
After awhile it prints in the output:
```
Exception thrown by PacketStream substream end handler Error: unexpected hangup
    at Object.cb (/home/dwolf/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/dwolf/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/dwolf/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/dwolf/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/dwolf/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/dwolf/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error: unexpected hangup
    at Object.cb (/home/dwolf/patchwork/node_modules/pull-box-stream/index.js:117:44)
    at drain (/home/dwolf/patchwork/node_modules/pull-reader/index.js:46:23)
    at /home/dwolf/patchwork/node_modules/pull-reader/index.js:63:18
    at /home/dwolf/patchwork/node_modules/pull-reader/index.js:114:13
    at drain (/home/dwolf/patchwork/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/dwolf/patchwork/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
The npm build works as it's expected, but I haven't managed to build an AppImage form it (I'm, sorry I'm quite a noob with these things). 

Versions:

yarn 1.22.10
node v15.6.0
Manjaro-arm current
aarch64 RK3399 Pinebook Pro

**Comment by black-puppydog** [comment]
@FoundOne to clarify:

* does the application open a window at all?
* if so, does it show anything? Or does it look like this?
![image](https://user-images.githubusercontent.com/189241/105762845-42a68400-5f55-11eb-8e18-4134aa5c6e42.png)

**Comment by black-puppydog** [comment]
Also, I haven't run anything on the pinebook yet, but on my pine*phone* the indexing can *feel* like forever, but it's actually just *really, really slow*. :laughing:

**Comment by FoundOne** [comment]
Yes, it opens a window. It looks almost like this. I don't have the friends list yet. I joined a couple of rooms and they don't appear. I'm still quite hesitant to join some of the pubs. Also I don't have the text "indexing database" and the progress bar. There is only the loading animation at that place. 
I'm just looking for portable package.

**Comment by black-puppydog** [comment]
Do you have pre-existing ssb data or is this a "fresh" identity?
If it's the latter, and you haven't joined a room or pub, then it *should* be empty, since your client hasn't connected to anyone else yet. 
Before you join a pub (that might indeed overwhelm the poor thing) consider joining a *room* instead. I explained a bit about rooms & pubs here today:

https://ssb.muchmuch.coffee/%25fnEO0XOWpa%2FhNQ0nkWd%2BXnGpqaqoxXGKHFGljpPX19g%3D.sha256

**Comment by FoundOne** [comment]
It's quite new identity. There is not much in my timeline. It was mostly stumbling to learn how things work (I learned I can't disconnect from the rooms/pubs) and I set up my profile. The npm build works fine. I guess I have to deal with the tarball :disappointed:  IMO AppImages are more practical, if there is no official (or AUR) package.

**Comment by black-puppydog** [comment]
I've honestly not used yarn much, and not at all in patchwork... Is it important for your environment that you use yarn?

**Comment by FoundOne** [comment]
Not really. My main issue is that I can't make an AppImage. If someone tell me how to do it with npm, I'd be very happy. Anyway, I see the advantages of yarn over npm. It does the things in parallel, it uses a cache to build and looks better imo, but It does not build a working app unfortunately.

**Comment by black-puppydog** [comment]
ah, for me `npm run dist` usually does the trick. 
But indeed, I haven't tried that on arm yet. :P

**Comment by FoundOne** [comment]
Unfortunately it does not work. It ends with:
```
⨯ cannot execute  cause=exit status 1
                    out=
    > @felixrieseberg/spellchecker@4.0.12 install /home/dwolf/patchwork_npm/node_modules/@felixrieseberg/spellchecker
    > node-gyp rebuild
    
    make: влизане в директория „/home/dwolf/patchwork_npm/node_modules/@felixrieseberg/spellchecker/build“
      CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/base/md5.o
    make: излизане от директория „/home/dwolf/patchwork_npm/node_modules/@felixrieseberg/spellchecker/build“
    
                    errorOut=g++: error: unrecognized command-line option ‘-m64’
    make: *** [hunspell.target.mk:128: Release/obj.target/hunspell/vendor/hunspell/src/base/md5.o] Грешка 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:12)
    gyp ERR! System Linux 5.7.19-1-MANJARO-ARM
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/dwolf/patchwork_npm/node_modules/@felixrieseberg/spellchecker
    gyp ERR! node -v v15.6.0
    gyp ERR! node-gyp -v v7.1.2
    gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @felixrieseberg/spellchecker@4.0.12 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the @felixrieseberg/spellchecker@4.0.12 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/dwolf/.npm/_logs/2021-01-25T21_58_03_863Z-debug.log
    
                    command=/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js rebuild @felixrieseberg/spellchecker@4.0.12 cld@2.5.1 keyboard-layout@2.0.16 leveldown@5.3.0 sodium-native@3.2.0 utp-native@2.1.7 leveldown@5.6.0 leveldown@5.6.0 leveldown@5.6.0 sodium-native@3.2.0 leveldown@5.6.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-patchwork@3.18.1-beta.2 dist: `electron-builder -c.snap.publish=github`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@3.18.1-beta.2 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dwolf/.npm/_logs/2021-01-25T21_58_04_023Z-debug.log
```
And then, I can't run the `npm start` command successfully, until I run `npm install` again. It just gives me a blank window. By what I see it gives a parameter which does not exist in gcc-aarch64 (-m64).

**Comment by black-puppydog** [comment]
Yeahhh... that module should really not be there anymore. See #1383. I know that this statement isn't super helpful in this situation. :P
But this seems to be an issue with choosing the right compile options. I just found the error here: https://stackoverflow.com/questions/58244095/gcc-7-error-unrecognized-command-line-option-m64

But I really don't understand how the build system for electron-spellchecker works, and because the whole module is deprecated, I really don't want to be learning that, just to kick it out later. Sorry...
