### ISSUE TITLE
Search gets stuck on single result

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1391]
I thought this had been reported, can't find it... If anyone knows the matching issue, plz link :)

Full text search pretty consistently only returns a single result, then gets stuck with a spinner.
Oasis running against patchwork's ssb-server however returns the expected results, so it seems to be a UI/electrron coordination issue, not a problem with ssb-search or such.

**Comment by hjacobs** [comment]
Yes, I experience the same problem.
