### ISSUE TITLE
Colon (":") is incorrectly identified as part of a hashtag (channel)

### ISSUE THREAD

**Issue by hjacobs** [ssbc/patchwork#1392]
I repeatedly stumble over this: colons which directly follow on hashtag are identified as part of the channel. So there are channels like `#ssb:` where `#ssb` would be the correct one:
![Screenshot_2021-01-30_19-32-44](https://user-images.githubusercontent.com/510328/106364791-f5019100-6331-11eb-92a5-0fb3c0bf3b1a.png)

The original message is this (note that I intended to use the existing `#ssb` hashtag):
![Screenshot_2021-01-30_19-33-43](https://user-images.githubusercontent.com/510328/106364814-195d6d80-6332-11eb-8046-f0b8990823dc.png)

**Comment by black-puppydog** [comment]
Note though that in the text, the highlight is correct. And if I open `%1BSOsYMcy5zOcutjjWlt6/5Sr4mqB33lO5cMRZoq4P8=.sha256` and click on `#ssb` it does open `#ssb`, not `#ssb:`
I wonder if that is just a fortunate bug masking the wrong detection or what's happening there. :thinking:
