### ISSUE TITLE
Font sizes are all wrong size in (by design)

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1398]
`%Yixc7LlyDjFyXyS9NQcSNtT/ItGTAl9UPbrCVuWsx/0=.sha256`
This is how it *should look:*

![image](https://user-images.githubusercontent.com/189241/106480760-053d7b80-64ac-11eb-932a-377f3e6989e8.png)

just switching out H1 already helps but shouldn't be done alone:

![image](https://user-images.githubusercontent.com/189241/106480801-11c1d400-64ac-11eb-900d-b246f23e22b1.png)

**Comment by 4rtmelly** [comment]
Hey, can I work on this issue ? :)

**Comment by black-puppydog** [comment]
@4rtmelly you certainly can. 
However, be aware that development on patchwork is gonna seize very soon. 
If you're familiar with how the styling works and can get this in within a week or two, we can make the last release look nicer than otherwise.
But I wouldn't want to waste your time, so I just wanna be up-front. :)

**Comment by 4rtmelly** [comment]
Oh, I'm new and just installed this project so i'm trying to understand how it works & where the style is coded

**Comment by black-puppydog** [comment]
If you're just looking around ssb, and want to contribute styling/UI work, may I suggest you look at [manyverse](https://gitlab.com/staltz/manyverse) or [oasis](https://github.com/fraction/oasis/) instead? I think getting familiar with their code-bases is easier and more fruitful, since they're both under active development.

**Comment by 4rtmelly** [comment]
Okay! Thank you :)
