### ISSUE TITLE
invalid ELF header while trying to run arm64 appimage.

### ISSUE THREAD

**Issue by norayr** [ssbc/patchwork#1415]
hello,

I am using 64bit Gentoo on aarch64 pinebook pro.

I wanted to thank you for preparing an appimage for my architecture.

However, when running the appimage, I get:

```
./Patchwork-3.18.0-arm64.AppImage: error while loading shared libraries: /usr/lib64/libz.so: invalid ELF header
```

my kernel: 5.10.16 from manjaro pinebook pro source.
zlib: 1.2.11-r3
glibc: 2.32-r7

i have /lib/ld-linux-aarch64.so.1 which points to the same file in /lib64.

i got fuse module loaded.
i have both fuse-2 and fuse-3 installed (i know appimage works with fuse 2 only).

what could be the reason?

**Comment by black-puppydog** [comment]
Hi @norayr! Actually cel did some debugging of this the other day: [`%Te7Az/JO1HecWSiryW9KwMI0e2hUixRFP8dzY74BsKs=.sha256`](https://ssb.muchmuch.coffee/%25Te7Az%2FJO1HecWSiryW9KwMI0e2hUixRFP8dzY74BsKs%3D.sha256)

**Comment by norayr** [comment]
thank you!
i never iuilt appimages, so think i'll just wait! or will try to build patchwork from source.
