### ISSUE TITLE
Posts with a timestamp > local will continuously show up in the "new updates" queue

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#143]
This is because the asserted timestamp of the message is being used, when it should not.

All of PWs indexes need to shift from asserted timestamp to receive timestamp (within reason). Will require some careful thought, for reasons I'll outline in another issue.

**Comment by dominictarr** [comment]
What are you thinking for this? if we just iterate/filter the log index (received time) it should give us the correct behavior here.

**Comment by pfraze** [comment]
Some various options...
 1. Receive timestamp. This is fine except for when you're doing an initial sync of an existing user, in which case we'll need:
 2. Initial sync-squashing. We detect when PW is fetching a log for the first time and suppress those events. This might be done by knowing the timestamp of the follow event, and comparing that against receive time. This is good for solving the "New Updates" alert, but it doesn't quite solve ordering the feed by chronology, in which case we might try:
 3. Minimum timestamp: `Math.min(receiveTS, assertedTS)`. When we rank by most-recent-first, this approach would stop somebody from boosting their ranking (accidentally, maliciously) with a bad TS.

**Comment by pfraze** [comment]
This specific issue was happening because, when the newsfeed is opened, it starts a live-stream query for messages later than `Date.now()`. If a message was received with a TS in the future, it would be emitted by the query. #176 uses technique 3 (above) to stop this from happening.

**Comment by dominictarr** [comment]
@pfraze if you do `pl.read({live: true, old: false})` it will get you a stream with _ONLY_ new messages, which should fix that. (actually there might be some spots where I need to fix that, but if you have a live stream that I have written that doesn't support that consider it a bug)

**Comment by pfraze** [comment]
Good tip

**Comment by pfraze** [comment]
I added `{old: false}` to be double-sure this works correctly
