### ISSUE TITLE
Info about how to see old private messages

### ISSUE THREAD

**Issue by iz5wga** [ssbc/patchwork#1438]
Hello,
if I write a privmessage (I use them as private note for just myself) I see them only till they are marked as "new".
If I read them, and close/restart the client patchwork, I'm not able to see them again.
How do I recover them?

**Comment by iz5wga** [comment]
Ok I see that priv messages disappear if I launch patchbay in the same folder as patchwork. It seems it moves files eleswhere.
Is there any way to undo the whole thing ?

**Comment by black-puppydog** [comment]
Hi @iz5wga, I don't have a lot of time right now but just two things:

1. Don't run patchbay and patchwork at the same time
2. If you run them one after the other they will "re-index" a lot of data every time you switch. during that time, not seeing your messages is normal. 
3. Patchbay has been completely unmaintained for a while
4. Patchwork will be unmaintained in about one week from now.
5. None of the two will move your data back or forth. It will always live in `~/.ssb/flume/offset.log` which both patchbay and patchwork read & write to, regardless of which folder you launch them in.

**Comment by black-puppydog** [comment]
Here's an explanation I wrote a while back about re-indexing: `[%udGeAIq/I36t/TnjtmZfXcb/ZnHBZkLLiP7qndMoWCc=.sha256](https://ssb.muchmuch.coffee/%25udGeAIq%2FI36t%2FTnjtmZfXcb%2FZnHBZkLLiP7qndMoWCc%3D.sha256)

**Comment by iz5wga** [comment]
> 4. Patchwork will be unmaintained in about one week from now.

Ah... and what are we using under linux as client then? Are there any alternatives?

**Comment by black-puppydog** [comment]
For the time being, patchwork will of course continue to work. 
Oasis and manyverse are both working hard at making them viable alternatives.
