### ISSUE TITLE
Windows installer throws errors

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#149]
on windows 10, i got : 

```
Error opening file for writing :

C:\Program Files(x86)\Patchwork\resources\app\node_modules\babel\node_modules\bable-core\node_modules\regenerator\node_modules\defs\node_modules\yargs\node_modules\cliui\node_modules\center-align\node_modules\align-text\node_modules\kind-of\node_modules\is-buffer\node_modules\.travis.yml
```

(typed by hand so may have errors)

other similar ones LISCENCE and .zuul.yml files ... Tried ammering the IGNORE button.
Seeing index.js , package.json README.md, .npmirgnore

there are too many to click through and too many that look too core for it to appear safe

**Comment by mixmix** [comment]
@pfraze its going to get really useful to have versions on these installer files so we can reference them more clearly

**Comment by pfraze** [comment]
Ok, will version them in the future.

Does this occur on install or first start?

**Comment by mixmix** [comment]
Install, the installer is powering through copying files and it chokes on some ... I wonder if it's length of path going over some value ... though I thought that wasn't a thing with NTFS

**Comment by mixmix** [comment]
ah ... yes 260 chars limit : http://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10

**Comment by mixmix** [comment]
wow there's a lot of heat on this topic https://github.com/nodejs/node-v0.x-archive/issues/6960#issuecomment-46704998

**Comment by mixmix** [comment]
seems npm 3 resolves this with built in flattening / deduping 
https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by ahdinosaur** [comment]
:+1: npm@3

**Comment by pfraze** [comment]
Used npm 3 to create a new package, here: http://grimwire.com/patchwork.win.dec3-1.zip

**Comment by dominictarr** [comment]
I got this error. Looks like the problem is sodium.

![not-a-valid-windows-application](https://cloud.githubusercontent.com/assets/259374/11574369/31acb4bc-9a70-11e5-8523-66089c90fd59.png)

**Comment by pfraze** [comment]
I bet that's because I built it on OSX, and so the OSX sodium build gets used in the npm_modules.

**Comment by dominictarr** [comment]
Yeah, it would probably work if it didn't have a compiled dependency, but I fear we will need to build this on windows for this to work.

**Comment by pfraze** [comment]
I bet we can get some cloud-hosted windows to run the build for us

**Comment by dominictarr** [comment]
yeah, we'll need to figure out how to make it work first though. That, or there is some sort of cross compiler? I think sodium is gonna be the hard bit, but we can how leveldown does it as a guide.

**Comment by dominictarr** [comment]
I really understand too little about C and windows to get this working I think. Another option might be to write a compatible binding based on http://tweetnacl.cr.yp.to/ which is the same thing, but all in one file + one header file. that should be waaaaay easier to get running

**Comment by dominictarr** [comment]
and you won't need all the suite of build tools - it should be pretty simple...

**Comment by pfraze** [comment]
I'm on board for whatever you think's best

**Comment by mixmix** [comment]
Dominic did you try building in linux for Windows on the off chance?

**Comment by dominictarr** [comment]
@mixmix I don't know how to do that yet.

**Comment by pfraze** [comment]
https://github.com/ssbc/patchwork/blob/master/docs/BUILDING.md#electron-package

doubtful it would work, but you need nsis and wine, and then run

```
npm run build:win
npm run pack:win
```

and the install binary should be in `./dist/win`

**Comment by pfraze** [comment]
I think we could make it work if we could do an `npm install` with windows as the target platform, for the prebuilts

**Comment by mixmix** [comment]
I know the dependencies, i was the one that added those to the readme :)
was just checking whether Dominic had tried that yet. Sounds like he's been
working on some important blocks though

**Comment by pfraze** [comment]
@mixmix oh yeah, I was just repeating them for dominic

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale.

in other news we released and magically [just got `v3` to build on windows](http://viewer.scuttlebot.io/%25%2BSBr3lvHbR2yNKASU7FfLX7fTN06yk4ON1qUipaG9fk%3D.sha256)! :tada:
