### ISSUE TITLE
Subwindows, splitwindows, tabs

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#15]
Viewing replies required a page navigation to the thread's page. This was tedious. It made it hard to monitor threads.

The latest build experiments with the subwindow component (it was already built). Here's what it looks like:

![screen shot 2015-08-14 at 4 28 43 pm](https://cloud.githubusercontent.com/assets/1270099/9284458/99c0b912-42a1-11e5-817a-5f9917d30a42.png)

 - Clicking a message opens its thread in a subwindow.
 - The inbox page also opens in a subwindow. ([pictured here](https://cloud.githubusercontent.com/assets/1270099/9284380/06db0058-42a1-11e5-955f-4ba88bc38e5f.png).)
 - The feed and subwindows update in realtime.

The idea is that you can open threads in subwindows to watch for replies.

**Comment by pfraze** [comment]
I'm not sold on the subwindow UI, but they were already built, and give us 99% of the experience that we want to test (opening threads in an external window to watch).

I'm inclined to think what we really need is tabbed browsing, or some kind of window-manager.

Tabs are a proven pattern, but we could do something different if we wanted.
I mocked up a tiling window-manager:

![screen shot 2015-08-14 at 4 14 55 pm](https://cloud.githubusercontent.com/assets/1270099/9284565/73544856-42a2-11e5-842d-3f5d2138ea98.png)

Homepage on left, inbox on right.

**Comment by pfraze** [comment]
The blob page uses this tiling window manager concept:

![screen shot 2015-08-14 at 4 47 56 pm](https://cloud.githubusercontent.com/assets/1270099/9284769/521c8124-42a4-11e5-988d-aec4f63694d0.png)

If you want to try it, nav to `&suZsSsRXjVGCB3HrJKv2/HFe15JTTtIl20wXouUSWmU=.sha256` and click the comments icon next to the location bar. The sideview that opens shows all the comments which link to that blob. You can toggle that view off/on.

It's a little bit similar to the devtools.

**Comment by pfraze** [comment]
Google hangouts uses a sidenav for multiple active conversations:
![google hangouts nav](http://storage.j0.hn/hangouts.png)

**Comment by pfraze** [comment]
Here's a mockup of what a feed-as-nav might look like:

![feednav-mockup](https://cloud.githubusercontent.com/assets/1270099/9285174/be02bee0-42a8-11e5-9c93-92d9a7851725.png)

**Comment by pfraze** [comment]
Mocked up a sidenav-based UI. Keep scrolling for an explanation of the parts:

![mockup_raw](https://cloud.githubusercontent.com/assets/1270099/9289975/80b40456-4346-11e5-8a75-8151abd6aa02.jpg)

![mockup_content](https://cloud.githubusercontent.com/assets/1270099/9289973/80b1f8dc-4346-11e5-8aac-e44fd7656e65.jpg)
![mockup_content-nav](https://cloud.githubusercontent.com/assets/1270099/9289974/80b27fdc-4346-11e5-8c17-3c9808ced533.jpg)
![mockup_sidenav-sections](https://cloud.githubusercontent.com/assets/1270099/9289976/80b588f8-4346-11e5-83d8-d8cccb09458a.jpg)
![mockup_sidenav-entries](https://cloud.githubusercontent.com/assets/1270099/9289977/80b8417e-4346-11e5-87b6-e61e131dc70f.jpg)

The sidenav would be persistent (though collapsable).
It would help you navigate through threads.
It would update in realtime.

Clicking a thread in the sidenav would open it in the content area.
The content area would browse independently of the sidenav.

**Comment by dominictarr** [comment]
An example of a mainstream app with a tiling layout is tweetdeck.
This actually works pretty well, without most of the weird bugs that twitter.com has.
you can manage many accounts, and it also has keyboard shortcuts for power users!
They don't work perfectly, sometimes it looses focus, but it is a pretty powerful interface!

![2015-08-15-192750_1366x768_scrot](https://cloud.githubusercontent.com/assets/259374/9290059/268b80ce-4384-11e5-9fe5-7aa674173042.png)

by default you have columns, and you can expand a post.
In the screenshot I have expanded one of the messages in the notifications column

**Comment by dominictarr** [comment]
by the way, the subwindow looks really great. it's so familiar it really feels like you are sending a message.
How it separates from the background suits that. it's for private messages, and visually separated from the shared messages.

**Comment by pfraze** [comment]
@dominictarr ok cool, I'll take that as a +1 for subwindows (in some capacity)

I'm checking out tweetdeck. First impressions are positive. Manages to be both more powerful and cleaner than default twitter.
Customizable columns are very cool.

What if we did...
Window-manager with column tiles.
Default layout as I drawn above: two columns, with multiple feed-views stacked, and the main content-browser on right.
The stacked sidenav sections could be dragged out into new columns.
All columns could be re-arranged.

**Comment by dominictarr** [comment]
I'm definately :+1: on subwindows in the case of secret messages. but not for replies.

**Comment by pfraze** [comment]
Experiment branch for a sidepane nav, WIP shot:

![screen shot 2015-08-16 at 11 00 36 am](https://cloud.githubusercontent.com/assets/1270099/9294035/209621f6-4406-11e5-84cc-b85dab590b7c.png)

**Comment by pfraze** [comment]
More work on the sidenav, showing read/unread state:

![screen shot 2015-08-16 at 12 22 46 pm](https://cloud.githubusercontent.com/assets/1270099/9294391/9b36e778-4411-11e5-898c-01fd2d14baa9.png)

**Comment by pfraze** [comment]
Multiple sidenav views (home, inbox, your stars):

![screen shot 2015-08-16 at 3 46 52 pm](https://cloud.githubusercontent.com/assets/1270099/9295292/2518d2dc-442e-11e5-8efc-fa910104a13c.png)

**Comment by pfraze** [comment]
New UI experiment, focusing more on [Patchwork as a browser](https://gist.github.com/pfraze/1f281b738cefbada0164).

Here's the home screen. It's similar to the launcher view when you open a new tab in chrome or FF, but it shows users instead of sites. (The pictures should probably be 3/5 as big.)

![screen shot 2015-08-17 at 2 21 16 pm](https://cloud.githubusercontent.com/assets/1270099/9313972/a8c63076-44eb-11e5-9b0f-d3ce386e523b.png)

Right of the location bar (top) is a dropdown. This lets you select different views for the content you're on.

![screen shot 2015-08-17 at 2 21 18 pm](https://cloud.githubusercontent.com/assets/1270099/9313991/c85ddb14-44eb-11e5-89cd-aa218c4b59fd.png)

The home screen gives you some basic high-level views: the launcher, the home feed, network status page, and raw data feed. Whatever view you select will be the same view used the next time you go home.

![screen shot 2015-08-17 at 2 21 21 pm](https://cloud.githubusercontent.com/assets/1270099/9314031/031df892-44ec-11e5-9212-cb676e3d0304.png)
![screen shot 2015-08-17 at 2 21 23 pm](https://cloud.githubusercontent.com/assets/1270099/9314033/032b9b00-44ec-11e5-9c63-1d9148130e87.png)
![screen shot 2015-08-17 at 2 21 25 pm](https://cloud.githubusercontent.com/assets/1270099/9314032/03280242-44ec-11e5-8dad-46c3e068a389.png)

The main reason for the view selection is for when you're browsing content:

![screen shot 2015-08-17 at 2 31 13 pm](https://cloud.githubusercontent.com/assets/1270099/9314139/a5117afc-44ec-11e5-88de-7cc4dd8792fc.png)

You can jump to other kinds of information that's related. For instance, the discussion view would show conversations that link to the blob. This could be a good place for backlink views.

![screen shot 2015-08-17 at 2 31 09 pm](https://cloud.githubusercontent.com/assets/1270099/9314138/a4f7e416-44ec-11e5-8327-0e8aa3f61de0.png)

By default, when you nav to a user, you'll see their published homepage.
If you wanted to see their posts, friends, etc, you'd jump to their profile view.

**Comment by pfraze** [comment]
[Video walkthrough of the current experiment](https://www.youtube.com/watch?v=Kh-OlD3EIDQ&feature=youtu.be)

**Comment by pfraze** [comment]
I wasn't fully in love with that view dropdown, so I decided to simplify a bit:

![screen shot 2015-08-18 at 11 39 31 am](https://cloud.githubusercontent.com/assets/1270099/9336389/ec992ef8-459e-11e5-91c1-ba473c45569d.png)

The homepage now has a fixed links bar, which can take you to some common apps.
User pages now look like this:

![screen shot 2015-08-18 at 11 46 11 am](https://cloud.githubusercontent.com/assets/1270099/9336407/0ff4ed60-459f-11e5-9382-1beef0dc9f34.png)

The sidepanel can be toggled by clicking the blue question mark on the nav bar:

![screen shot 2015-08-18 at 11 46 14 am](https://cloud.githubusercontent.com/assets/1270099/9336416/1e5b638e-459f-11e5-9ad5-52dc445148bf.png)

I decided to remove the files UIs until we decide whether to use a files abstraction, or a bundle/package one.

There's currently not a way to view posts by a single user (which is what a user page used to show). The news feed app could do that -- click a user's profile on the right column to filter down to their posts.

**Comment by pfraze** [comment]
[Ask HN: What would you want in an ideal web browser?](https://news.ycombinator.com/item?id=10071744)

**Comment by pfraze** [comment]
Moved more out of the navbar and into the home launch shortcuts

![screen shot 2015-08-18 at 3 53 03 pm](https://cloud.githubusercontent.com/assets/1270099/9342701/eb98c09e-45c2-11e5-9005-1b6d6b72bd88.png)

**Comment by pfraze** [comment]
Site publisher UI:

![screen shot 2015-08-19 at 4 00 56 pm](https://cloud.githubusercontent.com/assets/1270099/9368875/87b1cb10-468b-11e5-9f43-e1e93048b2d9.png)

**Comment by pfraze** [comment]
[Video demonstration of the publisher](https://www.youtube.com/watch?v=Oe2-6wRuDtE&feature=youtu.be)
