### ISSUE TITLE
Fails to parse ipv6 invites

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchwork#153]
sbot generates the following invite code when only a IPv6 address is configured:

`"2a03:2267::ba27:ebff:fe8c:5a4d:8080:@gYCJpN4eGDjHFnWW2Fcusj8O4QYbVDUW6rNYh7nNEnc=.ed25519~DxiHEv+ds+zUzA49efDgZk8ssGeqrp/5kgvRVzTM7vU="`

Pasting this as an Invite leads to an `Something is wrong with the invite code.`-Error. Using `[...v6..]:$port:@invite..` also fails with the same error.

Workaround: Setting up a `/etc/hosts`- or DNS-Entry.

PS: [ffhh](http://hamburg.freifunk.net/) pub coming next week

**Comment by pfraze** [comment]
Ok thanks for the report!

**Comment by dominictarr** [comment]
the problem here is that https://github.com/ssbc/ssb-ref/blob/0e59569105d2e5d030ed69454cd16b539d81b1ab/index.js#L31-L46 is not aware of ipv6 addresses.
