### ISSUE TITLE
double messages on post

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#16]
i'm getting more double messages

![2015-08-15-191334_1366x768_scrot](https://cloud.githubusercontent.com/assets/259374/9289998/e5f4c95a-4381-11e5-9f75-ba05325307d3.png)

**Comment by pfraze** [comment]
Yeah, when you refresh, they go away, right?

**Comment by dominictarr** [comment]
yes.

**Comment by pfraze** [comment]
Got it

**Comment by pfraze** [comment]
Fixed in `ssb-patchwork-ui@0.0.11`
