### ISSUE TITLE
When hovering over a link, show the URL somewhere in the UI

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#163]
url preview for links please...  make it work just like a browser

as mentioned in this private conversation with @pfraze  : 
%EuStmweGPLn4pRdUOAsAPBStzYpTOdNpxeivmHWkh/o=.sha256

hmm .. http://localhost:7777/%EuStmweGPLn4pRdUOAsAPBStzYpTOdNpxeivmHWkh/o=.sha256
guess that's blob-address .. but daydreaming ...

**Comment by mixmix** [comment]
hah .. [http://localhost:7777/%EuStmweGPLn4pRdUOAsAPBStzYpTOdNpxeivmHWkh/o=.sha256](http://localhost:7777/%EuStmweGPLn4pRdUOAsAPBStzYpTOdNpxeivmHWkh/o=.sha256)

manually linking ...

**Comment by mixmix** [comment]
wow I'm a derpster @ahdinosaur to the rescue again  !

**Comment by pfraze** [comment]
?

**Comment by mixmix** [comment]
Lord, i woke up at 5am that day and made a lot of mistakes.
Paying and closing wrong issue for example

**Comment by pfraze** [comment]
Haha

**Comment by ahdinosaur** [comment]
superseded by https://github.com/ssbc/patchwork/issues/520
