### ISSUE TITLE
Improve all load performance 

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#173]
Feed load, feed scroll, and thread load are all too slow. This can be improved in rendering, and with better processing and caching. Make it so!

**Comment by pfraze** [comment]
Some opportunities I've found:
 - Setting env var `NODE_ENV="production"` disables some React debugging that shaves off some ms
 - [shouldComponentUpdate](http://facebook.github.io/react/docs/advanced-performance.html) is essential to getting small updates and scrolling to be jank-free.

Rendering 30 messages on the newsfeed purely from memory takes ~80ms. From SSB, takes ~250-300. I need to chart performance of the pure API loads, and then of the IPC transfers. There should be some improvements to make in there.

The last resort solution is to cache messages inside the UI thread.

**Comment by pfraze** [comment]
https://facebook.github.io/react/docs/perf.html react perf tools

**Comment by dominictarr** [comment]
what about streaming the load, it's nice to have 30 mesages because I will scroll down in a second, but I can't read that fast. would showing the first message asap be faster?

**Comment by pfraze** [comment]
I've been planning to try that again. In previous tests, the render performance for streaming in posts was really poor. But, since then, I discovered the `shouldComponentUpdate` optimization could solve the slowdown.

**Comment by dominictarr** [comment]
hmm, what is `shouldComponetUpdate`? that sounds like a leaking abstraction.
maybe react isn't ideal for streamy appends, but is really for easy to maintain arbitary updates.
If we go with something to specially manage the infinite scrolly bits (feeds) how would that integrate with react? can we add react components into a thing which is not react? can we just add one more react element?

**Comment by pfraze** [comment]
It's an optimization to deal with a component that has a lot of vdom to diff (which the msg-list does). I think it's better to use it, than to try to escape out of React for this piece.

**Comment by pfraze** [comment]
Both of those improvements were implemented. Performance is an ongoing task, but I'm going to close this issue
