### ISSUE TITLE
Create a module for producing posts (extract from composer)

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#179]
Per @NHQ's request, let's put the composer's post-preparation into a module so it can be reused.

**Comment by NHQ** [comment]
[ssb-ref](https://github.com/ssbc/ssb-ref/blob/master/index.js) needs only a small change to be useful in the manner, from regexp.test to .exec

We could add exports.has* methods to match all of exports.is* methods.

I'll do that unless you have something smoother.

**Comment by mmckegg** [comment]
Probably not relevant anymore with patchbay. Closing!
