### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by thomasdelaet** [ssbc/patchwork#18]
Hey,
I would like to try patchwork. Any tips on how to get it to run on Linux?

I did npm install. When I try to run npm run build:nix I get the following output:
thomas@sting:~/repositories/patchwork$ npm run build:nix

> ssb-patchwork@0.0.5 build:nix /home/thomas/repositories/patchwork
> electron-packager ./ scuttlebot --out=dist/linux --platform=linux --arch=x64 --ignore=node_modules/electron* --version=0.28.3 --icon=assets/osx/scuttlebot.icns

Packaging app for platform linux x64 using electron v0.28.3
[ { [Error: ENOENT, stat '/home/thomas/repositories/patchwork/dist/osx/Scuttlebot.app/Contents/Frameworks/Electron Framework.framework/Libraries/Libraries']
    errno: -2,
    code: 'ENOENT',
    path: '/home/thomas/repositories/patchwork/dist/osx/Scuttlebot.app/Contents/Frameworks/Electron Framework.framework/Libraries/Libraries' },
  { [Error: ENOENT, stat '/home/thomas/repositories/patchwork/dist/osx/Scuttlebot.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/Libraries']
    errno: -2,
    code: 'ENOENT',
    path: '/home/thomas/repositories/patchwork/dist/osx/Scuttlebot.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/Libraries' },
  { [Error: ENOENT, stat '/home/thomas/repositories/patchwork/dist/osx/Scuttlebot.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries']
    errno: -2,
    code: 'ENOENT',
    path: '/home/thomas/repositories/patchwork/dist/osx/Scuttlebot.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries' } ] undefined

npm ERR! Linux 4.1.0-1-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:nix"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! ssb-patchwork@0.0.5 build:nix: `electron-packager ./ scuttlebot --out=dist/linux --platform=linux --arch=x64 --ignore=node_modules/electron* --version=0.28.3 --icon=assets/osx/scuttlebot.icns`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@0.0.5 build:nix script 'electron-packager ./ scuttlebot --out=dist/linux --platform=linux --arch=x64 --ignore=node_modules/electron* --version=0.28.3 --icon=assets/osx/scuttlebot.icns'.
npm ERR! This is most likely a problem with the ssb-patchwork package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./ scuttlebot --out=dist/linux --platform=linux --arch=x64 --ignore=node_modules/electron* --version=0.28.3 --icon=assets/osx/scuttlebot.icns
npm ERR! You can get their info via:
npm ERR!     npm owner ls ssb-patchwork
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/thomas/repositories/patchwork/npm-debug.log

Any tips?

**Comment by pfraze** [comment]
Hey @thomasdelaet. Did you run `npm install -d`, with the -d switch on?

**Comment by thomasdelaet** [comment]
Not sure anymore. Will try again.

I read documentation in your docs repository and tried npm start. This gives the following output:

thomas@sting:~/repositories/patchwork$ npm start

> ssb-patchwork@0.0.5 start /home/thomas/repositories/patchwork
> electron .

[25065:0831/180759:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App threw an error when running [Error: Module version mismatch. Expected 44, got 14.]
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Module version mismatch. Expected 44, got 14.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/thomas/repositories/patchwork/node_modules/ssb-keys/node_modules/chloride/lib/sodium.js:16:15)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)

**Comment by thomasdelaet** [comment]
-d flag is just for debugging, right? So it wouldnt change anything I guess ...

**Comment by pfraze** [comment]
@thomasdelaet `-d` tells npm to install dev dependencies. We're still in active development, so you need those.
Also, I'm running `iojs@2.3.0`, and you'll probably need to do the same. I recommend using https://github.com/creationix/nvm to set the version.

**Comment by thomasdelaet** [comment]
Okay. Clear.

The documentation mentions 2.5.0 BTW. But will try with 2.3.0

**Comment by thomasdelaet** [comment]
Works. Thanks!

I think the reason was that I didnt install automake + also didnt use iojs

**Comment by thomasdelaet** [comment]
would be great to get an invite ;-)

**Comment by pfraze** [comment]
Cool :) sorry for the trouble, we're not quite operational yet

**Comment by dominictarr** [comment]
@thomasdelaet here is an invite for you: 176.58.117.63:8008:@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519~u+ZSuJhpItAboqAYtVo0wmW9iLmY6t7QGp+qXlz2GAE=

**Comment by mixmix** [comment]
I had the same issue. I've got the app working on `iojs 2.5`, (used that because of [this doc](https://github.com/ssbc/docs#overview)), but unable to get `npm run pack` working.

will try with `iojs 2.3`
