### ISSUE TITLE
Show topic in main nav bar

### ISSUE THREAD

**Issue by jrf0110** [ssbc/patchwork#182]
![Topic](http://storage.j0.hn/Screen%20Shot%202015-12-12%20at%201.35.01%20PM.png)

Just going to paste from chat:

> Could truncate

> I'd imagine it would animate in
> moving that whole thing over
> also, I changed the styles on that nav
> opacity: 0.5 and 1.0 for active

> but... you could make that a fixed width area
> that shows your current context
> and if it gets trucnated
> then animate the text
> music player style

**Comment by jrf0110** [comment]
Related to #178

**Comment by pfraze** [comment]
I dont think we're going to do this, but I'll keep it in mind in the future, if it does seem like the right call
