### ISSUE TITLE
The 4 Modes: Feed, Forum, Inbox, and Chat

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#192]
There may be some room to debate this, but I would assert there are four dominant modes of conversation online:

 - **The Feed**. Twitter / Facebook. Good for sharing short-form media inline, like pictures, videos, links, or quips.
 - **The Forum**. Reddit / HN / Slashdot. Good for sharing links and having long conversations.
 - **The Inbox**. Email / RSS Readers. Good for short & long conversations that require your attention.
 - **The Chat**. Gchat / IRC. Good for realtime conversation.

In the past, we've discussed these different modes in PW informally. We talked about the "feed" as the distraction mode, and the "forum" the discussion mode. And, we decided to implement a Feed and an Inbox, as two necessary pieces. However, I think we sometimes waffle on our 4 modes, by letting Forum and Chat creep into ideas for Feed and Inbox, and this hurt our focus.

Most crucially, I think we need to make a hard distinction between Feed and Forum. The Feed is not good for managing conversations; it's best as a way to browse inline media. Trying to force the Feed into a dual purpose -- both for browsing media and for managing conversations -- has been ineffective.

(The toggle in the current build, for instance, to put the feed into "inboxish" rendering vs "feedish" rendering, was an attempt to make the feed handle both tasks. It hasn't felt very good to me. Posts which are made for a Feed just don't belong in a Forum or an Inbox, because they tend to be throw-away observations or simple images. The medium is the message, or at least it determines what messages you want in the space.)

I believe we should remain focused on the communication modes we've chosen, and accept their limitations. The feed is not ideal for conversations, but it excels in media discovery.

If we feel the Forum and Chat should be included, let's slate them as future features. Speaking personally, I would very much like to have a Forum, perhaps even in the near future. But, I don't have the capacity for it. If there is anybody who wants to contribute the Forum, I will happily work alongside you to make that happen!

**Comment by kumavis** [comment]
good summary @pfraze
