### ISSUE TITLE
download should save the filename, not the hash

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#200]
when saving a pdf, it trys to save it as the hash, which is hard to work with.
Also, it wanted to save in a weird place (~/.config/ssb-patchwork/Downloads)
this seems to be a electron thing (other directories looked like browser stuff)
is there anyway to work around this?

**Comment by pfraze** [comment]
Yes, agree with your assessment, and this should be easily solveable.

**Comment by pfraze** [comment]
https://github.com/ssbc/patchwork/commit/b0aa437c6bee19733c07e268da99b887a36b7319 improves this by using the link's text as a suggested filename

**Comment by dominictarr** [comment]
:+1:

**Comment by pfraze** [comment]
going to close, reopen if anything's not working

**Comment by dominictarr** [comment]
:+1:
