### ISSUE TITLE
Mentions are incorrectly included in detection of whether a thread has any unread replies

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#205]
Similar to https://github.com/ssbc/patchwork/issues/137, but this time for checking the unread state

**Comment by cryptix** [comment]
Does this mark bookmarks as unread again as well?
I saw that and questioned sanity of me and/or my devices.

**Comment by pfraze** [comment]
That might be an unrelated issue, I'm unsure.

**Comment by pfraze** [comment]
Solved with `patchwork-threads@1.1.4`
