### ISSUE TITLE
Expand threads in-place

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#218]
@dominictarr has been requesting this for ages. Let's see what in-place expansion feels like, especially compared to the "thread preview panel" we tried earlier.

**Comment by pfraze** [comment]
This is from an old branch

![screen shot 2015-12-26 at 8 12 13 pm](https://cloud.githubusercontent.com/assets/1270099/12008712/3789fdaa-ac0d-11e5-90a2-79e5d47520cf.png)

**Comment by dominictarr** [comment]
looks good!

**Comment by pfraze** [comment]
This should be done for all 3 view modes (inline, large, compact)

**Comment by pfraze** [comment]
Here's how this should be done:

For "inline" rendering mode, the last two replies should be shown, similar to the screenshot above (but prettier if you can manage it). If there are more than 2 replies, clicking on the number of replies should expand it inline. There should also be a reply box at the bottom, at all times.

For the "large" and "compact" rendering modes, clicking on a message in the feed should expand the entire thread in-place, underneath the message.

**Comment by pfraze** [comment]
Done
