### ISSUE TITLE
Enforce node v5 with .nvmrc and package.json

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#221]
Seeing as anything but node v5 now makes electron die in flames, we should probably give users a helping hand in the config files.

- Update .nvmrc to suggest v5
- Update package.json to force v5

**Comment by ahdinosaur** [comment]
https://github.com/ssbc/patchwork/pull/223

**Comment by mmckegg** [comment]
Looks like this was fixed. Closing!
