### ISSUE TITLE
code organization: ui/com -> ui/views/com ?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#250]
it seems that everything in `ui/com` is a jsx and I'm guessing this is only used from things that are already in `ui/views`? is the distinction here that things in `ui/views` are top level and everything in `ui/com` is used by more than one view? (or recursively in other things in com?)

If it's next to views that implies that it's used by other things at the top level.
Also does "com" mean the same thing as "lib"?

**Comment by pfraze** [comment]
> is the distinction here that things in ui/views are top level and everything in ui/com is used by more than one view? (or recursively in other things in com?)

Yes. Com = Component, View = Toplevel (basically "Page"). Coms get used outside of views sometimes, like in `layout.jsx`.

Ideally everything in `com` will get factored out into modules someday

**Comment by dominictarr** [comment]
ohhh I thought "com" meant "common"... is `layout.jsx` is the only other one, that could be in views too?

**Comment by pfraze** [comment]
Yeah I think it's just `layout` and `views/*`

**Comment by dominictarr** [comment]
can we move those both into views? I think that would make what depends on what more obvious.

**Comment by pfraze** [comment]
eh, that'd be more work then you'd expect. I'd have to update the include paths in every file under com and views. Can we just leave it till com is modularlized out?

**Comment by dominictarr** [comment]
I'll do it. It will be good to get to know the frontend.
and lets be honest, modularizing these out "someday" is probably a very low priority.

**Comment by pfraze** [comment]
yeah, I was actually just wondering whether now's a time to prioritize that, but then I started to wonder if anybody will ever *actually* use them. I figure, when somebody shows up asking for it in their project, is probably when that'd happen

**Comment by dominictarr** [comment]
I wouldn't be surprised if one or two things get reused, but most of the things wont be. Also many of them have depend on globals (../lib/app is a global dressed as a dependency)

**Comment by pfraze** [comment]
yeah, the global can get fixed through a couple different solutions (one is to pass in all props explicitly, the other is react's `context` thing). But I think the reusability point is right

**Comment by dominictarr** [comment]
Ui elements are very hard to modularize anyway. most of these are specific to patchwork, so it seems unlikely. maybe higher up the stack things get modularizable... like something that deals with infinite scroll etc
