### ISSUE TITLE
"peers.toJSON is not a function" on initial startup

### ISSUE THREAD

**Issue by gardner** [ssbc/patchwork#260]
``patchwork-electron``: 780c21afb4ca008fc5d3c70b1bfe9006be407afe
``patchwork``: be611f5dbd6aa4af502a8c9ad11c44328131ece2

<img width="1136" alt="screen shot 2016-01-22 at 4 31 38 pm" src="https://cloud.githubusercontent.com/assets/787026/12501757/c12f68ba-c125-11e5-9aff-2ab87f68fb9d.png">

peers.toJSON is not a function

TypeError: peers.toJSON is not a function
    at FollowNearby.onPeersUpdate (http://localhost:7777/main.build.js:76210:23)
    at http://localhost:7777/main.build.js:76218:16

This was an unhandled exception.

**Comment by pfraze** [comment]
Yeah I've been getting this. Investigating now.

**Comment by pfraze** [comment]
Thanks for reporting!
