### ISSUE TITLE
Insert the RPC manifest into the frontend

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#269]
Currently it's being duplicated by hand into `ui/lib/ws-client.js`, and it really ought to be inserted into the page at load-time.

**Comment by pfraze** [comment]
In `http-server.js`, the `ui/main.html` file is served by the `ServeApp` function. You should be able to get the RPC manifest with `sbot.getManifest()`. By splicing that into `main.html` as a JSON, you'll be able to replace the manifest that's in `ui/lib/ws-client.js`

**Comment by dominictarr** [comment]
we did this before by putting the manifest in a separate script tag that set a global variable. which is nice because it doesn't require a build step.
