### ISSUE TITLE
Build fails on windows due to environment variables

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#272]
`NODE_ENV=development node ...` doesnt work on windows, causing the builds to fail

**Comment by pfraze** [comment]
There are also issues with nix-specific commands, like mkdir -p

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

in other news we magically [just got `v3` to build on windows](http://viewer.scuttlebot.io/%25%2BSBr3lvHbR2yNKASU7FfLX7fTN06yk4ON1qUipaG9fk%3D.sha256)! :tada:
