### ISSUE TITLE
"Read more" link does not work

### ISSUE THREAD

**Issue by lachenmayer** [ssbc/patchwork#281]
![image](https://cloud.githubusercontent.com/assets/38614/12659665/e80a1994-c607-11e5-952d-b436dd827366.png)

**expected behavior:** the message should expand.
**actual behavior:** nothing happens in the UI, the console logs the following:

> Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

This happens every time, for every "Read more" link.

**browser version:** Google Chrome Version 47.0.2526.111 (64-bit)
**OS:** OS X 10.11.2
**patchwork version:** [master@bc4b4f4](https://github.com/ssbc/patchwork/commit/bc4b4f488684ff577b7a029303e2c46a6a6edec5)

✌️

**Comment by lachenmayer** [comment]
Actually, viewing a specific message, the message does expand. The same error message is logged though.

**Comment by clehner** [comment]
It sounds like it could be because of the "javascript:" URLs from [#248](https://github.com/ssbc/patchwork/pull/248/files). Pehaps "javascript:" could be whitelisted somehow in the CSP. Or the javascript URLs could be replaced with href="" and the onclick handlers could cancel the default action. @paul @krl?

**Comment by pfraze** [comment]
Yeah those warnings should be harmless, but the right way to deal with this is to have the handlers cancel the events. @lachenmayer is it not expanding?

**Comment by lachenmayer** [comment]
@pfraze only in a specific message view. In the feed view nothing happens.

**Comment by pfraze** [comment]
This feature has been replaced, so......fixed!
