### ISSUE TITLE
Keyboard scrolling is broken

### ISSUE THREAD

**Issue by krl** [ssbc/patchwork#283]
Reproduce:

When the page is loaded, press the down-arrow. In chrome nothing happens, in firefox the 'Loading' div is scrolled into view.

When clicking somewhere with no link on the page, scrolling now works as expected.

I tried fixing this with html autofocus, but did not get anywhere. calling .focus() on the main div does nothing as far as i can tell.

**Comment by pfraze** [comment]
It's not great that scrolling doesnt work without clicking first, but that may be an inescapable consequence of the VerticalFilledContainer which is frequently used throughout the application. (Especially in earlier iterations, I found a frequent need for containers that scrolled vertically within the document.)

If we can just make sure that the 'Loading' element is never made visible (in Firefox) that would be a suitable fix, for now. When the page is rendered in `ui/main.js`, there's an opportunity to remove that Loading element.
