### ISSUE TITLE
make: node: Command not found

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#292]
Matthew Slater tried to install Patchwork at my suggestion and reports this problem:

He did
`npm install ssb-patchwork -g`

> my ubuntu refused to install patchwork.
> make: node: Command not found
> Makefile:9: recipe for target 'configure' failed
> make: **\* [configure] Error 127
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
> Nodejs is up to date. 
> I'm on Ubuntu 15

I should also add, I don't think he is really very interested, he is just humoring me... :grin:

**Comment by pfraze** [comment]
This is a problem with Ubuntu's packaging of node. Apparently there was already a `node` program, so they named it `nodejs`, and that's why this is failing.

Valid bug, we'll need to update our make to handle this.

**Comment by pfraze** [comment]
@dominictarr what are the odds this is in the crypto build? I think the only things which get 'maked' on install is the crypto and level.

**Comment by dominictarr** [comment]
oh yeah, don't use apt-get to install node, they don't keep their registry uptodate enough for node style development. it's just really old. I'd recommend using nvm instead.

or, probably better, install from one of the dists https://github.com/ssbc/dists

**Comment by irab** [comment]
A couple of option to get around this in Debian if for some reason you don't want to use NVM

1.  Make a symlink to /usr/bin/node: `ln -s /usr/bin/nodejs /usr/bin/node`
2.  I think the nodejs-legacy package uses the original /usr/bin/node: `apt-get install nodejs-legacy`
3.  Install NodeJS 6 (or 4) directly from nodesource.com: `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
