### ISSUE TITLE
Search for message, feed, or blob ID should work

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#295]
The navigation special cases for search seem to have been lost in #293 or so.
This makes it hard to navigate to a thing when having only its ID. I find it useful to be able to paste a message ID into the search bar to navigate to the message. Anyone else?

**Comment by pfraze** [comment]
Yes agreed, this is a regression

**Comment by dominictarr** [comment]
Just saying this is something that would be pretty easy to test.

**Comment by clehner** [comment]
Fixed in #305, lack of tests notwithstanding
