### ISSUE TITLE
electron: focusing search field sometimes fails

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#297]
After the app first loads, if I press CmdOrCtrl+K to focus the search bar, it works. But after I navigate to any page, pressing the shortcut triggers an error:
```
TypeError: Cannot read property 'focus' of undefined
    at TopNav.focusSearch
```
It seems that 'search' disappears somehow from TopNav's refs object, even though the SearchPalette is still in the DOM.

**Comment by pfraze** [comment]
@clehner I think this is fixed

**Comment by clehner** [comment]
Yes, I can no longer reproduce it. :+1:
