### ISSUE TITLE
quirks encounter running patchwork

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#3]
1. switching between text and video creates multiple textareas
2. ctrl-l should select the location bar (firefox shortcut)
3. alt-left/alt-right should move forward/backwards in history
4. control-enter should post whatever form you are in
5. need to add a pub server is not obvious, should be an obvious helper if you arn't on a pub yet.

**Comment by dominictarr** [comment]
6. pub error is not helpful "Invalid Invite Code" stack trace would be better. it feels like it's not actually trying.
7. an alert pops up on an invalid pub message. should just ignore it.

**Comment by dominictarr** [comment]
8. pub page does not update when i add a pub manually. reload doesn't help.

**Comment by pfraze** [comment]
Added keyboard shortcuts to the planwiki https://github.com/ssbc/patchwork/wiki#keyboard-shortcuts

Also added a section about detailed error modals: https://github.com/ssbc/patchwork/wiki#detailed-error-modals. Im ok putting stack traces in there if it's behind an "advanced" ui-control that is collapsed by default. Stack traces freak people out, they usually mean there's an error that the program didnt catch, and so now the trace is getting dumped.

Keep updating with experiences with the pubs and onboarding, that's an area that hasnt gotten a lot of love yet

**Comment by dominictarr** [comment]
@pfraze behind a thing is fine, but if someone tells me about a problem i want to be able to get useful information.

**Comment by dominictarr** [comment]
9. you click on "sync" on the pub screen, but it doesn't give any sign of doing anything. if there was an error it should indicate that some how.

**Comment by dominictarr** [comment]
11. pub "members" should include the pub itself.

**Comment by dominictarr** [comment]
2. there is no indication a new message has arrived. you have to refresh. people expect more "realtime" interfaces these days.

**Comment by dominictarr** [comment]
12. right-click on post link (time) doesn't work.
13. pasting a link to a message in a message isn't detected as anything.

**Comment by pfraze** [comment]
Message IDs should be recognized, though not with any autocomplete. Can you paste the ID here?

**Comment by dominictarr** [comment]
this is the raw message:

``` json

{
  "key": "%yvu4Xcke/X9oYPHTQtvpB28lpC3Jk/C60qHH/THqGmk=.sha256",
  "value": {
    "previous": "%1K5E/GDHxA9BDM0FsdIV0SYRrdvQJ3zzcbjjVAFs9Yg=.sha256",
    "author": "@BIbVppzlrNiRJogxDYz3glUS7G4s4D4NiXiPEAEzxdE=.ed25519",
    "sequence": 18,
    "timestamp": 1438977059743,
    "hash": "sha256",
    "content": {
      "type": "vote",
      "vote": {
        "link": "%Qzdgg3yhpG3RQnBbQpapVf86cwDNQVGdCPy0VWsnptY=.sha256",
        "value": 1
      }
    },
    "signature": "8L7T04my9D0kbmZsEBEuU8X8+5DTM+SmNW8NgLxZMs4GFD7lNWF0XdvEiXUvW1BxNYPWW+/7nXPoEByOit4EBw==.sig.ed25519"
  },
  "timestamp": 1438977059746
}
```
it is detected! but it's not rendered as a link );

**Comment by pfraze** [comment]
@dominictarr is that the right raw message? "pasting a link to a message in a message isn't detected as anything." made me think you were pasting a message id into Patchwork's post form, so I was expecting a `type: post`

**Comment by dominictarr** [comment]
sorry, wrong message

**Comment by dominictarr** [comment]
this is the right one

``` json
{
  "previous": "%utxyjNw8dtbedYlb0Rnn3P7ks4V0kGEDdyzG5O6ETxY=.sha256",
  "author": "@BIbVppzlrNiRJogxDYz3glUS7G4s4D4NiXiPEAEzxdE=.ed25519",
  "sequence": 16,
  "timestamp": 1438976856523,
  "hash": "sha256",
  "content": {
    "type": "post",
    "text": "hello\n\n%sYZDD1+cOg52V+AQnXwcLsagUyYW2CUSynk5RFORV0c=.sha256",
    "mentions": [
      {
        "link": "%sYZDD1+cOg52V+AQnXwcLsagUyYW2CUSynk5RFORV0c=.sha256"
      }
    ]
  },
  "signature": "e8jaDNxBEv8nQAhHUsiUF0K/9uwn7QkEFkL8GW83CM9nys3opBHLnU/MDMg3COW5JjCFOf+VNQkIOrOqkCwEBQ==.sig.ed25519"
}
```

**Comment by pfraze** [comment]
Ah, the newline is failing as a preceding character. Something broken in the regex. Easy fix.

**Comment by dominictarr** [comment]
@pfraze use \b i think, for "word boundry"

**Comment by dominictarr** [comment]
14. unread messages inbox number never goes down.

**Comment by dominictarr** [comment]
15. the progress bar on the sync page doesn't seem work right.

**Comment by dominictarr** [comment]
some of these bugs i am finding are actually scuttlebot bugs.
adding tests and fixing them when i find them.
