### ISSUE TITLE
Broken Link in Docs: "HOWTO: Setup a Pub"

### ISSUE THREAD

**Issue by gardner** [ssbc/patchwork#309]
**Steps to Reproduce**
Visit https://ssbc.github.io/patchwork/
Click the link labeled "HOWTO: Setup a Pub"
Please note the browser is directed to https://ssbc.github.io/sbot/howto-setup-a-pub.md which produces a 404 error

**Comment by pfraze** [comment]
Thanks, I'll fix that link.
