### ISSUE TITLE
Reply to a post in the middle of a conversation thread

### ISSUE THREAD

**Issue by tristanls** [ssbc/patchwork#31]
I found myself wanting to reply to a post in the middle of a conversation thread but couldn't figure out how to make that happen. I only saw the ability to reply to the last post in the conversation thread.

**Comment by dominictarr** [comment]
what you can do is create a new thread, and mention the post you are replying to by mentioning it's id
(click on that message, copy the location bar, then paste it into a new message) then that message will have a backlink to your new thread shown in the UI.

**Comment by tristanls** [comment]
lol... have you tried reading that out loud 3 times :)

**Comment by dominictarr** [comment]
yeah, I'd also prefer a threading model, but @pfraze was working on this and thinks that a flat thread looks nicer.

**Comment by tristanls** [comment]
Oh... you responded too quickly.. I was trying to figure out how to embed this :) 

https://www.youtube.com/watch?v=H70Fp81A7SE

**Comment by tristanls** [comment]
I've attempted the approach. The outcome was unexpected in that it looks like I'm replying to the originating message instead of a reply to that message?

<img width="665" alt="screen shot 2015-09-30 at 5 23 07 pm" src="https://cloud.githubusercontent.com/assets/730640/10208311/1900d070-6798-11e5-9789-9e0c8c8d784b.png">
