### ISSUE TITLE
network sync view

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#333]
Since I've been refactoring the gossip sbot plugin, there are some things I'd like to remove,
but are used in the patchwork network sync view.

So, I looked through the patchwork code to check what it properties it actually uses on the peers view,
so for now, these are just my notes.
-  `.time.connect` and `.time.attempt` (checks whether you have successfully connected to this before)
- `.host` (to check if this is a localhost or lan address - instead use instead, it would be better ot use.source===`local`)
- `.announcers` (used sorting; change to sorting by last connect, and compare connected peers by lowest ping)
- `.key` (to check if this peer follows you) 
- `.connected` (to see if currently connected)

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

@dominictarr if you'd prefer this to stay open, please re-open.
