### ISSUE TITLE
Feature/module request: reactive message byte counter UI with overhead calculation built in

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#334]
The 8kb limit is just sort of vignette-length, which is grating but understandable :P

A UI element in the Composer view counting down against the character limit would ease the pain.

**Comment by pfraze** [comment]
This is hard to do well (I tried it). You have to create the message JSON, including all links, and then estimate how big the headers are going to be too. Then, every keystroke, you have to recalculate that. (Gross but it wasnt slowing things down too much.)

The biggest problem is how it appeared to the user. If you mention something, then links get added to the message, and suddenly the available character-count drops by like 100. It's WTF inducing.

I think there are only two realistic solutions to this:

 1. Impose an artificially-low character limit; so low (say... 140 chars?) that the mention-links wont end up going over.
 2. Automatically turn too-long messages into a different structure. Put the extra text as a second message, or as a blob, and then reconstruct the message correctly. That way, there is no character limit.

I think choice 1 would be great for a micro-post type in a different kind of app than patchwork, and choice 2 would be right for patchwork.

**Comment by dominictarr** [comment]
what about don't show characters, just have a progress bar?
@du5t really only needs to know when he's getting close to the max.

**Comment by christianbundy** [comment]
I think this might be easier after https://github.com/ssbc/scuttlebot/issues/574 is resolved. I've played around with it a bit but haven't found a way to do it yet.
