### ISSUE TITLE
When trying to sign up for patchwork for the first time

### ISSUE THREAD

**Issue by bcomnes** [ssbc/patchwork#34]
iojs v2.5.0
npm 2.13.2

```
message has invalid properties

Error: message has invalid properties
    at Object.exports.isInvalidShape (/Users/bret/repos/patchwork/node_modules/scuttlebot/node_modules/ssb-feed/util.js:105:12)
    at validate (/Users/bret/repos/patchwork/node_modules/scuttlebot/node_modules/ssb-feed/validator.js:69:14)
    at /Users/bret/repos/patchwork/node_modules/scuttlebot/node_modules/ssb-feed/validator.js:50:7
    at /Users/bret/repos/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/index.js:317:22
    at /Users/bret/repos/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:15
    at /Users/bret/repos/patchwork/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:120:19

This error occurred while trying to post a new profile in setup.
```

**Comment by bcomnes** [comment]
Console.logging message out of ssb-feed i get:

```
*****WWWEEEEE*****
{ previous: null,
  author: 'lzMHSo63Do77Fg4qdDrcIk6yJ+HWQs6YH+fD217S6+s=.ed25519',
  sequence: 1,
  timestamp: 1444535285679,
  hash: 'sha256',
  content: 
   { type: 'about',
     about: 'lzMHSo63Do77Fg4qdDrcIk6yJ+HWQs6YH+fD217S6+s=.ed25519',
     name: 'bret' },
  signature: 'xzdtZHR7cTQn1iVj2PFmupgHS+PSUQajmHjdokR/KP4n8ec5G4mwrSF+1tC/3OckRNX4iIJctlDFtXTFwSbRBQ==.sig.ed25519' }
```

@dominictarr said it was strange that the hash is missing `@`  `¯\_(ツ)_/¯`

**Comment by pfraze** [comment]
Yeah, that's pretty odd. I'll poke around for spots where that could be happening...

**Comment by bcomnes** [comment]
Note, the `*****WWWEEEEE*****` was a logging marker I thew in.  I started digging into node_modules with `console.log` in hand in order to understand whats going on.

**Comment by pfraze** [comment]
We found the issue, @dominictarr has a fix coming

**Comment by pfraze** [comment]
Ok, run `npm update` so that `ssb-keys` is version `4.0.5` and your issue should be resolved.

**Comment by bcomnes** [comment]
\o/  Will a little after work!  Out of curiosity, was this the fix? https://github.com/ssbc/ssb-keys/commit/76a13d673e996010f656adc44a1d69cc41b38633

Will close out this evening after I test.

**Comment by pfraze** [comment]
No, the fix was
https://github.com/dominictarr/ssb-keys/commit/ace73b3d767f81bc5e2733880d76cec0259e9666#diff-168726dbe96b3ce427e7fedce31bb0bcR125

Basically the situation is, you had a slightly old keyfile format from an
earlier version, that didnt have the @ sigil in the ID. That caused
everything to freak out. So, we just add the @ if it's missing.

**Comment by dominictarr** [comment]
@bcomnes did this work for you?

**Comment by bcomnes** [comment]
Swamped by work.  Haven't had a chance to check yet :frowning:

**Comment by dominictarr** [comment]
okay, I'm gonna reopen this till you confirm

**Comment by bcomnes** [comment]
> Basically the situation is, you had a slightly old keyfile format from an earlier version, that didnt have the @ sigil in the ID.

Totally possible.  I tried this a while back.

**Comment by bcomnes** [comment]
Ok I got on! :grinning: 

`@lzMHSo63Do77Fg4qdDrcIk6yJ+HWQs6YH+fD217S6+s=.ed25519`
