### ISSUE TITLE
NotFoundError causing crash

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#360]
```
note @f/6 REPL @uRECWB4KIeKoNMis2UYWyB2aQPvWmS3OePQvBj2zClg=.ed25519 success "Feeds updated: 2, New messages: 2"
note @f/6 REPL @V+sfZ+X/MSUb+cO3GVI4gn1cCVVwz1+t6B+J9DlUkQs=.ed25519 success "Feeds updated: 1, New messages: 2"
note @f/6 REPL @j3qWwQrWPzTM9zNgk0SI0FcqP1ULGquuINYEWfL330g=.ed25519 success "Feeds updated: 1, New messages: 1"
NotFoundError: Key not found in database
    at /usr/local/src/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:18
    at /usr/local/src/secure-scuttlebutt/node_modules/level-sublevel/nut.js:120:19
patchwork (master)@cel (node system)$ echo $?
1
patchwork (master)@cel (node system)$ node .
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Patchwork - Copyright (C) 2015-2016 Secure Scuttlebutt Consortium
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions (GPL-3.0).

Starting...
Loading plugins from /home/cel/.ssb/node_modules
Loading plugin "ssb-notifier"
Log level: notice
Serving at http://localhost:7777
Log history read...
Indexes generated
NotFoundError: Key not found in database
    at /usr/local/src/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:18
    at /usr/local/src/secure-scuttlebutt/node_modules/level-sublevel/nut.js:120:19
patchwork (master)@cel (node system)$
```

**Comment by pfraze** [comment]
Terrible stack trace. I'd guess that's from some code doing this:

```js
db.get(key, function (err, value) {
  if (err) throw err
  ...
})
```

**Comment by pfraze** [comment]
There's a small chance that there's a `.get()` being called without a callback, in which case a notFound would result in an error thrown. https://github.com/ssbc/scuttlebot/pull/338 will identify that, if it's the case.

Small chance, but worth trying.

**Comment by clehner** [comment]
I'm trying out ssbc/scuttlebot#338 now and will report back if anything happens

**Comment by clehner** [comment]
On the async-validation branch I didn't get the error while running patchwork for roughly a day. Then after switching back to the plugins branch I got the error after a few hours.

**Comment by pfraze** [comment]
😑

**Comment by clehner** [comment]
Since I changed ssb-notifier to not modify message objects at all, I haven't seen this error. Could it be that modifying a message was causing its hash to be computed differently somewhere, causing the key to change?

**Comment by clehner** [comment]
Actually I am still getting the NotFoundError. I think I will need to modify the code to fix the stack trace to find out what is going on.

**Comment by clehner** [comment]
I eventually got this to go away in ssb-notifier after making sure that message objects are not modified and that errors are always handled.
