### ISSUE TITLE
Bug in verifyClient for websocket connection

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#364]
> 18:08 < cryptix> hrm.. something is weird.. patchwork now sets $localip like 192.168.x.x as its host for the webinterface at :7777 and not on localhost
18:09 < cryptix> i can do node index.js --host localhost
18:09 < cryptix> but i wonder why it started doing this
18:09 < cryptix> fresh install

The autodetected IP is being used, when it should instead be checking just whether it's a loopback

**Comment by dominictarr** [comment]
is this related? https://github.com/ssbc/secret-stack/pull/6

**Comment by pfraze** [comment]
No but I thought the same thing.

No, @cryptix went onto a network that was using DHCP, so his `host` param was being set to a network address. The `verifyClient` method was using `host` to make sure the client origin was correct, but that's not the right logic.

**Comment by mmckegg** [comment]
Not worth fixing since #423. Closing!
