### ISSUE TITLE
fresh npm install; missing front-end assests

### ISSUE THREAD

**Issue by JLilic** [ssbc/patchwork#369]
Installed from npm and min.main.js and /css/main.css fail to load. OS mac.

**Comment by pfraze** [comment]
did you install -g, or clone and run npm install?

**Comment by wanderer** [comment]
it was with install -g

**Comment by pfraze** [comment]
That's odd! I just gave it a go, and it seemed to work. What npm/node version are you using?

You might try going to the global install path and running `npm run build-release`

**Comment by wanderer** [comment]
it was on a fresh install of v5. No errors on install aftering using `--unsafe-dep` (cholride wouldn't build without it)

**Comment by pfraze** [comment]
unsafe dep? I'm not familiar with that and cant find a doc on it, what's that about?

@wanderer I'm really not sure how this could occur. The built files should be included in the npm deployment.

Did you check the devtools to see that this is the issue? What was the exact problem?

**Comment by wanderer** [comment]
oh mean `--unsafe-perm` and yes devtools just show min.main.js and /css/main.css returning a 404

**Comment by pfraze** [comment]
Hmm. Was the install with sudo? Has the machine had its npm global install dir put in the user's home dir?

**Comment by wanderer** [comment]
yep installed with sudo.

> Has the machine had its npm global install dir put in the user's home dir?

nope.

**Comment by evbogue** [comment]
Because of the issues I've been having with Node v6, I did a few things, such as

`% sudo npm uninstall ssb-patchwork -g`
`% sudo npm install ssb-patchwork -g`

That didn't work. So I pulled the latest version of patchwork down from Github, and now I have the error mentioned above. patchwork works fine with Node 6, but now I'm missing the front-end dependencies.

See screenshot
![2016-04-27-120657_1366x768_scrot](https://cloud.githubusercontent.com/assets/2468866/14859128/c5c619b4-0c70-11e6-8c76-117df344436d.png)

**Comment by pfraze** [comment]
I'm sure you ran `npm install` in the github cloned copy, right? That should have run `prepublish`, which in turn runs `npm run build-release`.

Try running `npm run build-release` manually. I wonder if npm has changed some behaviors.

**Comment by evbogue** [comment]
I ran `npm install` and `npm run build-release` on the github cloned copy. 

Next I typed `npm start` to start patchwork in github cloned copy.

I see the scary C stack trace errors mentioned on Patchwork before it stopped working for me. 

Another error comes up right away when I type `npm start`. It is

```
(node:9463) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

**Comment by evbogue** [comment]
These are the versions I'm using:

I'm running on a Arch Linux 64 bit system.

```
npm info using npm@3.8.6
npm info using node@v6.0.0
```

**Comment by pfraze** [comment]
Hm. I dont know about the node-process bugs, but let's not bog down this thread with some of the node 6 weirdness.

Were you able to see if the assets built?

**Comment by evbogue** [comment]
The only file in the `css` folder is: hint.min.css

**Comment by pfraze** [comment]
Hmm. Well, if you're pulling from github, you're on latest -- which should be a different situation than the issues people are having when installing from npm.

I'll check into that in a few.

**Comment by pfraze** [comment]
@evbogue so you're not totally screwed in the meantime, you did try to run `npm run build-release`, right?

**Comment by evbogue** [comment]
@pfraze Just ran it again, nothing but hint.min.css in the css folder. Is there a manual(er) way I can build the front-end assets? 

No worries if this takes a few days to fix, I'll just be drinking Tecates and chillin at the schoolhouse.

**Comment by pfraze** [comment]
Is there any error? What happens if you run `npm run build-release:css` ?

**Comment by evbogue** [comment]
I checked out master and started the build from scratch. It appeared to work, with only this error which may be unrelated 
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm info ok
```

However, the css folder still has nothing.

Running `npm run build-release:css` doesn't produce more css files.

This is the output from `npm run build-release:css`

```
[ev@arch patchwork]$ npm run build-release:css
(node:1765) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:1765) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:1765) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v6.0.0
(node:1765) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm info lifecycle ssb-patchwork@2.7.0~prebuild-release:css: ssb-patchwork@2.7.0
npm info lifecycle ssb-patchwork@2.7.0~build-release:css: ssb-patchwork@2.7.0

> ssb-patchwork@2.7.0 build-release:css /home/ev/patchwork
> mkdir -p ./ui/css && lessc ./ui/less/main.less --autoprefix ./ui/css/main.css

npm info lifecycle ssb-patchwork@2.7.0~postbuild-release:css: ssb-patchwork@2.7.0
npm info ok
```

**Comment by pfraze** [comment]
Those warnings must be relevant. I cant imagine why else that would be happening

**Comment by pfraze** [comment]
I'll load up node 6 and look into this.

**Comment by pfraze** [comment]
Hey @evbogue, this is still on my radar, Ive just had a heavy week of client work. Sorry for the wait.

**Comment by evbogue** [comment]
This may have been an Arch Linux issue with their `npm` package. I updated npm to a new version today and Patchwork worked again after a global reinstall. With Node 6, of course.

**Comment by kyrias** [comment]
I can confirm that doing a `npm install` in the cloned repo still doesn't build the CSS for me on Arch.  Running `build-release` manually does work though.

**Comment by Kubuxu** [comment]
My versions:
```
 ~/git/dnsrouter   master ?  npm --version                                                  ✘ 
3.8.8
 ~/git/dnsrouter   master ?  node --version
v6.0.0
```
Can someone compare?

**Comment by kyrias** [comment]
```
 λ  npm --version
3.8.8
 λ  node --version
v6.0.0
```

**Comment by pfraze** [comment]
looks like a node 6 thing

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).
