### ISSUE TITLE
HTML5 Notifications

### ISSUE THREAD

**Issue by Kubuxu** [ssbc/patchwork#373]
When getting private message it would be great to receive browser wide HTML5 notification.

**Comment by clehner** [comment]
was implemented in defunct branch #243. other discussion: #114

I think it might be time to integrate [ssb-notifier](https://github.com/clehner/ssb-notifier/tree/pluginify), as long as it works with the electron bundling.

**Comment by Kubuxu** [comment]
It is not asking on FF about notification permission nor sending it.
