### ISSUE TITLE
CSS is not being generated

### ISSUE THREAD

**Issue by Kubuxu** [ssbc/patchwork#379]
The `main.css` file is missing for me. It changed recently.

**Comment by cryptix** [comment]
`$ npm run build:css` should recreate it.

Check the `scripts` section in `package.json` for more helpers.

**Comment by Kubuxu** [comment]
It doesn't work for some reason:
```
 ~/git/patchwork   master  npm run build:css

> ssb-patchwork@2.7.0 build:css /home/kubuxu/git/patchwork
> mkdir -p ./ui/css && lessc ./ui/less/main.less ./ui/css/main.css

 ~/git/patchwork   master  ls ui/css
hint.min.css
```

**Comment by cryptix** [comment]
hmmm... Can you run `lessc ./ui/less/main.less ./ui/css/main.css` on it's own?
Not sure why npm would swallow the error(s)...

**Comment by Kubuxu** [comment]
```
 ~/git/patchwork   master  node_modules/less/bin/lessc ./ui/less/main.less ./ui/css/main.css
 ~/git/patchwork   master  ls ui/css
hint.min.css
```
Can you try cleaning your `node_modules` and running patchwork.

**Comment by pfraze** [comment]
More discussion here: https://github.com/ssbc/patchwork/issues/369

Not sure what's going on.

**Comment by mmckegg** [comment]
Probably okay now? Closing!
