### ISSUE TITLE
Opening a PDF triggers security warning

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#38]
When you open a PDF, it will be saved into a directory, and then you get this message:

`Security Error This page attempted to navigate out of its sandbox through explicit circumvention. Do not trust it!`

**Comment by dominictarr** [comment]
it seems like it tries to open that pdf as a webview, which is probably the problem... it should probably open that in the os's pdf viewer, and/or provide a "save as" option on right click.
