### ISSUE TITLE
procedure for switching from npm installation to dists

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#383]
If I install patchwork from https://github.com/ssbc/dists do I lose my patchwork identity, ssb db, etc?

Or, to ask the same question in a different way, what is the switching procedure?

(I am currently locked out of patchwork because the npm installation is not working for me: https://github.com/ssbc/patchwork/issues/382 )

**Comment by pfraze** [comment]
No it's fine, your data is read from the same `~/.ssb` directory

**Comment by bhaugen** [comment]
Please excuse ignorance.
I did the dist install. Now, how do I run patchwork?
patchwork
patchwork-electron
ssb-patchwork-electron
all command not found

I assume I am missing something that I should have known...

**Comment by pfraze** [comment]
What OS?

**Comment by bhaugen** [comment]
ubuntu 12.04

**Comment by pfraze** [comment]
Ok, I havent done the install in that ecosystem, but it shouldve added an icon to one of your application menus

**Comment by bhaugen** [comment]
Thanks. It did. Should have known. Sorry to bother you about it.

**Comment by pfraze** [comment]
no worries

**Comment by clehner** [comment]
To run from the command line, use `/opt/ssb-patchwork-electron/ssb-patchwork-electron`. The installer should probably put a symlink to this in `/usr/bin/`...
