### ISSUE TITLE
patchwork binds to wrong address, creating CSP issue which prevents use

### ISSUE THREAD

**Issue by Aranjedeath** [ssbc/patchwork#385]
I just got setup with patchwork via `npm install ssb-patchwork -g`, using nvm node.

Installed successfully. 

I run `patchwork` and it binds to my computer's zerotier address. 
I haven't changed any settings, so the web interface is supposed to be available on 127.0.0.1:7777, but it fails to load with a weird stack trace. https://gist.github.com/Aranjedeath/a4ef7a7dd4d2e07f120692f222001399
the error looks like https://mirror.explodie.org/Screenshot_20160520_113716.png

the reason, from browser console:

`Content Security Policy: The page's settings blocked the loading of a resource at ws://127.0.0.1:7777/ ("connect-src http://127.0.0.1:7777 ws://29.202.146.242:7777 wss://29.202.146.242:7777").`

So, it appears hardcoded to bind on 127.0.0.1, but for some reason the ws/wss binding logic is picking my zerotier address to bind. patchwork flatly refuses (as it should) to respond on the zerotier address, preventing whatever it needs to load from websocket, from loading. 

node version 4.4.4 (latest stable)
npm version 2.15.1 (latest for that node)

**Comment by Aranjedeath** [comment]
retested with new node and npm (5.11.1/3.8.6) and no dice.

**Comment by mmckegg** [comment]
This is not a problem in patchbay / patchwork-next. Probably not worth fixing since #423. Closing!
