### ISSUE TITLE
Make dug indicator more explicit

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#386]
[%fuMrQdh8DGzCx4fCQSmbse0I3/WoJDk4MPpqmekk9Bc=.sha256](http://localhost:7777/#/msg/%25fuMrQdh8DGzCx4fCQSmbse0I3%2FWoJDk4MPpqmekk9Bc%3D.sha256)

> It would be nice to have a more explicit indicator that you dug something.

> For example just filling in the "dug icon" with a color would be good. I keep undigging things that I dug because I don't see that I dug them in the first place

**Comment by mmckegg** [comment]
This has been addressed in patchwork-next. Closing!
