### ISSUE TITLE
error loading sodium bindings: Module version mismatch.

### ISSUE THREAD

**Issue by magician11** [ssbc/patchwork#390]
Hi guys,

I'm trying to get [electron](https://github.com/ssbc/patchwork-electron) running.

When I use node v4.4.5 I get

> Error: Module version mismatch. Expected 47, got 46.

Using node v6.2.2 I get

> Error: Module version mismatch. Expected 47, got 48.

**Comment by clehner** [comment]
Have you tried node v5?

**Comment by magician11** [comment]
Yes... that's the obvious choice come to think of it.

v5.11.1 worked. Thanks.
