### ISSUE TITLE
Link How to setup a pub does't work

### ISSUE THREAD

**Issue by davidhq** [ssbc/patchwork#395]
Here:

https://github.com/ssbc/patchwork/blob/master/docs/help-faq.md

it points to

https://github.com/ssbc/patchwork/blob/master/docs/scuttlebot/howto-setup-a-pub.html

which doesn't exist: 

![image 2016-07-05 at 4 19 44 am](https://cloud.githubusercontent.com/assets/3899/16572342/e2f613e0-4267-11e6-8b8f-61aa179967f5.png)

**Comment by clehner** [comment]
Thanks for pointing this out. The doc was moved to https://ssbc.github.io/docs/scuttlebot/howto-setup-a-pub.html (https://github.com/ssbc/docs/blob/master/scuttlebot/howto-setup-a-pub.md)
