### ISSUE TITLE
h.theos.kyriasis.com showed up as a potential wifi contact

### ISSUE THREAD

**Issue by tiagocpontesp** [ssbc/patchwork#398]
and I'm home alone... I THINK.
2.9.2

**Comment by dominictarr** [comment]
that should have been fixed by https://github.com/ssbc/patchwork/pull/392

**Comment by tiagocpontesp** [comment]
Happening every time here on /#/contacts.

**Comment by clehner** [comment]
i see it too. I guess #392 didn't work

**Comment by clehner** [comment]
Actually #392 fixed it for the sync page - this is for the Contacts page. I'll make another fix
