### ISSUE TITLE
pubs can appear twice in network view

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#4]
![2015-08-07-190247_1366x768_scrot](https://cloud.githubusercontent.com/assets/259374/9141162/01f8616c-3d37-11e5-874d-9458b09a872c.png)

this is not right. if you query the gossip.peers api you get this:

``` json
[
  {
    "port": 8008,
    "key": "@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519",
    "host": "localhost",
    "announcers": [
      "@BIbVppzlrNiRJogxDYz3glUS7G4s4D4NiXiPEAEzxdE=.ed25519"
    ],
    "time": {
      "connect": 0,
      "attempt": 1438966681043
    },
    "connected": true
  },
  {
    "host": "176.58.117.63",
    "port": 8008,
    "key": "@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519",
    "announcers": [
      "@BIbVppzlrNiRJogxDYz3glUS7G4s4D4NiXiPEAEzxdE=.ed25519"
    ],
    "time": {
      "connect": 1438966696787,
      "attempt": 1438966696603
    },
    "connected": true,
    "id": "@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519",
    "failure": 0
  }
]
```

seems like duplicated functionality and it should just consult the peers api.

**Comment by mmckegg** [comment]
This still seems to be the case.

**Comment by dominictarr** [comment]
currently we take pub addresses announced by anyone, which means you have to connect to all of them to see which one is real, and you get multilpes if a pub changes ip, but keep it's key.

if this was changed, so that pubs announced themselves, then you could just take the latest announcement per pub, which would be cleaner, and closer to the gossip refactor %vB5bEoo/Sg8e1OVCX0A1iQjoQE4uhteRAhz/oCBUzNg=.sha256

**Comment by ahdinosaur** [comment]
assuming stale. if not, re-open!
