### ISSUE TITLE
channel creation is not obvious.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#402]
I've had several people ask to create a channel, or assume that you need a pub to create a new channel.

in the channel field it says "set the topic here (optional)" maybe that should say something like "select or enter new channel name"?

**Comment by mmckegg** [comment]
Not worth fixing in this iteration, but probably worth looking at channels in general in bay/next.

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!

**Comment by mmckegg** [comment]
@ahdinosaur

Ironically enough, channel creation is even harder in patchwork-next. But at least it does tell you how  to in another channel. 

I kind of don't really want to fix this though. Would prefer splitting channels into two seperate things: groups and tags.
