### ISSUE TITLE
packet-stream naming conflict

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork#413]
noticed this in the logs:

```
packet-stream asked to read after closed { value: { substack: { type: 'name-conflict', name: 'substack', ids: [Object] } },
  end: false,
  req: -5 }
```

**Comment by cryptix** [comment]
hum - sounds like a high level problem not bubbling up correctly?
I guess this case started when substack lost his key recently?

**Comment by dominictarr** [comment]
hmm, yeah, patchwork doesn't like it when you follow two keys with the same name.
(patchbay doesn't care though)
if are meant to rename one of them. Is patchwork still functioning without complaining?
I'd recommend renaming the old substack to lost_substack

**Comment by mmckegg** [comment]
Don't think this stops patchwork from functioning, but I do recall it may cause @ mentions to work a bit unpredictably. Closing as bay/next doesn't have this problem.
