### ISSUE TITLE
install process hang

### ISSUE THREAD

**Issue by myf** [ssbc/patchwork#414]
the install process hangs with the following displayed on screen while doing `npm install`

> [             .....] - extract:watchify: sill doParallel extract 1007

npm version `3.10.6`
node version `v6.5.0`

**Comment by gardner** [comment]
Some times npm will fail for reasons like network connectivity or their servers being overloaded. Are you still able to reproduce this?

**Comment by ahdinosaur** [comment]
hey. i'm closing this since stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
