### ISSUE TITLE
OSX: closing window quits instead of hides

### ISSUE THREAD

**Issue by davidguttman** [ssbc/patchwork#42]
Customary OSX app behavior is to stay running even when all windows are closed.

**Comment by pfraze** [comment]
That's true. Will fix.

**Comment by davidguttman** [comment]
Here's my fix for reference: https://github.com/ssbc/patchwork/pull/43

**Comment by pfraze** [comment]
Thanks!

**Comment by pfraze** [comment]
Fixed
