### ISSUE TITLE
Log level notices ?

### ISSUE THREAD

**Issue by fredhampton** [ssbc/patchwork#422]
When I ' sbot sever' I receive a message that says 'log level notice'
When we send messages they are very slow to be received. Is there a way to see what the notices are ? Are the notices slowing the messages down ?

**Comment by dominictarr** [comment]
the notice is just a log message, that won't be effecting anything - you are running a seprate network to the main patchwork network, right?

how long does it seem to take? we might need to add some sort of logging to see why it is taking long

**Comment by fredhampton** [comment]
This is the log level notice 

Log level: notice
server error Error: wrong number
    at abort (/root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/handshake.js:86:20)
    at drain (/root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
    at more (/root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:51:13)
    at /root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:62:9
    at /root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/root/.nvm/versions/node/v5.3.0/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)



On October 24, 2016 at 6:13:38 AM, Dominic Tarr (notifications@github.com) wrote:

the notice is just a log message, that won't be effecting anything - you are running a seprate network to the main patchwork network, right?

how long does it seem to take? we might need to add some sort of logging to see why it is taking long

**Comment by dominictarr** [comment]
that error means that it tried to connect to a pub server, but it had used the wrong key.
I.e. telephone analogy, you called the wrong person.
That will happen if you regenerate you pub key, or copy it to another server.

That on it's own shouldn't be making it slow... how many pubs are you connecting too? do you see pub messages? and check the network sync view. does it show you are connected to pubs?

**Comment by fredhampton** [comment]
We are only receive messages of we run receiving message if we run ‘ gossip.reconnect’
If we don’t not do run this most of the messages are not sent out

There are 2 users connected to 1 pub 
We only see messages and pub messages if we run ‘ gossip.reconnect’


Thanks for all of your help


On October 25, 2016 at 1:36:23 PM, Dominic Tarr (notifications@github.com) wrote:

that error means that it tried to connect to a pub server, but it had used the wrong key.
I.e. telephone analogy, you called the wrong person.
That will happen if you regenerate you pub key, or copy it to another server.

That on it's own shouldn't be making it slow... how many pubs are you connecting too? do you see pub messages? and check the network sync view. does it show you are connected to pubs?

**Comment by dominictarr** [comment]
Okay, that is really interesting. It sounds like somehow it's loosing the connection, but without realizing.
That is probably I can reproduce. We can also make a quick fix to just reconnect periodically, and at least that will make it work.

**Comment by fredhampton** [comment]
How can we make a quick fix to reconnect periodically ?


Thanks !!!!


On October 27, 2016 at 8:52:44 AM, Dominic Tarr (notifications@github.com) wrote:

Okay, that is really interesting. It sounds like somehow it's loosing the connection, but without realizing.
That is probably I can reproduce. We can also make a quick fix to just reconnect periodically, and at least that will make it work.

**Comment by fredhampton** [comment]
We are trying to find a way to have reconnects periodically 
Can you point us in the right direction ?


Thanks !!!


On October 27, 2016 at 12:16:22 PM, William Dyson (william@ida.coop) wrote:

How can we make a quick fix to reconnect periodically ?


Thanks !!!!


On October 27, 2016 at 8:52:44 AM, Dominic Tarr (notifications@github.com) wrote:

Okay, that is really interesting. It sounds like somehow it's loosing the connection, but without realizing.
That is probably I can reproduce. We can also make a quick fix to just reconnect periodically, and at least that will make it work.

**Comment by fredhampton** [comment]
We are trying to find a way to have reconnects periodically 
Can you point us in the right direction ?
Also is there a way to see when reconnects are taking place 


Thanks !!!

**Comment by dominictarr** [comment]
add this code
``` js
setInterval(function () {
  console.log('reconnect')
  sbot.reconnect()
}, 60e3*10) //ten minutes
```
here
https://github.com/ssbc/patchwork/blob/master/server-process.js#L42

and it will reconnect every 10 minutes.
This will work, but I think it will use more data than I'd like.
I do have improving the gossip stuff in the pipeline... so I'll be looking into this...

**Comment by fredhampton** [comment]
Thanks !!!


On October 29, 2016 at 1:05:04 PM, Dominic Tarr (notifications@github.com) wrote:

add this code

setInterval(function () {
  console.log('reconnect')
  sbot.reconnect()
}, 60e3*10) //ten minutes
here
https://github.com/ssbc/patchwork/blob/master/server-process.js#L42

and it will reconnect every 10 minutes.
This will work, but I think it will use more data than I'd like.
I do have improving the gossip stuff in the pipeline... so I'll be looking into this...

**Comment by fredhampton** [comment]
I have added the code
Is there a way for me to see of the reconnect is happening ?


Thanks !!!


On October 29, 2016 at 5:53:31 PM, William Dyson (william@ida.coop) wrote:

Thanks !!!


On October 29, 2016 at 1:05:04 PM, Dominic Tarr (notifications@github.com) wrote:

add this code

setInterval(function () {
  console.log('reconnect')
  sbot.reconnect()
}, 60e3*10) //ten minutes
here
https://github.com/ssbc/patchwork/blob/master/server-process.js#L42

and it will reconnect every 10 minutes.
This will work, but I think it will use more data than I'd like.
I do have improving the gossip stuff in the pipeline... so I'll be looking into this...

**Comment by fredhampton** [comment]
The reconnect is working but it is shutting down patchwork each time there is a reconnect 


Thanks !!!!


On November 1, 2016 at 2:10:52 PM, William Dyson (william@ida.coop) wrote:

I have added the code
Is there a way for me to see of the reconnect is happening ?


Thanks !!!


On October 29, 2016 at 5:53:31 PM, William Dyson (william@ida.coop) wrote:

Thanks !!!


On October 29, 2016 at 1:05:04 PM, Dominic Tarr (notifications@github.com) wrote:

add this code

setInterval(function () {
  console.log('reconnect')
  sbot.reconnect()
}, 60e3*10) //ten minutes
here
https://github.com/ssbc/patchwork/blob/master/server-process.js#L42

and it will reconnect every 10 minutes.
This will work, but I think it will use more data than I'd like.
I do have improving the gossip stuff in the pipeline... so I'll be looking into this...

**Comment by fredhampton** [comment]
I see the below settings in sbot.js …..could this be a place to also change reconnect ?


 },
    gossip: {
      connections: 3
    },
    path: path.join(HOME, '.' + name),
    timers: {
      connection: 0,
      reconnect: 5*SEC,
      ping: 5*MIN,
      handshake: 5*SEC
    },



On November 1, 2016 at 2:54:57 PM, William Dyson (william@ida.coop) wrote:

The reconnect is working but it is shutting down patchwork each time there is a reconnect 


Thanks !!!!


On November 1, 2016 at 2:10:52 PM, William Dyson (william@ida.coop) wrote:

I have added the code
Is there a way for me to see of the reconnect is happening ?


Thanks !!!


On October 29, 2016 at 5:53:31 PM, William Dyson (william@ida.coop) wrote:

Thanks !!!


On October 29, 2016 at 1:05:04 PM, Dominic Tarr (notifications@github.com) wrote:

add this code

setInterval(function () {
  console.log('reconnect')
  sbot.reconnect()
}, 60e3*10) //ten minutes
here
https://github.com/ssbc/patchwork/blob/master/server-process.js#L42

and it will reconnect every 10 minutes.
This will work, but I think it will use more data than I'd like.
I do have improving the gossip stuff in the pipeline... so I'll be looking into this...

**Comment by dominictarr** [comment]
hmm, i think that is a different type of reconnecting...

**Comment by fredhampton** [comment]
Is there a place in the code where sbots default connection settings live ?


On November 3, 2016 at 6:05:29 AM, Dominic Tarr (notifications@github.com) wrote:

hmm, i think that is a different type of reconnecting...

**Comment by ahdinosaur** [comment]
hey. i'm closing this as stale due to [`v3` release](https://github.com/ssbc/patchwork/releases).

if it's still a problem, open again!
