### ISSUE TITLE
patchwork breaks in rare case where desktop actually has a static ip address

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#427]
@evok3d was trying to get patchwork running on his computer and ran into a problem that patchwork was refusing to expose the client to remote computers, but it was doing so because it was detecting it was running on a static, public ip address!

Which is great, because it means he can actually run a pub server on his local computer, but it's bad because it's not working. but anyway, lets fix it properly, and we can use this issue for any more issues we have with it.

**Comment by dominictarr** [comment]
```
dominictarr
1:55 PM okay, try if this works: `ssb_host=localhost npm start`
1:56 then open localhost:7777
evok3d
1:59 PM nice!
1:59 it worked
```

**Comment by ahdinosaur** [comment]
with the [`v3` release](https://github.com/ssbc/patchwork/releases), is this still an issue?
