### ISSUE TITLE
Error running patchwork

### ISSUE THREAD

**Issue by oren** [ssbc/patchwork#432]
I install patchwork from npm and see the following error in the browser:
```
We're sorry! Patchwork experienced an error while loading.
Uncaught undefined
```

in the terminal i see:
```
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Patchwork - Copyright (C) 2015-2016 Secure Scuttlebutt Consortium
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions (GPL-3.0).

Starting...
Log level: notice
Serving at http://104.156.102.204:7777
Log history read...
Indexes generated
```

in the chrome's console I see:
```
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:7777/css/hint.min.css".
localhost/:9 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:7777/css/main.css".

main.build.js:62021 Refused to connect to 'https://example.com/' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:7777 wss://localhost:7777".
main.build.js:35961 WebSocket connection to 'ws://localhost:7777/' failed: HTTP Authentication failed; no valid credentials available
loading.js:42 
ErrorEvent {isTrusted: true, message: "Uncaught undefined", filename: "http://localhost:7777/main.build.js", lineno: 69302, colno: 14…}
main.build.js:69196 Unexpected Error 
ErrorEvent {isTrusted: true, message: "Uncaught undefined", filename: "http://localhost:7777/main.build.js", lineno: 69302, colno: 14…}
 This was an unhandled exception.
```

Here is my environment:
ubuntu 16.04, Node v6.9.1, npm 3.10.8

Thanks!

**Comment by ahdinosaur** [comment]
hey @oren, thanks for the detailed bug report. :watermelon: 

i wonder if this is related to https://github.com/ssbc/patchwork/issues/431, /cc @mmckegg.

in the meantime, if you're okay with Electron, you can also try:

- [`patchwork-electron`](https://github.com/ssbc/patchwork-electron/releases/tag/v2.12.3) (this repository built into a standalone electron release), 
- :star2: [`patchwork-next`](https://github.com/mmckegg/patchwork-next) (a work-in-progress successor to Patchwork classic built using Patchbay),
- or [`patchbay`](https://github.com/dominictarr/patchbay) (an unopinionated and pluggable interface).

sorry about this, keen to help you connect to the network one way or another. :cat:

**Comment by dominictarr** [comment]
this looks like a duplicate of https://github.com/ssbc/patchwork/issues/433

I see you have a public ip address. you are running this on your local machine?
try starting with `patchwork --host localhost`

**Comment by oren** [comment]
works now. i believe it crashed when i was trying to upload an image but i restarted it and i can see my inbox now. Thanks!

I guess my next step is join the IRC and get an invite code at #scuttlebutt

**Comment by oren** [comment]
btw, here is the error i see in the console. I am not sure if I should care about it:
```
Refused to connect to 'https://example.com/' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:7777 wss://localhost:7777".
```

**Comment by evbogue** [comment]
@oren email me if no one gets back to you with a pub invite in IRC: ev@evbogue.com

I second @ahdinosaur's encouragement to try one of the newer clients. I use https://github.com/ssbc/patchbay

**Comment by oren** [comment]
awesome. I didn't realize these are newer! if that's the case i'll
definitely try them.

**Comment by oren** [comment]
Also, is there a web client that can run on a mobile browser?

**Comment by evbogue** [comment]
@oren Mobile client: yes! Bay can be used on mobile if you compile the 'lite client' and use a remote pub.

**Comment by oren** [comment]
nice. thank you.
