### ISSUE TITLE
error with latest electron build

### ISSUE THREAD

**Issue by mafintosh** [ssbc/patchwork#433]
Currently just getting this error when running patchwork

![screen shot 2016-12-28 at 13 27 56](https://cloud.githubusercontent.com/assets/376661/21521946/99b99268-cd01-11e6-980b-f983ecd343b9.png)

I installed it a few weeks ago using the mac build. Everything has been working fine until now.

**Comment by dominictarr** [comment]
I saw this before one time, what is happening is your computer has been given a non-private address (`154.217.246.64`) and patchwork thinks it's being accessed remotely - the solution is to start patchwork with `--host localhost` option.

**Comment by mafintosh** [comment]
Okay cool. Can I do that from inside the app somehow? (or inside the web console). I'm using the packaged app.

**Comment by dominictarr** [comment]
you can create an ~.ssb/config file with `{"host": "localhost"}` also, I think you can still run the packaged app from the command line.

**Comment by ahdinosaur** [comment]
hey @mafintosh, we just released a new major version: [`v3`](https://github.com/ssbc/patchwork/releases). :sparkles: 

closing this for now, hope you join us again. :smiley_cat:
