### ISSUE TITLE
Proposal: Pubs could become "connect me to x" services

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#440]
I would like to go to `pub.coolserver.com` and say: 

> I `matt/@FbGoHeEce...` would like to connect to a person called "Mikey". 

It would give me a special link for me to open with my patchwork and another one to send (however I want) to Mikey. 

If Mikey doesn't have patchwork already, this will let him download it and will automatically set his name to whatever the invite said.

When `mikey` uses the code, he automatically follows me and my client also follows him back (ensuring that this is actually the `mikey` I invited). I get a notification that `mikey` has accepted my invitation!

The pub follows both of us, but we don't follow the pub (we do however broadcast the pubs existence). 

This means we won't be replicating all of the random strangers that also use that pub. Pubs become less visible than they are right now, and mostly just keep things ticking along without being visible in the graph.

---

[port-hole into cross-posted thread on ssb](http://viewer.scuttlebot.io/%257%2FWkKvxMU%2BBd%2BUy8LUGrGKxZWn8EQD%2FxvfJLt6aJQM8%3D.sha256)

**Comment by staltz** [comment]
Just to clarify, is this something only with Patchwork and pubs, or does it require changes in Scuttlebutt/bot too?

**Comment by mmckegg** [comment]
Hmmm, the only thing that could be difficult to do without changing scuttlebot would be the additional meta data (who issued the invite, who to follow, invitee name). And it would probably make sense to store that info on the pub itself to avoid making the invite codes any longer than they already are.

@dominictarr what do you think?

**Comment by dominictarr** [comment]
Yes this would require changes in sbot. I've wanted to do something like this for a while. have a search for discussions about "user invites". @mmckegg I like the idea of having the people follow each other but not the pub.

**Comment by christianbundy** [comment]
I think the latest info on this is [`%LMYARKcJ5/HVrkfyGo0oSV4j/whFmpeiJlQnvPw53PE=.sha256`](http://viewer.scuttlebot.io/%25LMYARKcJ5%2FHVrkfyGo0oSV4j%2FwhFmpeiJlQnvPw53PE%3D.sha256).
