### ISSUE TITLE
feature request: a page to see all messages

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#444]
sometimes i want to see all messages that i'm replicating (followers of followers), rather than just messages i'm following. this is especially useful when discovering new users.

**Comment by mmckegg** [comment]
"Discovery" mode.

**Comment by ahdinosaur** [comment]
solved with https://github.com/ssbc/patchwork/commit/ead5d15c75ce6e84eb01e6e0f16ba10e3552d905
