### ISSUE TITLE
remove customized scuttlebot

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#447]
This is a pull request request. @mmckegg can you make a PR that adds what you need to do the progress bar into the standard scuttlebot? I had some progress stuff in there already but don't really mind either way, just that it's better to have one version at this point.

This issues came out of https://github.com/ssbc/scuttlebot/pull/379

**Comment by mmckegg** [comment]
Yes! Keen to do this.

Now that ssbc/scuttlebot#379 has been merged, I think "progress" is the only reason it is still running a fork. 

I have an idea how to make the progress stuff much simpler than what I've got right now. Will implement that and send a pull request.
