### ISSUE TITLE
Quitting patchwork does not free port 8008

### ISSUE THREAD

**Issue by lachenmayer** [ssbc/patchwork#454]
I just did the `patchwork-next` -> `patchwork` reshuffle :) I still have a couple of issues with the Electron-based patchwork unfortunately... I'm going to open a couple of issues, if that's ok.

To reproduce:

1. start patchwork
2. quit patchwork via Cmd+Q
3. start patchwork again

I get the following error message:

```
Error: bind EADDRINUSE 0.0.0.0:8008
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Patchwork actually handles this & seems to just work, but I can't use eg. `sbot server`, or anything that spawns its own sbot process (eg `patchwork-vintage` ehhh `classic`).

The weird thing is that I can't find anything to do with port 8008 in `lsof`, `netstat` & friends, and I can't find any process belonging to patchwork still running after I quit.

Logging out / rebooting fixes it (once), so it shouldn't be due to some other process taking up port 8008.

Versions:
**OS**: macOS 10.11.6
**patchwork**: 42cae2a
**Electron**: 1.4.15
**Node**: 7.7.1

**Comment by lachenmayer** [comment]
The same issue has also been reported here: http://stackoverflow.com/questions/40512274/release-udp-port-used-by-dead-process-on-os-x
(cc @ktorn)

Can anyone on macOS 10.12 confirm that this doesn't happen?

**Comment by lachenmayer** [comment]
Same issue: https://github.com/ssbc/patchwork-classic-electron/issues/13

**Comment by lachenmayer** [comment]
As mentioned by @mmckegg in https://github.com/ssbc/patchwork-classic-electron/issues/13#issuecomment-259418387
commenting out the local plugin is a workaround:

```diff
var createSbot = require('scuttlebot')
   .use(require('ssb-blobs'))
   .use(require('scuttlebot/plugins/invite'))
   .use(require('scuttlebot/plugins/block'))
-  .use(require('scuttlebot/plugins/local'))
+  // .use(require('scuttlebot/plugins/local'))
   .use(require('scuttlebot/plugins/logging'))
   .use(require('./lib/private-with-index'))
   .use(require('./lib/query-with-progress'))
```

@mmckegg, are you on macOS 10.12 by any chance?

**Comment by dominictarr** [comment]
weird! @lachenmayer try updating broadcast-stream to 0.1.2, let us know if it works

**Comment by dominictarr** [comment]
(didn't mean to close, but posted a comment about closing with a ref to this issue)

**Comment by lachenmayer** [comment]
This doesn't work unfortunately :(
I updated broadcast-stream to 0.1.2 in my local scuttlebot repo and pointed patchwork at it - (weirdly the whole scuttlebot test suite runs on `npm install`?)
I added some logging to the `exit` callback that you added and it never gets executed.

**Comment by mmckegg** [comment]
@lachenmayer I see from this issue that you _are_ using the quit command to exit. Interesting. Have you tried this with the standalone version from https://github.com/ssbc/patchwork/releases?

This is such a strange bug. Really weird how only a few systems seem to be affected. So far it only seems to be macOS.

**Comment by mmckegg** [comment]
Oh and @lachenmayer, I'm still on `v10.11.6`, and no sign of this bug!

**Comment by mmckegg** [comment]
People who experience this bug: **is it only when quitting patchwork?** (as opposed to quitting sbot?)

I suspect it might be to do with how electron handles terminating processes. Maybe it's killing the internal sbot process before it finishes cleaning up.

---

Also being discussed on SSB: %I07DZ/OxettsynxfDcz+/UNZREfaAXNtUYGBcZPV9LI=.sha256

**Comment by yangwao** [comment]
Looks like it happens also when I run sbot and killing it with ctrl-C I can't run it again.

**Comment by christianbundy** [comment]
@yangwao Does this happen each time that you run Patchwork (or Scuttlebot)? I'd be curious if you're still having the same problems with the latest versions. Please let me know if you have any way I can help test this and/or reproduce the issue!
