### ISSUE TITLE
Clicking on a channel in the sidebar throws 'could not find matching timestamp' error.

### ISSUE THREAD

**Issue by lachenmayer** [ssbc/patchwork#455]
To reproduce:

1. Start patchwork
2. Click on '#patchwork' in the "Active Channels" column in the sidebar.

Expected:

Messages from channel load

Actual:

Loading spinner displays indefinitely, log shows the following:

```
Error: could not find matching timestamp for index:{"value":{"content":{"channel":"patchwork"}},"timestamp":1475714534560.012}
    at /Users/harry/Documents/Code/patchwork/node_modules/streamview-links/index.js:164:31
    at /Users/harry/Documents/Code/patchwork/lib/query-with-progress.js:83:26
  Error: missing timestamp:1475714534560.012
    at /Users/harry/Documents/Code/patchwork/lib/query-with-progress.js:83:29
    at /Users/harry/Documents/Code/patchwork/node_modules/level-sublevel/shell.js:101:15
  NotFoundError: Key not found in database
    at /Users/harry/Documents/Code/patchwork/node_modules/level-sublevel/shell.js:101:18
    at /Users/harry/Documents/Code/patchwork/node_modules/level-sublevel/nut.js:121:19
```

My `.ssb` directory has gone through lots of patchwork iterations & manual messing around with `sbot` etc. I once tried to "start fresh" by clearing my `.ssb/db` folder, but that ended in disaster - is there a "safe" way to do something like that?

Versions:
**OS**: macOS 10.11.6
**patchwork**: 42cae2a
**Electron**: 1.4.15
**Node**: 7.7.1

**Comment by cryptix** [comment]
I've also got this in patchbay and patchfoo. I fear it's a problem with scuttlebot? 

Very wild unverified guess: could it be that the subscribe-posts taint the channels?
