### ISSUE TITLE
How do we handle oversized messages?

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#456]
**Problem**: there is a limit on msgs total size of 8KB (this includes all headers / envelop).
When a user tries to publish a large message (like a blogpost), the interface does nothing ... Right now it sounds like these are silently failing (publish never completes, as [mentioned](http://viewer.scuttlebot.io/%256674ZhT7dif%2BBoC%2BIq2xq8K6yYQ4yAuGuJ3b5erVf%2Bg%3D.sha256) by @staltz). 

Really there should be some kind of user notification of why the message cannot publish.

**Comment by staltz** [comment]
Newbie question: are large messages text content in the log or blobs?

**Comment by ahdinosaur** [comment]
@staltz at the moment, all message content is stored in the log, large or small, up to 8kb per message.

so, for example, a [post message](http://scuttlebot.io/docs/message-types/post.html) looks like:

```json
{
  "type": "post",
  "root": "%xIusAdfLgQ/M1fmInPpcvSscSTHFrtgIWlsPex/mfSw=.sha256",
  "branch": "%xIusAdfLgQ/M1fmInPpcvSscSTHFrtgIWlsPex/mfSw=.sha256",
  "channel": "faq",
  "recps": null,
  "text": "hey [@Lu](@1sFsZz+3IBM4QEr2LG9nQp/2NX1GbiAVJ5wYKgNSBcg=.ed25519), yes that is correct. we're also not very satisfied with how channels are at the moment.
\n\nfor a proposal by [@matt](@FbGoHeEcePDG3Evemrc+hm+S77cXKf8BRQgkYinJggg=.ed25519) on an alternative approach for Patchwork: %gTHLf3Rlc48RSjwATVDJZpe9VlWGfxMmio1+o3KX
vjA=.sha256.",
  "mentions": [
    {
      "link": "@1sFsZz+3IBM4QEr2LG9nQp/2NX1GbiAVJ5wYKgNSBcg=.ed25519",
      "name": "Lu"
    },
    {
      "link": "@FbGoHeEcePDG3Evemrc+hm+S77cXKf8BRQgkYinJggg=.ed25519",
      "name": "matt"
    },
    {
      "link": "%gTHLf3Rlc48RSjwATVDJZpe9VlWGfxMmio1+o3KXvjA=.sha256"
    }
  ]
}
```

of course all wrapped up in:

```json
{
  "previous": "%Ad1BpyPh8B3c/eLXpTwngZ3wlQmkjqwA1bSMMEXg1jw=.sha256",
  "author": "@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519",
  "sequence": 2625,
  "timestamp": 1491551529543,
  "hash": "sha256",
  "content": ${content},
  "signature": "u5jvQsCfYRrf3JSV9Z85E9JogCBAyKlqZBz0WxMabci4yzQZJ4CzgLuCHpMoFOaJozJhQJRqVH2q8ZVOU31nCA==.sig.ed25519"
}
```

[some time ago](http://viewer.scuttlebot.io/%25fqQvn2qHoj3LNkStpjmDG71IlP2UBeE1kZ2aJ5tI0yc%3D.sha256#%25Bsoq076eGE0g7YyWz2Wzh8TqM1SS6L0gg8nAwBV%2Fwuo%3D.sha256), i had an idea: what if content was always a blob id? or for a less radical idea (which i _think_ could keep the indexing all the same?), what if a post "text" field could reference a blob containing markdown?

**Comment by staltz** [comment]
would text content as blob be a problem for tamper protection? I guess not, right? Your markdown idea makes sense to me

**Comment by ahdinosaur** [comment]
blobs are immutable since they are content-addressable (the id of a blob is the hash of it's contents), so if the content changes then it no longer matches the same address as referenced by the log message.

**Comment by mmckegg** [comment]
Patchwork now displays an error dialog when your message is too long. But there must be a better way!
