### ISSUE TITLE
Lots of usernames do not show up

### ISSUE THREAD

**Issue by lachenmayer** [ssbc/patchwork#457]
Lots of usernames show up as truncated keys, rather than their human-readable names. I guess this is to be expected when I don't follow users, but even when I specifically follow someone, their name doesn't show up.

I just switched back to patchwork-classic to verify that names there do show up.

Not sure what other diagnostic info I can give - let me know if there's anything I should try out.

Versions:
Patchwork: 42cae2a
macOS: 10.11.6
Node: 7.7.1

**Comment by dominictarr** [comment]
that is what happens while the names are loading. are you seeing no names at all?
are you running patchwork@3 with a separate sbot? I think you need to have ssb-query also installed if you do it that way.

**Comment by lachenmayer** [comment]
Yep, this happens even when I leave patchwork open for a long time.
Names are loaded instantly on patchwork-classic.
And I do have ssb-query installed on my global `sbot`.

I'm sticking with patchwork-classic for now, as I've still not found a way of closing my mystery ports (#454). Will update if I find out anything further.

**Comment by mmckegg** [comment]
@lachenmayer Patchwork doesn't play very nicely with global sbot right now (i'm using a few custom indexes). Is this how you are using it? If so can you try running it standalone?

AFAIK the mystery ports are also a problem with patchwork classic too. It seems odd that you are not experiencing them here. From memory, I seem to recall that it all depended on how you terminated the app. If you did a `Ctrl+C` style term, the ports got stuck. But if you closed the app by closing the window or `quit` command, it was fine. It also only affected a few systems. I have never personally experienced this on any operating system.

Also how are you running patchwork-classic, is it in the command line, or standalone app?
