### ISSUE TITLE
finding pubkey in UI usability

### ISSUE THREAD

**Issue by joeyh** [ssbc/patchwork#461]
As a new patchwork user, I was stumped by how to find my pubkey in its UI. I expected to see it on the profile page, or for there to be some UI element that allowed me to see it. Perhaps with some guidance about what the consequences of sharing the key with other would be.

It took a hint on IRC for me to notice that I could right-click on Profile and that the "link ref" was a public key.

**Comment by mmckegg** [comment]
Good point. This should be addressed!

**Comment by Aranad** [comment]
yeah this is a major problem, I've spent two hours trying to figure out how to connect with a friend after we both installed it!

**Comment by mmckegg** [comment]
Added the public key to the profile page. Now appears clearly under the person's name and can be copy-pasted!
