### ISSUE TITLE
Other users' channel subscriptions seem to trigger the "Show X updates" bar, but the subscription action doesn't show up in the timeline

### ISSUE THREAD

**Issue by neutralinsomniac** [ssbc/patchwork#463]
So this leads to you getting an update notification where nothing seems to occur when you click it. You can see the subscription event if you just so happen to navigate to the relevant channel.

**Comment by mmckegg** [comment]
Thanks for pointing this out. 3d32dd2cc4892720337acdff65bf871556608561 makes this a bit better by making it so patchwork only notifies for posts (rather than other kinds of events).

Mentions will still notify for follows though.
