### ISSUE TITLE
memory use

### ISSUE THREAD

**Issue by joeyh** [ssbc/patchwork#465]
ssb-patchwork process grew to 50% of memory use in top, on my 4 gb ram laptop. Luckily, restarting it dropped memory to 2%.

That process started life with a mostly empty ~/.ssb and downloaded all the backlog. Then I went offline for several hours and browsed pretty extensively through old posts, including scrolling many months back. So the memory use was probably caused by one of those things.

**Comment by joeyh** [comment]
(Using patchwork-3.2.2-linux-x86_64.AppImage)

**Comment by christianbundy** [comment]
Hey, thanks for opening this issue. Are you still having this issue on the latest Patchwork? I think #858 may be relevant as well.

**Comment by joeyh** [comment]
I have not noticed patchwork eating quite that much memory lately.

-- 
see shy jo

**Comment by Serkan-devel** [comment]
Isn't that the habint of electron applications in general?

**Comment by ahdinosaur** [comment]
@Serkan-devel it's the habit of web applications in general, as most web developers don't think to care about memory performance, electron is just an easy way to make a web application into a desktop application. fortunately Matt (who i consider _the_ expert in JavaScript memory performance from his work on [Loop Drop](http://loopjs.com)) has invested a heap of time and energy into reducing bloat: https://github.com/mmckegg/patchtron, https://github.com/ssbc/patchwork/issues/858.

**Comment by Serkan-devel** [comment]
Or could one just rewrite patchwork/ssb into something that isn't javascript?
It might reduce memory usage even further when it's written in something like Crystal

**Comment by ahdinosaur** [comment]
@Serkan-devel: i agree with what you're saying (see [the Sunrise Choir](http://sunrisechoir.com/) for a complete re-write in Rust), but i don't appreciate how you're saying this ("one could just..." :confused: ) . if you want to reduce memory usage in Scuttlebutt, please help us by contributing!

to paraphrase [`%4JT/+ITi0ecWU8n1/DWqt3+SNxagF76b33MyJ/CAdTU=.sha256`](https://viewer.scuttlebot.io/%254JT%2F%2BITi0ecWU8n1%2FDWqt3%2BSNxagF76b33MyJ%2FCAdTU%3D.sha256):

> I mean I believe [we need] people working on hard problems… more than [we need] people confirming that [hard problems exist]

**Comment by Powersource** [comment]
> I have not noticed patchwork eating quite that much memory lately.

Closing (not that performance is ever a solved problem).
