### ISSUE TITLE
.ssb/secret created with insecure permissions

### ISSUE THREAD

**Issue by joeyh** [ssbc/patchwork#474]
The .ssb/secret created by patchwork was mode 644 so other users could read it. Please make sure to create the file with secure permissions eg 600. 

Some users lock down their home directories such that no files in them can be read by other users, but it's still common to have the home directory world-readable and prevent read to specific files that are known to be private such as encryption keys.

In case it's relevant, I ran patchwork using the appimage.

I wonder if all of ~/.ssh should not default to 700 too.

**Comment by ahdinosaur** [comment]
yep, makes sense!

the relevant code for this is `create` and `createSync` in [`ssb-keys/storage`](https://github.com/ssbc/ssb-keys/blob/master/storage.js#L92-L117).

**Comment by dominictarr** [comment]
just merged a pr to fix this! git pull https://github.com/qbit/ssb-keys.git master

**Comment by dominictarr** [comment]
update to 7.0.7
