### ISSUE TITLE
List channel subscribers in sidebar

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#477]

**Comment by masukomi** [comment]
I like the idea, _but_ privacy violations need to be considered. It's fine in a work setting to show everyone who follows a Slack channel, but if i enjoy reading the `#gay_people_in_love` channel and that is made public there are certain situations where I could get in a lot of trouble. 

I see two options: adding a  "Subscribe Secretly"  button which sets some flag on the intersection of you and that channel. The problem with that is that now every profile has a list hidden in the public data of all the channels they subscribe to but don't want anyone knowing about. Not good.

Better, would just be a flag on the user that indicated that they didn't want to appear in channel lists. The fact that they subscribe would still be visible in the raw data but at least we wouldn't know which ones they're uncomfortable about people knowing about.
