### ISSUE TITLE
Should preview description before publishing

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#479]
It contains markdown and can be easy to mess up.

Another option would be to rollup about messages properly. Only show the most recent ones then it doesn't matter if you change it a few times.

**Comment by ivilata** [comment]
Given the slightly different interpretations of Markdown between different systems and the fact that info pushed to SSB is immutable and cannot be corrected, that preview functionality would in my opinion be a big win in usability for the general public.

(Plus it's ugly for [Getting Started instructions](https://www.scuttlebutt.nz/getting-started.html#some-places-to-start) to tell users to "use your spellcheck, actually look at the Preview" when there's no preview in the main user-facing tool!)

**Comment by mmckegg** [comment]
Okay, new behaviour is show a confirm dialog that shows you just the things you have changed. 

Will be included in the next release!

**Comment by ivilata** [comment]
Cool, thank you! :smile:
