### ISSUE TITLE
Expand the number of petnames which are used in mentions

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#48]
We noticed a message by max to mix included "@mixmix," but it didnt register as a mention in the system. That's because max doesn't follow mix, and mentions are currently only recognized for people you follow. But, since max sees mix from FoaF, he expects to be able to mention him.

So, he should be able to!

**Comment by mixmix** [comment]
nice catch. oh the edge cases.
I'll try find that message now ..

**Comment by mmckegg** [comment]
This does still seem to be the case.

**Comment by mmckegg** [comment]
This is handled properly in patchbay / patchwork-next and not worth fixing in this iteration since #423 - closing!
