### ISSUE TITLE
Can't adjust zoom to improve readability

### ISSUE THREAD

**Issue by cameralibre** [ssbc/patchwork#480]
I am finding the default zoom level in version 3.3.0 somewhat difficult to read, and I haven't found a way to zoom in as I might in a web browser - it doesn't seem to be configurable in any way.

Using Patchwork-3.3.0-linux-x86_64.AppImage installed in Ubuntu Gnome.

![screenshot shoing zoom levels in firefox (normal) and patchwork (too small)](https://cloud.githubusercontent.com/assets/15368010/24829138/ad17db16-1c6c-11e7-9ef9-add4b44267b0.png)
Comfortable zoom level in firefox, just-slightly-too-small-to-be-comfortable in patchwork.

**Comment by ralphtheninja** [comment]
You should be able to zoom just like in the browser, e.g. `Ctrl-+`

**Comment by cameralibre** [comment]
ah, ok, thanks! I had been trying `Ctrl +` and also  `Ctrl` with double finger scroll on the touchpad, neither worked for me, and I couldn't find any 'Preferences' menu or similar. 
But after your suggestion I tried out a few other likely combinations. 

`Ctrl Shift +` works.

For future reference, are shortcuts or other tips documented anywhere?

**Comment by oren** [comment]
should i create a separate issue for fixing this? in the browser there is no need for shift.

**Comment by ahdinosaur** [comment]
recent thread: [%HwmPZHAsnt4O8WzkBSf+ghXHtjj1RVq3Rw1lgoECz4g=.sha256](http://viewer.scuttlebot.io/%25HwmPZHAsnt4O8WzkBSf%2BghXHtjj1RVq3Rw1lgoECz4g%3D.sha256)

**Comment by mmckegg** [comment]
It's related to the fact that the shortcut you want is actually `Ctrl` + `=`.

For some reason, electron handles this correctly on macOS, but on Windows (and maybe others?) it uses `Ctrl` + `Shift` + `=`.

https://github.com/electron/electron/issues/6731

There's probably a way of hacking around this per platform.

**Comment by adamnovak** [comment]
On Mac at least, there's a `View -> Zoom In` in the OS menu bar.

I resorted to hacking the stylesheet with the Inspector, though, since changing the global zoom made all the UI stuff bigger as well as the post text.

**Comment by interfect** [comment]
It looks like https://github.com/ssbc/patchwork/commit/43345f5ac86fe49350fb78162606634c3f920de4 has already fixed the underlying tiny text issue.

**Comment by mmckegg** [comment]
Is this still a problem for folks?
