### ISSUE TITLE
Undo on @mention selection undoes typing instead of selection

### ISSUE THREAD

**Issue by mawise** [ssbc/patchwork#481]
If I want to mention someone, I type @ then the first few characters of their name, then [enter] to select.  This turns the text into `[@Name](@key)`.  In this example, if I type `@Nam` then enter, it will change `@Nam` to `[@Name](@key)`.  But now if I undo, instead of turning back to `@Nam` so I can select the right user, it undoes the `m` letter, turning it into `[@Nae](@key)`.  If you undo enough times to get rid of the leading `@` then it removes the entire tag, but this isn't the cleanest interface.

**Comment by mmckegg** [comment]
Yeah, the tagging is pretty nasty right now.

In fact the whole markdown thing is pretty confusing for new users. We could do a lot to improve this.

**Comment by mmckegg** [comment]
This is still a bug.

**Comment by mmckegg** [comment]
This is still a problem and somewhat annoying.
