### ISSUE TITLE
re-implement i18n for Patchwork version 3

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#483]
[%mdlJLEUiWe+F0pqOmvKCnQDqo0vX5hJynfLgsdKm6rg=.sha256](http://viewer.scuttlebot.io/%25mdlJLEUiWe%2BF0pqOmvKCnQDqo0vX5hJynfLgsdKm6rg%3D.sha256)

translations from Patchwork version 2 ("Patchwork Classic") are in [ssbc/patchwork-classic-translations](https://github.com/ssbc/patchwork-classic-translations)

/cc @gmarcos87

**Comment by gmarcos87** [comment]
Hello, does it make sense that I finish translating? Or is it better to contribute in the re-implementation of i18n in v3?

**Comment by ahdinosaur** [comment]
@gmarcos87 it's up to you. if you feel comfortable helping with code, it's probably best to help with re-implementing i18n in v3, since then we know exactly what words and phrases are in the current interface. otherwise, you can continue with v2 translations, but keep in mind the words and phrases will likely change with v3. in general, it'd be really great to have you as our primary maintainer of the Spanish translations. :smiley:

**Comment by ahdinosaur** [comment]
regarding implementation, we need to pick a i18n library to help handle translation data and strings. here's what i can find, anyone have preferences?

- [polyglot.js](http://airbnb.io/polyglot.js/) (used in Patchwork v2)
- [format.js](https://formatjs.io/) seems to be the most popular, we'd use [`intl-messageformat`](https://www.npmjs.com/package/intl-messageformat)
- [`format-message`](https://www.npmjs.com/package/format-message)
- [`nanotranslate`](https://github.com/ajoslin/nanotranslate) very minimal

then we'll need to extract out all the current strings into a separate file and use one of these to format them back.

**Comment by ahdinosaur** [comment]
began writing a patch\* module for internationalization: https://github.com/ssbc/patch-intl. will try and get this working with Patchwork so we can start extracting the current English strings into a locale.

**Comment by gmarcos87** [comment]
I had trouble understanding depnest :disappointed: . Anyway I extracted the text strings in English. If you show me how to implement only one translation I can do the same with the rest. 
English strings: https://gist.github.com/gmarcos87/5a8e10903f01c3577ecc9d13aac21617

**Comment by ahdinosaur** [comment]
hey @gmarcos87, great! https://github.com/ssbc/patchwork/issues/485 is ready to receive those English strings, do you think you can follow what i've done so far?

**Comment by gmarcos87** [comment]
Yes @ahdinosaur, sure. And if it's not hassle one of these days you can explain me by IRC how depnest works. If you do not mind. Thanks for the patience.

**Comment by ahdinosaur** [comment]
sweet. yep, but i'm not really on IRC much so can it be a thread here, on Patchwork, or a private Patchwork message? in short, `depnest` is syntactic sugar for writing [`depject`](https://github.com/depject/depject) modules, and `depject` is the module system used by Patchwork that supports overlapping opinions.

**Comment by dangerousbeans** [comment]
eep, didn't see this - I whacked together something crude here: https://github.com/ssbc/patchwork/pull/527

wasn't sure how to switch locale sensibly though

**Comment by ahdinosaur** [comment]
@dangerousbeans awesome. can you do this on top of https://github.com/ssbc/patchwork/pull/497?
