### ISSUE TITLE
mouse buttons should trigger forward/backward in browsing history

### ISSUE THREAD

**Issue by cblgh** [ssbc/patchwork#487]
I have a [Razer Deathadder](https://assets.razerzone.com/eeimages/products/17531/feature-button.png) mouse, and I'm very used to using MB4/MB5 for going backwards and forwards in my browser history. Patchwork has the same kind of buttons, but when I press MB4/MB5 on my mouse nothing happens!

 It's not a big thing, but it would feel a lot better navigationally if you could use those buttons in the same way as when browsing in Firefox or Chrome.

**Comment by mmckegg** [comment]
In addition it would be nice if macOS style back/forward page gestures worked.

**Comment by fenwick67** [comment]
Some FYIs for anybody wanting to implement these:

At least for Windows the `app-command` [event can be used to grab the back button clicks](https://electronjs.org/docs/api/browser-window#event-app-command-windows).

On MacOS the `swipe` [event is used for three-finger swipes](https://electronjs.org/docs/api/browser-window#event-swipe-macos).

The lack of support for mouse buttons for linux is a problem [Brave has encountered and hasn't solved yet](https://github.com/brave/browser-laptop/issues/3101).

**Comment by ThunderFD** [comment]
oh yes please, I was about to open an issue about this. Has someone tried implementing this already?

**Comment by kroppt** [comment]
Looks like someone is going at a solution in Electron: https://github.com/electron/electron/pull/15441

**Comment by gergelypolonkai** [comment]
I will keep an eye on that Electron PR; whenever that is released, my solution will be obsolete.

**Comment by lostmsu** [comment]
This does not seem to be working on Windows 10 with v3.17.7 (probably haven't worked before either).
