### ISSUE TITLE
How to build for windows 

### ISSUE THREAD

**Issue by fredhampton** [ssbc/patchwork#496]
Are there build instructions for Windows ?

**Comment by ralphtheninja** [comment]
This is a good question. What would it take to build for windows? cc @mmckegg

**Comment by ahdinosaur** [comment]
@ralphtheninja we already do build for windows. :smile: 

instructions here: [%+SBr3lvHbR2yNKASU7FfLX7fTN06yk4ON1qUipaG9fk=.sha256](%25%2bSBr3lvHbR2yNKASU7FfLX7fTN06yk4ON1qUipaG9fk%3d.sha256).

would appreciate if anyone wanted to contribute a "build instructions" page in a `docs` directory and add these instructions to it.

**Comment by mmckegg** [comment]
From %+SBr3lvHbR2yNKASU7FfLX7fTN06yk4ON1qUipaG9fk=.sha256:

> - installed node lts from nodejs.org using msi installer
> - installed git from git-scm.org
> - followed instructions on [node-gyp README](https://github.com/nodejs/node-gyp#installation), option # 1: `npm install --global --production windows-build-tools`
> - configure npm to use windows python executable location: `npm config set python C:\Users\%USERPROFILE%\.windows-build-tools\python27\python`
> - clone down patchwork `git clone https://github.com/ssbc/patchwork` + `cd patchwork` + `npm install` > - `npm start`
>
> THAT IS ALL! WORKED PERFECT!
>
> Also forgot to mention: do all this inside an administrative powershell rather than cmd.

**Comment by av8ta** [comment]
Thanks @mmckegg that's helped me to get further along than before. I still didn't have "make" on my system though so installed mingw-w64. Then added the mingw bin PATH and copied mingw32-make.exe to make.exe in the bin directory. Now make is working but it fails on libtoolize at sodium-prebuilt

> sodium-prebuilt@1.0.22 install C:\code\patchwork\node_modules\sodium-prebuilt
> prebuild --install --preinstall make

./autogen.sh: line 13: libtoolize: command not found
Makefile:8: recipe for target 'configure' failed
make: *** [configure] Error 127
prebuild ERR! build Error: make  failed with exit code 2
prebuild ERR! build     at Object.exports.spawnFailed (C:\code\patchwork\node_modules\prebuild\error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (C:\code\patchwork\node_modules\prebuild\util.js:116:14)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

I'm guessing you already had some other windows build tools installed already? I haven't got the behemoth visual studio installed on this machine and want to avoid it if I can.

**Comment by ahdinosaur** [comment]
hey @av8ta, i have no idea, but is that not included in:

> * Option 1: Install all the required tools and configurations using Microsoft's [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) using `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).

**Comment by mmckegg** [comment]
@av8ta are you running all this from an admin console? I used powershell.

**Comment by av8ta** [comment]
@ahdinosaur yup, I had that installed already - without the production flag but that should be okay?
@mmckegg  yes, powershell admin

after the above post I got libtoolize installed only to have another error. The same as described by this ubuntu user:
https://github.com/mafintosh/node-sodium-prebuilt/issues/10#issuecomment-293849292

**Comment by mmckegg** [comment]
@av8ta when I ran the suggestions above, it was on a freshly installed windows 8 computer. Haven't yet tried on my windows 10.
