### ISSUE TITLE
That's an imposter!

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#498]
see @mixmix's threat: %L+5/1y2hXY5rOGnpeJ41me8XXof+Gw3JbY5kEkwn5BU=.sha256
we should be able to distinguish friends from people posing as friends

this should also apply to suggest box mentions (highlight who are friends)

maybe show an icon next to people's names if you don't follow them (hover to see who does?)

lots of room for discussion here!

**Comment by mixmix** [comment]
Nice catch with suggest mentions...   That design Charlene just keeps
getting deeper as a topic.
