### ISSUE TITLE
Ability to disable PMs or turn off end-to-end encryption

### ISSUE THREAD

**Issue by frostyfrog** [ssbc/patchwork#499]
Odd request, I know, but I was curious if it was possible to disable PMs or turn off end-to-end encryption. I'm asking because of [97.113(a)(4) and 97.309(b) of part 97 of the FCC's regulations](https://www.ecfr.gov/cgi-bin/text-idx?c=ecfr&SID=336ab7469b61ecbfa15086dbf1bf2c59&rgn=div5&view=text&node=47:5.0.1.1.6&idno=47#47:5.0.1.1.6.1.157.1) prohibit a system such as patchwork from operating with end-to-end encryption.

Patchwork looks like an awesome system and it appears that it could be used to help amateur radio operators communicate over systems such as AREDN and Broadband-Hamnet (Though I haven't measured the bandwidth usage yet to determine feasibility), if it didn't pose a risk of violating FCC regulations.

**Comment by dominictarr** [comment]
I would love to support users on amature radio! I think this issue should be on scuttlebot though, because it's about the protocol not the ui. see https://github.com/ssbc/scuttlebot/issues/395 instead
