### ISSUE TITLE
need a way to get the id of a comment

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#5]
there is currently no way to get the id of a comment. this is useful when demoing ssb and explaining how it all works, but it is also important if you want to refer to another comment later, or look it up with the CLI.

**Comment by pfraze** [comment]
Yeah, this fits into an ongoing task of designing the "chrome" around each message, and including everything you need without overloading the UI visually.

Currently, you can go to the "Behind the scenes" page via nav to find the ID of any message -- though, obviously that's tedious.

For the root message of a thread, you can click on the age of the post ('yesterday', '1h ago', etc) to open the message-page, and then copy the ID out of the location bar. That won't work for replies, however.

**Comment by dominictarr** [comment]
Yes, I see that. want a way for it to do that with replies. what about short relative time representations `2d` `6h` `10m` it wouldn't be wider than 3 chars. unless it was `100y`.

**Comment by pfraze** [comment]
Yeah, the chrome is a solveable problem, it's just a design thing so I need to let it evolve a bit. We also need to be able to star and flag replies.

**Comment by dominictarr** [comment]
you could click on the reply, and it could expand and show those extra details. having something that expands to show more details is pretty common through out the interface.

**Comment by pfraze** [comment]
most recent version `0.0.3` put the chrome on all messages, which includes the age for opening a direct link, and I think it looks good enough so Im going to close this

(reply's page still needs work though)

**Comment by dominictarr** [comment]
i saw it, awesome.
