### ISSUE TITLE
How might this run on Chrome OS?

### ISSUE THREAD

**Issue by trosel** [ssbc/patchwork#500]
Pretty soon, Chromebooks will be able to run Android apps. So it could wait until something like Patchwork works on a phone.

But how easy would it be to run Patchwork as a Chrome OS app?

**Comment by IamCarbonMan** [comment]
Not easy and probably not possible.

**Comment by dominictarr** [comment]
@WildYorkies it's entirely possible, it's just a matter of implementing the right polyfils to make what you get easily on chrome os to work with the things we need. You are the first person to ask for chrome os, so unless you wanna take this on and make it happen, we'll probably get to it after web and android (which are priorities) at that point, chromeos will probably be pretty easy anyway.

**Comment by IamCarbonMan** [comment]
@dominictarr I wasn't aware that standalone web was a current priority. It seems that the older Patchwork Classic which ran in the browser was deprecated only in December and the new Patchwork 3 has only been released in the past month or two. Is there any existing milestone for this?

**Comment by dominictarr** [comment]
the UI ran in the browser, but you still needed a local server (node.js), I don't know if that is doable on chrome os, but my impression is that it's closer to chrome extention? there is also https://github.com/ssbc/patchlite which is the same deal.

**Comment by dominictarr** [comment]
oh, and we are not so organized as to have "milestones" this is an open source project where people work on what excites them. Sometimes big things happen and I guess you could call those milestones!

**Comment by ahdinosaur** [comment]
is running on Chrome OS the same as a "Chrome App"?

if so, it might be as easy as using these polyfills:

- [`fs`](https://www.npmjs.com/package/web-fs)
- [`dgram`](https://www.npmjs.com/package/chrome-dgram)
- [`net`](https://www.npmjs.com/package/chrome-net)
- [`http`](https://www.npmjs.com/package/http-node)

**Comment by WildYorkies** [comment]
Let's leave it open and label as "enhancement" then? :)

**Comment by christianbundy** [comment]
@mmckegg Is this something you're interested in supporting in Patchwork? I'm not sure how Electron-specific the current code is.

**Comment by cauerego** [comment]
i've been trying to use FUSE with crostini (aka chrome OS linux beta) 74 latest stable and the latest stable AppImage... so no dev trickery what so ever. and it [almost works](https://www.reddit.com/r/Crostini/comments/b4d7gy/trying_to_install_an_appimage/eny8esn/)! but it's still unusable. :(

i also tried installing node (doesn't exist from the default source) or the debian dependencies (to try and make AppImage work somehow), but nothing helps to fix this error:

[ssb.log](https://github.com/ssbc/patchwork/files/3193248/ssb.log) acquired by using `./Patchwork-3.11.6-linux-x86_64.AppImage > ssb.log 2>&1`

![Screenshot 2019-05-17 at 22 59 50](https://user-images.githubusercontent.com/560418/57958436-ba568b80-78f7-11e9-87f3-1a8305edcb53.png)

the GUI is somewhat usable, but nothing really works. on the log file, after the first error, when trying to update the profile, we get the `Gtk-Message` warning:
![Screenshot 2019-05-17 at 23 00 19](https://user-images.githubusercontent.com/560418/57958442-bdea1280-78f7-11e9-9522-717af426f1be.png)

**Comment by christianbundy** [comment]
That looks great! I think that bug may be resolved in the latest prerelease, I might recommend trying that. Super excited to see that this is so close on ChromeOS.
