### ISSUE TITLE
Security error prevents webcam loading

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#51]
When I click the webcam icon, the webcam media area is empty, and an error appears in the console:

> main.html:1
> Refused to load media from 'blob:file%3A///31acfe39-df1a-45d8-bfb7-92556a0a6b82' because it violates the following Content Security Policy directive: "default-src 'self' http://localhost:7777 http://localhost:7778". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

When I then click the webcam media area, the following message is logged on the console, followed by the same error as before:
> /usr/local/src/patchwork/ui/lib/com/webcam-giffer-form.js:250
> Webm video encoded: 321 bytes

Debian testing amd64, Node v4.2.1, patchwork 4fb5789b5002bd587a273ef0a33bc2072b34baab

**Comment by pfraze** [comment]
Thanks for the report, will look into it

**Comment by dominictarr** [comment]
@clehner interesting. I get the same error. For me, _sometimes_ the webcam works, sometimes it doesn't. I'm also on (arch) linux.
