### ISSUE TITLE
Allow opening content in tabs

### ISSUE THREAD

**Issue by mitar** [ssbc/patchwork#524]
I know that there are alternative implementations like Patchbay, but I would suggest that also patchwork has a way for user to open content in tabs, or even external windows. It is sometimes hard to discuss things because one has to move back and forth between feeds. (BTW, great job on not loosing already typed content into a form while I move back on forth.)

**Comment by edwardgalligan** [comment]
Is this a duplicate of #705?

**Comment by christianbundy** [comment]
@edwardgalligan Actually looks like #705 may be a duplicate of this issue, nice catch!
