### ISSUE TITLE
Message notifications over e-mail

### ISSUE THREAD

**Issue by mitar** [ssbc/patchwork#525]
It would be really great if I could get an e-mail notification for at least replies on my posts. Especially in the early days of patchwork this would be great so that I would get informed of some activity I care about even if I closed patchwork for some time. It would get me to go back and look.

**Comment by slinlee** [comment]
Do you have any ideas for how this could work on decentralized system? I'm curious. Who/what would email you? Would it be based on if there was a reply to you and you haven't been seen in a while (seen where? a pub?)

**Comment by mitar** [comment]
I think we could name this service "notifier", just to have a term. And yes, it could reside on a pub, but it could also be separate. And you would decide to which one you want to connect. And when you connect, it would connect to same feeds as you. And then if you disconnect, it would start sending you e-mails until connect again, from the feeds on which you are.

**Comment by dominictarr** [comment]
it could notify you about public messages, the pub would have to know your email address, but you could send it the address in a private message. Then, the link it emails you could be "encrypted", but could open in your local client. This would certainly improve "engagement" and would probably bring people that are on the cusp into active use.

**Comment by mitar** [comment]
Not sure how private messages are done, but sender and recipient are not visible for private messages? Because if they are, then it can send you e-mails even for thse.

I think what is in the e-mail is a different thing, and should probably be customizable:
- just a link
- a link + snippet
- a link + full text of message
- (a link + full text) encrypted with gpg
