### ISSUE TITLE
Show number of pending updates in Patchwork icon on Mac

### ISSUE THREAD

**Issue by mitar** [ssbc/patchwork#528]
Many applications show a number badge on their icon for number of updates, notifications, etc. Patchwork could do the same on Mac.

**Comment by dmamills** [comment]
This looks possible using [electron's `setBadge`](https://electron.atom.io/docs/api/app/#appdocksetbadgetext-macos)

**Comment by mmckegg** [comment]
This was added in b1b0ee71c45997c433aba9eaf0175aa177983a29
