### ISSUE TITLE
No indication of nested replies

### ISSUE THREAD

**Issue by soggypretzels** [ssbc/patchwork#533]
While viewing a thread there is no way to see if a given message has any replies to it without manually clicking on the age of each message.

For example when viewing the thread %qoNNiitlQRBNzd3mGI+zlFMlm44tN/qm/GQIG203vfM=.sha256 it is not possible to see that the message %0SwZD7B5m+DWLbPxHcOtRtQ3O8PJ9nl1sfpvsXZJquw=.sha256 was replied to by the message %LAQKPw1RIJVWfA7tAczkV1u0b5p1DEngL8jWVSfYMQ4=.sha256. This means it is easy to miss whole parts of the conversation and get lost in what people are talking about.

Perhaps an indented block that shows the first reply outside of the thread and a button to view/expand the sub-thread for additional messages?

**Comment by clehner** [comment]
this is what i was referring to in  %9j/1gJS6xKVZzYNVEzQtPbc75wYEuNMqkrq69w83RuY=.sha256

**Comment by dominictarr** [comment]
before the patchcore refactor a reply to a reply would take the root from the first reply. that at least gave consistent behaviour across the UIs. forking the thread is a valid option, but it should show that the message has it's own thread.

**Comment by mmckegg** [comment]
This was addressed in c2d8083ad55e777a6e7b82aaa57f2aaa27f5a607 (on master, not yet released)

Patchwork now shows a "Someone forked this discussion" message similar to backlinks.
