### ISSUE TITLE
redact a message

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#54]
Being able to hide a message you mistakenly posted would help enable hacking on new applications - at least it would make it safer to test them with out annoying everyone by filling their feeds with noise.

Currently, spam flags do work somewhat like this... but it's not obvious that you can do this by flagging your own message as spam.

That said, redaction shouldn't hide the message entirely - it's still there in the database, so it would be dishonest of the application to hide it completely. Opening that message directly should show it, for example.

**Comment by pfraze** [comment]
Seems like authors should be able to edit or delete, but recipients should be able to override/pin messages.

**Comment by dominictarr** [comment]
or at least, always be able to see the original, and link to them somehow. hmm, how to distinguish? it seems like the message renderer needs modes?

**Comment by mmckegg** [comment]
Don't think this is gonna happen in the current iteration of patchwork. Gonna make it a priority for [patchwork-next](https://github.com/mmckegg/patchwork-next) though. 

Closing!
