### ISSUE TITLE
add zoom controls to window menu

### ISSUE THREAD

**Issue by molstrangler** [ssbc/patchwork#540]
I have use a laptop with a high resolution display and the GUI (especially the text) is small and not a comfortable read.

It would be very useful if you have some keyboard short cuts to zoom in and out:

- OS X users CMD+ CMD-
- Windows users CTRL+ and CTRL-

Also for the zoom level to be stored for when relaunching the application.

**Comment by mmckegg** [comment]
Ideally you would adjust your screen's DPI, but I understand that it is easy to get used to that massive desktop space!

But yes, Patchwork already supports zoom with `Cmd`-`+` and` Cmd`+`-`. On Windows for some strange reason, zoom in is `Ctrl`-`Shift`-`+`.

It's also available in the menu bar (hidden on Windows until you press alt).

I don't think the zoom level is persisted after app close though, which is a bit annoying.

**Comment by molstrangler** [comment]
You cannot change the DPI on a screen, you change the scaling factor.  Just to be picky.

Thanks for hint for using the shift key on Windows, it works perfectly.

**Comment by robjloranger** [comment]
#872 will fix the weird need for `shift` when zooming in. If persistent zoom on restart is desired as #764 requests I can investigate there.

**Comment by robjloranger** [comment]
this might be closable from #872, the controls are in the `view` menu and have hotkeys `ctrl+=` and `ctrl+-`.

**Comment by christianbundy** [comment]
I think that's a good idea, thanks! Feel free to close. :+1:

**Comment by robjloranger** [comment]
closing as zoom controls are both available in an application menu and via common keyboard shortcuts.
