### ISSUE TITLE
sometimes setting display images doesn't work

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#546]

**Comment by gergelypolonkai** [comment]
@mmckegg do you have any memories on this? Any known circumstances, ways to reproduce it would be great.

**Comment by mmckegg** [comment]
@gergelypolonkai Haven't noticed this for a long time, and can't remember anyone reporting recently. Probably safe to close.

**Comment by gergelypolonkai** [comment]
Thanks for clarifying. Letʼs hope it wonʼt come back ☺
