### ISSUE TITLE
save for later

### ISSUE THREAD

**Issue by geovanisouza92** [ssbc/patchwork#549]
Hello everyone! Thanks for this awesome project.

I just started to learn about Patchwork, but would like to ask if would be possible to add some kind of "save for later / bookmark / favorite" option to keep posts?

Thank you.

**Comment by av8ta** [comment]
I've been thinking a feature for collecting would be great. Right now you can right click and copy the message ID of any post and save it for yourself by pasting it into a private message. You can always go back to your private messages to find it. Can also paste those links into search in patchwork to browse straight to the content.

**Comment by dominictarr** [comment]
yes, we have talked about this before. I can gaurantee will be a parade in the honor of whoever eventually implements this!
