### ISSUE TITLE
Tracking relationships with Pubs

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#55]
I'd like to keep a registry of pubs that the user has joined. Why:

 - When the user publishes new data, we could prioritize syncing with the users' joined pubs, to ensure quick delivery.
 - If the users' joined pubs are not reachable, we can alert the user.
 - If the user hasn't joined any pubs yet, we can give instructions to do so.

The registry could be updated when an invite is successfully used.

@dominictarr you have any objections to this? Do you think this registry should live in the invites plugin, or in PW?

**Comment by dominictarr** [comment]
isn't this as simple as filtering the followers by those who are pubs? This is something that would be very easy to calculate as a query.

**Comment by mmckegg** [comment]
I think some of these issues are being addressed in the changes to gossip in the latest scuttlebot branches in git-ssb. There is also discussion about prioritizing connections to pubs you follow.

Closing!
