### ISSUE TITLE
Gatherings not publishing

### ISSUE THREAD

**Issue by srccon** [ssbc/patchwork#566]
Not sure how to debug this, I put info into a new gathering and press publish and ... nothing. So I press publish over and over and ... nothing. I remake gathering without a picture in case it was too big, and press publish and ... nothing. 

I'm running debian 8, with Patchwork v3.5.1 from the AppImage.

**Comment by mmckegg** [comment]
Yeah, sorry. There was a bug in the most recent version of Patchwork that stops gatherings from publishing. Originally reported here: #563 

It has been fixed in the latest code, but not yet released.

**Comment by ahdinosaur** [comment]
released! [v3.6.2](https://github.com/ssbc/patchwork/releases/tag/v3.6.2)

**Comment by srccon** [comment]
Excellent!
