### ISSUE TITLE
Port 8008 is also used for CalDAV

### ISSUE THREAD

**Issue by Sam-Hall** [ssbc/patchwork#568]
I tried to run Patchwork on my Ubuntu desktop, something was clearly wrong with it because it just liked spinning loader animations and not much else. Running it from the terminal showed that it couldn't bind on port 8008. I have DavMail running a local CalDAV server on port 8008 for providing access to an MS Exchange calendar.

I can reconfigure DavMail, but you might want to check if port 8008 is available on startup, and if not give the user some feedback.

**Comment by mmckegg** [comment]
I was wondering when someone was going to encounter this. Yes, we need to handle this better!

**Comment by ahdinosaur** [comment]
https://github.com/mikeal/getport ?

or if we want to be _modern_: https://github.com/sindresorhus/get-port ?

**Comment by dominictarr** [comment]
what error happens when this occurs? I guess we just need to show an error if the port is in use, and an instruction/option for configuring a different port?

udp advertisement won't work on a random port, so we need a standard port for that, anyway.

**Comment by dominictarr** [comment]
btw, if you start your server without setting a port, it will take some available port.

**Comment by Sam-Hall** [comment]
As a newbie end-user that has no idea of the ins and outs of the software, I'd have been happy if you caught the error and told me to free up the port, or tell me how to change the port used by Patchwork. If there is some functionality that can't work without binding a specific port, perhaps the solution is to visibly disable that functionality until the user figures out how to free up the port and then try to "reconnect" or simply restart Patchwork or whatever works.

Here's the terminal output...
```
$ ./Patchwork-3.5.1-linux.AppImage 
installed: X-AppImage-BuildId=cca1fe50-541e-11a7-2583-2f67f290edfb image: X-AppImage-BuildId=cca1fe50-541e-11a7-2583-2f67f290edfb
Log level: notice
Error: listen EADDRINUSE :::8008
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at Object.server (/tmp/.mount_SqgDq3/usr/bin/resources/app.asar/node_modules/multiserver/plugins/net.js:21:10)
    at Object.server (/tmp/.mount_SqgDq3/usr/bin/resources/app.asar/node_modules/multiserver/compose.js:77:20)
    at /tmp/.mount_SqgDq3/usr/bin/resources/app.asar/node_modules/multiserver/index.js:30:21
    at Array.map (native)
    at Object.server (/tmp/.mount_SqgDq3/usr/bin/resources/app.asar/node_modules/multiserver/index.js:29:26)
git-ssb is not installed, or not available in path
```
