### ISSUE TITLE
#🍆 not showing message posted in channel

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#572]
using the latest (https://github.com/ssbc/patchwork/commit/0a2a19abbd326534732b6aee3ec2351e94dd7a32), when i browse to #🍆 i don't see [%gyM/4Lexdpn6br/nCmRKcXNBTIAw8reAzKhFW/TVfFI=.sha256](https://viewer.scuttlebot.io/%25gyM%2F4Lexdpn6br%2FnCmRKcXNBTIAw8reAzKhFW%2FTVfFI%3D.sha256)

**Comment by mmckegg** [comment]
Fixed by 7825ae89c253685cdcbee4c04c902518a786231b
