### ISSUE TITLE
on the left sidebar, have a separate list for your "subscribed channels" and the generic "active channels"

### ISSUE THREAD

**Issue by WildYorkies** [ssbc/patchwork#574]

**Comment by mmckegg** [comment]
Related: #552 

The next version will have a list of everything you are subscribed to under a drop down menu on the top bar:

<img width="660" alt="screen shot 2017-06-30 at 12 52 49 pm" src="https://user-images.githubusercontent.com/66834/27716523-11eaac0a-5d93-11e7-9924-2b91c79b3711.png">

You can try this out on the latest master version if you're game!

Does this solve the issue for you?
