### ISSUE TITLE
git-ssb isn't always starting

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#582]
For some reason it gets left running after patchwork closes (sometimes). Then when patchwork reloads, git-ssb immediately crashes, and doesn't start again.

**Comment by mixmix** [comment]
further notes from conversaiton with matt: 
- works every 2nd time?
- sometimes git-ssb isn't spawning .. perhaps because it didn't close ports previously?

There should be a broader conversation about how integrations should be handled across apps in the ecosystem.
