### ISSUE TITLE
local peers not removing from interface (fine after reloading interface)

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#588]

**Comment by mmckegg** [comment]
Still the case!

**Comment by olizilla** [comment]
Also, local peers are much _jigglier_ in recent releases. See 3.8.10:

![patchwork-local-replication-dance](https://user-images.githubusercontent.com/58871/37350255-3c4cfaa0-26d0-11e8-9c33-a03be6ae4b7e.gif)
