### ISSUE TITLE
rework: missing "back" functionality

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#59]
I'm not saying it needs to be a back button, but eg, if you open an image to view it, you can't easily go back to where you were. Clicking on feed again takes you to the top of the feed.

**Comment by dominictarr** [comment]
when viewing a thread, the close button normally does this. but when you scroll down on a longish message the close button disappears. Maybe the close button could float when you scroll down? (possibly also be simplified to just show an "x" or and "<x" to indicate "close and back"

**Comment by mixmix** [comment]
yeah dito : 
http://porthole.mixmix.io:5000/%zZk1h5NIRrtR9MGaMj9ue3Lsn9+kkZAzwHlBvwodsDk=.sha256

**Comment by pfraze** [comment]
fixed
