### ISSUE TITLE
Realtime reply experience ~weird

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#590]
Need to have a sorted add on https://github.com/ssbc/patchwork/blob/master/overrides/patchcore/backlinks/obs.js

Also should consider using the old sort function from ssb-ref.

**Comment by mixmix** [comment]
e.g. weird case where when you are typing a reply but a new reply rolls in as you're pushing post, it looks like your reply is to a message that just arrived ... so context is wrong.

possible solution - when you start typing, and a new message is discovered, then it shows you a "New messages" bar or something that you have to actively click to update the thread.
