### ISSUE TITLE
"show x updates" is including some posts more than once leading to incorrect count

### ISSUE THREAD

**Issue by morganrallen** [ssbc/patchwork#592]
I'm being shown the "Show x updates" notification for messages that Patchwork cannot handle. If the message `type` isn't something Patchwork is concerned with, they should be ignored.

**Comment by mmckegg** [comment]
It looks like the actual problem is just that each post is being emitted more than once. Other message types aren't actually being included.

Renaming the topic!

**Comment by morganrallen** [comment]
I was getting updates for a message with `type` `position`

**Comment by mmckegg** [comment]
Strange issue. I think this is fixed now so closing, but feel free to reopen if this is still a problem.
