### ISSUE TITLE
Reference is not a tree

### ISSUE THREAD

**Issue by bumcheekcity** [ssbc/patchwork#594]
When trying to npm install on both Windows and Linux, I get the below error:

This happens after cloning the git branch and typing "npm install" - nothing else needed to replicate. My linux installation has the additional items required in the README.md

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout 901c79c841d9a4ee771ce6d9f3951459f8f8079b
npm ERR! fatal: reference is not a tree: 901c79c841d9a4ee771ce6d9f3951459f8f8079b

**Comment by mmckegg** [comment]
Whoops, this is because a fix was merged in another module, but the branch was removed.

Should be fixed now.

**Comment by bumcheekcity** [comment]
Yep, works perfectly, thanks!
