### ISSUE TITLE
Patchwork hangs, I think because my post is too long?

### ISSUE THREAD

**Issue by rdbartlett** [ssbc/patchwork#598]
I'm on macOS Sierra. Sometimes when I post a comment, Patchwork hangs indefinitely. My best guess is that I'm overshooting some length limit, but not getting visual feedback. 

Anything I can do to help debug?

**Comment by mmckegg** [comment]
An error is logged to console saying that "Message exceeded max size".

If a handler was added to https://github.com/ssbc/patchwork/blob/master/modules/message/html/compose.js#L155 that displays the error message, then at least the user would know what was going on.

See #456 for some extended discussion.

---

This also could be the dreaded locking bug (#597) that occurs when a remote peer unexpectedly terminates a connection

**Comment by rdbartlett** [comment]
Gotcha. Wheee now I know about the console!
