### ISSUE TITLE
RPC bugs between main thread and ui thread

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#6]
I'm seeing some bugs in patchwork-ui's RPC connection with patchwork's main thread. How it manifests:
 1. On the message page, replies will sometimes fail to auto-insert. It tends to be the first new reply since page-load, but this is inconsistent. This means `createLogStream({ live: true })` is sometimes failing to emit. The `{sync: true}` message will emit, then the new reply will not.
 2. Sometimes, a page's feed will fail to load, and the page has to be refreshed.
 3. At random, patchwork-ui will error, saying it received a message for an inactive request or stream. The sequence number, when this occurs, is usually higher than the most recent sequence number.

Patchwork's RPC code: [main thread](https://github.com/ssbc/patchwork/blob/master/app/lib/muxrpc-ipc.js) and [ui thread](https://github.com/ssbc/patchwork-ui/blob/master/lib/muxrpc-ipc.js). I put logs in both ends and found that, when the reply auto-insert message fails to emit, it fails to emit on the server-side ([at this point](https://github.com/ssbc/patchwork/blob/67713ee1e71c4f93ea205ab5ed21f5fa78f782ce/app/lib/muxrpc-ipc.js#L40)). This suggests that the issue is not within the messaging channel. It may be a bug with how I've setup the RPC in the main thread, or a bug in muxrpc/packet-stream.

Sidenote: There are currently 2 kinds of refresh in patchwork: soft, which reloads the current view, and hard, which reloads the entire ui thread. The in-ui refresh button does a soft reload, while `ctrl/cmd+r` does a hard reload. When a hard reload occurs, `resetRpc` is called ([code here](https://github.com/ssbc/patchwork/blob/67713ee1e71c4f93ea205ab5ed21f5fa78f782ce/app/lib/muxrpc-ipc.js#L50-L55)). I was suspicious that a bug in `resetRpc` could be causing the issue, but found that was not the case. The issues occur on a fresh load, with no hard refreshes having occurred.

@dominictarr Can you review the RPC code in patchwork and patchwork-ui to see if there are any visible bugs? If it looks correct, I'll dig into muxrpc and packetstream to see if the issue is there.

**Comment by pfraze** [comment]
Managed to get an example of the random error (number 3, above).
I noticed the req number was `-45` for this error once in the past. Maybe a coincidence, maybe a pattern?

```
no stream for incoming msg
{
  "req": -45,
  "stream": true,
  "end": false,
  "value": {
    "key": "%fndO1NgfVjFjQ1xXogeNp+W4EjpKEagS9sMMY3LvjLs=.sha256",
    "value": {
      "previous": "%X0tzGRuIbvDsutjlCpmQ3ptjYSg+wkOFgb0m6ns/wKM=.sha256",
      "author": "@lQeCkxZlrHKCwsgY211KVunqeOFXlrumQfA7rnnf5Lw=.ed25519",
      "sequence": 75,
      "timestamp": 1439480448180,
      "hash": "sha256",
      "content": {
        "type": "post",
        "text": "Thu Aug 13 10:40:47 CDT 2015",
        "root": "%oMtWQGgf/bX75+6BYpNNZYJkJDyF/fUACjVc1NCHegI=.sha256",
        "branch": "%oMtWQGgf/bX75+6BYpNNZYJkJDyF/fUACjVc1NCHegI=.sha256"
      },
      "signature": "HIMU6g8iaoufg7ZglMti2ioFz9R3TXuUtFDjL6b/BEiiv6Fp6wuhBci0IYC25HO3+ckWULgwvl22kmBMDdDeBw==.sig.ed25519"
    },
    "prefix": []
  }
}
```

**Comment by dominictarr** [comment]
Okay I this code is weird. I don't know. you have two things that are tightly coupled to each other even though they are in different repos. Are ipc messages always received in the order you send them?

**Comment by dominictarr** [comment]
really, there should be a pull-ipc module that wraps electron ipc in a pull-stream, and then we are working with ordinary muxrpc. To know this is correct we need test coverage, and this would be a lot easier to test in it's own module.
If muxrpc has an ordering problem that is a big bug. however muxrpc is well tested so i don't think that is it.

**Comment by pfraze** [comment]
Progress report...
Published [pull-ipc](https://www.npmjs.com/package/pull-ipc). Going to work on its test suite to make sure it's 100%, but I used it in the app briefly, and still saw the bug in this issue.
Also published [electron-tape](https://www.npmjs.com/package/electron-tape) to help with writing tests in electron apps.

**Comment by dominictarr** [comment]
awesome!

**Comment by pfraze** [comment]
*SMH* I think I solved this... muxrpc was behind a major version on the patchwork repo.

**Comment by pfraze** [comment]
Still looking good. I thought I saw the bug again, but that ended up being a bug in live-updating of secret message threads.
