### ISSUE TITLE
Oversized blobs (attachments)

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#600]
At the moment, when you attach a file bigger than the sbot replication limit (currently 5MB), you see it in your feed but no-one else does.

There is no warning, only _confusion_

Possible solutions:
- Resize if image? 
- Or at least warn that blob is too big!

**Comment by mmckegg** [comment]
Pull request for warning that blob is to big: #624 

Still probably worth adding an option when adding an image to automatically resize.

**Comment by mixmix** [comment]
do you know of easy tools which do that ?
problem is designing some interface which does that. I guess it should be an auto-on setting, and people can go disable it if they want, and then hit this 5MB limit

**Comment by mmckegg** [comment]
Closing this issue since this is no longer a major problem. Made a new issue for auto resizing: #634

**Comment by mixmix** [comment]
I'm onto autoresizing!
