### ISSUE TITLE
attachments (blobs) on private messages should be encrypted

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#604]
Currently, in private messages, attachments (blobs) are not encrypted (though the text is).

this PR disables patchwork attachments in private messages https://github.com/ssbc/patchwork/pull/538, but there should really be a solution added to patchcore

There's rumour patchfoo has a nice solution to this.

**Comment by mmckegg** [comment]
Here is patchfoo's solution: http://localhost:7718/%25YAg1hicat%2B2GELjE2QJzDwlAWcx0ML%2B1sXEdsWwvdt8%3D.sha256/commit/440274d19f302e0f293d56cba685e39e372cda12

(need to be running `git-ssb-web` or patchwork with `git-ssb` installed)
