### ISSUE TITLE
Block / Mute

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#608]
we need the feature re-enabled in some form as a safety + community building feature.

note: "blocking" can be one way or bi-directional: 
- mute = you don't see their content / take it
- hide = they don't get your content / see you
- block = gone gone ? don't know 

there's also a common request to be able to not propogate bad actors communication. not sure where that fits.

block already exists in sbot .. just need to wire it up!

Might be good to consider how pubs deal with these signals.

**Comment by mmckegg** [comment]
Have implemented block in the latest patchwork master.

It is a block/mute combo. If you block them, all of their previous posts are hidden and you will no longer sync new content.

Closing this issue!
