### ISSUE TITLE
rework: contualize adder button

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#61]
currently the adder always defaults to a public post. But I feel it should be contextual:

* If I am currently viewing a profile, it should probably default to a message for just that person.
* If I am currently viewing a private discussion it should default to the people in that discussion.
* If I am currently viewing a thread it should be a reply to that message

thoughts?

**Comment by pfraze** [comment]
I... *think* that's a good idea, but I'm honestly not sure. I think it may not be wholly clear to people why the behavior has changed, and therefore consistency might be preferable.

**Comment by dominictarr** [comment]
Hmm, okay this is interesting because when you mentioned the idea of the universal adder button I just assumed it was a way to add something to the page you where currently on...
Because that is the behavior that makes sense given the context you are currently in.
Otherwise, you have a button that (by default) adds something to a page you are not looking at (unless you are on the home feed page)

**Comment by pfraze** [comment]
That was the original idea, but I'm unsure now that Im looking at it. I'll go with one or the other, and we'll consider the feedback

**Comment by pfraze** [comment]
Adder btn is now gone.
