### ISSUE TITLE
Using with global sbot (the plugin problem)

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#610]
discussion with matt: 

> plugin usage in patchwork is really not ecosystem friendly. Poor mix can't use stuff I've writ, cos I've had to monkey plugins to get them good.

> versioning is the big issue

proposal is the community would benefit from a review of the plugins situation and what a stable future for everyone might look like

**Comment by mmckegg** [comment]
I've been thinking that this all might be a lot simpler if you could run patchwork as a plugin inside sbot. Then it could make sure that all the correct hooks were engaged and versioning of plugins/client would no longer be an issue. 

I'm thinking patchwork would have two modes of operation:

1. Completely standalone like now
2. Running as a global sbot plugin

**Comment by mmckegg** [comment]
Some discussion about this on ssb: [%lLkKzkWdjtg5mJFwQneLiplxqS5PxZI8KqxKy83IlUM=.sha256](https://viewer.scuttlebot.io/%25lLkKzkWdjtg5mJFwQneLiplxqS5PxZI8KqxKy83IlUM%3D.sha256)

**Comment by simonv3** [comment]
I think I'm experiencing this issue where it was pretty hidden to me that patchwork wasn't using the same sbot I'm using to try and install plug ins, so that the result of `sbot server` and just running patchwork from the AppImage as installed from the releases are different (and I can't use `sbot plugins.install` while using the AppImage but I can use it if I run `sbot server` in the terminal. This took me a lot of poking around to figure out (because of what felt like sparse documentation). 

Does this problem exist with other clients (looks the same with Patchbay, which I just quickly tried out)? Is it specifically because I used an AppImage to install the app rather than installing it from the terminal?

**Comment by kode54** [comment]
Meanwhile, I am attempting to run the macOS version against a global sbot instance, by passing the -g switch to the process on startup:

```
open -a Patchwork --args -g
```

**Comment by mixmix** [comment]
Electron clients must commonly run an internal sbot process. This will
start up, unless there is a global sbot running on the ports its trying to
use. In this case you need to be sure the global sbot is running the same
plugins (and versions of plugins) that the client application needs. At the
moment this is an impossible requirement to meet if you want to switch
between patchwork and patchbay, because patchbay is using eg a newer
ssb-query, and patchwork has (i think) some internally defined sbot
plugin...

The sbot you run in command line is a globally installed sbot and that
stores plugins in ~/.ssb/node_modules (with a list of active plugins in a
file called plugins I think in the .ssb folder). If that global one is
running when you launch a client the clients sbot (if it's using same
ports) will not start and the global sbot will be connected to instead.

Perhaps talk about your use case or what you're trying to achieve so re can
help more specifically?

**Comment by kode54** [comment]
I am trying to use Patchwork with a global Scuttlebot instance, so I can also use the same instance and identity with git-ssb, ssb-npm-registry, and possibly other Scuttlebot consuming and feeding tools. So far, only git-ssb appears to work with the sbot that's built into Patchwork.

Even installing ssb-npm-registry requires a recent ssb-backlinks, which Patchwork does not appear to implement. `links2.get`, I think.

I may just settle for using Patchwork with git-ssb and git-ssb web, as those are the only two addons I am currently using, other than ssb-ooo, which I don't even know if it's working, or if it's a totally bad idea to use.

**Comment by mixmix** [comment]
Good to know about your use case. I've got a PR updating pw to use some
more recent plugins, not sure if the requirements of ssb-npm stuff, so I'm
not much help there.
The problem is @mmckegg (matt) has used an about pluggin which can't be
unstained easily in your global sbot, it's some custom thing in pw
See it here the line .use(require('./sbot'))
https://github.com/ssbc/patchwork/blob/master/server-process.js

The pluggin that points to needs extracting, or be needs to make pw run in
a limited mode when a global sbot is running.
(hmm notice I'm saying this is matts work)
I recommend you fork patchwork, and publish that plugin yourself. It'll be
easy to maintain the fork. If matt wants this change in pw he can merge
your change.

**Comment by black-puppydog** [comment]
Nooooooooooo..... I didn't find this earlier because it got closed... Spent most of my day trying to get it to work. :( 
I'd want this for much the same as @kode54: running a global sbot, then different clients like pw & patchfoo for exploring their respective code, and maybe wiring up some automation like reacting to new git commits for patchfoo becoming available. So I think this is very much still useful. Anyone else think so?

**Comment by mixmix** [comment]
Can't see the full context easily from my phone but there is aversion of
ssb-about we released a week ago which is the extracted plug in from
patchwork. I don't know if matt is using it yet.

Matt is currently not up for investing in a global sbot. I personally think
he'll come around when scuttle-shell reaches significant maturity

**Comment by black-puppydog** [comment]
I was actually only advocating for reopening this issue, even if it's gonna take a while.

**Comment by cryptix** [comment]
Ah! This is the duplicate of #686 that I couldn’t find earlier...

**Comment by black-puppydog** [comment]
Very much still relevant IMO, and being worked on in a very fundamental manner at the moment. See [%buttti3OH8FSd2dtF6eYQmYp4ZQ7kGFYrL0kXTAxE4I=.sha256](https://viewer.scuttlebot.io/%25buttti3OH8FSd2dtF6eYQmYp4ZQ7kGFYrL0kXTAxE4I%3D.sha256) for a discussion.

**Comment by mikeruddy** [comment]
I managed to nuke my sbot by installing npm-ssb. It told me to restart sbot, then sbot says:

> Error: missing ssb-links2 scuttlebot plugin

But now I can't start up sbot to install the plugin 😄

**Comment by christianbundy** [comment]
@mikeruddy Sorry to hear you're having problems -- you may be interested in this issue: https://github.com/ssbc/ssb-links/issues/7#issuecomment-480466721

You should be able to edit `~/.ssb/config` without starting sbot. Please open a new issue with the relevant module if you're still having problems!
