### ISSUE TITLE
Patchwork 3.6.6 not working on Debian

### ISSUE THREAD

**Issue by theWebalyst** [ssbc/patchwork#612]
I just ran the AppImage for patchwork 3.6.6 and I get a blank window (title: Patchwork) and if I run from the console I see:

```
$ ./patchwork-3.6.6.AppImage 
installed: X-AppImage-BuildId=f3ff28c0-71be-11a7-0414-d9264c1eb09a image: X-AppImage-BuildId=f3ff28c0-71be-11a7-0414-d9264c1eb09a
Log level: notice
git-ssb is not installed, or not available in path
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.ppGWDj)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_QBB5y2/usr/bin/resources/app.asar/node_modules/@paulcbetts/spellchecker/lib/spellchecker.js:3:16)
    at Object.<anonymous> (/tmp/.mount_QBB5y2/usr/bin/resources/app.asar/node_modules/@paulcbetts/spellchecker/lib/spellchecker.js:116:3)
```

I may have messed up the installation by renaming and moving the AppImage but I don't think so. The first time I ran it I ran from the file manager in the downloads directory and it asked if I wanted it to install on the system so I said yes. I think at this point I got the blank window with title Patchwork (so I don't think my subsequently moving / renaming the AppImage (keeping the file ext) is the issue.

I have not installed git-ssb so is that the issue?

**Comment by mmckegg** [comment]
@ahdinosaur look, this issue finally struck.

@theWebalyst This is because some of the native dependencies in the built release were compiled on a newer version of libstdc. You can try building from source. That should work. @ahdinosaur will probably have some good ideas 😄

**Comment by ahdinosaur** [comment]
hey @theWebalyst, thanks for reporting! what version of Debian are you running? curious if it's Wheezy, Jessie, or Stretch. i think Stretch should work, but Jessie is questionable, and Wheezy certainly won't. the reason this version breaks is that previously i have been compiling the Linux images on my Jessie machine, but then i spilled tea on that machine and so this release was compiled by @mmckegg and now on a new machine i'm using Stretch. i'll see if i have time this week to sort out a way to compile on Jessie.

**Comment by theWebalyst** [comment]
Thanks guys. Sorry forgot to mention: Debian Jesse, and sorry to hear about the coffee murder :( @ahdinosaur 

I have now built and ```npm start``` gives me a profile to fill out, but "Publish" now hangs. I have a UI I can play with but it seems not to be working as I'd expect - things don't seem to complete (I have to / can 'cancel' though and move onto something else in the UI). So I have:

- tried and failed to enter a profile & publish
- entered a pub invite which affected the UI but left a dialog to be cancelled. And is now hung with "Loading..." after I hit retrieve.

So not sure if this is system/config/internet or the build still not working.

BTW Can I build an executable package (not in the readme.md)?

Here's the console o/p:

```
npm start

> ssb-patchwork@3.6.6 start /home/mrh/src/scuttlebutt/patchwork
> electron index.js

Reading /home/mrh/src/safe-test9/safe_examples/email_app/node_modules/devtron/manifest.json failed.
Error: ENOENT: no such file or directory, open '/home/mrh/src/safe-test9/safe_examples/email_app/node_modules/devtron/manifest.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at getManifestFromPath (/home/mrh/src/scuttlebutt/patchwork/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:34:26)
    at App.<anonymous> (/home/mrh/src/scuttlebutt/patchwork/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:363:26)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
Log level: notice
git-ssb is not installed, or not available in path
TypeError: Illegal invocation
    at Single._timeout (/home/mrh/src/scuttlebutt/patchwork/node_modules/async-single/proto.js:30:22)
    at Single.write (/home/mrh/src/scuttlebutt/patchwork/node_modules/async-single/proto.js:17:10)
    at write (/home/mrh/src/scuttlebutt/patchwork/node_modules/flumeview-reduce/inject.js:60:9)
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/flumeview-reduce/inject.js:134:15
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/throughs/map.js:19:9
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-cursor/cursor.js:32:13
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/aligned-block-file/blocks.js:72:11
    at get (/home/mrh/src/scuttlebutt/patchwork/node_modules/aligned-block-file/blocks.js:28:7)
CONNECT net:128.199.41.108:8008~shs:UZnDjmefaQo//6JcMNLlfzhXqPzO7Ktn3ZoXy2yVGz8=
Connected 128.199.41.108:8008:@UZnDjmefaQo//6JcMNLlfzhXqPzO7Ktn3ZoXy2yVGz8=.ed25519
```

I didn't get a chance to enter an invite or anything. So am not sure what "Publishing..." is trying to do.

**Comment by ahdinosaur** [comment]
> "Publish" now hangs

this might be #605 or #597. you should be able to publish without needing to have used an invite yet (since everything is written to your local database first then replicated to peers upon connection), but if you haven't used an invite and you aren't on local wifi with another peer than how would you replicate...

the error log might be innocuous. does it happen every time you start Patchwork or was it just the first time?

/cc @dominictarr 

> BTW Can I build an executable package (not in the readme.md)?

we build our packages with https://github.com/ssbc/patchwork-builder

**Comment by theWebalyst** [comment]
Thanks. The TypeError seems to happen every time, the "challenge not accepted" is intermittent.

Current status is I have a UI but can't do anything seemingly useful with it. I tried adding two pubs with invite codes and these were seemingly accepted, and I have seen both listed in the UI, although on start-up just now I only see one (I assume the challenge error). But I have wait/progress icons on the left and on the right (under Write a public message - saying "Loading") which never stop.

Since I can't save a Profile, maybe all these issues are due to some local problem? Again for reference, here is the console output on start, and left for a few minutes:

```
npm start

> ssb-patchwork@3.6.6 start /home/mrh/src/scuttlebutt/patchwork
> electron index.js

Log level: notice
git-ssb is not installed, or not available in path
TypeError: Illegal invocation
    at Single._timeout (/home/mrh/src/scuttlebutt/patchwork/node_modules/async-single/proto.js:30:22)
    at Single.write (/home/mrh/src/scuttlebutt/patchwork/node_modules/async-single/proto.js:17:10)
    at write (/home/mrh/src/scuttlebutt/patchwork/node_modules/flumeview-reduce/inject.js:60:9)
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/flumeview-reduce/inject.js:134:15
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/throughs/map.js:19:9
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-cursor/cursor.js:32:13
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/aligned-block-file/blocks.js:72:11
    at get (/home/mrh/src/scuttlebutt/patchwork/node_modules/aligned-block-file/blocks.js:28:7)
CONNECT { host: 'ssb.rootsystems.nz',
  port: 8008,
  key: '@L+nPFTMUHWXuchOwuzT6Z8Ea8wD/Rtd7leVRxGaknVk=.ed25519',
  source: 'stored',
  announcers: 1,
  duration: null,
  stateChange: 1503329034003,
  client: true,
  ping: 
   { rtt: { mean: 2716, stdev: 0, count: 1, sum: 2716, sqsum: 7376656 },
     skew: { mean: 666, stdev: 0, count: 1, sum: 666, sqsum: 443556 } },
  failure: 0 }
CONNECT { host: '128.199.41.108',
  port: 8008,
  key: '@UZnDjmefaQo//6JcMNLlfzhXqPzO7Ktn3ZoXy2yVGz8=.ed25519',
  source: 'stored',
  announcers: 1,
  duration: 
   { mean: 39447.1,
     stdev: 98931.92701595376,
     count: 20,
     sum: 788942,
     sqsum: 226871997630 },
  stateChange: 1503329677750,
  client: true,
  ping: 
   { rtt: { mean: 377, stdev: 0, count: 1, sum: 377, sqsum: 142129 },
     skew: { mean: 66.5, stdev: 0, count: 1, sum: 66.5, sqsum: 4422.25 } },
  failure: 0 }
Connected 128.199.41.108:8008:@UZnDjmefaQo//6JcMNLlfzhXqPzO7Ktn3ZoXy2yVGz8=.ed25519
CONNECT { host: 'ssb.rootsystems.nz',
  port: 8008,
  key: '@L+nPFTMUHWXuchOwuzT6Z8Ea8wD/Rtd7leVRxGaknVk=.ed25519',
  source: 'stored',
  announcers: 2,
  duration: { mean: 0, stdev: 0, count: 1, sum: 0, sqsum: 0 },
  stateChange: 1503399180508,
  client: true,
  ping: 
   { rtt: { mean: 2716, stdev: 0, count: 1, sum: 2716, sqsum: 7376656 },
     skew: { mean: 666, stdev: 0, count: 1, sum: 666, sqsum: 443556 } },
  failure: 1,
  state: undefined,
  error: 'Error: challenge not accepted\n    at abort (/home/mrh/src/scuttlebutt/patchwork/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/home/mrh/src/scuttlebutt/patchwork/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/home/mrh/src/scuttlebutt/patchwork/node_modules/pull-reader/index.js:42:23)\n    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-reader/index.js:59:18\n    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-reader/index.js:20:7\n    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/throughs/through.js:19:9\n    at drain (/home/mrh/src/scuttlebutt/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/mrh/src/scuttlebutt/patchwork/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)' }
Connected ssb.rootsystems.nz:8008:@L+nPFTMUHWXuchOwuzT6Z8Ea8wD/Rtd7leVRxGaknVk=.ed25519
Disconnected ssb.rootsystems.nz:8008:@L+nPFTMUHWXuchOwuzT6Z8Ea8wD/Rtd7leVRxGaknVk=.ed25519
```

If I now try to create my profile (again), enter a name and short description, hit Publish, it just hangs (no further console output).

I'll probably leave this now. I just wanted to play really but thanks for your help. Scuttlebutt is an interesting project and shares some ground with SAFEnetwork (I heard of scuttlebutt on the SAFE forum). 

Off-topic: One thought I had is that porting ssb apps to use SAFE storage for the diaries would simplify some areas a lot and remove limits on device (one account per device) and reliance on pubs (which are vulnerable), although SAFE doesn't support mesh yet so you'd lose that. Best of both would be to use SAFE as one large pub that is decentralised and autonomous, and then fall back to mesh/wifi style when needed.

**Comment by mmckegg** [comment]
@theWebalyst the issue you encountered when trying to create a profile sounds a lot like a corrupt database. It can be fixed by deleting everything in `~/.ssb` and relaunching patchwork to start again. 

_By the way, if you had an identity you wanted to keep with existing posts, you could back up your `~/.ssb/secret` file, then delete your `~/.ssb` directory. Then after you have created a new identity (by relaunching patchwork) and followed yourself on the network (waiting for your old posts to download), swap your old `secret` file back in._

I think this might be related to https://github.com/ssbc/scuttlebot/issues/427 where the database could get randomly corrupted 😢 and then everything would break (naturally).

This issue has been fixed in the latest scuttlebot and will be included with the next release, but is currently on master!

---

I am going to leave this issue open as the title refers to no having a build that runs on older versions of debian. I'll leave this to @ahdinosaur to either resolve or close as he sees fit. 😺

**Comment by theWebalyst** [comment]
@mmckegg Thanks for the suggestion but it doesn't appear to be a corrupt database based on what you've suggested.

I just tried:
```
rm -rf ~/.ssb
./Patchwork-3.6.6-linux.AppImage
```

The symptoms remain as in the OP (blank window).

Then:
```
rm -rf ~/.ssb
cd patchwork
npm start
```
..gives me a UI and a popup to fill in for my profile. Again, same symptoms as reported above: 'Publish' hangs, or 'Cancel'. Then 'Join pub', paste invite: A pub is added but the invite dialog doesn't clear until I hit 'Cancel'. Clicking on the new pub it opens up and I get a wait symbol for... as long as I'm prepared to wait it seems :-). Console output at this point is:
```
npm start

> ssb-patchwork@3.6.6 start /home/mrh/src/scuttlebutt/patchwork
> electron index.js

Log level: notice
git-ssb is not installed, or not available in path
CONNECT net:ssb.exitsystemcall.com:8008~shs:gSb2Dt4qtUSIt0jV1yrugKPiBriKPIUFfYB574vWhrM=
Connected ssb.exitsystemcall.com:8008:@gSb2Dt4qtUSIt0jV1yrugKPiBriKPIUFfYB574vWhrM=.ed25519
TypeError: Illegal invocation
    at Single._timeout (/home/mrh/src/scuttlebutt/patchwork/node_modules/async-single/proto.js:30:22)
    at Single.write (/home/mrh/src/scuttlebutt/patchwork/node_modules/async-single/proto.js:17:10)
    at write (/home/mrh/src/scuttlebutt/patchwork/node_modules/flumeview-reduce/inject.js:60:9)
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/flumeview-reduce/inject.js:134:15
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-stream/throughs/map.js:19:9
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/pull-cursor/cursor.js:32:13
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/mrh/src/scuttlebutt/patchwork/node_modules/aligned-block-file/blocks.js:72:11
    at get (/home/mrh/src/scuttlebutt/patchwork/node_modules/aligned-block-file/blocks.js:28:7)
```

**Comment by mmckegg** [comment]
@theWebalyst Hmm, okay. It is definitely a problem accessing the database though.

Version 3.6.6 is quite old now, and had a lot of issues. Have you tried the latest release (3.7.1), or version from latest github master? Master rolls in the latest database updates that were supposed to stop the corruption issue, and it might solve your problem (looks the same as the error you get with a corrupt database).

I suggest trashing your `~/.ssb` directory again before trying the new version.

**Comment by theWebalyst** [comment]
@mmckegg Matt, thanks but seems the same with the app-image for 3.7.1 anyway. On first run it asks about setup, I respond Yes ... I get a blank window. Console output below.
```
$ rm -rf ~/.ssb
$ ./ssb-patchwork-3.7.1-linux-x86_64.AppImage 
installed: X-AppImage-BuildId=f3ff28c0-71be-11a7-0414-d9264c1eb09a image: X-AppImage-BuildId=59c4f8c0-a751-11a7-20b3-3328d3820a09
Log level: notice
git-ssb is not installed, or not available in path
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.pGHD4U)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_Bpjg3E/usr/bin/resources/app.asar/node_modules/@paulcbetts/spellchecker/lib/spellchecker.js:3:16)
    at Object.<anonymous> (/tmp/.mount_Bpjg3E/usr/bin/resources/app.asar/node_modules/@paulcbetts/spellchecker/lib/spellchecker.js:116:3)
```

**Comment by ahdinosaur** [comment]
>  seems the same with the app-image for 3.7.1

this error is back to the releases being built on too recent of a glib version. i'm tasked with solving that problem, for now you'll need to install manually.

**Comment by theWebalyst** [comment]
No problem, it isn't important for me (just responding to Matt).

**Comment by ahdinosaur** [comment]
hey @theWebalyst, can you try one of the latest [releases](https://github.com/ssbc/patchwork/releases)?

https://github.com/ssbc/patchwork/releases/download/v3.8.5/Patchwork-3.8.5-linux-x86_64.AppImage

---

context: @mmckegg has now setup all the native dependencies to be pre-built ([%ttOgSGxgXllkVagurGhx38qDxde2ukvVYipCgmcWggo=.sha256](https://viewer.scuttlebot.io/%25ttOgSGxgXllkVagurGhx38qDxde2ukvVYipCgmcWggo%3D.sha256)), which means he is now able to build for all versions on his Mac. i wonder if the AppImage being built for Linux now uses a compatible version of libc for older linux installs. cheeers!

**Comment by tmakarios** [comment]
The v3.8.5 AppImage works for me.  (Which is to say, I get more than a grey window now, but I haven't tried connecting to anyone yet.)

**Comment by theWebalyst** [comment]
I'm getting 'archive type not supported' for this image. Previous ones were fine.

**Comment by ahdinosaur** [comment]
@tmakarios what version of (Debian) Linux are you using?

---

@theWebalyst interesting! i wonder if under the hood, the new releases are being built with a different compression archive format, such as ["gz" | "bzip2" | "xz"](https://www.electron.build/configuration/linux), and you had the other format tools installed but not the new format. hmmm.

**Comment by mmckegg** [comment]
@ahdinosaur interesting. What a pain 😆 

Hmm, doesn't look like archive format is configurable for AppImage in electron-builder: https://www.electron.build/configuration/linux

**Comment by tmakarios** [comment]
I'm using Trisquel 7, which is based on Ubuntu 14.04 (Trusty).

**Comment by DanielHeath** [comment]
Running the .deb from the latest release gives me this error.
