### ISSUE TITLE
Add keyboard shortcuts for navigation

### ISSUE THREAD

**Issue by slinlee** [ssbc/patchwork#614]
I'd like to be able to navigate back/forwards, or in and out of threads with the keyboard.

There is tons of space for discussion for which conventions to use, but here's an example from browsers on Mac:

Back: cmd-left
Forwards: cmd-right

**Comment by mrchrisadams** [comment]
Okay, I've started on this #802.

If that gets merged in we'll at least have back and forward keyboard shortcuts.

If anyone is able to share some useful published guidance, in terms of idiomatic shortcuts for each platform, I'd be grateful, as I've just implemented what I've seen in well known applications, which more or less follow Apple's guidance about browser shortcuts in their [Human Interface Guidelines](https://developer.apple.com/macos/human-interface-guidelines/user-interaction/keyboard/).

**Comment by slinlee** [comment]
Thanks @mrchrisadams !
