### ISSUE TITLE
Make dat:// url clickable

### ISSUE THREAD

**Issue by slinlee** [ssbc/patchwork#616]
I'd love to be able to just click on the links like the https one.
-------- Screen shot Below --------
<img width="689" alt="screen shot 2017-08-25 at 5 18 37 pm" src="https://user-images.githubusercontent.com/1197406/29736816-b2b52c9e-89b9-11e7-8907-3a93ce433c6d.png">

**Comment by robjloranger** [comment]
Is this fixed with the pull request in `ssb-markdown`?

**Comment by christianbundy** [comment]
I think this would be solved by adding `protocols: ['http', 'https', 'dat']` [here](https://github.com/ssbc/patchcore/blob/master/message/html/markdown.js#L70).

**Comment by christianbundy** [comment]
Just tried this and it didn't work, looks like things have changed since https://github.com/ssbc/ssb-markdown/pull/20 was merged and now the protocols seem to be hardcoded again. Hmm.

**Comment by christianbundy** [comment]
This now works! Links like `dat://example.com` work perfectly, but hash links have to be encapsulated with `<` and `>` to avoid https://github.com/ssbc/ssb-markdown/issues/25. For example:

```md
<dat://fdc941b24e12cb84697e31304f27f4aeb4ff3b51e90bbf4c4853f5c0f5b047f0>
```
