### ISSUE TITLE
recording a gif does not show what you captured

### ISSUE THREAD

**Issue by nickdesaulniers** [ssbc/patchwork#63]
this is probably a symptom of a larger issue with recording an animated gif, but the UI changed to show a box, but that box was empty.  I suspect the footage being captured will be shown there? Also, the resulting gif seems broken: %xFjj3lZ1Oynxj+X4BLpirZFY5ZDEBbnrdoONACscVik=.sha256

**Comment by dominictarr** [comment]
@nickdesaulniers what OS are you on? This isn't as reliable as we would like on linux especially.

**Comment by nickdesaulniers** [comment]
osx 10.10.5

**Comment by dominictarr** [comment]
okay thanks. @pfraze

**Comment by pfraze** [comment]
Yeah, this is feature keeps breaking, sorry about that. I'll give it another look

**Comment by dominictarr** [comment]
also, it's worth noting that not many people really used it. it's a nice novelty, but apart from testing it out when they first install people havn't used it much... if we arn't really gonna develop or tune this feature prehaps we should drop it?

**Comment by pfraze** [comment]
I'd be pretty ok with dropping it.
