### ISSUE TITLE
Configurable on screen notifications

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#633]
There have been several issues/PRs posted in the past (#587 #512 #448) about including ssb-notifier in patchwork. However to get proper click through integration, I would prefer to roll this functionality directly in and make it configurable from the Settings page.

Anyone want to give this a go?

**Comment by dangerousbeans** [comment]
how about we have a simpler notify thing with no broken click through and just get toast notifications working again for now? I miss them :C
