### ISSUE TITLE
Need help in setting up a pub without renting server from Amazon or Linode

### ISSUE THREAD

**Issue by balogic** [ssbc/patchwork#635]
Hi,
I am a newbie and don't have much exposure to server hosting and other terms. I have followed [this](https://ssbc.github.io/docs/scuttlebot/howto-setup-a-pub.html) tutorial. But it says to rent a server on Amazon or Linode. I need to host this pub myself. Please help.

**Comment by olizilla** [comment]
@balogic can you give us any more info on what you'd like to achieve? It's totally fine to use patchwork without hosting your own pub. Anyone who follows you and is online at the same time as you will replicate and share your messages. A pub is just a follower that is more likely to be online all the time. 

Also there are a bunch of pubs out there that you could get an invite to (basically request to follow you) https://github.com/ssbc/scuttlebot/wiki/Pub-Servers

**Comment by balogic** [comment]
@olizilla I need to have a pub 24x7 running in my house irrespective of my own patchwork setup. By that way, others would connect to the pub and follow others in the pub and could recover data, even if someone lost data or is offline.

**Comment by olizilla** [comment]
Private messages are encrypted so no one but the intended recipients can read them. The pub cannot read them, it just stores and passes on messages, so I still recommend using any of the public pubs. 

As your group find and follow each other they will all be backing up each others messages, and if you all join the same set of pubs, you can be reasonably sure that your messages will be replicated across the network and available for you to sync when you've a connection.

This issue isn't really patchwork related, so maybe come ask on patchwork?

**Comment by balogic** [comment]
Sure. Thanks for the reply :slightly_smiling_face:
