### ISSUE TITLE
README: Update screenshot to show new themes

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#638]
Because they're awesome!

**Comment by christianbundy** [comment]
I'd love a new screenshot!

@matthiasbeyer how are other projects doing this sort of thing? I've always seen a relative link in the readme, but I'd love a cleaner solution.

**Comment by matthiasbeyer** [comment]
IMHO the cleanest solution is to host the image somewhere and include the image from the external domain. As said, binary blobs do not belong into git because git is very bad with binary data
