### ISSUE TITLE
rework: electron doesn't close properly (linux)

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#64]
the window just stays open but is frozen.
my hunch is that the OSX stuff may be related: https://github.com/ssbc/patchwork/pull/45

**Comment by pfraze** [comment]
how do you close it? the UI window stays open?

this may be related to an issue I've seen where a timer seems to stay active, or a task finishes before the process closes. I haven't had a chance to track it down, but on-wakeup is part of the problem for sure.

(We need to talk about on-wakeup, it's doing something pretty odd!)

**Comment by dominictarr** [comment]
Oh, now I think I may have done this wrong. Lets just leave this for now and if it doesn't continue to be a problem we can just close this.

**Comment by pfraze** [comment]
Is this still occuring?

**Comment by mmckegg** [comment]
Should be fixed now. On non-darwin platforms, the app is explicitly exited on main window close.
