### ISSUE TITLE
Cannot download any messages

### ISSUE THREAD

**Issue by cameralibre** [ssbc/patchwork#641]
Something went wrong while trying to post a message, so after a few minutes of waiting, I closed the application. 

Upon re-opening Patchwork, it gets stuck trying to download messages. 
![patchwork stuck](https://user-images.githubusercontent.com/15368010/31223070-6fa0aeee-a9c9-11e7-8705-7e05dd934d52.png)

Even on my profile page it fails to find my alias, profile pic etc.
![profile](https://user-images.githubusercontent.com/15368010/31223101-8649831e-a9c9-11e7-834c-cb157f9f3dbf.png)

Version: ssb-patchwork-3.7.1
OS: Solus 3

![3-6-6](https://user-images.githubusercontent.com/15368010/31229532-53a67e0e-a9e1-11e7-952f-f8a9fe703b25.png)

(same issue with 3.6.6)

**Comment by cameralibre** [comment]
my issue was solved by replacing my .ssb directory with a backup from a couple of weeks ago, but I still have the borked .ssb directory if there is anything I can share to help work out what caused this.

**Comment by mmckegg** [comment]
Looks like something very bad happened to your database.

Would be interesting to see if any errors were being thrown. If you right click on patchwork and select "Inspect Server Process" and then go to the "Console" tab it will display the errors. 

They will also be displayed in the terminal if you start patchwork from there.

**Comment by cameralibre** [comment]
Sure thing - here's the terminal output, I don't know which parts are relevant for you or whether there's any personal info there, so I just removed anything called 'key':

`ssb-patchwork-3.7.1-linux-x86_64.AppImage `
`installed: X-AppImage-BuildId=59c4f8c0-a751-11a7-20b3-3328d3820a09 image: X-AppImage-BuildId=59c4f8c0-a751-11a7-20b3-3328d3820a09`
`Log level: notice`
`git-ssb is not installed, or not available in path`
`Error: when trying to retrive:type,pub,1507186087955at since:141558473`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumeview-level/index.js:125:26`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumelog-offset/inject.js:57:17`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumelog-offset/frame/recoverable.js:32:22`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/blocks.js:91:26`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/blocks.js:37:36`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/file.js:27:18`
`  Error: aligned-block-file/file.get: requested block index was greater than max, got:8643, expected less than or equal to:8640`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/file.js:27:21`
`    at Function.many.once (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/node_modules/obv/index.js:38:49)`
`    at Object.get (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/file.js:24:14)`
`    at get (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/blocks.js:33:12)`
`    at Object.readUInt32BE (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/aligned-block-file/blocks.js:90:9)`
`    at Object.getMeta (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumelog-offset/frame/recoverable.js:31:12)`
`    at Object.get (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumelog-offset/inject.js:56:13)`
`    at Object.get (/tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumedb/index.js:29:10)`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/flumeview-level/index.js:124:17`
`    at /tmp/.mount_WWfBun/usr/bin/resources/app.asar/node_modules/pull-paramap/index.js:41:11`
`CONNECT { host: 'ssb.the-travel-agency.net',`
`  port: 8008,`
`  key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',`
`  source: 'stored',`
`  announcers: 3,`
`  duration: `
`   { mean: 4093.637931034483,`
`     stdev: 15390.039966225218,`
`     count: 58,`
`     sum: 237431,`
`     sqsum: 14709449697 },`
`  stateChange: 1507201876700,`
`  client: true,`
`  ping: `
`   { rtt: { mean: 2752, stdev: 0, count: 1, sum: 2752, sqsum: 7573504 },`
`     skew: { mean: 1000, stdev: 0, count: 1, sum: 1000, sqsum: 1000000 } },`
`  failure: 6,`
`  error: 'Error: challenge not accepted\n    at abort (/tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/pull-reader/index.js:42:23)\n    at /tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/pull-reader/index.js:59:18\n    at /tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/pull-reader/index.js:20:7\n    at /tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/pull-stream/throughs/through.js:19:9\n    at drain (/tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/tmp/.mount_iLuxzx/usr/bin/resources/app.asar/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)' }`
`CONNECT { host: 'pub.tshirt.horse',`
`  port: 8008,`
`  key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',`
`  source: 'stored',`
`  announcers: 14,`
`  duration: `
`   { mean: 144918.52777777778,`
`     stdev: 267625.74382080307,`
`     count: 36,`
`     sum: 5217067,`
`     sqsum: 3334497064161 },`
`  stateChange: 1507201884330,`
`  failure: 0,`
`  client: true,`
`  ping: `
`   { rtt: { mean: 1099, stdev: 0, count: 1, sum: 1099, sqsum: 1207801 },`
`     skew: { mean: 304.5, stdev: 0, count: 1, sum: 304.5, sqsum: 92720.25 } } }`
`Connected pub.tshirt.horse:8008:@s4shurQwrASqNj2LunBOB24r2/ubNOjn0+5EBz8CNBo=.ed25519`
`skip gossip`
`CONNECT { host: 'ssb.kamp.site',`
`  port: 8008,`
`  key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',`
`  source: 'stored',`
`  announcers: 1,`
`  duration: { mean: 0, stdev: 0, count: 20, sum: 0, sqsum: 0 },`
`  stateChange: 1507201943317,`
`  client: true,`
`  ping: `
`   { rtt: { mean: 1, stdev: 0, count: 1, sum: 1, sqsum: 1 },`
`     skew: { mean: -225.5, stdev: 0, count: 1, sum: -225.5, sqsum: 50850.25 } },`
`  failure: 20,`
`  error: 'Error: connect ECONNREFUSED 158.69.48.74:8008\n    at Object.exports._errnoException (util.js:1022:11)\n    at exports._exceptionWithHostPort (util.js:1045:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)' }`
`CONNECT { host: 'ssb.hypersignal.xyz',`
`  port: 8008,`
`  key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',`
`  source: 'stored',`
`  announcers: 149,`
`  duration: `
`   { mean: 42257.338461538464,`
`     stdev: 82010.98589790871,`
`     count: 65,`
`     sum: 2746727,`
`     sqsum: 553246490017 },`
`  stateChange: 1507201986991,`
`  client: true,`
`  ping: `
`   { rtt: { mean: 1907, stdev: 0, count: 1, sum: 1907, sqsum: 3636649 },`
`     skew: { mean: -613.5, stdev: 0, count: 1, sum: -613.5, sqsum: 376382.25 } },`
`  failure: 0 }`
`Connected ssb.hypersignal.xyz:8008:@XRg7pXoQqsWDDk4dmgvSWHUqzwS6BmqMo4IdbMKPjWA=.ed25519`
`CONNECT { host: 'pub.hacky.af',`
`  port: 30434,`
`  key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',`
`  source: 'stored',`
`  announcers: 31,`
`  duration: `
`   { mean: 135800.87179487178,`
`     stdev: 285488.5153682871,`
`     count: 39,`
`     sum: 5296234,`
`     sqsum: 3897877198310 },`
`  stateChange: 1507202002707,`
`  client: true,`
`  ping: `
`   { rtt: { mean: 2453, stdev: 0, count: 1, sum: 2453, sqsum: 6017209 },`
`     skew: `
`      { mean: -1018.5,`
`        stdev: 0,`
`        count: 1,`
`        sum: -1018.5,`
`        sqsum: 1037342.25 } },`
`  failure: 3,`
`  error: 'Error: getaddrinfo EAI_AGAIN pub.hacky.af:30434\n    at Object.exports._errnoException (util.js:1022:11)\n    at errnoException (dns.js:33:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)' }`
`Connected pub.hacky.af:30434:@VqbBx7dr72FQwO5ztq4FULpareSMFSwegY1Ruh7XpjA=.ed25519`
`skip gossip`
`Disconnected pub.tshirt.horse:8008:@s4shurQwrASqNj2LunBOB24r2/ubNOjn0+5EBz8CNBo=.ed25519`
`skip gossip`

**Comment by mmckegg** [comment]
This bug was recently fixed in sbot: https://github.com/ssbc/scuttlebot/issues/427

It seems like it could very likely be what caused your issue here! Hopefully this is last we see of it.

Closing this issue, but feel free to reopen if this happens again!
