### ISSUE TITLE
Unable to build on macOS High Sierra

### ISSUE THREAD

**Issue by alanshaw** [ssbc/patchwork#645]
I'm running into this issue when building on macOS right now:
https://github.com/electron-userland/electron-spellchecker/issues/96

Hopefully it'll be fixed soon without any need for changes to patchwork, but until then if you need to build the project you can change the `electron-spellchecker` dependency version to `1.1.2`.

**Comment by mmckegg** [comment]
@alanshaw Does trashing `node_modules` and running `npm install` also solve the issue?

**Comment by alanshaw** [comment]
🙄 sorry, npm had dropped a `package-lock.json` in the project so I was just getting the same old version each time, this is not because of the v1.2.0 version that was published (this doesn't matter because the "latest" version in npm is set to c1.1.2)...non issue, please ignore.
