### ISSUE TITLE
add offline mode

### ISSUE THREAD

**Issue by spaceywolfi** [ssbc/patchwork#646]
would be cool if i there was a setting to use patchwork in offline mode

**Comment by Happy0** [comment]
@spaceywolfi do you mean that you'd open patchwork, but it wouldn't connect to any peers and download any new messages from them? :)

What's your use case for this? To save bandwidth in certain situations, etc?

**Comment by spaceywolfi** [comment]
yes thats what i mean :)
my use case is when i have very limited mobile data (max 100mb per month) and do not want to disable my wifi network before starting patchwork to look at messages that i have downloaded previously.

**Comment by Happy0** [comment]
Makes sense.

I wonder if there's a way we could get patchwork to gossip only over the local network :o

**Comment by mmckegg** [comment]
> I wonder if there's a way we could get patchwork to gossip only over the local network :o

Yep this is all possible in sbot! Just need to expose the options in patchwork's interface somewhere!

**Comment by dominictarr** [comment]
we could do this my temporarily changing the config, if we made sure the the relavant things always checked the config object directly instead of getting the value one time and remembering it. This wouldn't be that hard and would work for this case.

**Comment by voronoipotato** [comment]
stale bot what have you done.

**Comment by voronoipotato** [comment]
thank you christian :)

Okay so what is needed to get this done? Someone said that there's a config that would allow for this?

**Comment by voronoipotato** [comment]
I saw that you said you began working on this, I didn't mean to create more work for you but rather to maybe try to offer some help :).

**Comment by christianbundy** [comment]
Sorry, to be specific I was working on taming stale[bot] to ensure that issues like this don't get closed so quickly (or at all, if folks are interested in resolving them). I haven't spent time on resolving this specific issue, sorry for the ambiguity!

**Comment by voronoipotato** [comment]
It's okay :). I just wanted to make sure I wasn't bullying you by accident.
