### ISSUE TITLE
rework: flag/unflag

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#65]
I created a new account, made a post, flagged it, then unflagged it.

But if I went back to the main feed this message was still shown as flagged.
If I restarted patchwork it is shown correctly, but not if I simply switch back to the feed view.

**Comment by dominictarr** [comment]
with another flag added so it shows as flagged, I switched to my own account, and viewed the feed. Since the new account is followed by my pub I had it replicated but it was shown and not flagged. I think this surely should have been flagged. It was flagged by the account that posted the message, who was friend of a friend (via an autofollow).

My connection to that user as a flagger shouldalbe as close as my connection as a flagger... So theirfore it should accept the flag. Also, logged in as my self it didn't show anything about whether that was flagged.

**Comment by pfraze** [comment]
> I created a new account, made a post, flagged it, then unflagged it.

> But if I went back to the main feed this message was still shown as flagged.
If I restarted patchwork it is shown correctly, but not if I simply switch back to the feed view.

That's a bug, will look into it.

> I think this surely should have been flagged. It was flagged by the account that posted the message, who was friend of a friend (via an autofollow).

Ok, I think that's the right behavior for now.

**Comment by pfraze** [comment]
#81 and #82 together solve this.
