### ISSUE TITLE
Sidebar scrollbar persists over content

### ISSUE THREAD

**Issue by mathias** [ssbc/patchwork#652]
It looks a little funky. Here it is (also happens over individuals' posts, but I figured I wouldn't screenshot those):

![screen shot 2017-10-16 at 9 20 48 pm](https://user-images.githubusercontent.com/3340/31643744-f3cbf344-b2b7-11e7-9e56-bfc3c2ae7141.png)

![screen shot 2017-10-16 at 9 20 10 pm](https://user-images.githubusercontent.com/3340/31643752-fb8f2c2c-b2b7-11e7-9fb7-da5c3ab25e97.png)

**Comment by mmckegg** [comment]
@mathias weird! Never seen this before. Do you have scrollbars set to always display by any chance?

Just tried that myself and cannot reproduce. What version of macOS are you running?

**Comment by mathias** [comment]
OSX 10.12.6, no setting for scrollbars set to always display afaik. I did resize the app with my window management keybindings after it opened, and I can see the width of the sidebar changes when I drag the width of the window, but the scrollbar never goes away.

**Comment by phivk** [comment]
I encountered the same issue running Patchwork 3.7.1 on OSX 10.12.6, while starting Patchwork for the first time:

![patchwork changing channel names](https://user-images.githubusercontent.com/902958/32487599-698b8858-c3aa-11e7-9087-f83b0ec0ac76.gif)

Now I am no longer able to reproduce it...
I use a window manager called [Spectacle](https://www.spectacleapp.com/), not sure if that could be related...
