### ISSUE TITLE
An easy way to scroll back to the top

### ISSUE THREAD

**Issue by olpeh** [ssbc/patchwork#653]
Hi. I really love patchwork and I'm using it every day :+1: 

One thing I find confusing and a bit irritating is that there is no easy way to scroll back to the top of the page. I think a natural place for that would be that clicking the public link on the top would scroll to the top if the user is already on that page. Would that make sense? Same feature could be added for the private link also?

**Comment by mmckegg** [comment]
@olpeh,

> clicking the public link on the top would scroll to the top if the user is already on that page

This is a good idea. Will implement this in the next release!

**Comment by olpeh** [comment]
Thank you! It works :+1:
