### ISSUE TITLE
kdialog args cause AppRun exit

### ISSUE THREAD

**Issue by rhetr** [ssbc/patchwork#657]
I'm trying to run [3.7.1](https://github.com/ssbc/patchwork/releases/download/v3.7.1/ssb-patchwork-3.7.1-linux-x86_64.AppImage) on KDE neon but I don't see the KDialog asking if I want patchwork to be "installed" locally. I took at look inside the AppImage using and found that `kdialog` is being passed invalid arguments in `/AppRun` on line 81:
```
...
LD_LIBRARY_PATH="" kdialog --caption "Disk auswerfen?" --title "$TITLE" -yesno "$TEXT" || exit 0
...
```
`--caption` is deprecated as referenced [here](https://www.linuxquestions.org/questions/slackware-14/kdialog-caption-option-4175609186/) and `-yesno` should be `--yesno`. This explains the stderr output as well:
```
Unknown options: caption, y, e, s, n, o.
```

I'd submit a PR but I don't know where the appimage stuff is in the repository (nor do I know how to package things in general)!

update: I tested the [3.8.0 prerelease](https://github.com/ssbc/patchwork/releases/download/v3.8.0/Patchwork-3.8.0-x86_64.AppImage) too, it doesn't look like this has been fixed here either.

**Comment by mmckegg** [comment]
Hey @rhetr,

Thanks for reporting! The appimage is created using https://github.com/electron-userland/electron-builder so I guess that the bug is in there somewhere.

This looks promising:

https://github.com/electron-userland/electron-builder/blob/247c18af95d165ebdb6c434f7765493a9ad6b4a7/packages/electron-builder/templates/linux/AppRun.sh

**Comment by rhetr** [comment]
Ok, I'll open up an issue over there

**Comment by rhetr** [comment]
Electron-builder pushed [this](https://github.com/develar/electron-builder/commit/0ee8779b7422588d263a07034afa66ab021ae14b) commit which should fix the issue.

**Comment by mmckegg** [comment]
Awesome, thanks @rhetr. Will build the next version using the latest `electron-builder`.
