### ISSUE TITLE
rework: user blocking

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#66]
This doesn't work with the ui rework because the message type has changed and the backend handles another message type.

**Comment by pfraze** [comment]
Are you sure? I believe the rework publishes a type: contact with blocking: true, in addition to a type: vote with a value: -1

**Comment by dominictarr** [comment]
ah that is correct. I did see a block message. but it doesn't seem to actually be blocking it... hmm, maybe this is because the pub servers are old and don't have the blocking code?

**Comment by pfraze** [comment]
> hmm, maybe this is because the pub servers are old and don't have the blocking code?

yikes, that's a scary thought

**Comment by dominictarr** [comment]
and since there are lots of pub servers one would be enough.

**Comment by mmckegg** [comment]
Probably fine now? Closing.
