### ISSUE TITLE
UI: ordering of active channels keeps changing, making it hard to click subscribe

### ISSUE THREAD

**Issue by phivk** [ssbc/patchwork#667]
I'm running Patchwork 3.7.1 on OSX 10.12.6
Active Channels get continuously reordered in the UI panel on the left side bar as wel as in the full-screen "More Channels..." view:

![patchwork changing channel names](https://user-images.githubusercontent.com/902958/32484554-8c35a2c6-c3a0-11e7-9314-ce1096573f12.gif)

this makes clicking the "Subscribe" button on one of these channels near impossible. A workaround I used is to search for the channel name I want to click, but that shouldnt be necessary...

#552 mentions that channels are ordered by latest post. I think it's good to communicate this info, but probably not by affecting the ordering so directly.

**Comment by mmckegg** [comment]
@phivk It only does this when you are still onboarding and downloading new messages. The rest of the time it doesn't change very often.

But, the way it behaves isn't very helpful now that the network is growing. Active channels should probably be weighted by recent posts / amount of posts, so they act more like trends. This is definitely something I'd like input about and happy to discuss!

**Comment by mmckegg** [comment]
Oh I do see that there is an extra scrollbar appearing over the content that shouldn't be there though. That is a bug that I haven't been able to reproduce: #652 

I would be interested if it is still there after restarting, onboarding has finished.

**Comment by phivk** [comment]
@mmckegg you are right, now that messages have finished updating the channels ordering no longer changes 👍 

> But, the way it behaves isn't very helpful now that the network is growing. Active channels should probably be weighted by recent posts / amount of posts, so they act more like trends. This is definitely something I'd like input about and happy to discuss!

I agree that it would be good to have a more static ordering of channels during the 'updating state'. A quick fix - which would improve things massively already - would be to simply sort alphabetically by name.

More long term I could imagine a UI component that lets users choose how they want to sort channels, e.g. by name, number of subscribers, last active, number of messages, etc. This could be a simple dropdown on the top of the "More channels..." view. I believe it could work for both 'updating' and 'finished updating' states.
