### ISSUE TITLE
rework: the left-hand menu makes scroll a bit weird

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#67]
if you are moused over the left hand menu area, then trackpad scroll doesn't work because you are not on the movable part. However, this area extends all the way down to the bottom of the screen, and doesn't have any clear barrier (it has the same color background as the main part of the page)

Maybe if the left-hand menu was floating with position: fixed or had mouse events disabled then you could keep it in place but also not effect scrolling.

**Comment by pfraze** [comment]
ok, I'll give this some thought

**Comment by pfraze** [comment]
Removed, in part for this reason!
