### ISSUE TITLE
How can I restore my profile?

### ISSUE THREAD

**Issue by creationix** [ssbc/patchwork#674]
I'm trying to follow @mmckegg's instructions from https://github.com/ssbc/patchwork/issues/529#issuecomment-304741060

But for the last part:

> - replace ~/.ssb/secret with your original backed up secret file.
> - Relaunch patchwork. You should be "you" again!

My profile is still the new empty profile.  I can see my old posts so I know my old data synced, but I'm not me yet.

Any ideas?

**Comment by creationix** [comment]
I'm on Version 3.7.1 on OSX if that helps any.

**Comment by creationix** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/89353/32962005-678ffba4-cb90-11e7-84d9-ae36b06bb488.png">

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/89353/32962031-7f691a30-cb90-11e7-9ad6-26ebb940caf5.png">

**Comment by creationix** [comment]
Hmm, I followed pub.lua.cz (a pub I was using before, but who's invite code seems broken) and it triggered a lot more data downloads, waiting for sync to finish...

**Comment by cryptix** [comment]
Hmm.. the instructions to restore could be better.

When you restore from the `secret` file alone, the `sbot server` (either standalone or embedded in patchwork) won't connect to any peers until you tell it to do so since there is no persisted `gossip.json` in `$HOME/.ssb` yet it simply doesn't know where to connect.

If you use an invite for a pub you already used the pub will respond with `already following` which is an _error_ but could just be a warning, I think.

Another way to re-sync with the network is to use `sbot gossip.connect pub.ip:port:@pubkey.ed25519` but it would be nicer to not have to use the command line for this.

**Comment by creationix** [comment]
I've got my old `gossip.json` and `manifest.json` backed up as well, but restoring those doesn't seem to help.

**Comment by creationix** [comment]
My gossip file does have some strange errors in it that may be causing some of the trouble.

```json
[
   {
      "host":"pub.lua.cz",
      "port":8008,
      "key":"@xYSW6eVu8gTS/nTSXZiH97dgKZ+wp7NkomR6WKK/PBI=.ed25519",
      "source":"stored",
      "announcers":2,
      "duration":{
         "mean":0,
         "stdev":0,
         "count":17,
         "sum":0,
         "sqsum":0
      },
      "stateChange":1511197173766,
      "error":"Error: connect ECONNREFUSED 81.201.60.131:8008\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)",
      "failure":17
   },
   {
      "host":"pub.creationix.com",
      "port":8008,
      "key":"@uII4xYkFzuoAYz4Qg+ZC4OoT7lp6cGnM4zR3XRFEHTU=.ed25519",
      "source":"stored",
      "announcers":8,
      "duration":{
         "mean":176679.45454545456,
         "stdev":446693.7910046054,
         "count":11,
         "sum":1943474,
         "sqsum":2538260698386
      },
      "stateChange":1511197210473,
      "client":true,
      "ping":{
         "rtt":{
            "mean":527,
            "stdev":24.91318258807345,
            "count":3,
            "sum":1581,
            "sqsum":835049
         },
         "skew":{
            "mean":97.83333333333333,
            "stdev":23.188838311183776,
            "count":3,
            "sum":293.5,
            "sqsum":30327.25
         }
      },
      "failure":7,
      "error":"Error: connect ECONNREFUSED 165.227.3.194:8008\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)"
   }
]
```

(PS, I'm assuming these are public keys since they are only 32 bytes and it would make sense they are public keys.  So here's hoping I'm not posting secret keys on github)

**Comment by creationix** [comment]
Both of these pubs seem to be down.  I'm pretty sure mine is gone, the lua one shows a webpage with the reusable invite code, but it's not usable in patchwork.

**Comment by mmckegg** [comment]
@creationix 

> My profile is still the new empty profile. I can see my old posts so I know my old data synced, but I'm not me yet.

Try comparing the public key on your old account with the file at `~/.ssb/secret`. If it is different, then verify that you have actually restored your key correctly from backup.

If the backup key doesn't match either, then you must be somehow using the wrong backup. If the secret file does match your old profile's public key, and you have restarted patchwork and it still isn't working, there must be ghosts in your machine 👻 ... only possible explanation 🤣 

The public key for a profile is much easier to find in Patchwork 3.8.0 (displayed at the top of the profile), but can be found in older versions by right clicking on their name at the top of a post and selecting "Copy ref".

**Comment by creationix** [comment]
You're right.  I had a backup of an empty profile.  Silly me.

I did find a backup of an older profile.  Not the one I was looking for, but it's something.

I was trying to restore @gHHJtga9a/r3tpoGuRgbLrBtoZbhBpHTYAvSqRwfmf4=.ed25519, but I think that secret key is gone.  Last access 6 months ago.

I was able to restore another from 3 months ago!
@yEaK9okGIxoentGzOtN0QydDdn902lypmJkGh4j2paU=.ed25519

**Comment by ninabreznik** [comment]
Oh yes, I now replaced a new `~/.ssb/` folder with my backed up one and it worked. So, replacing only `secret` file didn't, but replacing the whole folder content with the old one did the trick!

**Comment by mmckegg** [comment]
@ninabreznik you need a little bit more than the secret file. Usually also copying the gossip.json file is enough. But yes, as you discovered, just copying everything works very well too!

**Comment by stephenreid321** [comment]
Hi all! I just have my ~/.ssb/secret file, no gossip.json - any tips on how I can get my profile back?

**Comment by christianbundy** [comment]
@stephenreid321 Do you have `conn.json`? That's the new version of gossip.json.

**Comment by christianbundy** [comment]
Also, could you make a new issue please? I don't want to keep sending notifications to everyone in this thread. :~)
