### ISSUE TITLE
Profile View - public key breaks layout when zooming in or increasing font size

### ISSUE THREAD

**Issue by robjloranger** [ssbc/patchwork#680]
when zooming text size with `ctrl+shift+=` or just setting the base font size higher, the UI starts to break. The user hover flyouts break layout, the user profile picture shrinks down tiny.

Double checked on 3.7.1 and nothing seems to break under similar conditions.

**Comment by robjloranger** [comment]
![screenshot from 2017-11-24 19-53-03](https://user-images.githubusercontent.com/13278126/33227124-3e0e35d6-d151-11e7-827a-b51b222eef3c.png)
![screenshot from 2017-11-24 19-53-43](https://user-images.githubusercontent.com/13278126/33227125-3e25d650-d151-11e7-8b7e-4d0d73ca8a4a.png)

**Comment by robjloranger** [comment]
Narrowed it down, it's the addition of the `publicKey` element. It can't wrap so it pushes everything else around. Maybe it should be a flyout/tooltip over the users name?

**Comment by mmckegg** [comment]
I want to make it easy for people to copy and paste the public key. There was always the right-click option, but no one could find it. Maybe its font-size could be fixed `px` rather than relative? We could also add a [text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) to it. It would still be copy and pastable, but wouldn't break the layout.

**Comment by robjloranger** [comment]
What about a copy to clipboard button? Maybe not as discoverable.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mmckegg** [comment]
@robjloranger hmm, maybe. 

I just tried using `text-overflow` on the public keys, and it does seem to fix the problem! I pushed it to master, see how it works with the font-size changes.

**Comment by mmckegg** [comment]
@robjloranger  Actually, I think we can call this fixed now! I'm going to close it. Let me know if you find anything else that breaks like this.
