### ISSUE TITLE
TypeError: Cannot read property 'content' of null

### ISSUE THREAD

**Issue by joeyh** [ssbc/patchwork#682]
Patchwork says it is "Scuttling" and "Loading" and never displays any content.

    TypeError: Cannot read property 'content' of null
    at /tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/patchcore/message/async/name.js:27:23
    at /tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/patchcore/sbot.js:147:15
    at Object._requests.(anonymous function) (/tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/packet-stream/index.js:151:26)
    at PacketStream.write (/tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/packet-stream/index.js:134:41)
    at /tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/tmp/.mount_patchwRJm44X/app/resources/app.asar/node_modules/pull-reader/index.js:39:14)

This is occurring with both v3.8.0 and v3.7.1 from the appimage.

I have tried rebuilding the flume db, as well as restoring .ssb from a couple week old backup. The former didn't help at all; the latter allows browsing some messages until it downloads most of them, and then it gets stuck in the same way again. 

I fear this is a network communnications bug, or a bad message causing the crash..

**Comment by mmckegg** [comment]
Yeah, it's a rogue message breaking rendering. Those clients will never be able to scroll past that point in the feed ever again 😢 

Just pushing out a v3.8.1 pre-release that rolls in @arj03's [fix](https://github.com/ssbc/patchcore/pull/45) for this.

**Comment by mmckegg** [comment]
@ahdinosaur 

Any chance you can build this for Linux? https://github.com/ssbc/patchwork/releases/tag/v3.8.1

I had to update electron-builder to get this working. Not sure if you will also have to.

**Comment by bhaugen** [comment]
I had this problem earlier today on v3.8.0 , but I was ok for awhile today if I never scrolled down to the bad message, but now I am dead again. I think a new bad message. So the bad messages keep coming. Same TypeError as above.

**Comment by bhaugen** [comment]
Now using Patchwork-3.8.1-x86_64.AppImage - lookin good! Problem seems to be solved. Thanks, gang!
