### ISSUE TITLE
Windows builds are two versions out of date

### ISSUE THREAD

**Issue by interfect** [ssbc/patchwork#684]
Neither v3.8.0 nor v3.8.1 has a Windows build. Do Windows users not need the "emergency release" fixes in 3.8.1? Has something gone wring with the Windows build process?

**Comment by interfect** [comment]
I'm kind of stuck on #682.

**Comment by mmckegg** [comment]
Yeah, I broke my windows build system. Hopefully get it sorted in the next day!

**Comment by mmckegg** [comment]
@interfect 

Windows build is now up! https://github.com/ssbc/patchwork/releases
