### ISSUE TITLE
Allow patchwork to be installed as an sbot plugin

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#686]
`sbot plugins.install ssb-patchwork`

At the very least this should load patchwork/sbot.

Other things we could do to make this better:
- use ssb-ws for blobs instead of the custom patchwork server (more compat with other clients)
- sbot could serve browserified patchwork bundle so patchwork could be used in the browser (related to https://github.com/ssbc/ssb-ws/pull/8)

A browserified patchwork would not be _too_ difficult. Just need to shim out the menus (right click, more) and electron dialogs.

cc @cryptix

**Comment by cryptix** [comment]
I'm not even sure I want to go this far. My main complaint was the need for forked embedded plugins but very glad to see this.

**Comment by cryptix** [comment]
Just to get this a bit rolling again: the idea is to turn the current [sbot folder](https://github.com/ssbc/patchwork/tree/master/sbot) in this repo into it's own npm package, right?

**Comment by cryptix** [comment]
I'd say we keep this open but I don't have anything actionable to add right now...

**Comment by mmckegg** [comment]
@cryptix my idea was to run patchwork itself as an sbot plugin so that we could ensure that the plugin and client versions matched.
