### ISSUE TITLE
private replies I wrote do not appear in my Private tab until I reload Patchwork

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#688]
This has happened three times today. This seems to apply only to replies to private messages, not new PMs. 

Also, I @mentioned Lynn Foster in one private reply, and she can't see it in her Private tab, even after she reloaded, but this might be a different issue. The private thread did not include her at first, I only mentioned her in a reply to another message in the thread.

**Comment by mmckegg** [comment]
@bhaugen 

This is also fixed in the latest build 3.8.2.

No linux version yet. This week I want to work on improving the build system so that we can easily push out for all platforms with a single build script. I lost my linux machine, so lately I've been getting @ahdinosaur to build them.

**Comment by bhaugen** [comment]
@mmckegg thanks for the response. I try never to be in a hurry. When it's ready...

**Comment by mmckegg** [comment]
@bhaugen I pushed out some experimental 3.8.3 builds today (built the AppImage from my mac): https://github.com/ssbc/patchwork/releases

Can you give that a try and see if it works?

**Comment by bhaugen** [comment]
@mmckegg looks good so far! Thanks!

**Comment by mmckegg** [comment]
Awesome! Closing :)
