### ISSUE TITLE
Is there a way to export posts?

### ISSUE THREAD

**Issue by schollz** [ssbc/patchwork#689]
I'd like to backup just my personal posts (e.g. in Markdown + Images) instead of just tar.gz-ing the whole .ssb directory to make backups. Is it possible to dump the data this way?

**Comment by cryptix** [comment]
not in the current ui at least.

depending on how well you can script, you can extrat your feed (or others) from the database using `sbot createUserStream --id "@yourPubKey.ed25519" > myFeed.json` and filtering out the `type:post` messages with something like `jq  'select(.value.content.type == "post")' myFeed.json`. The Images are linked to by the `mentions: [ ... ]` blocks and can be fetched with `sbot blobs.get "&hash.sha256"`.

**Comment by schollz** [comment]
Thanks, that works for me!
