### ISSUE TITLE
Can't connect to SSB

### ISSUE THREAD

**Issue by luandro** [ssbc/patchwork#690]
Hey, this is my first issue here, so I'm sorry if this isn't specific to Patchwork.

Since I've started using other clients, Patchbay and Patchfoo, all clients have slowly stopped working. First Patchwork, than Patchfoo and finally Patchbay.

Using Patchwork 3.8.3 I get this:
```
image: X-AppImage-BuildId=85eb16b0-de3c-11a7-3e78-a72dfba98991
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  path: '/home/diego/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KH##########################################YRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 7777,
  server: true,
  plugins: { patchfoo: true },
  _: [],
  configs: [ '/home/diego/.ssb/config' ],
  config: '/home/diego/.ssb/config' }
Log level: notice
git-ssb is not installed, or not available in path
RELOAD 2 174092891
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
RELOADED 174092891
Error {}
```

Then it just keeps printing ` Error {}` until it throws a `RangeError: Maximum call stack size exceeded`. Did different clients conflict with each other? Should I delete all my files and start over?

**Comment by luandro** [comment]
Patchwork is working besides the errors. Just taking a really really long time to index everything.

**Comment by cryptix** [comment]
Hi @luandro!

Sad to hear that your clients deteriorated like that... 

The logging is currently very verbose and intimidating. Everything before `Log level: notice` is the current sbot configuration and even though the `shs` key is technically a _shared secret_, unless you change it to yourself to use a more clandestine network, it is okay to share. For reference: The default one is hard-coded into sbot [here](https://github.com/ssbc/scuttlebot/blob/master/lib/ssb-cap.js#L5).

That empty `Error {}` is indeed weird, though... Not sure how to dig deeper into that one.
