### ISSUE TITLE
Feature request: Opt-in Tree-like message view?

### ISSUE THREAD

**Issue by matthiasbeyer** [ssbc/patchwork#691]
I'd love to have some tree-like message view (think reddit) option, where I can hide some sub-trees if I want.

From what I understand, replies are not globally (as in "reply to this thread") but locally (as in "reply to this message of the thread"). Hence it would be nice to have a tree-view of a thread, where one is able to hide sub-trees.

This is mostly a UI feature, from what I see.

**Comment by mmckegg** [comment]
This is definitely something I’m considering. 

I believe that @mixmix has been experimenting with this.

**Comment by mixmix** [comment]
I want to make hermes-post as a helper module to make posting and rendering
easy

**Comment by christianbundy** [comment]
@mmckegg Should this have been labeled "discussion"?

**Comment by mmckegg** [comment]
With the new "fork" attribute added to patchwork recently (and also patchbay??), this should now be possible to do, but I don't know how it fits in with the existing views. 

Maybe this could be an option on the _thread view_? But the problem of realtime updating becomes less trivial. Right now, we can just append new messages to the bottom of the thread.

Yeah, @christianbundy definitely needs some discussion.

**Comment by mixmix** [comment]
Fork is different than nested tree to me.
But that's just me maybe
