### ISSUE TITLE
what happened to gatherings?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#692]
I'm investigating all the ways that plugins are used in the patch-* ecosystem, and I noticed that patchwork isn't using gatherings - but I remembered that it was previously - and there is a module for it: https://www.npmjs.com/package/patchwork-gatherings

I am curious as to the story about removing it..? I thought that it was fairly popular?

**Comment by mmckegg** [comment]
Still in there, but patchwork is just using ssb-about and patchcore to render them.

**Comment by mmckegg** [comment]
More > Gatherings
