### ISSUE TITLE
Linux App Icon

### ISSUE THREAD

**Issue by robjloranger** [ssbc/patchwork#693]
The appimage app has a default icon instead of the patchwork logo/icon.

Other appimage apps have the correct icon so it should be possible. I'm running linux, gnome 3.26 on openSUSE.

**Comment by robjloranger** [comment]
I should add this is just in the Dash. The program finder fly out thing shows the correct icon.

**Comment by simonv3** [comment]
I've noticed this is the case in a couple of Electron apps, and I wonder if the fix is the one detailed here: 

https://github.com/electron-userland/electron-builder/issues/2269

?

**Comment by thattolleyguy** [comment]
@mmckegg 
I'm not sure if this is this issue or should be a different one (or if I'm doing something wrong) but I can't figure out why my icon isn't working for the alt-tab. It correctly works in my application launcher. 

![iconnotworking](https://user-images.githubusercontent.com/3777734/40060823-b67b7714-5814-11e8-9694-725b1bb479f4.png)

**Comment by simonv3** [comment]
@thattolleyguy I think it's the same issue :). The next release of patchwork should have the fix for this in it #798. (though I'm not sure when that's planned for).
