### ISSUE TITLE
Get regex warning when writing a smiley

### ISSUE THREAD

**Issue by mafintosh** [ssbc/patchwork#7]
Got the following error when adding a smiley `:)` to a message.

<img width="1142" alt="screen shot 2015-08-13 at 21 05 28" src="https://cloud.githubusercontent.com/assets/376661/9259055/1f365406-41ff-11e5-96e1-a5c831d94bcb.png">

**Comment by pfraze** [comment]
@mafintosh yep, I just got that too. Thanks.

**Comment by pfraze** [comment]
Published `suggest-box@1.1.9` which should solve this issue
