### ISSUE TITLE
Use Config gossip count

### ISSUE THREAD

**Issue by nanomonkey** [ssbc/patchwork#700]
Please allow for custom gossip counts in the .ssb/config file, instead of using 2 hops only.

**Comment by mmckegg** [comment]
@nanomonkey my understanding is that this is the case. 

(not sure if it was when you posted the issue though)

Closing, but feel free to reopen if I am wrong about this.

**Comment by mmckegg** [comment]
For reference, you need to either add to (or create) a `~/.ssb/config` file (no extension).

```json
{
   "friends": { 
     "dunbar": 150, 
     "hops": 3 
  }
}
```
