### ISSUE TITLE
Warning when you're not following anybody that you won't be able to see new content.

### ISSUE THREAD

**Issue by Happy0** [ssbc/patchwork#707]
I noticed that someone who was not following anybody (they unfollowed the pubs they were originally following) posted to the 'new people' channel (%5TXFe2XWKvVOMWCelFF74a3t0OVhPkYi4HGpeMqSlpg=.sha256).

I think they might not be able to see any new content because they're not following anyone.

Perhaps we need a big red warning at the top of patchwork saying 'you may not be able to see new posts because you're not following anyone' - perhaps with a link to documentation about the 'friend of a friend' semantics.

**Comment by masukomi** [comment]
This arose because a recent thread %5TXFe2XWKvVOMWCelFF74a3t0OVhPkYi4HGpeMqSlpg=.sha256 involved a new user @3lve+rxiKa+tow0oQ/iHXYaFXnZ7caIr59KQKh5FIKw=.ed25519 asking for pointers, who had managed to unfollow the 2 pubs he was following and was following no individuals.
