### ISSUE TITLE
Security Error This page attempted to navigate out of its sandbox through explicit circumvention. Do not trust it!

### ISSUE THREAD

**Issue by nickdesaulniers** [ssbc/patchwork#71]
tried to download a link from @dominictarr to a pdf, saw this:
<img width="1142" alt="screen shot 2015-11-06 at 11 45 54 am" src="https://cloud.githubusercontent.com/assets/1823839/11007022/0620c8ec-847c-11e5-96ff-98e22a3932c5.png">

**Comment by dominictarr** [comment]
oh, that is because it's trying to open it as html or something.
for now, you can get that file via the cli,
`npm install -g scuttlebot`
then:
`sbot blobs.get '&aqRD7DmVr/ZswM1z2ssbnOe7Sd7M9oNqesyYeCSj6B8=.sha256' > secret-handshake.pdf`

**Comment by pfraze** [comment]
Closing as a duplicate of https://github.com/ssbc/patchwork/issues/38
