### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by setupminimal** [ssbc/patchwork#712]
It would be nice to get desktop notifications, so that I don't find myself always switching over to Patchwork to see if there's been any activity. This also looks fairly easy to add support for, so I'll take a stab at it and we'll see how it goes.

**Comment by ahdinosaur** [comment]
hey @setupminimal, this would be great. you might be interested in https://github.com/ssbc/patchwork/pull/448 and https://github.com/ssbc/patchwork/pull/512 for some context.

**Comment by christianbundy** [comment]
@mmckegg Sorry, should this have been labeled "discussion" as well?

**Comment by mmckegg** [comment]
@christianbundy yes, probably. This would be easy to just add, but I think it would require a lot of supporting work to do correctly (configuration, thread mute).

**Comment by mrweiss** [comment]
any chance this could be reopened? should be able to plug into each systems OS notifications .. Windows/macOS/Linux (GNOME/KDE.. others?) .. could be approached on a per-platform basis

I need the Windows ones and I'm happy to pick up the build (and look at the GNOME ones later..)
