### ISSUE TITLE
More Channels page has poor usability.

### ISSUE THREAD

**Issue by masukomi** [ssbc/patchwork#715]
related to but not the same as #667 

The More Channels page is difficult to find anything you're looking for on. It comes across as a huge list of random "words" that just doesn't seem reasonable to ask users to find anything in.

## Problems

* the more channels page has Many... MANY channels on it. 
* they are in no obvious order
* there is no way to search the page for a given keyword that may be in the middle of a channel name. 

## Suggested improvements: 

* make it alphabetical 
* maybe separate the channels you've already subscribed to into an alphabetically sorted group at the top. 
* make it possible to search the content on the page. I think THIS is probably a much larger ask that's not specific to this page at all and should probably be a separate issue because i TOTALLY want to be able to search on page in basically every page Patchwork has.

**Comment by ahdinosaur** [comment]
> Practically speaking the More Channels page is useless. 

if you see a job that needs doing (#somebodyshould), it's your job to do!

> they are in no obvious order

i think they are ordered by most recent update.

regarding searching the page for a given keyword, this might be covered by #507 ?

**Comment by masukomi** [comment]
reworded intro to not sound like such a jerk. sorry.

**Comment by masukomi** [comment]
this should probably be reopened. since it's still not sorted in a way that's going to be useful to the user.

Also it now says "Browse Recently Active" which makes it unclear if that is ALL the channels or just some of them, and if it's just some then how would you browse _all_
