### ISSUE TITLE
Bookmarks / Favorites / View liked messages

### ISSUE THREAD

**Issue by maackle** [ssbc/patchwork#717]
There are so many good conversations in my scuttleverse, but I often feel that they will quickly get buried in the stream of new messages. This is compounded by the lack of ability to open multiple windows (#705). It would be a lovely and simple feature to have the ability to "bookmark" a message, and have it show up in a list for later reading.

This could simply be a client-side store of message hashes, or could be a new message type that actually gets posted via ssb.

At the very least, it would be nice to be able to see a list of Liked messages, which would be a UI-only change.

**Comment by ahdinosaur** [comment]
hi @maackle, you'd probably be interested in:

[%oeKVdT1Jqt5uubSvhptTJDuiSSekuG7Lv8sDCCWc/lU=.sha256](https://viewer.scuttlebot.io/%25oeKVdT1Jqt5uubSvhptTJDuiSSekuG7Lv8sDCCWc%2FlU%3D.sha256)

**Comment by christianbundy** [comment]
I think the feature request for lists is resolved by tags, but we don't have:

> a list of Liked messages, which would be a UI-only change
