### ISSUE TITLE
Inaccessible on macOS

### ISSUE THREAD

**Issue by aral** [ssbc/patchwork#727]
The main content area in Patchwork appears to be entirely invisible to the accessibility subsystem on macOS. VoiceOver sees the buttons in the toolbar but that’s it.

This means that the audience for Patchwork is currently limited to a subset of able-bodied people.

**Comment by mmckegg** [comment]
That’s a shame. I suspect this will involve quite a lot of work. 

Can you try patchfoo and patchbay and see how they compare?

I suspect that patchfoo will work a lot better with screen readers as it is browser based and semantic.

**Comment by aral** [comment]
Any updates on this?

**Comment by christianbundy** [comment]
@aral I know Matt has been pouring a ton of energy into #858 and I don't currently have the bandwidth to work on this, but if you have the time I'm sure a PR for this would get merged. I agree that accessibility is important. Have you been able to try Patchfoo or Patchbay to see how they compare?
