### ISSUE TITLE
32-bit support for Windows binary

### ISSUE THREAD

**Issue by Logicbloke** [ssbc/patchwork#733]
I was surprised to see that the release is a 64-bit without it being marked anywhere. I think it would help to mention it on the releases page.

Also, if you can add support for 32-bit OSes that would be great!

Thank you,

**Comment by mmckegg** [comment]
32-bit OS are becoming rather uncommon these days, but there is no reason why we can't build for them. Will see if this is possible when we do the next release.

**Comment by robjloranger** [comment]
if this and #766 are still needed I can do it. (try anyway)

**Comment by christianbundy** [comment]
It looks like should be as simple as adding a target to our `package.json`, see here: https://www.electron.build/configuration/nsis.html#32-bit-64-bit

I'd love to merge a PR for this. :+1:

**Comment by Logicbloke** [comment]
I guess no 32-bit release yet as of today? Thanks!
