### ISSUE TITLE
could not connect to sbot -> challenge not accepted

### ISSUE THREAD

**Issue by semateos** [ssbc/patchwork#738]
I have Patchwork running on my mac desktop, tried to put a fresh install on my laptop (MacOS Sierra, Patchwork 3.8.6) and am getting the error "could not connect to sbot" with every pub in the getting started list. Dev tools shows the message "challenge not accepted" (see attachment). I can connect to friends on the local network so sbot appears to be running correctly. But for some reason can't connect to any pubs. Any ideas? Thanks!

<img width="1155" alt="screenshot 2018-02-08 11 27 48" src="https://user-images.githubusercontent.com/851795/35985382-880fb44e-0cc4-11e8-9f65-9fef76356c15.png">

**Comment by semateos** [comment]
I tried again yesterday at home with a couple pubs and it didn't work (same errors as before). I just tried again now using an invite from http://ssb.hypersignal.xyz/ and it DID work. So seems like an intermittent kind of issue. Those are always _super_ fun to track down. Happy to help if I can.

**Comment by Happy0** [comment]
I've seen similar issues where a pub is intermittently not responding to requests to redeem an invite, but then if you retry, it does respond. However, although patchwork follows the pub (on redeeming the invite) and your client receives some gossiped messages (at least, I think my friend's client did), the pub does not follow you back.

I'd like to:
* Make it clear when posting on patchwork with no followers that nobody will see your post, and you should try following another pub and making sure it follows you back.
* Track down the issue with the scuttlebot instance not following back and see if we can only complete the invite operation once it has followed back.. Or something. Perhaps the instance is simply too busy with other tasks.

**Comment by semateos** [comment]
Yeah, I'm wondering if we can get a sense from those pub owners about how much load they're seeing.  I tried _all_ of them multiple times, consistently saw that error, and there was no aspect of the connection working (I was not downloading any messages). But then my attempt at 2am worked - which could maybe point to load on the pubs. It would be good problem to have in a way, meaning the network is getting enough use to put a strain on all of those pubs... if that's the case, one thought for the short term would be to expand the list of pubs on the getting started page - there must be more reasonably stable pubs running out there - and could maybe randomize the order so new people are less clumped up...

**Comment by nsantini** [comment]
The same happening to me, trying to access any of the pubs listed on the public pub list...

**Comment by brylie** [comment]
I am having the same problem with the Linux AppImage. Firstly, most of the public hubs seem to be offline, or at least it is hard to find out how to get an invite. That aside, when I did manage to get an invite from https://ssb-pub.solvingmaz.es/ I get the `could not connect to sbot` error.

**Comment by simonv3** [comment]
To elaborate on that (I used https://ssb.nz which loaded, nothing else did), using AppImage on ubuntu 18.04 I get this in the console:

connect ECONNREFUSED <IP>:<PORT>
"Error: connect ECONNREFUSED <IP>:<PORT>
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)" 

How AppImage works is a bit of a mystery to me, but I can try and help debut.

**Comment by affinespaces** [comment]
I was having this issue with my own pub hosted remotely on Digital Ocean that I was trying to connect to with Patchwork running via `npm start` on my local machine. 

In my case it ended up being because my firewall was permitting UDP and DNS connections from my local IPv6 address but not my local IPv4 address. When I added the IPv4 address I was able to connect without issue.

**Comment by roberto68** [comment]
I get this on @3.11.0
