### ISSUE TITLE
Autocomplete includes channel size

### ISSUE THREAD

**Issue by rdbartlett** [ssbc/patchwork#741]
Minor bug in the latest release:

When I'm writing a comment, and I start typing "#ssb", and then click on "#ssbc-grants, 1078", the text that gets inserted in my comment is "#ssbc-grants, 1078". 

I was expecting just "#ssbc-grants".

**Comment by hbetts** [comment]
I can confirm this issue in Patchwork.

Looks like it was introduced by 2a20acf33d2e0b90142c3b19c1a1fa74d59d32da

cc @mmckegg
