### ISSUE TITLE
new message lost when changing the view

### ISSUE THREAD

**Issue by jerzydziewierz** [ssbc/patchwork#744]
steps to reproduce:
* Respond to an existing thread by clicking "reply" on one of the messages
* begin writing the message. Above the text box, there is only a few posts, or maybe only one post displayed, and in the very top there is "View Full Thread" button.
* Click the "View full thread". In the bottom, there is a text box, with the non-completed message missing.

Very annoying if writing a long answer.

**Comment by mmckegg** [comment]
I think this situation has been improved a lot by efead363d153b58ea67532a7044afee4c76bb99a (included in the current release) which causes the "reply" button to show the full thread from the start when you click reply on the latest message.

Also improving this situation shortly is persistent drafts. This will mean that unfinished replies will stay around indefinitely unless you click clear.

I'm going to close this for now.
