### ISSUE TITLE
[feature] improve the abiliy to @ mention folks from different languages

### ISSUE THREAD

**Issue by masukomi** [ssbc/patchwork#750]
## Problem
Recently Édouard joined us, but it turns out that you need to know how to create an É if you want to mention them. É should be easy on most systems, but a) many folks in the US are english only and have no clue about creating accented characters and b) there are MANY characters which are not, or are not even available. For example, ĉ is essentially impossible to type on a Mac without hacking your system or bringing up the stupid "Show Emoji and Symbols" tool, searching for it, and then double clicking on it. Even if something isn't that hard to type, _and_ if you language uses accented characters, there may be other accented characters which your language doesn't use, and you aren't immediately familiar with the creation of.

## Proposed solution
when bringing up the typeahead menu for `@` mentions and typing a character without [diacritics](https://en.wikipedia.org/wiki/Diacritic) it should search not only for exact matches (case insensitive) but _also_ for matches of the character with diacritics. SO typing `@e` would also match è,é,ê,ë,ē,ė,ę  BUT typing é would only match é (and É).

## Note
It should be possible to do this in a way that extends beyond languages that use Latin characters such that if you type _any_ unaccented character it will look include accented variants of it in the search.

**Comment by lachenmayer** [comment]
Should be possible to use https://www.npmjs.com/package/latinize in the profile suggestions
https://github.com/ssbc/patchwork/blob/master/modules/profile/async/suggest.js

This is called in the suggest box https://github.com/ssbc/patchwork/blob/master/modules/message/html/compose.js#L135

**Comment by masukomi** [comment]
thinking about this more. The way I see it there are two problems: 
1) how do you determine if the letter that's been typed already has a diacritic? (via combining character or pre-composed, or precomposed + combining character)
2) how do you generate a version of the letter without diacritics?

There's an example of how to handle separating characters from modifier characters (combining characters) in Java [here](https://stackoverflow.com/a/29133233/13973) with a good corresponding unit test [here](https://gist.github.com/rdp/0014de502f37abd64ffd). I don't think it handles pre-composed characters.

There's a node library ( [node-diacritics](https://github.com/andrewrk/node-diacritics) ) that removes diacritics but it's very limited. A quick glance at the source code makes it seem like it only works with latin character based languages, and i doubt it works with pre-composed characters. :/

**Comment by masukomi** [comment]
@lachenmayer it looks like latinize suffers from the same problem as node-diacritics which is, being very anglo/eurocentric and ignoring all the non-latin based languages that use diacritics.

That being said, if we used one of them we'd solve the problem for a lot of languages and that'd be better than solving it for no languages. :)

**Comment by mmckegg** [comment]
There might be something we can do based on [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare). See under `options. sensitivity`.

**Comment by mmckegg** [comment]
This is the current matching implementation:

https://github.com/ssbc/patchwork/blob/1e6062aabc2a6eb7a8c9db7195f0fcaa03ae5954/modules/profile/async/suggest.js#L102-L105

Using [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare), we could rewrite it to be something like this:

```js
function matches (text, startsWith) {
  return text.slice(0, startsWith.length).localeCompare(startsWith, 'default', {sensitivity: 'base'}) === 0
}
```

Now `matches("test", "Tést")` returns `true`!

Whoops, I guess I just did this. Might as well go ahead and add it to patchwork now 😆
