### ISSUE TITLE
Can not use torsocks

### ISSUE THREAD

**Issue by nicohansi** [ssbc/patchwork#753]
At the moment it is not possible to use `torsocks` to torify patchwork.
It throws two warnings
 >`1522081336 WARNING torsocks[18395]: [syscall] Unsupported syscall number 293. Denying the call (in tsocks_syscall() at syscall.c:488)`  
>`1522081336 WARNING torsocks[18395]: [syscall] Unsupported syscall number 292. Denying the call (in tsocks_syscall() at syscall.c:488)`

This might have something to do with [this issue](https://stackoverflow.com/questions/1911015/how-do-i-debug-node-js-applications?rq=1). But I have no idea.

**Comment by phaer** [comment]
I don't use `patchwork` yet, but I imagine that `SSB` needs to listen for inbiund connections and `torsocks` denies such for anything but `localhost` only. If so, I guess it would need deeper integration with tor than `torsocks` is able to provide, such as an onion service.

**Comment by HostFat** [comment]
I also hope to see this also :)

It will give a safer place to people that are afraid of impact on their real life, as it some regimes.

**Comment by cryptix** [comment]
with sbot@12 and above you should be able to configure a unix-socket for client applications, which shouldn't be touched by tsocks. you need this in your [`connections.incomming`](https://github.com/ssbc/ssb-config#connections) list of .ssb/config:

```
"unix": [{ "scope":"device", "transform":"noauth" }],
```

an ssb-client then uses a `remote` like this:  `unix:/path/tomy/ssb/socket~noauth` or [this in patchbay](https://github.com/ssbc/patchbay/blob/e722641cbffa14a6c07ea99bba8dccb1a15c78c1/config.js#L28)).

**but** this is all pretty new, please test this more! not having `net` in `connections.outging` should stop sbot from using it and only having onion should have it use the socket on `localhost:9050`  to make connections.

**Comment by mmckegg** [comment]
@cryptix so is this possible now?

Does something need to be added to patchwork, or is it a documentation issue?

**Comment by cryptix** [comment]
> so is this possible now?

I don't use tsocks myself so I can't verify or test this myself but I believe the pieces are all there.

Sadly we don't have any active windows devs to figure this out which made patchbay remove unix sock by default: https://github.com/ssbc/patchbay/pull/264 

So yes, I'd rather document a workaround for this than change the default connection type.

**Comment by linas** [comment]
I couldn't figure out how to make  #issuecomment-429852552 actually work.

**Comment by linas** [comment]
Oh hah. Pays to read the actual bug report. `Unsupported syscall number 293` is being tracked in in gitlab, https://gitlab.torproject.org/tpo/core/torsocks/-/issues/30658 from which I quote:
```
$ egrep '^(293|332|292)' arch/x86/entry/syscalls/syscall_64.tbl
292     common  dup3                    __x64_sys_dup3
293     common  pipe2                   __x64_sys_pipe2
332     common  statx                   __x64_sys_statx
```

so I can't imagine switching to unix-domain socks won't fix this; I think that electron is making these syscalls *before* patchwork or patchbay start up. Patchbay never gets to the splash screen. So this does not smell like a patchwork issue to me, it smells like a torsocks issue.
