### ISSUE TITLE
Suggest pubs to new users from within the app

### ISSUE THREAD

**Issue by celesteh** [ssbc/patchwork#759]
There are a lot of steps for new users, many of which are non-obvious. If the patchwork app could suggest a list of pubs that might issue invitations (or offer to obtain an invitation for a new user), this would make the whole process a lot more straight foward and would make it more likely for people to go through the trouble of joining.

**Comment by mmckegg** [comment]
Hmm, we are generally trying to avoid tying patchwork to a particular network or set of pubs.

We're waiting on proper user invites, and easier methods of creating your own pubs (or avoiding them all together). I think these will improve the situation you describe above.

As far as "make it more likely for people to go through the trouble of joining", that's not something we're too worried about. If someone really wants to get on, they'll find a way.

**Comment by celesteh** [comment]
There is a page online which has a list of pubs, which maybe the app could link to?

Accessibility is generally a valuable goal for FOSS projects. May communities would consider a lack of concern about this to be a bit of a red flag, so I'm somewhat taken aback by your reply. I'm sure this isn't what you meant, but I do think these issues should be considered. I know this is a new project and I want to see it thrive, so I think this necessitates the ability to attract and retain a diverse user base.

**Comment by mmckegg** [comment]
I posted some more thoughts about this topic on SSB:

[%uSukBEzOx2Ge8boal0b4v+xqq9bnF62wa2e/usKKlVE=.sha256](https://viewer.scuttlebot.io/%25uSukBEzOx2Ge8boal0b4v%2Bxqq9bnF62wa2e%2FusKKlVE%3D.sha256)

**Comment by ahdinosaur** [comment]
hi @celesteh, i'll try to share some ramblings, maybe helpful maybe not. :cat: 

i notice that you're talking about two things simultaneously as if they are the same: Patchwork/Scuttlebutt the _tool_ and Patchwork/Scuttlebutt the _social network_.

i think everyone here agrees that the tool should be as accessible as possible, everyone should be able to use the tool regardless of their background.

but should everyone be invited to our social network? (see also [paradox of tolerance](https://en.wikipedia.org/wiki/Paradox_of_tolerance) and [gardens need walls](https://www.ribbonfarm.com/2015/03/04/gardens-need-walls-on-boundaries-ritual-and-beauty/)) i've spent many years and many conflicts building relationships with other butts, together we've built up a solarpunk culture that is unique to our garden, why should i risk our healthy community to [infection](https://viewer.scuttlebot.io/%2543k0U0uGU87AFvvjfRUpq0RFalA7BxWEd1TOe8m5v1g%3D.sha256) by opening a door for strangers to walk in? (see also [eterenal september](https://en.wikipedia.org/wiki/Eternal_September), [the rando problem](https://viewer.scuttlebot.io/%25OkgDsogCxesWEWn77Znu2alWlqNTpZVgRI4AWxcckBc%3D.sha256))

as a tool, Scuttlebutt is like a walkie-talkie, you can use it to communicate to your social network. but having a walkie-talkie doesn't give you access to everyone's social network. it also doesn't mean i have to listen to you speak. (see [free listening manifesto](https://viewer.scuttlebot.io/%25V2rZOt%2BnuTrS%2F89OquyPSgBBRjkJAf81Stq%2Fsg2Fmtk%3D.sha256))

as a network, Scuttlebutt is more than just the initial seed that's been growing so far. as Matt said "proper user invites (removing need for pub invites) and ability to easily create pubs" should allow for more networks to blossom, each one with their own cultures. each community can decide for themselves what are the community standards (for example, when you enter a house, do you take your shoes off?) and who is welcome (wouldn't it kinda be weird to show up to some random person's house party?), i think that's way more exciting than a single big social network.

:heart:

**Comment by celesteh** [comment]
I see where you're going with this. I think, in order to facilitate this direction, there are a couple of things that might help:

1. Pubs as appimages or otherwise much easier to deploy on just about any kind of server (or included in syncloud or whatever)

2. Your documentation has a charming video which hints at these goals, but they're not made explicit anywhere that I've seen.

This distinction you're making between the tool and network is reasonable, but it's also not how we've largely been trained to think about tools and networks over the last few years of centralisation.

Thanks for taking the time to reply to this.

**Comment by ahdinosaur** [comment]
> 1. Pubs as appimages or otherwise much easier to deploy on just about any kind of server (or included in syncloud or whatever)

yeah agree. i've done my best to make a one-click installer (using a portable Docker image) with [`ssb-pub`](https://github.com/ahdinosaur/ssb-pub), am now funded via #ssbc-grants (and match funding) to work on [ButtCloud](http://buttcloud.org) for two months, so am currently working full-time to solve the pub hosting problem directly via an open source product / business.
