### ISSUE TITLE
Language change breaks Patchwork

### ISSUE THREAD

**Issue by skippednote** [ssbc/patchwork#761]
Hi folks

I changed Patchworks language to "Kashmiri" (the translation is in Urdu btw) and now all I see is a blank white screen. I tried reinstalling and clearing my `.ssb` directory but it's still loading in `Kashmiri` and I have lost all my data 😢.

- What else should I try to change the language back to English?
- I took a backup of my `secret` file in the `.ssb` directory. Can I use it access my previous identity?

FYI, this is all on Windows 10 🙀

**Comment by mischa-s** [comment]
As long as you haven't actually deleted your ./ssb/secret, you should be able to restore everything if you do the following:

• backup your ~/.ssb/secret file
• completely delete your ~/.ssb directory
• delete patchwork / reinstall patchwork (to reset the language)
• open patchwork to create a new ssb identity (don't worry about choosing a name or image, press cancel)
• join a pub that you used to be a member of
• wait for sync to complete, then close patchwork
• replace ~/.ssb/secret with your original backed up secret file.
• Relaunch patchwork. You should be "you" again!

source https://github.com/ssbc/patchwork/issues/761

**Comment by mmckegg** [comment]
I have reproduced this issue. Kashmiri indeed breaks patchwork.

I'm going to reopen this issue to fix the bug.

**Comment by skippednote** [comment]
@mmckegg While we are at it, can we also change `Kashmiri` to `Urdu`. The translations are in `Urdu` not `Kashmiri`.

**Comment by mmckegg** [comment]
I think I am going to drop that translation. It hasn't been updated for a long time. Happy to include an updated one if someone wants to go through and translate all the new strings.

Still need to figure out why it's crashing patchwork though.

**Comment by mmckegg** [comment]
@skippednote okay I found the problem, `ki` is not a valid language code. I changed it to `ur` and updated the name of the translation. Now everything seems to be working.

I'll leave it in there, but it still would be nice to get an update on the strings.
