### ISSUE TITLE
add ability to switch identities and use custom caps keys

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#762]
ideally open in new windows so you can run multiple identities/networks simultaneously.

**Comment by black-puppydog** [comment]
IMHO teh bot is wrong :P

Multi-identities are still a nice idea, and IIRC sbot already supports them, so it should be easier now than ever before. :)

**Comment by black-puppydog** [comment]
Still not implemented. Still relevant to me personally, but might be out of scope for patchwork, because it might fall into the architecture debate around lessbot (or such) instead. Opinions? /cc @christianbundy @Powersource

**Comment by christianbundy** [comment]
We can use [ssb-identities](https://github.com/ssbc/ssb-identities), and I'd love to merge a PR that allowed other identities, but I don't currently have bandwidth for this.

**Comment by black-puppydog** [comment]
didn't expect that. Just didn't want this to fall off a cliff due to stalebot :P

**Comment by christianbundy** [comment]
Totally, I understand that the stale[bot] thing can be frustrating.

To share where my head is at, my philosophy is that "open" means it's at least one of:

- it's on the roadmap of at least one SSBC member (determined by assignees)
- it's actively being discussed or implemented (determined by issue activity)

Keeping open inactive issues that nobody is planning to work on makes it difficult to organize and prioritize the more important ones, so we have the bot come through and close issues if they're unassigned and inactive. In my mind "closed" means "it's not a priority right now", but it's far away from "this will never get worked on" or anything like that.

**Comment by black-puppydog** [comment]
Then I'd say this can be closed for now. I'm not able to do this, and it will be sooo much easier once the new round of infra from the sunrise choir goes live...

**Comment by mixmix** [comment]
see also : https://github.com/ssbc/patchbay/issues/327
