### ISSUE TITLE
Zoom isn't persisted when running AppImage directly

### ISSUE THREAD

**Issue by mroseman95** [ssbc/patchwork#764]
When I close the application and relaunch, the zoomFactor I previously had is reset.
I'm running the latest patchwork as an AppImage on Arch Linux.

I did some digging to see what was causing this. It looks like Electron will automatically save the zoom level in a Preferences file for you. For me that is located at `~/.config/Patchwork/Preferences`
```
{"brightray":{"media":{"device_id_salt":"jseg77E9itZBCglpfi1R0A=="}},"partition":{"per_host_zoom_level
s":{"5448818296745141209":{"file:///tmp/.mount_Patchw3bCxsI/app/resources/app.asar/assets/base.html":3
.5}}}}
```
This is what it looks like when I first run it. (The very last number is the zoom level I set.)

If I then close the program and run it again, it resets the zoom level. At first if I look at the Preferences file, it looks like nothing changed, but if I then change the zoom again, the file updates to something like this.

```
{"brightray":{"media":{"device_id_salt":"jseg77E9itZBCglpfi1R0A=="}},"partition":{"per_host_zoom_level
s":{"5448818296745141209":{"file:///tmp/.mount_Patchw3bCxsI/app/resources/app.asar/assets/base.html":3
.5,"file:///tmp/.mount_Patchwbdd9He/app/resources/app.asar/assets/base.html":1.5}}}}
```

I don't know anything about how AppImages work, but it seems like it's creating a new instance with new settings?

One thing to note, is that when I run patchwork in development, this isn't an issue. It seems to be an issue with the AppImage, that is causing this.

**Comment by mmckegg** [comment]
@mroseman95 

Are you launching the AppImage file directly every time, or using the shortcut create in your app launcher?

**Comment by mroseman95** [comment]
@mmckegg 

Well I don't know about any shortcut.
This is how I run it...
1. Download AppImage
2. make AppImage executable with `chmod a+x Patchwork-3.8.10-linux-x86_64.AppImage`
3. create symbolic link in /usr/bin directory `ln -s /path/to/appimage patchwork`
4. and then I run it by launching it through rofi (to my knowledge this is just executing the AppImage every time, same as running it from terminal)

I don't see any desktop shortcut, or any other way to run it.

If I do the stuff with the symbolic linking, or if I run the AppImage just by executing `./Patchwork-3.8.10-linux-x86_64.AppImage`, I still have the zooming issue, and the new mount is created every time.

I don't understand enough to know if this is relevant, but this is what is printed when I launch from terminal
```
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_PatchwKKjwav/AppRun.
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  path: '/home/matthew/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 7777,
  server: true,
  _: [] }
Log level: notice
git-ssb is not installed, or not available in path
```

The line `Skipping /tmp/.mount_PatchwKKjwav/AppRun` is refering to the new mount point, not the old one.

**Comment by gergelypolonkai** [comment]
The desktop is not created because AppImage canʼt ask if it should create it, and thatʼs because both Zenity, KDialog, and XDialog is missing (see #490).

The actual problem, though, is that the Patchwork executable is in a different path every time you mount the AppImage. Since this is an Electron setting (or is it Patchwork specific?), it should be reported upstream.

**Comment by Powersource** [comment]
> Since this is an Electron setting (or is it Patchwork specific?), it should be reported upstream.

I'm guessing our policy on upstream bugs is to generally not track them in this repo, so closing.
