### ISSUE TITLE
No way to invite friends?

### ISSUE THREAD

**Issue by PhoenixRx7** [ssbc/patchwork#765]
I have to invite someone to a pub, then invite them from the pub. I can't have friends unless I have at least one friend who is in a pub. It is already a bit tricky to set up, adding another layer to getting to your friends will hold this platform back, a LOT.

**Comment by mmckegg** [comment]
Unfortunately this is the only way right now. But there is work being done to improve this situation.

@dominictarr has been working on a [user invites](https://viewer.scuttlebot.io/%25LMYARKcJ5%2FHVrkfyGo0oSV4j%2FwhFmpeiJlQnvPw53PE%3D.sha256) feature that should make it a lot easier to get your friends on the network 😄
