### ISSUE TITLE
Add 32-bit images for GNU-Linux

### ISSUE THREAD

**Issue by strypey** [ssbc/patchwork#766]
Many of the people SSB would be of interest to are folk like me, who live on the smell of an oily rag (and sometimes *in* an oily rag), and can't afford new computers, or even newer 2nd-hand computers. We would really appreciate 32-bit images being made available, so we can get on the ocean, without having to build our own boat from rough-sawn timber first. If you provide images for 32-bit, they will work on 64-bit PCs too. It's analogous to the way that if you put on a feast, any food you provide that's vegan can be eaten by anyone present (except maybe the gluten-free people, umm ...).

So ... the Issue is you don't seem to have 32-bit images available for download (especially for GNU-Linux), can that be done? Thanks heaps. Keep up the great work!

**Comment by mmckegg** [comment]
Related to https://github.com/ssbc/patchwork/issues/733

Yep, there's no reason we can't build for these platforms. I'll will see if we can update the build script so that 32bit versions are included in the releases.

**Comment by strypey** [comment]
That would be awesome! Thanks a lot for looking into this.

**Comment by strypey** [comment]
So, any progress on this? Also, I have an older mobile device, running Android 4.2.2 and F-Droid tells me that's too old to use the one SSB client it has available. I know that backwards compatibility for older devices adds a lot of dev and maintenance work, but it also has the potential to make the Scuttle-verse accessible to many more low income people.

**Comment by christianbundy** [comment]
@strypey I don't think there's been any progress on this, but if you check out the patchwork-builder repo you may be able to add 32-bit Linux support. Would an AppImage work on your device, or would you need it packaged another way?

**Comment by amuuza** [comment]
Hi. Same as @strypey here. I would also like to install Patchwork on GNU+Linux 32-bit machines.
Please, this is a solarpunk request, so that those who don't own the latest technologies can join too!

**Comment by strypey** [comment]
@amuza you might be pleased to know that Trisquel GNU/Linux will provide
32-bit images of version 9.0 (Etiona), based off Ubuntu 18.04.
Presumably with a Mate desktop, as if version 8.0. This means we will
have support for our old 32-bit PCs until 2028! If they are still
working by then, I'll be very impressed :)

I know, this is a way off-topic, but us 32-bit freaks have to stick
together!

**Comment by christianbundy** [comment]
It looks like Electron has [discontinued support for 32-bit Linux](https://electronjs.org/blog/linux-32bit-support), so I don't think we'll be able to help with this. Highly recommend [Patchfoo](https://github.com/ssbc/patchfoo) for a Scuttlebutt client that will run inside a web browser (with no JS!): https://github.com/ssbc/patchfoo

**Comment by strypey** [comment]
> It looks like Electron has discontinued support for 32-bit Linux

Yet another good reason to [not use Electron for native desktop apps](https://drewdevault.com/2016/11/24/Electron-considered-harmful.html) ;) Thanks for the tip though, I'll check out Patchfoo.

**Comment by christianbundy** [comment]
![](https://media.giphy.com/media/3ohze26aemk8BfyZjO/giphy.gif)
