### ISSUE TITLE
`modules` vs `plugs`?

### ISSUE THREAD

**Issue by jordydickinson** [ssbc/patchwork#768]
I'm interested in writing a plugin of sorts for Patchwork (a viewer for a custom message type). I've been looking at these two directories as that's where they seem to be placed but I'm not sure what the difference between these two is.

**Comment by mmckegg** [comment]
@jordydickinson 

`modules` are for adding new things
`plugs` are for extending existing things
`overrides` are for replacing or removing things

**Comment by mmckegg** [comment]
Let's leave this issue open as a reminder to update the [contributing](https://github.com/ssbc/patchwork/blob/master/contributing.md) guide with this info.
