### ISSUE TITLE
Inline video display

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#771]
I just tried just attaching a video from a twitter "gif" (really an mp4 file) to a post:
[viewer link](https://viewer.scuttlebot.io/%253yeP%2Br6F6whvKh0u8nnpaFpFEH9pTk805Ih16%2FdnaA0%3D.sha256)
[ssb link](%3yeP+r6F6whvKh0u8nnpaFpFEH9pTk805Ih16/dnaA0=.sha256)

I can open the file in the browser, but inline gif/video would be very cool. 
The alternative would be to use a very heavily compressed actual gif file. Not pretty, not practical.

**Comment by mmckegg** [comment]
I agree. Will investigate and see if we can do it via the same markdown as image embeds!

**Comment by mmckegg** [comment]
@black-puppydog 

Okay, have just added basic audio and video embedding into the latest master.

<img width="705" alt="screen shot 2018-04-13 at 10 42 58 pm" src="https://user-images.githubusercontent.com/66834/38730799-11cab420-3f6c-11e8-94b2-c12597d8785f.png">

Will be in the next release!
