### ISSUE TITLE
Don't Highlight Unfollows

### ISSUE THREAD

**Issue by hbetts** [ssbc/patchwork#776]
As discussed [here](https://viewer.scuttlebot.io/%25gjnFefaF6hAuGVb%2BlggHr2NGB7qYeSFcLOOkB344JGA%3D.sha256), it seems that someone _unfollowing_ you is highlighted as a _mention_ in Patchwork.

I feel that the action of unfollowing is the personal decision of the person doing the unfollowing, and shouldn't be highlighted. Doing so seems to trigger the mindset that I have done something wrong to cause the person to undertake the task of unfollowing me, when in reality, it's probably just because they want to prioritize other personal interactions.

**Comment by mmckegg** [comment]
@hbetts 

Yep, totally agree! 

Do you think we should still show unfollows in the public feed? I almost think not. Definitely should show blocks though I think (but maybe not in mentions?).

**Comment by hbetts** [comment]
> Do you think we should still show unfollows in the public feed?

If the goal is to replicate in-person interactions, then displaying `follows`, and `unfollow`s would be, I believe, the equivalent of someone announcing to a person when they begin listening, and then when they stop listening. It's not my experience (a subjective matter) that people I interact with do that.

Furthermore, the fact that someone has followed me, or un-followed me, is not actionable to me. The choice to follow, or un-follow, me is their prerogative. Exposing that information to me implies that I should take some action, however, since it's not my choice for someone to follow me, I don't see how displaying that information helps them, or myself.
