### ISSUE TITLE
Sending private messages very slow

### ISSUE THREAD

**Issue by goodnekk** [ssbc/patchwork#778]
For some reason private messages only arrive hours/days after they have been sent. Is there a way to make this faster?

**Comment by mmckegg** [comment]
There is nothing special about the transport of private messages. They should take just as long as a public message.

It all depends on the connections between the sender and receiver. If you follow each other, then generally it should be near instant (depending if at least one of you is followed by a good pub).

If the connection path is a bit rough, then it could take a while for the messages to gossip their way.
