### ISSUE TITLE
add support for ssb-web urls

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#779]
Example implementation from patchfoo: https://github.com/ssbc/patchfoo/commit/b037d20c242f538c48bf87cd060435b1e7cc2dc7

@noffle's post on ssb:

[%dBn9uyqFKuinu4wv4sEYY3Cp49kJswkrTMka7wJJXTM=.sha256](https://viewer.scuttlebot.io/%25dBn9uyqFKuinu4wv4sEYY3Cp49kJswkrTMka7wJJXTM%3D.sha256)

**Comment by noffle** [comment]
Happy to advise if anyone picks this up and gets stuck. :wave:

**Comment by gmarcos87** [comment]
Why not use ssb-viewer? Version 1.0.4 has the web view applied https://github.com/ssbc/ssb-viewer/commit/c71fb2a0899fe94c63306d8822b797c6dd42ef68
