### ISSUE TITLE
Mouseover of profiles should include some of the user bio

### ISSUE THREAD

**Issue by celesteh** [ssbc/patchwork#780]
The who to follow side bar is interesting, but mousing over a particular suggestion only gives me their profile picture and name. Including a bit of their bio/description would make this feature more useful and I might start using it to figure out who to follow.

**Comment by Cornelius-Sheahan** [comment]
This would be my first contribution to this project so I'd like to start with something small like this.

I assume the best place would be between the Name and Public Key, or is there a alternate spot?

How much of the Description should be shown?
- split on the first new line ('/n')
- character limit approx equal to the public key 
- the smallest between these first two 
- the entire length

**Comment by christianbundy** [comment]
For reference, here's how it currently looks:

![Screenshot from 2019-05-05 14-46-42](https://user-images.githubusercontent.com/537700/57200776-9e8cd600-6f44-11e9-9a07-a6ced2b73852.png)

I think the description would be cool, and I think this is the right heuristic:

> - split on the first new line ('/n')
> - character limit approx equal to the public key
> - the smallest between these first two

I'd also be interested to see some basic friend info, like "blocked by 4 people you're following and followed by 42".

**Comment by mmckegg** [comment]
It currently looks different if you don’t follow the person. 

You’ll see number of mutual friends or if people block them.

**Comment by lluisemper** [comment]
I am willing to help, what should I do? a fork of it, implement it and merge it?

**Comment by christianbundy** [comment]
Yep! There's more info in the [contributing guide](https://github.com/ssbc/patchwork/blob/master/docs/CONTRIBUTING.md).

**Comment by Powersource** [comment]
@lluisemper If you want help getting started with the implementation we could set up a call and I could sort of show you the ropes :)

**Comment by lluisemper** [comment]
Very kind your offer, let me a couple of days to try it out by myself and If I can not figure that out I let you know :) @Powersource 

Kind regards

Lluis

**Comment by black-puppydog** [comment]
Not sure if you all got notifications for this but #1277 does something like this and seems to work fine for me locally, but I wouldn't want to merge it without at least someone else checking it out to see if it runs. :P

**Comment by black-puppydog** [comment]
@celesteh I hope this version does something along the lines of what you thought when you started it. I'll be happy to iterate on this. I've been using this myself for a few days now and have to say even though it's a bit hap-hazard, I don't want to miss it any longer. :)
