### ISSUE TITLE
Assigning names to users should not be world readable

### ISSUE THREAD

**Issue by celesteh** [ssbc/patchwork#783]
I got a friend of mine to join SSB and she gave herself one of the names that she generally uses for a semi-anonymous identity on social networking.  I promptly assigned her real name to her so I could remember it was her and was chagrined to see that I had just outed her profile (and by extension the user name connected to me on several social networks)! 

I don't think users should have the ability to assign traits to each other as this can accidentally reveal personal information and could be misused for purposes of abuse.

**Comment by mmckegg** [comment]
This has come up quite a few times now. There's a discussion on ssb:

[%rGGSZEdtMJgU4JzytpJ1FqAsRnNyQi2mj9U/zBa4WU0=.sha256](https://viewer.scuttlebot.io/%25rGGSZEdtMJgU4JzytpJ1FqAsRnNyQi2mj9U%2FzBa4WU0%3D.sha256)

At the very least, we're going to ensure that the interface lets people know that these are public, and allow them to be assigned privately. 

I am tempted to remove public nicknames all together once there is a better mechanism for flagging old unused accounts.
