### ISSUE TITLE
Profile restore didn't work, broken state

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#785]
I'd just like to start with the obvious: this is likely my fault.

I think I've created a situation where my key is associated with two feeds: one from a month ago, one that's been active for the past few weeks, and my posts don't seem to be gossipped between one and the other.

## Timeline

- About a month ago I started up Scuttlebutt and created a brand-new identity.
- I had to format my hard drive, so I read https://github.com/ssbc/patchwork/issues/674 and saved my entire `.ssb` directory 
- I formatted my drive, moved `.ssb` back in-place, installed and started Patchwork.
- IIRC it complained that my database was corrupt.
- I moved `.ssb` elsewhere, started Patchwork, closed Patchwork, and then replaced `.ssb/secret` with my original keypair.
- I tried to connect to the pubs I'd previously used, but none would connect. Instead, I connected to some new pubs from the registry.
- My content didn't come back. Every few days I'd see "${person} followed you 3 weeks ago" or something, but at no point did I get my entire history back.
- I've been using Patchwork for about two weeks, but haven't hard anyone reply to my messages.
- Curious, I created a new profile, connected to the same pubs, and noticed that my profile is impossible to find. I'd been commenting in #new-people often, and noticed that while I could see the posts, my replies were non-existent.
- I created *another* new profile, but this time I imported **both** my original `.ssb/secret` and `.ssb/gossip.json`, and as soon as I booted up Patchwork and it downloaded all of my 1+ month old posts, but none of my recent ones.

## Current status

I now I have three identities:

- original `.ssb/secret`, which has a bunch of new posts that nobody can read
- disposable identity I used to check whether anyone could read my posts
- original `.ssb/secret` + `.ssb/gossip.json`, which only has my oldest posts

It sounds like The Right Way&copy; to do a profile sync is to save _both_ `.ssb/secret` and `.ssb/gossip.json` and wait for everything to sync. The Wrong Way&copy; is to import _only_ `.ssb/secret`, connect to pubs, and start posting before you've recovered _all_ of your old data.

## What now?

I'd rather not lose all of the [unseen] content I've been posting for the past couple weeks, but I understand if that's the only way to fix the problem. Please let me know if there's any troubleshooting I can help with, and/or what the preferred way of dealing with weird states is. Thanks for your help!

---

Potentially relevant: https://github.com/ssbc/secure-scuttlebutt/issues/157, https://github.com/ssbc/scuttlebot/issues/410, https://github.com/ssbc/secure-scuttlebutt/issues/157

I think I've created a situation where some folks have the original version of my feed (from 1+ month ago), some folks have the new version of my feed (active for the past couple weeks), and my posts aren't replicating from one to the other. Bummer.

**Comment by christianbundy** [comment]
I think this is the wrong repo. Closing.

**Comment by nonlinear** [comment]
@christianbundy wait, I wanna know how you fixed it. I'm having same problem.

**Comment by christianbundy** [comment]
I think I added some deets here: https://oasis-demo.fraction.io/thread/%25WIiCLuPpqFptpI5Sord0EhmHnAwz%2FWah2L%2B7lzt75Jg%3D.sha256#%25WIiCLuPpqFptpI5Sord0EhmHnAwz%2FWah2L%2B7lzt75Jg%3D.sha256

If you're forked and need help, I'm happy to try to do a call or synchronous chat or something! Being forked *suuuuucks*. 

Here's your latest posts that are visible on the network from my perspective: http://oasis-demo.fraction.io/author/%40mUNqmOd%2FuRBGbk9YMOzaUypf%2F6aPhxYI0lk6%2BhRyyK4%3D.ed25519
