### ISSUE TITLE
shell-init cwd error (solved)

### ISSUE THREAD

**Issue by brendanvg** [ssbc/patchwork#79]
when doing `npm install ssb-patchwork -g` on a mac I was getting 

electron-prebuilt shell-init error retrieving current directory permission denied

...tried cd'ing around and made sure i had root permissions, which i did and it didn't matter, and then I did
`sudo npm install --global --unsafe-perm ssb-patchwork`
and it worked.

**Comment by pfraze** [comment]
Hmm, you shouldn't need to do that. Were you using `sudo` both times?

**Comment by brendanvg** [comment]
was...

**Comment by pfraze** [comment]
No worries, that's what npm basically nudges you to do when installing globally. It's a bad default, imo.

See https://github.com/ssbc/patchwork/issues/69, similar/same issue. Once you've configured your npm prefix to be in your home directory, you can install globally without using sudo (for any package, include PW).

**Comment by dominictarr** [comment]
I think it's sodium that is failing when we use root. Some npm installations are configured that way, it would be easier (long run) to support that.

**Comment by pfraze** [comment]
@dominictarr what are the permissions of the installed package, when sudo is used? Is `root` the owner? Is there any safeguard it doesn't take advantage of?
