### ISSUE TITLE
Mentions/new posts ordered by thread is inconvenient

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#791]
There are a couple of longer threads I've participated in, or am interested in. The problem is that when a new message is added to those, the very first message of the thread appears on top of the mentions/public list, requiring me to scroll down various number of pages at times, just to find out what new content has been added. Usually, messages are being cropped out of sight in the middle, but it still means I end up seeing the same thread-starting message multiple times a day, when in fact I don't need or want to do that.

Maybe it could be a UI tunable how much cropping should take place, such that I could configure "all of the above", resulting in *only* the new message(s) to show up, with an expand link at the top, in case I'd want context. Or maybe even a tree-style display in the border, similar to gmane.org?

**Comment by mmckegg** [comment]
I think this depends a lot on your workflow and scrolling system. For example, on a system with momentum scrolling (macOS), it's fairly easy to just flick past. I personally enjoy seeing the full context.

But I can see how on an "inferior" scrolling system, this could be quite annoying. I would be open to adding an option to compress all other posts on threads that have new messages. Maybe this could even be a good default. My thinking is that normally, messages would show the usual size, but if any of the messages were new in a thread, then all non-new messages would compress down to the compact size (I think it is 400px max height) with a "view more".

Another thing I want to add is a little floating button in the bottom of the feed view "Unread ⬇️" that when clicked, scrolls down to the next unread message. And will disappear once you have read everything.

**Comment by madduck** [comment]
@mmckegg Yeah, of course it'd need to be configurable. I think having a "goto first unread" button would also be great, especially if it then briefly or permanently highlighted the new item for further visual ease.

**Comment by madduck** [comment]
.

**Comment by christianbundy** [comment]
I'd like to see this. My preference would be to only show the relevant message rather than a summary of the entire thread.
