### ISSUE TITLE
Arrows&PgUp/PgDn require pane activation for scrolling

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#793]
When I click on a tag or tab, I can't immediately use the arrow keys and/or PgUp/PgDn to scroll. I first have to click in the messages pane to transfer focus. I think it'd be more intuitive if focus was there right away, as most people will likely want to browse content right away, not be forced to (guess to) click first.

**Comment by mmckegg** [comment]
Patchwork hasn't really been optimised for keyboard use, and this is not something I plan on spending any of my time. But I'd be very happy to review and accept PRs in this space, if someone wants to head it up.

---

@madduck have you tried the patchbay client? It has much better support for keyboard shortcuts. It also uses quite a different method of displaying the main feed where on only shows new posts, and not the context.

Maybe it would be more suited to your style?

**Comment by madduck** [comment]
@mmckegg Yes, I am using those two clients, one on odd and the other on even days. Still unsure.

Given that you are using Chrome, maybe including a Chrome extension such as Vimium would get you a lot with fairly little work?

**Comment by madduck** [comment]
.

**Comment by gergelypolonkai** [comment]
I reopen this as it annoys me a lot, too (although iʼm pretty sure itʼs not too urgent). I might even try fixing it next week, if i have the time.
