### ISSUE TITLE
Display active channels/connected pubs/who to follow pane for tags too

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#794]
It'd be nice if the pane including active channels/connected pubs/who to follow pane were visible also when browsing a tag, or even private messages, profile, mentions, etc..

Any reason not to?

**Comment by mmckegg** [comment]
This sidebar is currently part of the public page. But it could be repositioned into the chrome instead as a sidebar that is always visible. It would then serve as a navigation bar (much like the nav buttons at top).

I think the reason this wasn't done before is that I was wanting to have specialised sidebars for the different views. For example on channels, it would be nice to see a list of subscribers, and private messages could list recent conversations/contacts. Also the profile view already has a sidebar, so on a smaller screen, things would get too narrow.

**Comment by madduck** [comment]
@mmckegg well, there are technically two sidepanes ;).

Also isn't variations in screen estate precisely why Twitter developed Bootstrap? Could that be used here? It's Chrome anyway, isn't it?

**Comment by madduck** [comment]
.
