### ISSUE TITLE
OSX scrollbar doesn't go away on page transition

### ISSUE THREAD

**Issue by gdpelican** [ssbc/patchwork#797]
Just downloaded the latest patchwork release (3.9.0, MacOSX dmg) after a looong hiatus, good to see the improvements!

I'm having an issue with the latest release where the Mac scrollbar (I'm on High Sierra 10.13.3) doesn't disappear when navigating the app:

Here it is in the right place on the 'Public' page:
![screen shot 2018-05-06 at 3 29 27 pm](https://user-images.githubusercontent.com/750477/39669563-61e5583c-5143-11e8-9c0c-0e0bafd445f9.png)

But in 'private':
![screen shot 2018-05-06 at 3 29 50 pm](https://user-images.githubusercontent.com/750477/39669534-b4a049de-5142-11e8-934d-98cb32f51f77.png)

And 'Gatherings':
![screen shot 2018-05-06 at 3 32 53 pm](https://user-images.githubusercontent.com/750477/39669535-b4d1e80e-5142-11e8-8bf1-c269afc14e8d.png)

**Comment by mmckegg** [comment]
@gdpelican 

This was reported a while back in #652, but I have not been able to reproduce.

What are your settings under System Preferences -> General -> "Show scrollbars"?

<img width="505" alt="screen shot 2018-05-06 at 4 04 33 pm" src="https://user-images.githubusercontent.com/66834/39669678-4bfd2262-5147-11e8-8572-56795d383bf4.png">

Also what sort of pointing device are you using?

**Comment by gdpelican** [comment]
I am regular trackpad pointer thingy; no special pointies for me, and am
also on 'Automatically based on mouse / trackpad'

It actually seems mitigated (if not squashed) now that I've downloaded the
2 years of history I was missing (which was crunching my CPU a bit),
possibly related? Or perhaps the scrollbar continues to show up due to new
content coming in?
