### ISSUE TITLE
Cross-post to Twitter

### ISSUE THREAD

**Issue by arcalinea** [ssbc/patchwork#799]
After thinking about interoperability between p2p and centralized social for awhile, I posted some questions on Patchwork. @olizilla said he'd use a ssb to Twitter bridge, so I hacked the basic functionality together, since I'd been wanting this myself. Is this a feature others would like to have? 

Right now I have a separate button on the message box in the Patchwork GUI to post to Twitter, was thinking it could be enabled or disabled as an option. A Patchwork-to-Twitter tweet: https://twitter.com/fireflixdragoon/status/994652799563579392

It could also be implemented as a button to simultaneously post to ssb and Twitter. 

Twitter-to-ssb cross-post or import is another related feature that would be nice to have. @staltz mentioned interest in doing this.

**Comment by mmckegg** [comment]
I think this is a cool idea, but it sounds more like an extension of some kind. Unfortunately there is currently no easy way to extend patchwork right now (apart from forks). 

I am going to close this as I think it is too specific of a feature to add directly to patchwork.
