### ISSUE TITLE
messages appear twice on replies

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#8]
we are seeing messages appear twice:

![2015-08-13-212830_1366x768_scrot](https://cloud.githubusercontent.com/assets/259374/9259724/8aa006e8-4203-11e5-8a51-7efedd87e48c.png)

**Comment by dominictarr** [comment]
reloading makes the second message appear, so this is obviously a UI bug.

**Comment by pfraze** [comment]
I've committed (not yet published) a fix to this. The issue was that general reply auto-insertion was happening in addition to code which inserted your new reply after publishing.

I removed the latter, but the issue in #6 will cause the reply not to show up sometimes until it is resolved.
