### ISSUE TITLE
patchwork stall...and ./bin.js error

### ISSUE THREAD

**Issue by brendanvg** [ssbc/patchwork#80]
When I run `patchwork` it doesn't give me an error message but it seems to be stalling out.... (no first-time on-screen instructions)....not sure how to start troubleshooting this...

Also when I run ./bin.js (with and without sudo) I get: 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3GetENS_6HandleINS_5ValueEEE
  Referenced from: /Users/joncox/patchwork/node_modules/ssb-keys/node_modules/chloride/build/Release/sodium.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3GetENS_6HandleINS_5ValueEEE
  Referenced from: /Users/joncox/patchwork/node_modules/ssb-keys/node_modules/chloride/build/Release/sodium.node
  Expected in: dynamic lookup

**Comment by pfraze** [comment]
This one looks like a version issue. We currently work for node 4. Which are you running?

relevant, https://github.com/ssbc/patchwork/issues/78
