### ISSUE TITLE
<code> style

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#800]
I think a full-blown syntax highlighter is probably out of the question, but I'm thinking some `<code>` style to match `<pre`> might be nice. I'm thinking something like this?

```
code {
    background: #fbfbfb;
    border: 1px solid #eee;
    padding: 0em .25em;
}

pre > code {
    background: none;
    border: none;
    padding: 0;
}
``` 

I've made sure to unset the CSS when it's code-fenced in a `<pre>`, but I wanted to get some feedback on whether this would be something you'd like in Patchwork or whether I should just keep it in my client.

**Before**:

![screenshot from 2018-05-10 12-21-24](https://user-images.githubusercontent.com/537700/39889425-b19d2cb8-544c-11e8-9b0f-60ee28871f4b.png)

**After**:

![screenshot from 2018-05-10 12-20-54](https://user-images.githubusercontent.com/537700/39889429-b5eec222-544c-11e8-80ef-26857589bdf9.png)

---

Note: I (mis)typed `padding: none` in the screenshot, but it should really be `padding: 0` like in the above code. I also changed the height padding after the fact as it screwed with the line-height. Example: ssb://%ZlixeC0p3BN1+jShs0DxGk/MrkP+H5DocAnHewpnDYA=.sha256

**Comment by magician11** [comment]
I quite like minimal formatting Slack offers. Things like code blocks and emphasis.

https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages
