### ISSUE TITLE
Option to put more information into the profile hover/tooltip

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#803]
My "who to follow" list just had a couple of people whose name/picture made me curious. So I clicked on one, and then went back eventually, but now the list had changed. Given how I cannot middle-click in Patchwork to open a tab (Patchbay can do that…), it'd be nice if I could configure patchbay to not just show me photo/name/key, mutual friends, and the follow button, but maybe also their biography, and maybe even the top of their timeline.

Not everyone would want it (as it needs to be loaded…), which is why there probably ought to be an option.

**Comment by mmckegg** [comment]
Yep, I agree that this would be nice. But merging this with #780!
