### ISSUE TITLE
Confirmations on creation of a gathering

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#804]
I just created my first gathering, and out of habit clicked "publish" to see if the markdown renders correctly (it didn't). But I was surprised that unlike regular postings, where I am asked for confirmation, the gathering just went online. Sure, I could edit it, but that was unexpected nonetheless.

**Comment by mmckegg** [comment]
Just recently merged #810 which now clearly labels actions that have a preview. 

I agree that it would be nice to have a preview on the gathering creation, but it is a little bit fiddly because gatherings are not just a single message, so they can't be previewed using the standard mechanism.

**Comment by mmckegg** [comment]
Okay, this has now been implemented in d513ed5cfa8254cfdde42c0391ea107d3ef9edd8 and will be in the next release!

Closing!
