### ISSUE TITLE
Local users not appearing on Linux

### ISSUE THREAD

**Issue by jackinthenet** [ssbc/patchwork#805]
#99 seems broken on Linux.

I've got a Windows and a Linux machine side by side on the same network.
They're successfully sending messages to each other with no other connections.
The "Local" list is only appearing on the Windows machine.

**Comment by mmckegg** [comment]
@jackinthenet 

The UDP broadcasts need to be able to reach the LAN for a local peer to show up. Have you got another linux machine you can try to see if it is the transmission, or receiving end that is causing the problem? 

Windows is more likely to blame here as its default firewall can mess with this sort of stuff. You need to make sure that you allow Patchwork access to the network:

![39909418-9b658818-54a7-11e8-9a16-e7a101cfadc6](https://user-images.githubusercontent.com/66834/40260863-2ebd231e-5b51-11e8-9218-b1759d64898e.png)

https://www.online-tech-tips.com/windows-10/adjust-windows-10-firewall-settings/

**Comment by jackinthenet** [comment]
Windows Firewall is already set to allow traffic on both private and public networks.

I haven't got another working Linux machine handy, but I can probably get a friend to help test the local networking sometime in the next few days.
