### ISSUE TITLE
Change "Publish" button label to "Preview and publish"

### ISSUE THREAD

**Issue by ivilata** [ssbc/patchwork#810]
Since messages in SSB cannot be edited so the user need be extra careful when posting, and hitting "Publish" actually shows you a preview dialog before really posting, it would be nice that the button label was explicit about this (e.g. by changing it to "Preview and publish") so that the user knows that hitting the button doesn't post the message straight away and gives an opportunity for preview (so that one doesn't need to prepare and preview the message in an external tool).

**Comment by mmckegg** [comment]
Implemented in #817 and #818. Closing!
