### ISSUE TITLE
Add electron updater so Patchwork automatically can get the latest version

### ISSUE THREAD

**Issue by mrchrisadams** [ssbc/patchwork#811]
Hi there,

I get that Patchwork is supposed to be decentralised, and yet, I'd still find it useful if Patchwork, when there _was_ an internet connection, was able to update itself without the user having to manually download the latest version each time.

If you're not using Linux, I'm not aware of a easy to do this.

However, I think you can add auto-update functionality like provided by [Sparkle](https://sparkle-project.org/), by using [electron-updater](https://www.electron.build/auto-update).

Would something like this be something that would be accepted to the project if I worked on it?

If so, I'm happy to have a go at it.

**Comment by mrchrisadams** [comment]
Oh neat, so it look like you can do this with Homebrew too - this isn't a bad stopgap, assuming the homebrew version is recent:

```
brew search patchwork
==> Searching local taps...
==> Searching taps on GitHub...
homebrew/cask/patchwork

```

**Comment by mrchrisadams** [comment]
Ah, it looks like this might be a better bet to look in to, right?

https://github.com/ssbc/patchwork-builder

**Comment by mrchrisadams** [comment]
Hello @mmckegg, I'm standing next to you at jsconf 👋

**Comment by daviewales** [comment]
So... Here's a possibly related idea.

Suppose Patchwork had its own SSB feed. Then, suppose the latest version of patchwork was posted on said SSB feed.

Now, suppose functionally was added to the Patchwork client to automatically update itself if it's subscribed to the Patchwork SSB feed and it receives an updated file.

Now, anyone who follows the Patchwork feed will get Patchwork updates, even if they are off-grid!

**Comment by mmckegg** [comment]
@daviewales 

What you are describing is the case with blobs. They only get synced when you specifically request them.

**Comment by christianbundy** [comment]
We're using electron-builder in `master` now, so I'd merge a PR for this. :+1:
