### ISSUE TITLE
Fix tab+enter to post comment behavior

### ISSUE THREAD

**Issue by alannallama** [ssbc/patchwork#813]
My understanding is tab+enter generally means "post/enter/submit" in a lot of software, and my muscle memory certainly thinks so. Currently if you tab it jumps to the "attachment" option and enter opens the "pick file" dialogue. If it could jump to "reply" instead, that would be grand.

**Comment by mmckegg** [comment]
**Implementation hint:** This should be possible to do by adding a manual [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to the elements in [modules/message/html/compose.js](https://github.com/ssbc/patchwork/blob/master/modules/message/html/compose.js#L107)

I'm not sure if this is really that common though. I just tried on Github, Facebook and Twitter, and none of those _tab_ to the submit button on first press. On Github, it is also attach, and on facebook and twitter it is the emoji button.

Normally tab ordering just follows the user interface ordering

Though, I would be open to adding a Shift+Enter shortcut to send.

**Comment by robjloranger** [comment]
It is very common to have `ctrl + enter`  submit whatever you are composing. Github, Twitter, Gitlab, etc.

**Comment by christianbundy** [comment]
I think these are two different behaviors:

- **`<ctrl> + <enter>`:** when selecting an `<input>` element most browsers will let you submit the form with this chord
- **`<tab>, <enter>`:** sometimes the submit button is the first element after the form so you can use `<tab>` to select the submit button and `<enter>` to select it.

I've never used either, but it seems that `<ctrl> + <enter>` is a standard browser behavior.

**Comment by robjloranger** [comment]
I use `<ctrl> + <enter>` all the time, it might just be me :grin:

**Comment by robjloranger** [comment]
I'll take this one if no one else has yet.

**Comment by robjloranger** [comment]
There's a bit of trouble with the tabindex on the file input button. Since the element is created in another module, we would have to change the signature of `FileInput` from the module create method in `module/blob/html/input`.

**Comment by robjloranger** [comment]
Any further thoughts on this one? If not I can go ahead and try again for just submitting via `tab+enter` with the input field focused.

**Comment by mmckegg** [comment]
@robjloranger 

I've thought about this a bit more, and based on the problems with tab-order you mentioned above, maybe **Shift+Enter** would be okay.

It would be important that the confirm box could to be dismissed using **esc**. Also, having the "Confirm" button focused by default could be risky, but it is probably the best option.

If you implemented that, I'd be very likely to merge it 👍

**Comment by robjloranger** [comment]
OK, so **shift+enter** *not* **Ctrl+enter**?

Some applications do use this pattern, but in my experience the control key is much more common. Either way is good though.

I could possibly also use the same combination in the confirm dialog, so once opens the dialog and a second time confirms.
