### ISSUE TITLE
Patchwork 3.9.0 crashing on load

### ISSUE THREAD

**Issue by rabble** [ssbc/patchwork#821]
When i try and load patchwork 3.9.0 today it dies right away. Patchbay with my same .ssb file loads but doesn't display a window. How do i debug this and find log information about the crashing?

Is this a corrupted .ssb db?

**Comment by rabble** [comment]
So i fixed it by blowing away my .ssb directory and saving my secret. Still this seems less than idea and i think there should be better solutions to recovery.

**Comment by mmckegg** [comment]
@rabble 

Generally you shouldn't have to trash your entire .ssb folder. Usually just deleting the indexes should be enough.

You can safely delete everything in `~/.ssb/flume` except `log.offset` and then you won't have to re-download anything, but the indexes will rebuild from scratch.

This could be a good automated "repair" option. Maybe clients should display an option to do this if certain "weird" errors occur.

**Comment by mmckegg** [comment]
> How do i debug this and find log information about the crashing?

If you run Patchwork from the command line, it will print out debug information to the terminal.
