### ISSUE TITLE
Is that possible to have the installation of SSB/patchwork in a USB thumbdrive?

### ISSUE THREAD

**Issue by deepcell** [ssbc/patchwork#822]
For example, my fedora is installed in a thumbdrive, is that possible to make the installation of SSB/patchwork in another thumbdrive (I want have it dedicated with a 64gb usb drive)? It would be very nice if this was an option.
Thanks for any idea.

**Comment by Serkan-devel** [comment]
I guess if one places the `.ssb` on the drive and configure patchwork to run from there, it could work

**Comment by deepcell** [comment]
I will try that, just to say in my Fedora it is also in my .config/
folder, then I have it in 3 different locations:

~/.config/Patchwork/ (it includes cache, local storage, cookies,
preferences, dict..)
~/.ssb/
~/Downloads/Patchwork-3.9.0-linux-x86_64.AppImage (executable)

I just move it all to the usb drive (size about 700mb)

Then I executed Patchwork and I think I messed up, because it recreate
all the folder I  mentioned above and it is empty. The Patchwork App
there is nothing related to data source, paths, etc.. perhaps I have
to check the source code and compile myself.

Any idea which file is related to configuration?

On 6/26/18, Serkan-devel <notifications@github.com> wrote:
> I guess if one places the `.ssb` on the drive and configure patchwork to run
> from there, it could work
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ssbc/patchwork/issues/822#issuecomment-400343176


-- 
PGP Key ID: 0x3F75FA35

**Comment by stripedpajamas** [comment]
@deepcell the problem is that Patchwork looks in `~/.ssb` for your secret+db, and if it doesn't find it, it initializes fresh. Patchwork pulls in [ssb-config](https://github.com/ssbc/ssb-config) and that allows a path override. right now, the config overrides aren't configurable in Patchwork -- [this line](https://github.com/ssbc/patchwork/blob/master/index.js#L46) specifies a `server` override but nothing else.

@mmckegg I could add a command line option (e.g. `--ssb-dir <dir>`) to pass into `ssb-config` to support USB Patchworkers?

**Comment by deepcell** [comment]
@stripedpajamas I downloaded a fresh new copy and apply your changes [](https://github.com/ssbc/patchwork/pull/829) to the files, then try to run again calling with the parameters, but it still looking the same .ssb source. 

`[crown@localhost patchwork]$ npm start --ssb-dir /run/media/crown/EXT/Scuttlebutt/.ssb/ --path /run/media/crown/EXT/Scuttlebutt/.ssb/

> ssb-patchwork@3.10.0 start /run/media/crown/EXT/Scuttlebutt/New/patchwork
> electron index.js "/run/media/crown/EXT/Scuttlebutt/.ssb/" "/run/media/crown/EXT/Scuttlebutt/.ssb/"

{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  path: '/home/crown/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1K3LiKZvAvjbY1ziZ33MXawbCEI16qwjCbm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: 
   [ '/run/media/crown/EXT/Scuttlebutt/.ssb/',
     '/run/media/crown/EXT/Scuttlebutt/.ssb/' ] }
git-ssb is not installed, or not available in path
`
Do I need git-ssb installed?

**Comment by stripedpajamas** [comment]
@deepcell ok two things: first is that in my PR i ended up using the command line option `--path` or `-p`, not `--ssb-dir`. second is that to pass arguments to npm you have to do a kind of weird syntax:

```
npm start -- --path /run/media/crown/EXT/Scuttlebutt/.ssb
```

can you give that a shot?

**Comment by deepcell** [comment]
@stripedpajamas outstanding.. it works perfectly. The issue was with the command line option, my bad, you stated that was --path and not --ssb-dir. 
Now I can carry my social network in my own pocket!
About your PR, I just download a fresh new copy and it not there yet.. anyway, I have my own copy now and working as expected.
Also I just checked my home folder, and this time nothing was created there. perfect!
Thanks a lot for your time and effort.

**Comment by stripedpajamas** [comment]
@deepcell awesome! :) @mmckegg gave me some tips on my PR that made it pretty much unnecessary except to stop it from erroring out on git-ssb-web. for your use case using `--path` was already supported it turns out :) 

cheers

**Comment by stripedpajamas** [comment]
@mmckegg this can be closed
