### ISSUE TITLE
search doesn't seem to be returning all results

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#823]
Not sure if this was since #789, but I just noticed that search is not returning all results for a given term.

For example, the search "hermies" returns 0 results.

"scuttlebutt" only returns 17 results

Any ideas @christianbundy, @arj03?

Hopefully I'll have time to investigate this on Friday.

**Comment by christianbundy** [comment]
That's not good. Any idea what might be triggering the issue?

"hermies" isn't returning any results, but "hermes" seems to be returning 5 results. Could that one be a typo?

I'm getting 81 results for "scuttlebutt". Here's my console results:

```console
$ npm start -- --disable-gpu

> ssb-patchwork@3.9.0 start /home/christianbundy/Source/patchwork
> electron index.js "--disable-gpu"

{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  path: '/home/christianbundy/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  'disable-gpu': true }
git-ssb is not installed, or not available in path
RELOAD 2 350674477
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
1835032 3932192 524288 2097160
RELOADED 350674477
```

I'm using `--disable-gpu` to resolve what I believe to be a driver incompatibility with Electron: https://github.com/electron/electron/issues/12820

**Comment by mmckegg** [comment]
@christianbundy 

Both "hermies" and "hermes" are valid names for the little scuttlecrab. If the search was working, you'd find some interesting discussions about this exact thing 😆 

Anyway, I discovered that deleting `~/.ssb/flume/search` and letting it reindex fixed the problem. It looks like the search is only including new posts added since upgrading to the latest scuttlebot. This seems to imply to me that there has been a schema change without an index bump on `ssb-search`. 

I'm going to go ahead and make a PR to add a bump, and this should fix the problem.

cc @dominictarr @arj03

**Comment by christianbundy** [comment]
Wow, I'm getting _way_ more results now. Can't find any discussions on the spelling by searching "hermes hermies", any other search query you can suggest?

**Comment by Serkan-devel** [comment]
What search engine is used anyway?

**Comment by christianbundy** [comment]
@Serkan-devel 

I believe it's [ssb-search](https://github.com/ssbc/ssb-search), which uses [flumeview-search](https://github.com/flumedb/flumeview-search).

**Comment by mmckegg** [comment]
Anyway, this has been fixed now, so closing!
