### ISSUE TITLE
including full res blob images directly in patchwork is making it slow and using a lot of ram

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#830]
I did some profiling of images vs no images, and the scrolling become much smoother. Also, the ram usage was much lower.

A possible optimisation would be to resize each blob to a thumbnail + medium res on first load and then cache the result. This could be handled by ssb-blobs.

**Comment by gmarcos87** [comment]
Perhaps a new method can be added at https://github.com/dominictarr/multiblob-http/blob/master/index.js
Something like /get/HASH/preview and generate a thumbnail  and put it in a cache.
So if you click on the content you see the original image in full resolution, but for the feed with the thumbnail it is sufficient and more efficient.

**Comment by mmckegg** [comment]
Yes that sounds good @gmarcos87! But I think it would be good if the client could specify a specific resolution so that we can optimize for (lack of) retina/hidpi screens etc.

Probably get huge gains just applying it to avatars, so my comment above might not be completely necessary. Patchwork does already size avatars to 500x500 on upload (I believe) so this won't be a huge problem compared to the massive images straight of digital cameras.
