### ISSUE TITLE
error when trying to follow the Replies (return arrow) link.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#84]
This happened on this message: %W2lo49ES4NWamaxyBVD+4zFb5NRHDsCdCZI58xzn43E=.sha256
trying to follow the link to the replied to message.

_this3.props.onSelect is not a function

TypeError: _this3.props.onSelect is not a function
    at /home/dominic/c/ssb/patchwork/ui/com/msg-view/index.jsx:179:66
    at /home/dominic/c/ssb/patchwork/ui/lib/util.js:334:9
    at /home/dominic/c/ssb/patchwork/node_modules/multicb/index.js:40:13
    at /home/dominic/c/ssb/patchwork/ui/lib/util.js:397:5
    at Object._requests.(anonymous function) (/home/dominic/c/ssb/patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/dominic/c/ssb/patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/dominic/c/ssb/patchwork/node_modules/muxrpc/node_modules/packet-stream/index.js:122:41)
    at /home/dominic/c/ssb/patchwork/node_modules/muxrpc/pull-weird.js:56:15
    at /home/dominic/c/ssb/patchwork/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
    at /home/dominic/c/ssb/patchwork/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9

This was an unhandled exception.

**Comment by dominictarr** [comment]
It also stalled patchwork so that [close] does nothing and I had to restart.

**Comment by pfraze** [comment]
I ran into this and solved it, in `ui-rework-2` or `mix-chrome` somewhere.

**Comment by pfraze** [comment]
Leave open until both are merged into master and we can confirm fixed.

**Comment by pfraze** [comment]
Confirm fixed, thought the replies arrow looks like garbage still
