### ISSUE TITLE
Warning for replies without any mentions

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#843]
I love the UI for posts that tells you whether posts will be private or public, and who exactly can decrypt your message. I also *don't love* how easy it is to reply to a message and forget to mention the person you're replying to.

Do you think it would be appropriate to use the same "warning" UI for public replies that don't message anyone in particular? The only edge-case I can think of is replying to your own post in order to chain posts, which is a case where you'd reply without mentioning anyone. Otherwise, I think a mention reminder would be super useful.

I'd love to volunteer some time to work on this, if it's within Patchwork's scope. :upside_down_face:

**Comment by mmckegg** [comment]
Hmm, interesting thought. I'm open to letting someone experiment with this 😀

**Comment by funwhilelost** [comment]
@christianbundy - alternatively my Mastodon client and others just automatically add the "@user" mention to the reply text box

**Comment by christianbundy** [comment]
Yeah, that's what I'm currently doing in Oasis and it works great. The only downsides:

- right now it mentions me when I reply to myself, oops
- when replying to a thread you don't only want to reply to people in the thread, but it seems weird to auto-fill *everyone* in the thread :man_shrugging:
