### ISSUE TITLE
cache files in ~/.config?

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#852]
I just found a ~200MB folder called "Cache" in `~/.config/patchwork`.
I'm fairly sure that's what `~/.cache` is for :P

**Comment by mmckegg** [comment]
I found this: https://github.com/electron/electron/blob/6f91af93433df4e9c0e7fb592e5b2dcb0b1c7888/chromium_src/chrome/common/chrome_paths_linux.cc#L77-L83

```c
// See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
  // for a spec on where cache files go.  Our rule is:
  // - if the user-data-dir in the standard place,
  //     use same subdirectory of the cache directory.
  //     (this maps ~/.config/google-chrome to ~/.cache/google-chrome as well
  //      as the same thing for ~/.config/chromium)
  // - otherwise, use the profile dir directly.
```

**Comment by black-puppydog** [comment]
well, that doesn't seem to work for me. does it handle a symlink `~/.cache` correctly? mine is symlinked to not have the cache on a (slow, space-limited) nfs

**Comment by black-puppydog** [comment]
not stale.

**Comment by christianbundy** [comment]
I think this needs to be resolved upstream: https://github.com/electron/electron/issues/8124

**Comment by black-puppydog** [comment]
yeah, but it doesn't look super likely... :/

**Comment by christianbundy** [comment]
Don't think we can do anything about this unfortunately, I'm going to close for now.
