### ISSUE TITLE
Updating an AppImage

### ISSUE THREAD

**Issue by stml** [ssbc/patchwork#857]
The latest release is the first time I've updated an AppImage. Do I just overwrite the existing one? Does all my SSB data (keys, logs, etc) persist elsewhere if I do this? If so, where, and if not, what's the correct procedure?

It might be helpful to add an updating guide to the Readme / FAQ (or index it better if it already exists).

**Comment by christianbundy** [comment]
@stml Yep, your steps should be:

1. If you haven't already backed up `~/.ssb` somewhere, do that now!
  - All of your important SSB files are in the `~/.ssb` directory.
  - The most important files are `~/.ssb/secret` and `~/.ssb/manifest.json`.
2. Download the new one and `chmod +x Patchwork-3.11.0-linux-x86_64.AppImage`
3. Run the new AppImage.
4. You can delete the old version of Patchwork whenever you like, the only important bit is that you won't be able to run both at the same time.

**Comment by christianbundy** [comment]
Closing this, please let me know if you have any follow-up questions!

**Comment by Serkan-devel** [comment]
Can't there be [AppimageUpdate](https://github.com/AppImage/AppImageUpdate) in place?
@probonopd

**Comment by probonopd** [comment]
Sure. Just include update information in the AppImage.

**Comment by christianbundy** [comment]
Is this the same problem space as #811? If so, we should probably continue the discussion over there since it was opened earlier.

**Comment by probonopd** [comment]
No, #811 talks about an electron related update mechanism whereas I am talking about he official AppImage update mechanism. 

Please see https://docs.appimage.org/packaging-guide/updates.html for more information.

**Comment by christianbundy** [comment]
Thanks for the context. I'm reading that there are some [issues with electron-builder](https://docs.appimage.org/packaging-guide/updates.html#using-electron-builder) but still likely possible. I'd love to see an issue or PR in https://github.com/ssbc/patchwork-builder for this.

**Comment by probonopd** [comment]
>  I'd love to see an issue or PR in https://github.com/ssbc/patchwork-builder for this.

Did you open one @christianbundy?

**Comment by probonopd** [comment]
This is still relevant. I don't know what is blocking it and I don't know what I can do to help move it forward. But I know for sure that doing nothing does not justify to close a ticket, ever. So I don't get why people use the stale bot. Go away.

**Comment by christianbundy** [comment]
Hey @probonopd. :wave: 

Keeping issues open indefinitely makes it difficult to know which issues are still relevant to a project, so we only keep open issues that are actively being discussed or are assigned to a team member. If you'd like to keep an issue open you're welcome to discuss or resolve the problem, but keeping hundreds of inactive issues on our collective to-do list adds stress and confusion to an already-stressful process.

I'm happy to re-open this issue if you'd like to take it on, but it's not something that I can prioritize right now. The electron-builder packages has also deprecated AppImage with their latest release, so it's unclear to me what our next move should be.

**Comment by probonopd** [comment]
> The electron-builder packages has also deprecated AppImage with their latest release, so it's unclear to me what our next move should be.

@develar can you give some guidance please? I'd be surprised indeed if electron-builder would have deprecated AppImage without a clear migration path, given the large number of applications out there that are using electron-builder to make AppImages.

**Comment by christianbundy** [comment]
Oops, it looks like I misread the info from here:

https://www.electron.build/configuration/appimage.html

I thought they were deprecating AppImage support in general, I didn't realize that it was just the desktop integration.
