### ISSUE TITLE
Agglutinative languages not easily supported by design

### ISSUE THREAD

**Issue by ppseprus** [ssbc/patchwork#868]
**Premise**

While in English, one writes _xy subscribed **to** something_, the same will be _xy felíratkozott valami**re**_ in Hungarian. Note the bold parts.

And this is further complicated by the fact that to different words, such a language often _agglutinates_ different word parts.
_valami**re**_ but _dolog**ra**_ (to something, to (a) thing)

**Problem**

The current JSON structure only allows translations to such languages that are not really native-like.

**Comment by christianbundy** [comment]
Thanks for noting this problem. I'm not very familiar, how do other projects work around this sort of problem? Is there a translation-friendly way to structure sentences, or is your suggestion to change the current translation implementation?

**Comment by ppseprus** [comment]
Well.. I have one thing. Some lines are static while others include the "context" as argument. If there's anything around the text, that should always be part of the language file as _%s_ argument. This way, the translators are provided with a little bit more freedom.
Probably will make a PR for this one :P

**Comment by mmckegg** [comment]
Yeah, would love to redo all the strings with `%s`, however with the current i18n implementation it makes is impossible to have the substitutions be styled or hyperlinks (which we need, e.g. linking to a user's profile).

The way forward is to solve the formatting/hyperlink issue (maybe with a different [mutant compatible] i18n lib), and then write some kind of script that goes through all of the existing translations and reformats them with the new translations.

**Comment by ento** [comment]
I started a Japanese translation and came across this issue. @ppseprus do you have time to push up a PR, even if it's not completely finished? I could pick off fixing some of the string usages based on your work.

**Comment by ppseprus** [comment]
Hey @ento! Sure! I'm a bit busy, but will try to make time for this in the next 2-3 days! : )

**Comment by ento** [comment]
@ppseprus I just realized we won't be able to collaborate within this repo easily since I don't have write access (if I had, I could push commits to your branch directly). So: opening a PR isn't really necessary and just pushing up a branch to your repo will be sufficient. I could either make a PR to your branch in your repo, or make smaller PRs to this repo by cherry-picking some of your commits (if you don't mind) and maybe adding my own commits.

**Comment by gergelypolonkai** [comment]
This is a really hard problem, and even English has something similar: **a [insert word here]** vs. **an [insert word here]**. I donʼt think there is a working solution for this.

There are workarounds like “X feliratkozott a(z) Y cimkére” (“X subscribed to tag Y” literally), but that might require extra work on the English version, too.
