### ISSUE TITLE
"Add / Modify Tags" modal stays open after navigation

### ISSUE THREAD

**Issue by ppseprus** [ssbc/patchwork#869]
**Description**
a) The "Add / Modify Tags" modal stays open after navigation, OR
b) The user is able to navigate away while the modal is open

**Steps to Reproduce**
1. Navigate to eg. "Public"
2. Find a comment with tags
3. Click on "Tags" to see all tags for that comment
4. Navigate to "Private" of "Other/ANY_OPTION"

**Current Behaviour**
The user is add and modify tags on a comment that is -possibly- out of the view port.

**Expected Behaviour**
No ambiguous "state" occurs.

**Comment by mmckegg** [comment]
I have _somewhat_ addressed this in the latest master by displaying the name of the message that is the target of the tag editor, and when clicked, this brings the target message into view.

Gonna close this for now, since there is no longer an ambiguous state.
