### ISSUE TITLE
Allow dragging of attachment files directly into compose textarea

### ISSUE THREAD

**Issue by sganz** [ssbc/patchwork#878]
Would be nice to be able to add more then one attachment at a time. For example add 5 pictures at once. Things like that. Currently you must add one photo attachment at a time. 

Also possibly being able to add attachments by Drag and Drop while composing.

**Comment by sganz** [comment]
@mmckegg Thanks for the info, I'll try the D&D onto the button, which is not so obvious but at least something for starters. Will wait for the next release to try the multi-attachment option. 

Again thanks for the heads up.

Sandy

**Comment by mmckegg** [comment]
This will be included in the next release 😄
