### ISSUE TITLE
Show missing messages in threads

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#88]
When a message in a thread replies to a message which is not locally available, the UI should indicate that there's an unknown post.

**Comment by dominictarr** [comment]
have you seen any cases like this yet?

**Comment by pfraze** [comment]
I dont think so, but I also dont think we'd know for sure w/o code to render the missing msg.

**Comment by dominictarr** [comment]
We could collect all the conversations and traverse the internal links.
That might work.. Hmm unless you already have everything. What about we
just add logging for a missing message? Actually sometimes this might
happen during replication , depending on order.

**Comment by pfraze** [comment]
Here's the scenario where I see this happening:

Alice `--follows-->` Bob `--follows-->` Carla `--follows-->` Dan

Alice's FoaF doeesnt reach Dan.

- Bob makes a post (msg 1)
- Dan replies to Bob's post (msg 2)
- Carla replies to Dan's reply (msg 3)
- Alice opens Bob's thread, and sees msgs 1 & 3. 2 is absent.

I've got some code almost ready to detect this and render a "this message is missing" card.

**Comment by pfraze** [comment]
Done
