### ISSUE TITLE
Opening new channel throws an error and hangs forever

### ISSUE THREAD

**Issue by smowafy** [ssbc/patchwork#882]
I am running from source code `master, tag: v3.11.31`

Reproducing from my side is so straight-forward: Click `more channels`, then click on any channels. It hangs forever and this appears in the logs

```
TypeError: Cannot read property 'content' of undefined
at checkBump (/home/blabla/patchwork/sbot/channel-feed.js:124:17)
```

I logged the message object and it had no `value` property

**Comment by christianbundy** [comment]
Hey @smowafy, thanks for this bug report.

Is this your first installation of Patchwork, or is this an upgrade? Also, could you confirm that you're on tag `v3.11.3`? Currently `master` is a bit ahead of that, but it's nothing substantial.

**Comment by smowafy** [comment]
Hey @christianbundy 
I had the repo cloned long time ago but I pulled master a couple of days ago. Commit hash `9c2d895dcba2999fe4b8dde55865dd0e871da2e1`, I believe this is the one with the release tag.

**Comment by christianbundy** [comment]
I was just double-checking because you specified `v3.11.31`. :wink: 

The line numbers are slightly off, but it looks like [this](https://github.com/ssbc/patchwork/blob/9c2d895dcba2999fe4b8dde55865dd0e871da2e1/sbot/channel-feed.js#L119) is the problem.

That's a bit strange, it sounds like you have a message with no `value` property. I might try adding `if (!msg.value) { console.log(msg) }` above that line (at the top of the function) and see if you can determine exactly which message is breaking this:

```diff
function checkBump (msg, { channel }) {
+ if (!msg.value) { console.log(msg) }
  if (msg.value.content.type === 'vote') return
  if (normalizeChannel(msg.value.content.channel) === channel) {
    if (getRoot(msg)) {
      return 'reply'
    } else {
      return 'post'
    }
  }

**Comment by smowafy** [comment]
@christianbundy Oh sorry my bad! :sweat_smile: 

Wellp, these are a couple of messages

```
{ key: '%vJZ3Y+ZXUMaY98aPDMZcQ1EnPT9YNwOUgxL+Z8wH2OA=.sha256',
  value: undefined }
```
```
{ key: '%NzjGkn8uEBUH0JZzeJMawmzTbUIcQRWaGObfxnWpgsk=.sha256',
  value: undefined }
```

**Comment by christianbundy** [comment]
No problem, just wanted to double-check! Could you find out which version of Patchwork you upgraded from? Those messages should be:

```json
{
  "key": "%vJZ3Y+ZXUMaY98aPDMZcQ1EnPT9YNwOUgxL+Z8wH2OA=.sha256",
  "value": {
    "previous": "%IkCXgsal42u3ikf0nmwG25QiSc1PjM43rmMD/aEr6W0=.sha256",
    "author": "@ZcjYF92reFjUtEYdoJ8ulOI6N6klwAAaIkghEEHdvSE=.ed25519",
    "sequence": 1872,
    "timestamp": 1519673636353,
    "hash": "sha256",
    "content": {
      "type": "post",
      "text": "[@inoas](@vmpbPT6vLrwfg/ku77zHUAies5tgznTvEkTW1P0SX/U=.ed25519)  apropos the discussion on IRC about  companies initially being very open and then shiutting it down, see [\nSlack's XMPP gateway is broken, and they won't be fixing it](https://lobste.rs/s/3ymveg/slack_s_xmpp_gateway_is_broken_they_won_t_be)",
      "channel": "centralization",
      "mentions": [
        {
          "link": "@vmpbPT6vLrwfg/ku77zHUAies5tgznTvEkTW1P0SX/U=.ed25519",
          "name": "inoas"
        }
      ]
    },
    "signature": "53zMtRwl5ro4F3XF96TfEN0/NuSz8nymap+zG4+7DjFa1pGg0pK/0oD5LcEZcCTi+RXhy5GjfBdwblobkdExAA==.sig.ed25519"
  }
}
```

```json
{
  "key": "%NzjGkn8uEBUH0JZzeJMawmzTbUIcQRWaGObfxnWpgsk=.sha256",
  "value": {
    "previous": "%DCfoKG6gYzaOvnew734it/7vCBR9otAFeBUEZC3IGuE=.sha256",
    "author": "@O71isksx77Du8JQvsf91sdPwW4kPnlZgnw8IotOYxlM=.ed25519",
    "sequence": 98,
    "timestamp": 1494290027372,
    "hash": "sha256",
    "content": {
      "type": "post",
      "channel": "software",
      "text": "Bot coding progress:\n\nAs I mentioned before, my current contract is about coding chatbots. More specifically, we are building a bot scripting platform, that instruments a MS Botframework bot.\n\nThe last couple of days I've been working on trying to get the bot to go back to previous actions. This is not supported out of the box, and it brought many challenges. Finally got it to work, and my brain is fried. It was a good challenge!",
      "mentions": []
    },
    "signature": "Sa1jIcdGU1TEUgRR7G3WfvLRm8sYOAf6e4SohWPGXHDNo8FIpd5jH3Ek8a0eiO+q3+Gdcn2WSPzl4lvUCJ/XCA==.sig.ed25519"
  }
}
```

While you have Patchwork open, could you open another terminal, `cd` to your Patchwork directory, and run `npx sbot get '%vJZ3Y+ZXUMaY98aPDMZcQ1EnPT9YNwOUgxL+Z8wH2OA=.sha256'`?
