### ISSUE TITLE
stale issues and PRs being closed without comment

### ISSUE THREAD

**Issue by xloem** [ssbc/patchwork#888]
A bot is closing the issues and PRs.

Its behavior does not seem to relate to their importance, which it has no way to judge other than activity.  This seems a bad choice, as important bugs that are hard to address could disappear (and then even be reopened later without a link to the old work).

This just happened with an issue and PR I have interest in.

Wouldn't it make more sense for the bot to bug a developer to take the time to comment on whether the issue or pr was releven, or to decide whether to close themt, than to just close them without discernment?

**Comment by christianbundy** [comment]
Hey @xloem, sorry that #484 got auto-closed, I agree that it should remain open and I've reopened the issue. I'd love to hear your thoughts on how to improve how issues are handled in `%jn8ZQC3f6gCyuZFpA3uBNF5Nw6/LtXVYwpzV1sko6OA=.sha256` if you have time, but the gist is that open issues with *any* activity stay open and inactive/abandoned issues are closed. This makes the open issue list closer to an actual todo list, whereas in the past it was a big archive that we weren't taking care of.

**Comment by xloem** [comment]
hey @christianbundy, sorry I paniced so much when that closed.  I don't have the capacity at the moment to craft a solution, but I feel somebody should have to confirm that issues should be closed before they are closed automatically.  a script could operate slowly so as not to ask people for too much at once.
some issues are important security or functionality things that are simply on the backburner.  it's scary to think of them just disappearing.
