### ISSUE TITLE
Composer interface improvements

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#89]
- save drafts
- cmd+enter / ctrl+enter to send
- resizable interface

**Comment by pfraze** [comment]
Done

**Comment by black-puppydog** [comment]
am I missing something? I came here because I wanted to file an issue for "ability to save drafts". How do I do that in the current interface?

**Comment by christianbundy** [comment]
Hi @black-puppydog. I think this issue refers to automatic quicksaves that the app does, so if you navigate away from a form you can hit the back button without losing your content (as long as you don't wait too long).

If you're looking for permanent drafts I'd recommend creating a new issue with your feature request.

**Comment by black-puppydog** [comment]
Sorry that I keep coming back to this issue, but I *also* don't see `Ctrl-Enter` do anything in current patchwork. Did that get dropped somewhere along the way?
