### ISSUE TITLE
Adding large attachments crashes patchwork 

### ISSUE THREAD

**Issue by APayerl** [ssbc/patchwork#893]
On version 3.11.3 I tried to add a video file to the public message but this silently failed, no error prompt or anything. The only thing that happened was that the OS became extremely slow for a couple of minutes.

This was done on a machine running Debian 9 "Stretch"
Hardware:
Intel Core i7 2630QM
7.7GB memory
Wireless network 802.11n 2.4Ghz

The video file in question had a .mp4 extention
Video:
Dimentions: 1280*720
Codec: H.254
Framerate: 60 fps
Bitrate: 12012 kbps

Audio:
Codec: MPEG-4 AAC
Channels: Stereo
Sample rate: 48 000 Hz
Bitrate: 256 kbps

Also worth noting is that the file was "added" from the synced local dropbox folder.

**Comment by APayerl** [comment]
The file was 716.5MB so it is most likely same issue as you discovered.

Since I am not involved in the development here AT ALL I can't say I understood what you meant other then it's not possible if file is max ~50MB.

Though maybe obvious a social media platform unable to share video greater then 5MB will have a huge drawback.

**Comment by mmckegg** [comment]
> Since I am not involved in the development here AT ALL I can't say I understood what you meant 

This is a public issue on an open source project, so I left those breadcrumbs to help out anyone that wants to take a look!

> a social media platform unable to share video greater then 5MB will have a huge drawback.

Yes, indeed. Video sharing hasn’t really been a thing on ssb so far for this reason. There are a lot of considerations for allowing large files on a network where there are no central servers and each peer needs a copy of the data. 

So far, we’ve kept it simple (limit file size, so it doesn’t matter), but hopefully in the future we can integrate something like dat or webtorrent for large files. Although, availability is always going to be a problem. The people with the large files will need to be online at the same time as others want to download.

**Comment by mmckegg** [comment]
This is fixed by https://github.com/ssbc/patchwork/commit/7ad6ad81bb780543eefbe673c623f2b8f5f62ffa and will be included in the next release. Closing!
