### ISSUE TITLE
linux appimage segfault

### ISSUE THREAD

**Issue by joeyh** [ssbc/patchwork#894]
I have the appimage from november, which had been working, but is now crashing on startup with a segfault. No window is displayed. Also happens if I move ~/.ssb away, so it's not database corruption. It seems to have been caused by an apt-get upgrade of my debian system, I use debian unstable and guess some library changed in a way that broke it.

installed: X-AppImage-BuildId=c63ff340-1698-11a8-244f-6fa2e97de546 image: X-AppImage-BuildId=12082020-d7f2-11a8-38da-b9df64c5f934
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_patchw0QFgHA/AppRun.
Segmentation fault

(Now installed with npm and that's working.)

**Comment by christianbundy** [comment]
@joeyh Is there anything I can do to try to help reproduce the issue? I'm on Arch but I can run Docker containers and such if you think it would be helpful. The only issue I've had recently has been an issue with [metacopy[(https://www.spinics.net/lists/linux-unionfs/msg06109.html) and my solution was:

```sh
echo N | sudo tee /sys/module/overlay/parameters/metacopy
```

Odds are that you're experiencing a completely different problem, but my issue cropped up at the exact same time so I thought I'd include the information just in case.

**Comment by joeyh** [comment]
I don't have metacopy. My only hint about what it may be is that the
strace tries to read a selinux config file (which DNE) just before the
segfault.

statfs("/sys/fs/selinux", 0x7ffe185a2e90) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7ffe185a2e90)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/filesystems", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(4, "nodev\tsysfs\nnodev\trootfs\nnodev\tr"..., 1024) = 361
read(4, "", 1024)                       = 0
close(4)                                = 0
madvise(0x3c650a3da000, 8192, MADV_DONTNEED) = 0
access("/etc/selinux/config", F_OK)     = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xb87650} ---

But I think this is a red herring: the last thing libselinux's
init_lib() does is access(SELINUXCONFIG), so it's done before the
segfault.

-- 
see shy jo

**Comment by christianbundy** [comment]
Hmm, any chance you have a list of upgrades from `/var/log/apt/history.log` that might have triggered this, or are you updating pretty constantly? I'd love to track this down but I'm not sure how.

**Comment by cryptix** [comment]
If this turns out do be related to a system upgrade it means the AppImages are not fully self-contained and we probably should escalate it to electron-builder. (Maybe there already is an issue over there?)

**Comment by christianbundy** [comment]
https://github.com/electron-userland/electron-builder/issues/3206?

**Comment by christianbundy** [comment]
Hey @joeyh, I've created some new prereleases after all of our build dependencies have been updated. Could you check the releases and let me know if the AppImage is still causing problems for you? Thanks!

**Comment by joeyh** [comment]
ssb-patchwork-3.12.0-alpha.4-x86_64.AppImage works for me

-- 
see shy jo

**Comment by christianbundy** [comment]
Woo! Thanks a lot, happy to hear that this was resolved.
