### ISSUE TITLE
Dependency issue with har-validator 5.1.2

### ISSUE THREAD

**Issue by Aversiste** [ssbc/patchwork#897]
Hello,

I tried to build patchwork from the master branch using the § build from source section of the README. Please excuse me in advance for inaccuracies here, this is first time I use npm, or a real javascript project.

The `npm install` command fails with the following error:

    npm ERR! 404 Not Found: har-validator@5.1.2

The `har-validator` package is a dependency of `request`, which is a dependency of `nugget`, which is a dependency of `electron-download`, itself a dependency of `electron` ; so I am not even sure this is the right Github project to open an issue on. Anyway, the version 5.1.2 doesn't exist according to npm registry. The closet existing versions are [5.1.0](https://registry.npmjs.org/har-validator/5.1.0) and [5.1.3](https://registry.npmjs.org/har-validator/5.1.3).

What can I do ?

**Comment by cryptix** [comment]
Hmmm.. weird. Can you give use a `npm ls har-validator`? Or the debug log from npm? I’m not sure where this comes from or why it doesn’t pick the latest patch release...

**Comment by christianbundy** [comment]
Could you try `npm ci`? We have a lockfile so you should be able to use the exact same dependency tree.

**Comment by Aversiste** [comment]
@cryptix:
```
$ npm ls har-validator
ssb-patchwork@3.12.0-dev /home/tleguern/others/js/patchwork
└── (empty)
```
I uploaded npm log [here](https://www.bouledef.eu/~tleguern/junk/2018-12-06T13_52_03_010Z-debug.log).

@christianbundy:

```
$ npm ci                                                               
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code E404
npm ERR! 404 Not Found: har-validator@5.1.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tleguern/.npm/_logs/2018-12-06T17_13_48_544Z-debug.log
```

I uploaded resulting npm log file [here](https://www.bouledef.eu/~tleguern/junk/2018-12-06T17_13_48_544Z-debug.log).

**Comment by christianbundy** [comment]
Looks like someone [unpublished](https://github.com/ahmadnassri/node-har-validator/issues/112#issuecomment-437378269) that module and broke the build. I'll push a PR to fix this now, thanks for reporting!
