### ISSUE TITLE
Growth: measure and reduce churn

### ISSUE THREAD

**Issue by dcposch** [ssbc/patchwork#900]
Patchwork has made amazing progress. The nux is still rough, syncing is still slow, and there's still a few bugs (I create a new Gathering, I can't interact with it in any way until I hard quit and restart Patchwork). But it much faster and more stable than last time--getting better!

**Sadly, we have already lost a number of users**, including users who are smart, technical, and care about decentralization. They downloaded Patchwork, took it for a spin, then stopped using it.

Those users include @jondashkyle, @pfrazee, arcalinea, @feross, substack, etc, etc, and, until yesterday, myself. (I hadn't opened Patchwork in ~6mo). I visit those pages and see last activity > 1 year ago, which is a bummer. Pretty much everyone's still active on Twitter.

## Goal 1: measure churn

I don't know if Patchwork currently has any growth metrics. How many people ever run the installer? How many of those people manage to join a pub? How many make it thru the (long!) sync process? How many ever make a post of their own? How many are still users on day 2 / week 2 / month 2?

Those numbers are critical--the centrally controlled, ad-monetized services we're up against track them religiously.

Those services also track every click and page view. We don't need to be nearly as intrusive, but a basic ping (user with pubkey X has run the app / has made a post) would go a long way. It can even be opt-out at install time.

Side note: this is roughly the same level of tracking that Signal uses. No metadata is collected (due to org policy), no contents can possibly be collected (due to e2e encryption). Open Whisper Systems only stores {phone number, pubkeys, date created, date of last sync}. Just enough for accurate DAU/MAU/churn metrics & no more.

## Goal 2: reduce churn

TBD depending on the results of measurement. Where in the funnel are people dropping off?

I suspect that speed is a main factor. If we could wave a wand and make Patchwork load instantly and reliably, I bet we'd have higher retention.

## Stretch goal: reverse churn

Some of the most active contributors to the decentralized world--the people listed above, Devine and Rekka, etc-- have tried SSB and moved on. Now that the obvious bugs are mostly fixed, how do we start getting people to give Patchwork a second look?

**Comment by retrohacker** [comment]
Heya, coming back after a long hiatus today and saw this message.

I think the biggest thing for me is identity management. I keep losing my keys (upgrading laptops, doing fresh installs, etc) and it isn't clear how I should be backing them up :thinking: 

I'm going to be starting my 4th identity now. First classing "backup your identity" may be useful? Maybe this already exists and I'm ignorant of it?

**Comment by dcposch** [comment]
@retrohacker as far as I understand, the only good way to solve this requires **multi-writer support** in the underlying protocol. in other words, the underlying protocol must be OK with two devices that come online independently of each other to both post to the same scuttlebutt feed.

### user story

You install & start using Patchwork. You download Manyverse. (Side note: you want consistent branding across interfaces and the underlying protocol. Signal used to be "TextSecure" for SMS, "RedPhone" for calls, and "Axolotl" for the underlying E2E protocol. Only nerds understood this--a journalist who just wants secure comms would get confused. So they fixed the problem: it's now "Signal", "Signal" and "Signal Protocol". We currently have a thing called "Patchwork", "Patchbay", "Manyverse" and "Secure Scuttlebutt" lol.)

You go to Patchwork > Profile > Add Phone. It shows a QR code. You scan it with Manyverse. Welcome, DC!

Your phone shows latest posts immediately, starts connecting to pubs and syncing deeper history in the background.

You get a new computer. You install Patchwork, go to Profile (empty profile...) > Add Phone. You scan this new QR code. Phone prompts, "Add DCs-Macbook to your account?". You click yes. Computer profile changes from empty to mine, posts start syncing in background.


### possible implementation

The QR code contains pub information and secret keys. Pubs enforce a limit on how many devices are allowed to connect per user. The secret keys
- 1. allow the new device to decrypt PMs sent to user, same as the old device
- 2. allow the new device to post on behalf of the user
- 3. allow the new device to sign a message authenticating itself to the pubs

The devices don't communicate to each other at all (except as normal SSB peers)--they just talk to the same pubs, authenticated as the same user.

This is a rough draft. In the ideal case, secret keys are ephemeral and never shared across devices. But I think it would solve the problems @retrohacker is pointing out.
