### ISSUE TITLE
Re-enable Travis CI

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#905]
Hey @mmckegg, I noticed that we have a Travis config but that we've had some broken builds pushed to `master`. Would you mind if I enabled Travis, or would you prefer that the config file is removed?

**Comment by mmckegg** [comment]
@christianbundy Yeah, sure go ahead if it is straight forward.

Patchwork doesn't have any tests, so I never bothered, but I can see that ensuring that the dependencies build is pretty useful!

**Comment by mikeruddy** [comment]
@christianbundy just starting to look into this project and looking for a good place to start.

How useful/feasible would a test bed environment be? I'm imagining creating a snapshot of a known SSB state - and then using that state for E2E tests.

**Comment by christianbundy** [comment]
Oops, just realized that this issue is now resolved -- I'm going to close it now.

@mikeruddy You may be interested in https://github.com/ssbc/ssb-integration-tests, is that what you mean? I'm going to close this issue for enabling Travis CI but I'd be happy to discuss your ideas on another issue (or on SSB).

**Comment by mikeruddy** [comment]
Pinged you @christianbundy on SSB but not sure if you got it. I'll just paste here.

Your integration-tests link seems like it's on the right track but it didn't work for me.

My main motivation is to easily reproduce a system state for development purposes - and ideally that state would be a bug needing to be resolved. Say I want to create a notification if I have zero friends, I wouldn't want to delete all my actual friends on patchwork. Or if a bug exists after I have 1000 friends, I wouldn't want to add 1000 friends.

Taken to the extreme, validating a bug could require including a database snapshot demonstrating the issue. And accepting the PR would require testing against the snapshot. And regression testing would be performed against the snapshot.

I have a few free days to get my hands dirty. Welcome to put me to work  :grinning: (on noobie tasks)
