### ISSUE TITLE
add optimistic updating back in for likes, follows, subscribes

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#906]
Or at least show in the interface that we are waiting for the backend to finish

When sbot is running slow, or during initial onboarding, clicking the various user action buttons does not update the user interface immediately.

This is a regression caused by #858. 

Ideally we'd fix it with some kind of holding tank solution, but it might just have to be a UI thing for now.

**Comment by christianbundy** [comment]
Is this like how it used to say "scuttling", or something different? I'm curious how easy optimistic updates are with Mutant, is that something we've done elsewhere?

**Comment by mmckegg** [comment]
This is something me and @pietgeursen have just been investigating.

Tomorrow I am going to attempt to tackle this. The plan:

- hook into publish [ssb-db/minimal.js:204](https://github.com/ssbc/ssb-db/blob/58d87c250b17438bf1d0bc5a7c2cdbc36af4052d/minimal.js#L204) and hold these messages (before being written to log and indexed) in memory.
- go through the various patchwork sbot plugins and update them to check this in memory cache for messages newer than the oldest result that match that particular query and append
- they'll also need some kind of notifier hook added for live streams
- something periodically cleans up the in memory cache of your posts once they have been properly written and indexed

This is entirely server side which means no weird hacks needed in client. Will be obsoleted when we switch to the new rust based indexing.

Requires a fork of `ssb-db`, but we should be able to keep the hook minimal enough to get it merged into master.

**Comment by mmckegg** [comment]
@christianbundy this is most visible while onboarding. Try clicking "Like" on a post or following someone while indexing is still in progress. Nothing happens (until indexing catches up minutes or so later).

**Comment by christianbundy** [comment]
I'm noticing that lots of folks are having issues with 3.11.x that don't seem to happen on `master`, so I'm excited to get this resolved and have a new release. Would it be alright to just disable these buttons when the indexes are behind?
