### ISSUE TITLE
AppImage fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by gh0st42** [ssbc/patchwork#907]
Executing AppImage 3.11.4 on Ubuntu 18.04 fails:
```
~/Downloads$ ./Patchwork-3.11.4-linux-x86_64.AppImage 
installed: X-AppImage-BuildId=c5ceb290-e2f6-11a8-07c2-b1ba5ffda287 image: X-AppImage-BuildId=c5ceb290-e2f6-11a8-07c2-b1ba5ffda287
/tmp/.mount_: symbol lookup error: /tmp/.mount_: undefined symbol: udata_setCommonData_59
```

```
~$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

Cloning the github repo, npm install and npm start work just fine on this system.

**Comment by christianbundy** [comment]
Hey @gh0st42, sorry to hear that you're having problems with Patchwork right now.

I'm not super familiar with debugging AppImages on Linux, but after searching the web for "undefined symbol: udata_setCommonData_59" it looks like this may be a common issue with other Electron applications.

Can you confirm that your packages are up-to-date with `apt-get update && apt-get dist-upgrade`?

**Comment by gh0st42** [comment]
Reboot didn't help, as expected..

**Comment by qypea** [comment]
As a point of reference my laptop is running 18.04 as well and is working fine with that appImage. In case it helps isolate the issue here's the list of packages I have installed(`apt list --installed`)
[packages.txt](https://github.com/ssbc/patchwork/files/2703918/packages.txt)

**Comment by christianbundy** [comment]
Are you using the same desktop environment and/or display manager? I'm trying to come up with which other variables might affect this.

**Comment by qypea** [comment]
I'm running xubuntu/xfce with the lightdm desktop manager.

**Comment by gh0st42** [comment]
Mmh.. my system was recently upgraded from 16.04 with unity to 18.04 using do-release-upgrade. I also tried installing the xubuntu-desktop meta package. This didn't help.. 
For the time being it's okay for me to manually start patchwork from the git repo and with `npm start` but for less techy people this might be more problematic and a showstopper.

**Comment by christianbundy** [comment]
I'm not sure, honestly. I've pushed some new prereleases, can you confirm whether this problem is resolved? Thanks!

**Comment by alancwoo** [comment]
I'm having a similar error with `v3.12.0-beta.2`:

> symbol lookup error: /tmp/.org.chromium.Chromium.85AHMT: undefined symbol: crypto_core_ed25519_scalarbytes

`lsb_release -a`
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.2 LTS
> Release:	18.04
> Codename:	bionic

**Comment by christianbundy** [comment]
@alancwoo I've just pushed a fix that should resolve this, could you let me know if it's working for you in the latest prereleases (or `master`)? Thanks!
