### ISSUE TITLE
Can't open Patchwork through ssh

### ISSUE THREAD

**Issue by eloyesp** [ssbc/patchwork#908]
I'm trying to open patchwork through ssh (because I'm not on my PC), but it seems that it does open the main window in a way that `ssh` with `ForwardX11` does not understand, any clues about how to make it work?

**Comment by christianbundy** [comment]
Could you post the command you're using right now? I don't know how to fix it, but I can run the command on my machine and add another data point for where the problem might be.

**Comment by eloyesp** [comment]
~~~
eloyesp@homepc:~$ ssh office
Linux office 4.18-amd64 #1 SMP Debian 4.18 (2018-11-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have mail.
eloyesp@cobre:~$ apps/Patchwork-3.11.4-linux-x86_64.AppImage 
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_PatchwGRFzEz/AppRun.
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  connections: { incoming: { net: [Array] }, outgoing: { net: [Array] } },
  path: '/home/eloyesp/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [] }
~~~

And it stays there. I've tested today using ssh to localhost and it does work.

**Comment by kaotisk-hund** [comment]
@eloyesp hi, just remembered from when I was running X apps through ssh. I think, and only think, that you need also an -X flag in ssh command to forward x11 properly. I think that when you enable this option you can use it with the -X flag. Try that if you are willing to :)

**Comment by eloyesp** [comment]
@kaotisk-hund I have the -X flag set as an option (Its `ForwardX11` on the config file).

The problem seems to be related with an old ssh version, it does work from with a newer version.

**Comment by eloyesp** [comment]
Sure, good idea:

- home: `I have OpenSSH_6.6.1p1 Trisquel_GNU/linux_7.0-1, OpenSSL 1.0.2g  1
Mar 2016`
- office: `OpenSSH_7.9p1 Debian-5, OpenSSL 1.1.1a  20 Nov 2018`

It does **not** work from home to office, but it does work when connecting
from office to home.

**Comment by christianbundy** [comment]
Thank you! That's super helpful.
