### ISSUE TITLE
automatic blob garbage collection (prune)

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#909]
Add an option to patchwork that allows the user to choose the maximum amount of blobs to store, and some kind of algorithm to clamp to that size. 

Treat blobs as a cache rather than permanent.

### An idea for handling cleanup:

- specify a max cache size in options
- on patchwork startup, scan and prune blobs 
  - scan all blobs and check if has a backlink from someone you follow or a foaf, if not delete it!
  - start deleting blobs if blobs folder exceeds max cache size, prioritized by
    - oldest blobs from people you don't directly follow (foafs)
    - random blobs from people you follow that are older than 1 month
    - any random blob

**Comment by christianbundy** [comment]
Just wanted to let you know that this is [on my radar](https://github.com/fraction/ssb-blob-prune) and will be packaged into an ssb-server plugin, most likely along with a blocked feed prune. :upside_down_face:
