### ISSUE TITLE
Dark theme scroll bars still light

### ISSUE THREAD

**Issue by despens** [ssbc/patchwork#912]
For some operating systems with permanently visible scrollbars, they stand out in dark mode as they seem to miss appropriate styling.

![selection_2018-12-29_10 44 37](https://user-images.githubusercontent.com/571494/50536640-c3b4a680-0b56-11e9-88df-7f9b7e432670.png)

I'm using Gnome Shell 3.28.2 on Ubuntu 18.04, and am going with the AppImage release of Patchwork.

navigator.userAgent returns `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Patchwork/3.11.4 Chrome/61.0.3163.100 Electron/2.0.13 Safari/537.36`

BTW, none of the scrollbars in Chrome, Chromium, or any other Electron app, are styled according to whatever global theme I chose, they always look the same.

**Comment by robjloranger** [comment]
What operating system is this on? Window manager if applicable as well.

**Comment by despens** [comment]
This is Ubuntu 18.04. 

Chrome/Electron apps do not have the system theme or window manager draw the scrollbar, it looks the same whatever styling used. Users resort to [extensions](https://chrome.google.com/webstore/detail/adwaita-scrollbars/gmfneilejimcjeceddlmingimegkdmef?hl=en) for fixing that in Chrome.

**Comment by robjloranger** [comment]
Interesting, I'm guessing unity?

I'm running i3 on arch and mine are themed.

**Comment by despens** [comment]
Thanks for guiding this, @robjloranger. I did a bad job in describing the issue, hope the new edited version is more helpful.

**Comment by christianbundy** [comment]
Oops, I mislabeled this as a bug -- I think we *may* be able to resolve this by adding CSS rules for the scrollbar, but I'm conflicted over whether we want to mess with them :man_shrugging:

**Comment by despens** [comment]
It looks like the scrollbars are now dark in dark mode in the Patchwork 3.14.1 AppImage release! Nice!
