### ISSUE TITLE
Option for manual searching for an update of the app

### ISSUE THREAD

**Issue by AssetBurned** [ssbc/patchwork#913]
Hi,

There should be an option, within the Patchwork menu, to check if an update of the app is available.

It would be even better if there would be also an optional auto update feature, but manual checking is the minimum I would expect of an app.

CU AssetBurned ;-)

**Comment by Powersource** [comment]
It does check for updates when you launch the app. If there's an update, a bar at the top will tell you about it.

**Comment by gergelypolonkai** [comment]
The functionality is there, thereʼs just no way to use it manually.

Also, on top of this, update checking should be done periodically (maybe based on a new user setting.) I donʼt know about others, but i often leave my Patchwork running on my notebook and this might be useful for such users.

**Comment by Powersource** [comment]
I believe this was fixed by https://github.com/ssbc/patchwork/pull/1084
