### ISSUE TITLE
Add option to opt into public hosting

### ISSUE THREAD

**Issue by steelman** [ssbc/patchwork#914]
(I am sorry if this isn't the right place to report bugs about the viewer)

# Steps to reproduce:

0. Open Patchwork.
1. Post a message.
2. Get its external [link](https://viewer.scuttlebot.io/%25GWnRLzfXjIUnkeAMVao8IrELNdtDa9RU5jCh5Cg5qfc%3D.sha256) 
3. Open in a browser.
4. Click the [@steelman](https://viewer.scuttlebot.io/@NBeFgSSWNtEo0yALqRoKsIF0U0rCFmCXwEbNUmIygeQ=.ed25519) link right next to the avatar.

# Expected result:

Some kind of a user profile/timeline is presented.

# Actual result

"Forbidden"

**Comment by christianbundy** [comment]
@steelman 

I've moved this issue to the Patchwork repository, maybe @mmckegg can comment on whether he wants `publicWebHosting` implemented (or how it should be done)?

**Comment by ksze** [comment]
@dominictarr 

> aha, this post explains it `%Fli0kemExYgucD1fLJm50qD5WptN6wZpsfIXddQpvNI=.sha256`

Is this supposed to be publicly accessible? I get HTTP 400 when I try to open https://viewer.scuttlebot.io/%Fli0kemExYgucD1fLJm50qD5WptN6wZpsfIXddQpvNI=.sha256

**Comment by christianbundy** [comment]
@ksze https://viewer.scuttlebot.io/%25Fli0kemExYgucD1fLJm50qD5WptN6wZpsfIXddQpvNI%3D.sha256

Profiles have been implemented as well, e.g. https://viewer.scuttlebot.io/@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519

**Comment by ksze** [comment]
@christianbundy But it's still not doable via the Patchwork client, right?

**Comment by christianbundy** [comment]
Oops, that's correct. I forgot that I'd moved this issue from the viewer repo to the Patchwork repo.

**Comment by Powersource** [comment]
(to clarify for anyone reading along, it being assigned to me doesn't mean I'm going to implement it, it's just so stalebot doesn't close it again)
