### ISSUE TITLE
voice / video mail

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#931]
prrrrp! here's a wee feature request, feel free to ignore. :smiley_cat: 

Scuttlebutt is really great for async communication, but so far we can only write messages with text or images. what if we could easily record audio or video snippets and post those too! :love_letter: 

basically i've come to enjoy using Signal's voice mail to send quick messages, when i'm either too lazy to type or i want to share something as a voice stream of consciousness. :speaking_head: 

we could use something like https://github.com/muaz-khan/RecordRTC or another module, this could also be a suitable well-scoped contribution for any new contributors, happy to support anyone who might be interested in this as well. :heart:

**Comment by nampdn** [comment]
I think it is possible to use WebRTC or IPFS. But the video is large which is should not be replicated to peers node. As to stream video, we need to have that peers who are holding the video online as utilize their internet traffic.
Would you like to build one on top of SSB and IPFS @ahdinosaur?

**Comment by ahdinosaur** [comment]
>  Would you like to build one on top of SSB and IPFS @ahdinosaur?

@nampdn i don't have the time or energy to build this now, sorry, at the moment i just want to capture my desire for this feature to exist.

with regards to IPFS, i was thinking since the voice / video mail would be small, we could use the existing SSB blob system, then in the future i'd love to see SSB blobs be superseded by [Dat](https://datproject.org/) blobs, since Dat seems to be more culturally aligned with SSB then IPFS, what with the technicals being very similar, but that's only a personal opinion.

**Comment by voronoipotato** [comment]
peertube may be a good example to pull from https://github.com/Chocobozzz/PeerTube . Essentially it uses webtorrent. Not sure how similar this is to dat files etc.
