### ISSUE TITLE
Nothing happens when launching on macos

### ISSUE THREAD

**Issue by marco-brandizi** [ssbc/patchwork#932]
I've just discovered Scuttlebutt and tried Patchwork. Nothing happens when I launch it on macos 10.14.12, the screen just shows the application's menubar, containing just the "Quit" item. If I run it from the command line (`Patchwork.app/Contents/MacOS/Patchwork`), I get this:

```bash
18:52:37 [brandizi@brandizmac MacOS]$ ./Patchwork
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3, autoPopulate: false },
  connections:
   { outgoing: { net: [Array] },
     incoming: { net: [Array], ws: [Array], unix: [Array] } },
  path: '/Users/brandizi/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps:
   { shs: '1KHL***',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  keys:
   { curve: 'ed25519',
     public: '7nhz***',
     private: '9trR***',
     id: '@7nhz***' },
  remote: 'unix:/Users/brandizi/.ssb/socket:~noauth:7nhz**' }
```
and then it stops until I quit or kill it. I've tried it both as regular user and as root, both `v3.11.4` and `v3.12.0-alpha`.

**Comment by christianbundy** [comment]
Hey, sorry to hear you're having trouble with this.

Could you try v3.11.6 or v3.12.0-alpha.1 and see if you have the same issue? Sorry this took so long to triage your issue.

**Comment by Powersource** [comment]
Closing for now. Please reopen if this still affects you :)
