### ISSUE TITLE
Indexes on `master` aren't being saved

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#935]
I'm not sure what's going on, but it basically goes like this:

1. Open Patchwork and see that it's "indexing database..."
2. Run `ssb-server status` and see that Patchwork-specific views are behind
3. Wait
4. Run `ssb-server status` and see that views are almost up-to-date
5. Wait a bit more
6. Run `ssb-server status` and see that it can't connect to ssb-server
8. Look at Patchwork and see that it still says "indexing database..."
9. Close out of Patchwork
10. GOTO 1 (indexes are somehow back to where they started)

```console
$ ssb-server status
{
  "progress": {
    "indexes": {
      "start": 371470125,
      "current": 495540217,
      "target": 533459552
    },
    "ebt": {
      "start": 0,
      "current": 52,
      "target": 52
    }
  },
  "sync": {
    "since": 533459552,
    "plugins": {
      "last": 533459552,
      "keys": 533459552,
      "clock": 533459552,
      "time": 533459552,
      "feed": 533459552,
      "backlinks--oaWWDs8g": 533459552,
      "private--oaWWDs8g": 533459552,
      "query": 533459552,
      "search": 533459552,
      "tags": 410253896,
      "patchwork-subscriptions": 410253896,
      "patchwork-channels": 410253896,
      "patchwork-contacts": 410253896
    },
    "sync": false
  },
  "rest of the output": "removed :)"
}
```

![screenshot from 2019-02-05 14-47-39](https://user-images.githubusercontent.com/537700/52309563-641b9900-2955-11e9-89de-86df9da83d9e.png)

```console
$ ssb-server status
Error: Could not connect to ssb-server :::8008
Use the "start" command to start it.
Use --verbose option to see full error
```

**Comment by christianbundy** [comment]
The workaround seems to be "open and close Patchwork about 10 times, very quickly, and eventually when you open it'll have all of the indexes done". WTF. I'm suspicious that a view is returning a bad `since` somewhere.

**Comment by christianbundy** [comment]
:man_shrugging:

**Comment by christianbundy** [comment]
I found it!

:man_scientist: 

https://github.com/flumedb/flumeview-reduce/issues/11

**Comment by black-puppydog** [comment]
hasn't been fixed upstream and still annoying. yeah, relevant to me.

**Comment by black-puppydog** [comment]
By now https://github.com/flumedb/flumeview-reduce/pull/16 is merged, *allowing* any flumeview-reduce index to make periodic writes. Now "all" that is left for patchwork is to find all the relevant views, and initialize them with periodic writes! Easy as pie! :)
