### ISSUE TITLE
mouse-forward-back: gyp ERR! stack TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by T-X** [ssbc/patchwork#936]
Hi!

When trying to ``npm install`` patchwork, I get the following build error:

<pre><code>pm WARN npm npm does not support Node.js v10.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> ssb-patchwork@3.12.0-dev postinstall /home/linus/dev-priv/patchwork
> npm run rebuild

npm WARN npm npm does not support Node.js v10.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> ssb-patchwork@3.12.0-dev rebuild /home/linus/dev-priv/patchwork
> cross-script npm rebuild --runtime=electron "--target=$(electron -v)" "--abi=$(electron --abi)" --disturl=https://atom.io/download/atom-shell

npm WARN npm npm does not support Node.js v10.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> @paulcbetts/cld@2.4.6 install /home/linus/dev-priv/patchwork/node_modules/@paulcbetts/cld
> prebuild-install || node-gyp rebuild

> @paulcbetts/cld@2.4.6 postinstall /home/linus/dev-priv/patchwork/node_modules/@paulcbetts/cld
> node bin/postinstall.js

> @paulcbetts/spellchecker@4.0.6 install /home/linus/dev-priv/patchwork/node_modules/@paulcbetts/spellchecker
> prebuild-install || node-gyp rebuild

> keyboard-layout@2.0.13 install /home/linus/dev-priv/patchwork/node_modules/keyboard-layout
> prebuild-install || node-gyp rebuild

> level@3.0.2 postinstall /home/linus/dev-priv/patchwork/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

> leveldown@3.0.2 install /home/linus/dev-priv/patchwork/node_modules/leveldown
> prebuild-install || node-gyp rebuild

> typechecker@2.0.8 preinstall /home/linus/dev-priv/patchwork/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

> typechecker@2.0.8 preinstall /home/linus/dev-priv/patchwork/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

> leveldown@4.0.1 install /home/linus/dev-priv/patchwork/node_modules/ssb-blobs/node_modules/leveldown
> prebuild-install || node-gyp rebuild

> level@4.0.0 postinstall /home/linus/dev-priv/patchwork/node_modules/ssb-blobs/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

(node:6794) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit

> leveldown@4.0.1 install /home/linus/dev-priv/patchwork/node_modules/ssb-blobs/node_modules/leveldown
> prebuild-install || node-gyp rebuild

> leveldown@4.0.1 install /home/linus/dev-priv/patchwork/node_modules/ssb-db/node_modules/leveldown
> prebuild-install || node-gyp rebuild

> level@4.0.0 postinstall /home/linus/dev-priv/patchwork/node_modules/ssb-db/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

> leveldown@4.0.1 install /home/linus/dev-priv/patchwork/node_modules/ssb-db/node_modules/leveldown
> prebuild-install || node-gyp rebuild

> mouse-forward-back@1.0.1 install /home/linus/dev-priv/patchwork/node_modules/mouse-forward-back
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot read property 'substring' of undefined
gyp ERR! stack     at Unpack.isValid [as filter] (/usr/share/node-gyp/lib/install.js:160:30)
gyp ERR! stack     at Unpack.[consumeHeader] (/usr/lib/nodejs/tar/lib/parse.js:134:48)
gyp ERR! stack     at Unpack.[consumeChunkSub] (/usr/lib/nodejs/tar/lib/parse.js:385:30)
gyp ERR! stack     at Unpack.[consumeChunk] (/usr/lib/nodejs/tar/lib/parse.js:362:30)
gyp ERR! stack     at Unpack.write (/usr/lib/nodejs/tar/lib/parse.js:309:25)
gyp ERR! stack     at Gunzip.ondata (_stream_readable.js:667:20)
gyp ERR! stack     at Gunzip.emit (events.js:189:13)
gyp ERR! stack     at addChunk (_stream_readable.js:284:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:265:11)
gyp ERR! stack     at Gunzip.Readable.push (_stream_readable.js:220:10)
gyp ERR! System Linux 4.19.0-1-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/linus/dev-priv/patchwork/node_modules/mouse-forward-back
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! mouse-forward-back@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the mouse-forward-back@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linus/.npm/_logs/2019-02-09T17_34_57_121Z-debug.log
npm WARN @staltz/sbot-gossip@1.1.6 requires a peer of scuttlebot@>=11 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 21.393s
</code></pre>

I'm running Debian unstable / amd64 with npm 5.8.0 and node v10.15.1. The patchwork commit I'm trying is 9750bc4d761e9243e144df7ecbc35c38e2b0a04e.

**Comment by christianbundy** [comment]
Could you update your npm? It looks like it's throwing warnings that it doesn't support Node 10, so I'm wondering whether this might be the cause of your issue.

**Comment by christianbundy** [comment]
Any chance that this is resolved for you now?

**Comment by T-X** [comment]
Hi @christianbundy. Sorry, had totally forgotten about this...

If I recall correctly, updating npm fixed the issue for me back then. At least I have npm 6.7.0 installed right now, along with nodejs v10.15.1.

Thanks for your help!

**Comment by christianbundy** [comment]
No problem, happy to hear that it's resolved! Please reach out if you notice any other funky behavior.
