### ISSUE TITLE
content strings in css aren't i18n'd

### ISSUE THREAD

**Issue by justinabrahms** [ssbc/patchwork#938]
In trawling source, I found https://github.com/ssbc/patchwork/blob/master/styles/light/compose.mcss#L49 wherein we embed content via CSS. This means, I believe, that the content won't be translated.

**Comment by christianbundy** [comment]
Still looking for a solution to this issue, unfortunately it doesn't look like we can give input elements custom text so this is the hack we're stuck with. Maybe we should be using a button or something instead? Or a `<label>`, honestly, would be the idiomatic way to do this.

**Comment by gergelypolonkai** [comment]
In this specific case (i havenʼt checked others yet) itʼs easy to switch this `::before` “element” to a proper label. I wonder why it was done this way…

**Comment by gergelypolonkai** [comment]
Oh,  look what i found:

`dark/compose.mcss`:

```
Compose {
  section.actions {
    input[type=file] {
      ::before {
        content: 'Attach';
      }
    }
}
```

`light/compose.mcss`:

```
Compose {
  section.actions {
    input[type=file] {
      ::before {
        content: '📎 Attach File'
      }
    }
  }
}
```
So it’s not just a translation problem, but an inconsistency between themes, too.

**Comment by gergelypolonkai** [comment]
Here is the full list i found on `master`:

```
$ ag 'content:'  # Irrelevant lines are filtered out from the below results
base/loading.mcss
37:      content: 'Loading...'
49:      content: 'Searching...'

base/message.mcss
49:            content: ' unread'
54:            content: ' new'
97:          content: 'private'

dark/compose.mcss
35:        content: 'Attach'

light/compose.mcss
49:        content: '📎 Attach File'
```
