### ISSUE TITLE
possible malformed 'remote' prevents discovery of patchwork ssb instance on LAN?

### ISSUE THREAD

**Issue by skyebend** [ssbc/patchwork#943]
I'm having trouble discovering and following patchwork ssb client running on my laptop from Manyverse on my phone and it appears information may be missing from patchwork's broadcast discovery packets. 

I previously opened a ticket for Manyverse https://gitlab.com/staltz/manyverse/issues/333 and followed suggestion from staltz to capture the UDP packets sent to 255.255.255.255 using wireshark

The packets from laptop (patchwork) look like:
```
ÿÿÿÿÿÿtå¹EBúÔ@@}ÄÀ¨jÿÿÿÿHH.á:unix:/home/skyebend/.ssb/socket~noauth
```
vs. packets from phone (manyverse) look like:
```
ÿÿÿÿÿÿ´ÎöýEd@@xpÀ¨qÿÿÿÿHHP.énet:192.168.1.113:26831~shs:MhGNu6tzZHSNv4U6nLRMVdnbvv+YLudFm5nqKqo7QJQ=
```
This makes it look like patchwork is  broadcasting a unix path instead of an IP and port for discovery? and maybe also omitting the identity?

This seems to align with the config data printed by patchwork at startup
```
remote: 'unix:/home/skyebend/.ssb/socket:~noauth:F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=' }
```
Am I missing some configuration somewhere?  Something needs to be set to 'net' instead of 'unix'? Is there a reference on what is supposed to be in the broadcast packets?

I'm using patchwork built from source from this repo (at git commit 9750bc4d761e9243e144df7ecbc35c38e2b0a04e) on Ubuntu (32bit so couldn't install directly)

**Comment by christianbundy** [comment]
I think this is because we're configuring the unix socket's [ssb-config scope](https://github.com/ssbc/ssb-config/) as "local" when it should really be "private". I always thought that "local" meant "local device" rather than "local area network". Oof. Thanks for posting this, I've been wondering why those unix addresses were being broadcast. I'll work on a fix for Patchwork and Patchbay now.

**Comment by skyebend** [comment]
more detailed log output from master branch (to contrast with output from branch on PR #944) 
```
> ssb-patchwork@3.12.0-dev start /home/skyebend/ssb
> electron index.js

error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
{ path: '/home/skyebend/.ssb',
  party: true,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  gossip: { connections: 3, autoPopulate: false },
  host: '',
  port: 8008,
  ws: { port: 8989 },
  connections: 
   { outgoing: { net: [Array] },
     incoming: { net: [Array], ws: [Array], unix: [Array] } },
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  keys: 
   { curve: 'ed25519',
     public: 'F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=.ed25519',
     private: null,
     id: '@F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=.ed25519' },
  remote: 'unix:/home/skyebend/.ssb/socket:~noauth:F/Lw6U9khCl8f/BrfYbSnsd1jMFqK+9otnyKBwfp9Es=' }
error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
Init replication limiter. maxNumConnections: 10, modeChangeThreshold: 100
Replication obs called, Limited mode enabled:  false
git-ssb is not installed, or not available in path
Listening on undefined:8008 (multiserver net plugin)
listening on socket unix:/home/skyebend/.ssb/socket
error loading sodium bindings: /home/skyebend/ssb/node_modules/sodium-native/build/Release/sodium.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
falling back to javascript version.
unix socket client
```
I see logging level: notice, is there a way to make it more verbose?
