### ISSUE TITLE
strange ui block glitches

### ISSUE THREAD

**Issue by masukomi** [ssbc/patchwork#945]
It starts with strange blocks in the UI of the mac version.

<img width="1440" alt="patchwork" src="https://user-images.githubusercontent.com/2829/53656358-09f2b880-3c21-11e9-8e90-91cad152e5f2.png">

when you type things get REALLY weird. 

![screenflow](https://user-images.githubusercontent.com/2829/53656374-19720180-3c21-11e9-8c05-9f5b501179f8.gif)

Note: it never went full black. that was just an artifact of the gif creation or something.

**Comment by christianbundy** [comment]
Looks like a GPU glitch, my guess is that this is an Electron thing. I have the same problem and have to use the patched version of Electron for my OS. Hmm. Can you confirm which version of Patchbay you're using?

**Comment by masukomi** [comment]
3.11.4 (patchwork not patchbay) @christianbundy

**Comment by christianbundy** [comment]
@masukomi 

I've just [pre]released a version with Electron 4, could you check whether this resolves the issue for you?

**Comment by Powersource** [comment]
Since (it sounds like) electron 4 fixed it for christian, and masukomi hasn't commented again, I'm gonna guess this is resolved.

**Comment by masukomi** [comment]
sorry. I haven't seen these glitches in ages. So yeah, closing it is probably correct.
