### ISSUE TITLE
Won't start on Linux

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ssbc/patchwork#951]
I get this error when trying to run `ssb-patchwork` on Arch Linux, using the [Arch Linux pkg](https://aur.archlinux.org/packages/ssb-patchwork/). It displays this in the terminal and just doesn't start.

```
(electron2:17259): Gtk-WARNING **: 22:26:22.503: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(electron2:17259): Gtk-WARNING **: 22:26:22.503: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(electron2:17259): Gtk-WARNING **: 22:26:22.503: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  connections: { incoming: { net: [Array] }, outgoing: { net: [Array] } },
  path: '/home/makeworld/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: 'REMOVED',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [] }
```
I'm going to tag @christianbundy here, since he maintains the Arch pkg.

Downloading and using the AppImage appears to work fine.

**Comment by christianbundy** [comment]
Hey! Sorry you're having trouble with that -- can you verify that you're on version 3.11.4-3?

Also, if you're feeling adventurous you can try out [ssb-patchwork-git](https://aur.archlinux.org/packages/ssb-patchwork-git/) and see if that works.

**Comment by makeworld-the-better-one** [comment]
I am on that version, the latest one in AUR.

**Comment by christianbundy** [comment]
Hmm. Can you verify that you're up-to-date with `pacman -Syu` and such? I'm currently running GNOME Shell on Wayland, any chance you're on something else? Either `patchwork-git` or building from source would be super helpful in adding another data point, but I understand if you don't have the time.

Thanks for your help in debugging this!

**Comment by makeworld-the-better-one** [comment]
I am not totally up to date, I can try that. I'm running XFCE on X. I can also try git, if updating doesn't work.

**Comment by christianbundy** [comment]
Heyo, any chance you've had time to try this out again? Thanks for your help debugging this problem!

**Comment by Powersource** [comment]
Gonna guess this is fixed with the electron updates. Please reopen if it's still broken for you :)
