### ISSUE TITLE
replies to message forks don't show on profiles

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#956]

**Comment by Powersource** [comment]
Removed blocking as this is already in 3.11.6.

**Comment by Powersource** [comment]
Yes still a bug I think.

@black-puppydog you didn't happen to learn anything about how to fix this while you were digging around the blog (?) stuff?

**Comment by black-puppydog** [comment]
@Powersource nope :/

**Comment by mmckegg** [comment]
I’m happy to pair with someone on this one of my office hours (Wednesday in most time zones)

**Comment by Powersource** [comment]
Yes still relevant (I think) hehe

**Comment by Powersource** [comment]
@mmckegg still having office hours? :P I'd be up for trying to fix this maybe next week.

**Comment by black-puppydog** [comment]
yes.

**Comment by black-puppydog** [comment]
For reference, the blog type issue is #930. There's also #1258.
