### ISSUE TITLE
Local gossip not working

### ISSUE THREAD

**Issue by mplorentz** [ssbc/patchwork#958]
I just upgraded to 3.11.5 and I cannot gossip with another machine on the same network. The other machine shows up in the "Local" section of the sidebar but messages are not transmitted between the two machines. Messages are transmitted fine when both machines  are running Patchwork 3.11.4.

Machines are running macOS 10.13.6 and 10.14.3
`~/.ssb.config` contents:
```
{
  “caps”: {
     “shs”: “secretkey”
  }
}
```

The `gossip.json` on one machine looked like this:
```
[{"host":"-redacted-","port":8008,"key":"@wnUdsQetC9YeEuW4DW6cC5/Zs8vSwla/u50b4nbshJs=.ed25519","address":"net:fe80::437:72a2:1a8c:9dc5:8008~shs:wnUdsQetC9YeEuW4DW6cC5/Zs8vSwla/u50b4nbshJs=;ws://[::]:8989~shs:-redacted-","source":"local","announcers":1,"duration":{"mean":0,"stdev":0,"count":44,"sum":0,"sqsum":0},"stateChange":1552917690911,"error":"Error: connect EHOSTUNREACH -redacted- - Local (:::50420)\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at internalConnect (net.js:971:16)\n    at net.js:1065:9\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","failure":44}]
```

**Comment by christianbundy** [comment]
@mplorentz 

Thanks for the bug report! Hmm, is your custom SSB config important? I'm noticing two quirks:

- I think it should be `~/.ssb/config` rather than `~/.ssb.config`
- I see `“` and `”` when it should just be `"`.

Are you trying to run on a secret network cap or just running on the regular network? If you're using the regular network you shouldn't need any SSB config.

**Comment by mplorentz** [comment]
Thanks for your reply @christianbundy. I am running these Patchworks on an alt-net. I'm not sure if this issue is related that fact. 

But the correct path to my config is `~/.ssh/config` and the smart quotes are normal quotes in the actual file. So I don't think either of those are the issue. Thanks for pointing them out though!

**Comment by christianbundy** [comment]
I just looked at the commits for the 3.11.5 release and found this: 10f43a74e1b4f762118174e4922f389a2d1c7c6c

It looks like we're using a [backported plugin](https://github.com/ssbc/patchwork/blob/10f43a74e1b4f762118174e4922f389a2d1c7c6c/lib/sbot-local-with-address-fix.js) to manage local connections, so my intuition is that something is broken in there.

On the other hand, I expanded the JSON you included and it looks like we have a problem:

```json
[
  {
    "host":"-redacted-",
    "port":8008,
    "key":"@wnUdsQetC9YeEuW4DW6cC5/Zs8vSwla/u50b4nbshJs=.ed25519",
    "address":"net:fe80::437:72a2:1a8c:9dc5:8008~shs:wnUdsQetC9YeEuW4DW6cC5/Zs8vSwla/u50b4nbshJs=;ws://[::]:8989~shs:-redacted-",
    "source":"local",
    "announcers":1,
    "duration": {
      "mean":0,
      "stdev":0,
      "count":44,
      "sum":0,
      "sqsum":0
    },
    "stateChange":1552917690911,
    "error":"Error: connect EHOSTUNREACH -redacted- - Local (:::50420)\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at internalConnect (net.js:971:16)\n    at net.js:1065:9\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)",
    "failure":44
  }
]
```

This concerns me for a few reasons:

1. We're seeing EHOSTUNREACH on what looks like `[::]:50420`, which is a malformed host:port combo *and* it's a meta address **and** it's a port I don't recognize.
2. We're broadcasting `::` as an address for ssb-ws, which is a meta-address like `0.0.0.0` but can't actually be connected to.
3. It looks like we're using an old version of ssb-server (scuttlebot) and an old version of ssb-ws, which I think is only meant to bind to `localhost`. Is this with the default config, or are you running a web-facing service on one of these peers?

cc: @mmckegg

**Comment by mplorentz** [comment]
> Is this with the default config, or are you running a web-facing service on one of these peers?

The config I posted above is my full config file. I haven't messed around with anything else - these are very fresh installations of Patchwork. There aren't any web-facing services running on either of the MacBooks.

**Comment by christianbundy** [comment]
Thanks, I'm working on #959 in an effort to fix this issue. If possible, could you test that branch and verify that it resolves the problem you're seeing?

**Comment by mplorentz** [comment]
@christianbundy thanks Christian! I should be able to test it tomorrow. Will report back here.

**Comment by mplorentz** [comment]
@christianbundy I gave the branch a try and Patchwork just stays on the "Loading" screen forever after `npm start`.

The steps I took were:
1. Change to `backport-updates` branch
2. `rm -rf node_modules`
3. `npm install`
4. `npm start`

I am running node v11.12.0 and npm 6.7.0. No errors are displayed in the console after Patchwork launches.

I did notice that if you save `gossip.json` from a 3.11.4 version of Patchwork then 3.11.5 is able to gossip locally. It is only on a fresh install that things are broken.

**Comment by mmckegg** [comment]
@mplorentz 

When starting v3.11.5 from the terminal (with the custom caps), what config is being logged out? Does your custom shs key show in there?

**Comment by egmatt** [comment]
@mmckegg yep it shows the config:
```
 caps:
   { shs: 'mysupersecrectkey',
     sign: null },
```

Also I have confirmed that the 3.11.6 has this same issue.

**Comment by johncronan** [comment]
I just installed Patchwork to test out Scuttlebutt for the first time.

Installed to my laptop, created my profile. Installed to desktop, with fake identity.

The other client is "@4MHf9pK ... [etc.]" in the "local" list, and its messages don't appear. Same vice versa.

**Comment by christianbundy** [comment]
Could you confirm that this is happening in `master` (and / or the prereleases)? Thank you!

**Comment by the-kenny** [comment]
@christianbundy I can confirm this is happening on master. It boils down to the `local` plugin announcing an ipv6 address of a wrong interface.

For me, it broadcasts a full ipv6 address, but of a disconnected lan interface. The broadcasts go out over wifi.

As for @mplorentz, it seems like his instance broadcasts `::: 50420`, i.e. `::` as ip and `:50420` for the port part.

My guess is that both are related issues.

**Comment by christianbundy** [comment]
I think we'll need to fix this in ssb-config, I've made a comment [here](https://github.com/ssbc/ssb-config/issues/49#issuecomment-490528821) and will update this thread once I've got a fix going. :+1:

**Comment by christianbundy** [comment]
Looks like we have a fix, please follow https://github.com/ssbc/patchwork/pull/1027 for updates. Would love some testing to ensure that it fixes the issue!

**Comment by the-kenny** [comment]
Hm - trying beta2 on multiple machines now I get the feeling this still doesn't work as it should.

While I now get a multitude of announce messages my local Patchwork instances still aren't able to connect to each other. It was working for some time now, but stopped working again.

Looking at `tcpdump` both instances still announce only one IP, and it's the wrong one again. 

The instance on my macbook announces 6 sockets, 3 being `net:` and the other 3 being `ws://` The three `net:` announcing port 8008 and the `ws://` announcing 8989. They all share the same identity (mine). This is all good and expected - but all of them share the same IP which doesn't make any sense (why announce the same `(ip, port, public_key)` tuple thrice?).

**Comment by christianbundy** [comment]
@the-kenny Hmm, sorry this isn't resolved for you. Could you post a new issue with info on:

- Do these instances follow each other?
- How long do they connect to each other before it "stopped working again"?
- How are you identifying that it stops working?
- What's the config output of both machines (should print to stdout on Patchwork startup)?
- What's the tcpdump output that you're referencing?

**Comment by the-kenny** [comment]
@christianbundy will do!
