### ISSUE TITLE
Patchwork 3.11.5 seems to be connecting to blocked pubs

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#960]
Not sure if this is a new bug (doesn't seem to exist in master). Most likely something to do with the backports. 

@christianbundy Can you check and see if this is fixed in #959 ?

**Comment by christianbundy** [comment]
I just noticed this in my branch, it's not fixed. Not sure where it came from though...

![Screenshot from 2019-03-18 14-01-39](https://user-images.githubusercontent.com/537700/54563453-72ae9480-4986-11e9-82ff-ec4dac2cd2b5.png)

**Comment by christianbundy** [comment]
I've downgraded from ssb-server@14 to ssb-server@13 and I think this is resolved -- not sure why it was happening, but it seems fine now.

**Comment by christianbundy** [comment]
Fixed in #961

**Comment by mmckegg** [comment]
@christianbundy  I think that maybe ssb-server just does this, not 100% sure though.

This is fixed in patchwork@master but I think that is because patchwork is in control of the peer table (as part of the ssb-friends rewrite), and it [excludes blocked peers](https://github.com/ssbc/patchwork/blob/master/sbot/index.js#L140) from the gossip table.

**Comment by christianbundy** [comment]
Fixed in `master` and prereleases. :tada:
