### ISSUE TITLE
3.11.6 AppImage not opening

### ISSUE THREAD

**Issue by ukch** [ssbc/patchwork#968]
I have just attempted to upgrade to 3.11.6 from 3.11.4, which I had installed from the downloadable AppImage file on GitHub. However, the latest AppImage file does not seem to have been put together correctly, in that when I try to open it it says it doesn't know how to open.

(Sorry I can't give any more information. The whole AppImage ecosystem is quite new to me)

**Comment by christianbundy** [comment]
Hi @ukch, sorry this is giving you a hard time!

Did you already run `chmod +x ./Patchwork-3.11.6-linux-x86_64.AppImage`? The file isn't executable by default, so you'll have to make it executable before you can double-click it.

**Comment by christianbundy** [comment]
More info here, just in case: https://docs.appimage.org/user-guide/run-appimages.html

**Comment by ukch** [comment]
Thanks @christianbundy, that solved the issue for me. Is there any way these files can be made executable by default to remove that extra step?

**Comment by christianbundy** [comment]
I don't think so, all of the AppImage documentation that I've found has described the mandatory step of making the image executable. If you can find any docs that suggest a streamlined workflow without the `chmod` I'd be happy to make that change, but I'd like to ensure that we're conforming to the AppImage standard.
