### ISSUE TITLE
syncing gets stuck and requires restart during onboarding

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#977]
This is due to a [bug in ebt](https://github.com/ssbc/ssb-ebt/issues/22) (that patchwork is now using). We either need to wait until the bug in ebt is fixed before we can release, or find some temporary hack (e.g. reconnect to pub if ebt progress stalls for an extended period of time).

@christianbundy Another release blocker!

**Comment by christianbundy** [comment]
@mmckegg Woo!

Do you think this is causing the permanent scuttling bug? #969

**Comment by mmckegg** [comment]
@christianbundy probably not, because that branch of Patchwork doesn't use ebt.

**Comment by christianbundy** [comment]
Another option would be to disable ssb-ebt again to match the [code in v3.11.6](https://github.com/ssbc/patchwork/blob/backfix-3.11.1/server-process.js#L23). It looks like it was re-added in https://github.com/ssbc/patchwork/commit/f03d884d4db127b92665d3631474bf1180e7beb8.
