### ISSUE TITLE
Would it be possible to have .deb package or a repo. for Debian ?

### ISSUE THREAD

**Issue by shirishag75** [ssbc/patchwork#983]
I am on Debian 10 (buster) .  I don't use .appimage but rely on .deb packages . Is there a possibility to have a .deb package or better yet a debian repo. for the same ?

Something on the lines like these - 

`deb https://riot.im/packages/debian/ stretch main`

You will need to have a public key , see this for instance 

https://riot.im/desktop.html

It would be nice if something like this can be done.

**Comment by christianbundy** [comment]
Hey, I think this is a great idea. I've packaged for Arch Linux but would *love* to have this on Debian as well. Are you familiar with how to create a `.deb` package? Unfortunately I'm only familiar with making `PKGBUILD`s.

**Comment by shirishag75** [comment]
I have done via using 'make' and then using 'debuild -us -uc' to make a Debian package. But for something which uses nodejs I have no clue.

**Comment by christianbundy** [comment]
Yeah, my intuition is that the build will be specific to Electron, I just haven't had time to do much research  on this yet.

**Comment by shirishag75** [comment]
Electron is a large package. What we have done is used riot but from a package repo. maintained by riot.im 

`deb https://riot.im/packages/debian/ stretch main`

**Comment by shirishag75** [comment]
Electron is a large package. What we have done is used riot but from a package repo. maintained by riot.im 

`deb https://riot.im/packages/debian/ stretch main`

Right now their infrastructure is down, see 

https://twitter.com/matrixdotorg/status/1116304867683905537

**Comment by christianbundy** [comment]
Hmm, looks like we may have an option via electron-builder: https://www.electron.build/configuration/linux.html

**Comment by shirishag75** [comment]
electron-builder is cool but electron itself seems to be still somewhat immature 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927057

I had and have plenty of bugs using riot-web (which is based on electron) under Debian. Firefox is my go-to-browser.

**Comment by christianbundy** [comment]
I'm not advocating for Electron, but it *is* the foundation of this implementation. We used to have a Patchwork-like client that ran in the browser called [Patchlite](https://github.com/ssbc/patchlite) but it hasn't seen maintenance for a long time. There's also [Patchfoo](https://github.com/ssbc/patchfoo), which doesn't use JavaScript, but I don't think that removing Electron from this project is something I have time for currently.

**Comment by christianbundy** [comment]
It looks like we'll just need to modify `package.json` to add a top-level `"deb"` property with all of the Debian dependencies. Here are the Arch dependencies I'm using while packaging, not sure whether all of these are actually necessary (or if there are others we need):

- alsa-lib
- electron2
- gconf
- gtk2
- libsodium
- libxext
- libxkbfile
- libxss
- libxtst
- nss
