### ISSUE TITLE
NPM audit for latest release 3.11.6

### ISSUE THREAD

**Issue by PragmaticCypher** [ssbc/patchwork#991]
the 'npm' audit command is suggesting several vulnerabilities in a security report.  Are they a concern?

Packages of with high severity warnings:
```
Issue: Arbitrary File Overwrite
Package: tar
Dependency: ssb-server
More info: https://nodesecurity.io/advisories/803

Issue: Arbitrary File Overwrite
Package: tar
Dependency: sbot-gossip
More info: https://nodesecurity.io/advisories/803

Issue:  Code Injection
Package: js-yaml
Dependency: standard
More info: https://nodesecurity.io/advisories/813
```

**Comment by gergelypolonkai** [comment]
Both problems seem to have fixes available, both as a minor version bump so *theoretically* it shouldn’t be a pain to upgrade them.

**Comment by christianbundy** [comment]
Thanks for the bug report! I don't like seeing those either.

I'm working on a new release (see #994) that should resolve this issue, but I'd like to keep this open until that's published and available for download. Please let me know if you notice any `npm audit` issues in `master`!

**Comment by christianbundy** [comment]
Should be good now, please open an issue or a PR if you notice anything in `master`!
