### ISSUE TITLE
Latest version shows 'scuttling' forever

### ISSUE THREAD

**Issue by ukch** [ssbc/patchwork#999]
I have been using version 3.11.4 with no problems. After upgrading to 3.11.6 I see the endless 'scuttling' loop and no content seems to load. Please let me know what debug information you need to be able to resolve this.

**Comment by christianbundy** [comment]
Hey @ukch, could you give some information on your operating system?

I'd be curious to know whether you have the same problem in `master` (alpha prerelease available [here](https://github.com/ssbc/patchwork/releases/tag/v3.12.0-alpha.1)) or whether this is specific to 3.11.6.

**Comment by ukch** [comment]
Oops, should have mentioned I'm on Linux, using the AppImage distribution. After first opening the alpha version, it said 'Indexing database' for a very long time, but then normal service resumed.

**Comment by christianbundy** [comment]
Sweet, happy to hear that this is resolved in the latest codebase. Now we just need to release! There are [a few issues blocking release](https://github.com/ssbc/patchwork/issues?q=is%3Aissue+is%3Aopen+label%3A%22blocking+release%22) but once those are resolved then we're good to go. If you have time, I'd love to know whether [the spellcheck problem](https://github.com/ssbc/patchwork/issues/996) is causing trouble in your AppImage release or if it's just me. Thanks for helping debug this!

**Comment by ukch** [comment]
Thanks @christianbundy. Unfortunately I am unable to test the spellcheck bug as I always disable spell checking (personally I find it more distracting than useful).
